<?php
/**
 * Body Map Terms - Body part names and body map modal UI strings
 */
return [

/* ---- Modal UI ---- */
'body_map_modal_title' => [
    'fi' => 'Merkitse loukkaantuneet kehonosat',
    'sv' => 'Markera skadade kroppsdelar',
    'en' => 'Mark injured body parts',
    'it' => 'Indica le parti del corpo infortunate',
    'el' => 'Επισημάνετε τραυματισμένα μέρη του σώματος',
],
'body_map_open_btn' => [
    'fi' => 'Merkitse loukkaantuneet kehonosat',
    'sv' => 'Markera skadade kroppsdelar',
    'en' => 'Mark injured body parts',
    'it' => 'Indica le parti del corpo infortunate',
    'el' => 'Επισημάνετε τραυματισμένα μέρη του σώματος',
],
'body_map_instruction' => [
    'fi' => 'Valitse kehokuvasta loukkaantunut kehonosa. Valinnat tallentuvat safetyflashin tietoihin ja näkyvät myös tilastoissa dashboardilla.',
    'sv' => 'Välj den skadade kroppsdelen från kroppsfiguren. Valen sparas i safetyflash-informationen och visas även i statistiken på dashboarden.',
    'en' => 'Select the injured body part from the body figure. Selections are saved to the safety flash details and also appear in the dashboard statistics.',
    'it' => 'Seleziona la parte del corpo infortunata dalla figura corporea. Le selezioni vengono salvate nei dettagli del safety flash e compaiono anche nelle statistiche della dashboard.',
    'el' => 'Επιλέξτε το τραυματισμένο μέρος σώματος από τη φιγούρα. Οι επιλογές αποθηκεύονται στα στοιχεία του safety flash και εμφανίζονται επίσης στα στατιστικά του πίνακα ελέγχου.',
],
'body_map_close_label' => [
    'fi' => 'Sulje',
    'sv' => 'Stäng',
    'en' => 'Close',
    'it' => 'Chiudi',
    'el' => 'Κλείσιμο',
],
'body_map_select_label' => [
    'fi' => 'Valitse kehonosat listasta',
    'sv' => 'Välj kroppsdelar från listan',
    'en' => 'Select body parts from the list',
    'it' => 'Seleziona le parti del corpo dall\'elenco',
    'el' => 'Επιλέξτε μέρη σώματος από τη λίστα',
],
'body_map_select_hint' => [
    'fi' => 'Pidä Ctrl/⌘ pohjassa valitaksesi useita.',
    'sv' => 'Håll Ctrl/⌘ nere för att välja flera.',
    'en' => 'Hold Ctrl/⌘ to select multiple.',
    'it' => 'Tieni premuto Ctrl/⌘ per selezionare più elementi.',
    'el' => 'Κρατήστε Ctrl/⌘ για να επιλέξετε πολλά.',
],
'body_map_svg_hint' => [
    'fi' => 'Tai klikkaa kehokuvasta',
    'sv' => 'Eller klicka på kroppsfiguren',
    'en' => 'Or click on the body figure',
    'it' => 'Oppure clicca sulla figura corporea',
    'el' => 'Ή κάντε κλικ στη φιγούρα σώματος',
],
'body_map_front_label' => [
    'fi' => 'Etupuoli',
    'sv' => 'Framsida',
    'en' => 'Front',
    'it' => 'Fronte',
    'el' => 'Μπροστά',
],
'body_map_back_label' => [
    'fi' => 'Selkäpuoli',
    'sv' => 'Baksida',
    'en' => 'Back',
    'it' => 'Retro',
    'el' => 'Πίσω',
],
'body_map_cancel_btn' => [
    'fi' => 'Peruuta',
    'sv' => 'Avbryt',
    'en' => 'Cancel',
    'it' => 'Annulla',
    'el' => 'Ακύρωση',
],
'body_map_save_btn' => [
    'fi' => 'Tallenna valinnat',
    'sv' => 'Spara val',
    'en' => 'Save selections',
    'it' => 'Salva selezioni',
    'el' => 'Αποθήκευση επιλογών',
],
'body_map_save_success' => [
    'fi' => 'Loukkaantumiset tallennettu',
    'sv' => 'Skador sparade',
    'en' => 'Injuries saved',
    'it' => 'Lesioni salvate',
    'el' => 'Τραυματισμοί αποθηκεύτηκαν',
],
'body_map_save_error' => [
    'fi' => 'Tallennus epäonnistui',
    'sv' => 'Det gick inte att spara',
    'en' => 'Failed to save',
    'it' => 'Salvataggio non riuscito',
    'el' => 'Αποτυχία αποθήκευσης',
],
'body_map_count_single' => [
    'fi' => '1 kehonosa valittu',
    'sv' => '1 kroppsdel vald',
    'en' => '1 body part selected',
    'it' => '1 parte del corpo selezionata',
    'el' => '1 μέρος σώματος επιλεγμένο',
],
'body_map_count_plural' => [
    'fi' => '{n} kehonosaa valittu',
    'sv' => '{n} kroppsdelar valda',
    'en' => '{n} body parts selected',
    'it' => '{n} parti del corpo selezionate',
    'el' => '{n} μέρη σώματος επιλεγμένα',
],
'body_map_remove_label' => [
    'fi' => 'Poista',
    'sv' => 'Ta bort',
    'en' => 'Remove',
    'it' => 'Rimuovi',
    'el' => 'Αφαίρεση',
],

/* ---- Category headings ---- */
'bp_cat_head_neck' => [
    'fi' => 'Pää ja niska',
    'sv' => 'Huvud och nacke',
    'en' => 'Head and neck',
    'it' => 'Testa e collo',
    'el' => 'Κεφάλι και λαιμός',
],
'bp_cat_torso' => [
    'fi' => 'Keskivartalo',
    'sv' => 'Bål',
    'en' => 'Torso',
    'it' => 'Tronco',
    'el' => 'Κορμός',
],
'bp_cat_upper_limbs' => [
    'fi' => 'Yläraajat',
    'sv' => 'Övre extremiteter',
    'en' => 'Upper limbs',
    'it' => 'Arti superiori',
    'el' => 'Άνω άκρα',
],
'bp_cat_lower_limbs' => [
    'fi' => 'Alaraajat',
    'sv' => 'Nedre extremiteter',
    'en' => 'Lower limbs',
    'it' => 'Arti inferiori',
    'el' => 'Κάτω άκρα',
],

/* ---- Body parts ---- */
'bp_head' => [
    'fi' => 'Pää',
    'sv' => 'Huvud',
    'en' => 'Head',
    'it' => 'Testa',
    'el' => 'Κεφάλι',
],
'bp_eyes' => [
    'fi' => 'Silmä / Silmät',
    'sv' => 'Öga / Ögon',
    'en' => 'Eye / Eyes',
    'it' => 'Occhio / Occhi',
    'el' => 'Μάτι / Μάτια',
],
'bp_ear' => [
    'fi' => 'Korva / Kuulo',
    'sv' => 'Öra / Hörsel',
    'en' => 'Ear / Hearing',
    'it' => 'Orecchio / Udito',
    'el' => 'Αυτί / Ακοή',
],
'bp_neck' => [
    'fi' => 'Kaula / Niska',
    'sv' => 'Hals / Nacke',
    'en' => 'Neck',
    'it' => 'Collo / Nuca',
    'el' => 'Λαιμός / Αυχένας',
],
'bp_chest' => [
    'fi' => 'Rintakehä',
    'sv' => 'Bröstkorg',
    'en' => 'Chest',
    'it' => 'Torace',
    'el' => 'Θώρακας',
],
'bp_abdomen' => [
    'fi' => 'Vatsa',
    'sv' => 'Mage',
    'en' => 'Abdomen',
    'it' => 'Addome',
    'el' => 'Κοιλιά',
],
'bp_pelvis' => [
    'fi' => 'Lantioseutu',
    'sv' => 'Bäckenregion',
    'en' => 'Pelvis',
    'it' => 'Bacino',
    'el' => 'Λεκάνη',
],
'bp_upper_back' => [
    'fi' => 'Yläselkä',
    'sv' => 'Övre rygg',
    'en' => 'Upper back',
    'it' => 'Schiena superiore',
    'el' => 'Άνω πλάτη',
],
'bp_lower_back' => [
    'fi' => 'Alaselkä',
    'sv' => 'Nedre rygg',
    'en' => 'Lower back',
    'it' => 'Schiena inferiore',
    'el' => 'Κάτω πλάτη',
],
'bp_shoulder_left' => [
    'fi' => 'Vasen olkapää',
    'sv' => 'Vänster axel',
    'en' => 'Left shoulder',
    'it' => 'Spalla sinistra',
    'el' => 'Αριστερός ώμος',
],
'bp_shoulder_right' => [
    'fi' => 'Oikea olkapää',
    'sv' => 'Höger axel',
    'en' => 'Right shoulder',
    'it' => 'Spalla destra',
    'el' => 'Δεξιός ώμος',
],
'bp_arm_left' => [
    'fi' => 'Vasen käsivarsi',
    'sv' => 'Vänster arm',
    'en' => 'Left arm',
    'it' => 'Braccio sinistro',
    'el' => 'Αριστερό χέρι',
],
'bp_arm_right' => [
    'fi' => 'Oikea käsivarsi',
    'sv' => 'Höger arm',
    'en' => 'Right arm',
    'it' => 'Braccio destro',
    'el' => 'Δεξί χέρι',
],
'bp_hand_left' => [
    'fi' => 'Vasen kämmen',
    'sv' => 'Vänster hand',
    'en' => 'Left hand',
    'it' => 'Mano sinistra',
    'el' => 'Αριστερό παλάμι',
],
'bp_hand_right' => [
    'fi' => 'Oikea kämmen',
    'sv' => 'Höger hand',
    'en' => 'Right hand',
    'it' => 'Mano destra',
    'el' => 'Δεξί παλάμι',
],
'bp_thigh_left' => [
    'fi' => 'Vasen reisi',
    'sv' => 'Vänster lår',
    'en' => 'Left thigh',
    'it' => 'Coscia sinistra',
    'el' => 'Αριστερός μηρός',
],
'bp_thigh_right' => [
    'fi' => 'Oikea reisi',
    'sv' => 'Höger lår',
    'en' => 'Right thigh',
    'it' => 'Coscia destra',
    'el' => 'Δεξιός μηρός',
],
'bp_knee_left' => [
    'fi' => 'Vasen polvi',
    'sv' => 'Vänster knä',
    'en' => 'Left knee',
    'it' => 'Ginocchio sinistro',
    'el' => 'Αριστερό γόνατο',
],
'bp_knee_right' => [
    'fi' => 'Oikea polvi',
    'sv' => 'Höger knä',
    'en' => 'Right knee',
    'it' => 'Ginocchio destro',
    'el' => 'Δεξί γόνατο',
],
'bp_calf_left' => [
    'fi' => 'Vasen pohje',
    'sv' => 'Vänster vad',
    'en' => 'Left calf',
    'it' => 'Polpaccio sinistro',
    'el' => 'Αριστερή γάμπα',
],
'bp_calf_right' => [
    'fi' => 'Oikea pohje',
    'sv' => 'Höger vad',
    'en' => 'Right calf',
    'it' => 'Polpaccio destro',
    'el' => 'Δεξιά γάμπα',
],
'bp_ankle_left' => [
    'fi' => 'Vasen nilkka',
    'sv' => 'Vänster fotled',
    'en' => 'Left ankle',
    'it' => 'Caviglia sinistra',
    'el' => 'Αριστερός αστράγαλος',
],
'bp_ankle_right' => [
    'fi' => 'Oikea nilkka',
    'sv' => 'Höger fotled',
    'en' => 'Right ankle',
    'it' => 'Caviglia destra',
    'el' => 'Δεξιός αστράγαλος',
],
'bp_foot_left' => [
    'fi' => 'Vasen jalkaterä',
    'sv' => 'Vänster fot',
    'en' => 'Left foot',
    'it' => 'Piede sinistro',
    'el' => 'Αριστερό πόδι',
],
'bp_foot_right' => [
    'fi' => 'Oikea jalkaterä',
    'sv' => 'Höger fot',
    'en' => 'Right foot',
    'it' => 'Piede destro',
    'el' => 'Δεξί πόδι',
],

];