<?php
/**
 * Button Labels and Footer Actions - Action buttons, footer controls
 */
return [
'btn_delete_selected' => [
    'fi' => 'Poista valitut',
    'sv' => 'Ta bort valda',
    'en' => 'Delete selected',
    'it' => 'Elimina selezionati',
    'el' => 'Διαγραφή επιλεγμένων',
],
'btn_delete_permanently' => [
    'fi' => 'Poista pysyvästi',
    'sv' => 'Ta bort permanent',
    'en' => 'Delete permanently',
    'it' => 'Elimina definitivamente',
    'el' => 'Διαγραφή οριστικά',
],
'btn_remove_image' => [
    'fi' => 'Poista kuva',
    'sv' => 'Ta bort bild',
    'en' => 'Remove image',
    'it' => 'Rimuovi immagine',
    'el' => 'Αφαίρεση εικόνας',
],
'btn_edit_main_image' => [
    'fi' => 'Muokkaa pääkuvaa',
    'sv' => 'Redigera huvudbild',
    'en' => 'Edit main image',
    'it' => 'Modifica immagine principale',
    'el' => 'Επεξεργασία κύριας εικόνας',
],
'btn_edit_image2' => [
    'fi' => 'Muokkaa lisäkuva 1',
    'sv' => 'Redigera extrabild 1',
    'en' => 'Edit image 2',
    'it' => 'Modifica immagine 2',
    'el' => 'Επεξεργασία εικόνας 2',
],
'btn_edit_image3' => [
    'fi' => 'Muokkaa lisäkuva 2',
    'sv' => 'Redigera extrabild 2',
    'en' => 'Edit image 3',
    'it' => 'Modifica immagine 3',
    'el' => 'Επεξεργασία εικόνας 3',
],
'btn_reset' => [
    'fi' => 'Palauta',
    'sv' => 'Återställ',
    'en' => 'Reset',
    'it' => 'Ripristina',
    'el' => 'Επαναφορά',
],
'btn_add' => [
    'fi' => 'Lisää',
    'sv' => 'Lägg till',
    'en' => 'Add',
    'it' => 'Aggiungi',
    'el' => 'Προσθήκη',
],
'btn_cancel' => [
    'fi' => 'Peruuta',
    'sv' => 'Avbryt',
    'en' => 'Cancel',
    'it' => 'Annulla',
    'el' => 'Ακύρωση',
],
'btn_delete' => [
    'fi' => 'Poista',
    'sv' => 'Ta bort',
    'en' => 'Delete',
    'it' => 'Elimina',
    'el' => 'Διαγραφή',
],
'btn_next' => [
    'fi' => 'Seuraava',
    'sv' => 'Nästa',
    'en' => 'Next',
    'it' => 'Avanti',
    'el' => 'Επόμενο',
],
'btn_prev' => [
    'fi' => 'Edellinen',
    'sv' => 'Föregående',
    'en' => 'Previous',
    'it' => 'Indietro',
    'el' => 'Προηγούμενο',
],
'btn_publish' => [
    'fi' => 'Julkaise',
    'sv' => 'Publicera',
    'en' => 'Publish',
    'it' => 'Pubblica',
    'el' => 'Δημοσίευση',
],
'btn_save' => [
    'fi' => 'Tallenna',
    'sv' => 'Spara',
    'en' => 'Save',
    'it' => 'Salva',
    'el' => 'Αποθήκευση',
],
'btn_save_draft' => [
    'fi' => 'Tallenna luonnos',
    'sv' => 'Spara utkast',
    'en' => 'Save draft',
    'it' => 'Salva bozza',
    'el' => 'Αποθήκευση πρόχειρου',
],
'btn_send_review' => [
    'fi' => 'Lähetä tarkistettavaksi',
    'sv' => 'Skicka för granskning',
    'en' => 'Send for Review',
    'it' => 'Invia per revisione',
    'el' => 'Αποστολή για έλεγχο',
],
'btn_ok_edit' => [
    'fi' => 'Siirry muokkaamaan',
    'sv' => 'Gå till redigering',
    'en' => 'Go to edit',
    'it' => 'Vai a modifica',
    'el' => 'Μετάβαση σε επεξεργασία',
],
'btn_comment_send' => [
    'fi' => 'Lähetä kommentti',
    'sv' => 'Skicka kommentar',
    'en' => 'Send comment',
    'it' => 'Invia commento',
    'el' => 'Αποστολή σχολίου',
],
'btn_send_request' => [
    'fi' => 'Pyydä lisätietoja',
    'sv' => 'Begär mer information',
    'en' => 'Request more information',
    'it' => 'Richiedi ulteriori informazioni',
    'el' => 'Ζήτα περισσότερες πληροφορίες',
],
'btn_send_comms' => [
    'fi' => 'Lähetä viestintään',
    'sv' => 'Skicka till kommunikation',
    'en' => 'Send to communications',
    'it' => 'Invia alla comunicazione',
    'el' => 'Αποστολή στο τμήμα επικοινωνίας',
],
'footer_edit' => [
    'fi' => 'Muokkaa',
    'sv' => 'Redigera',
    'en' => 'Edit',
    'it' => 'Modifica',
    'el' => 'Επεξεργασία',
],
'footer_comment' => [
    'fi' => 'Lisää kommentti',
    'sv' => 'Lägg till kommentar',
    'en' => 'Add comment',
    'it' => 'Aggiungi commento',
    'el' => 'Προσθήκη σχολίου',
],
'footer_return' => [
    'fi' => 'Palauta korjattavaksi',
    'sv' => 'Skicka tillbaka för korrigering',
    'en' => 'Return for corrections',
    'it' => 'Rimanda per correzioni',
    'el' => 'Επιστροφή για διόρθωση',
],
'footer_to_comms' => [
    'fi' => 'Lähetä viestintään',
    'sv' => 'Skicka till kommunikation',
    'en' => 'Send to communications',
    'it' => 'Invia alla comunicazione',
    'el' => 'Αποστολή στο τμήμα επικοινωνίας',
],
'footer_delete' => [
    'fi' => 'Poista',
    'sv' => 'Ta bort',
    'en' => 'Delete',
    'it' => 'Elimina',
    'el' => 'Διαγραφή',
],
'footer_publish' => [
    'fi' => 'Julkaise',
    'sv' => 'Publicera',
    'en' => 'Publish',
    'it' => 'Pubblica',
    'el' => 'Δημοσίευση',
],
'footer_publish_direct' => [
    'fi' => 'Julkaise',
    'sv' => 'Publicera',
    'en' => 'Publish',
    'it' => 'Pubblica',
    'el' => 'Δημοσίευση',
],
'btn_publish_direct' => [
    'fi' => 'Julkaise',
    'sv' => 'Publicera',
    'en' => 'Publish',
    'it' => 'Pubblica',
    'el' => 'Δημοσίευση',
],
'footer_send_to_review' => [
    'fi' => 'Lähetä tarkistettavaksi',
    'sv' => 'Skicka för granskning',
    'en' => 'Send for review',
    'it' => 'Invia per revisione',
    'el' => 'Αποστολή για έλεγχο',
],
'footer_settings' => [
    'fi' => 'Asetukset',
    'sv' => 'Inställningar',
    'en' => 'Settings',
    'it' => 'Impostazioni',
    'el' => 'Ρυθμίσεις',
],
'btn_save_translation' => [
    'fi' => 'Tallenna kieliversio',
    'en' => 'Save language version',
    'sv' => 'Spara språkversion',
    'it' => 'Salva versione linguistica',
    'el' => 'Αποθήκευση γλωσσικής έκδοσης',
],
'btn_back' => [
    'fi' => 'Takaisin',
    'sv' => 'Tillbaka',
    'en' => 'Back',
    'it' => 'Indietro',
    'el' => 'Πίσω',
],
'btn_close' => [
    'fi' => 'Sulje',
    'sv' => 'Stäng',
    'en' => 'Close',
    'it' => 'Chiudi',
    'el' => 'Κλείσιμο',
],
'btn_confirm' => [
    'fi' => 'Vahvista',
    'sv' => 'Bekräfta',
    'en' => 'Confirm',
    'it' => 'Conferma',
    'el' => 'Επιβεβαίωση',
],
'btn_confirm_yes' => [
    'fi' => 'Kyllä, lähetä',
    'sv' => 'Ja, skicka',
    'en' => 'Yes, send',
    'it' => 'Sì, invia',
    'el' => 'Ναι, αποστολή',
],
'btn_upload' => [
    'fi' => 'Lataa',
    'sv' => 'Ladda upp',
    'en' => 'Upload',
    'it' => 'Carica',
    'el' => 'Μεταφόρτωση',
],
'btn_take_photo' => [
    'fi' => 'Ota kuva',
    'sv' => 'Ta foto',
    'en' => 'Take photo',
    'it' => 'Scatta foto',
    'el' => 'Λήψη φωτογραφίας',
],
'btn_edit' => [
    'fi' => 'Muokkaa',
    'sv' => 'Redigera',
    'en' => 'Edit',
    'it' => 'Modifica',
    'el' => 'Επεξεργασία',
],
'btn_archive' => [
    'fi' => 'Arkistoi',
    'sv' => 'Arkivera',
    'en' => 'Archive',
    'it' => 'Archivia',
    'el' => 'Αρχειοθέτηση',
],
'footer_text' => [
    'fi' => 'Tapojärvi Safetyflash',
    'sv' => 'Tapojärvi Safetyflash',
    'en' => 'Tapojärvi Safetyflash',
    'it' => 'Tapojärvi Safetyflash',
    'el' => 'Tapojärvi Safetyflash',
],
'footer_send_to_supervisor' => [
    'fi' => 'Lähetä työmaavastaavalle',
    'sv' => 'Skicka till platschef',
    'en' => 'Send to Site Manager',
    'it' => 'Invia al responsabile di cantiere',
    'el' => 'Αποστολή στον υπεύθυνο εργοταξίου',
],
'footer_send_to_safety' => [
    'fi' => 'Lähetä turvatiimille',
    'sv' => 'Skicka till säkerhetsteamet',
    'en' => 'Send to Safety Team',
    'it' => 'Invia al team di sicurezza',
    'el' => 'Αποστολή στην ομάδα ασφαλείας',
],
'btn_remove' => [
    'fi' => 'Poista',
    'sv' => 'Ta bort',
    'en' => 'Remove',
    'it' => 'Rimuovi',
    'el' => 'Αφαίρεση',
],
'btn_create_translation' => [
    'fi' => 'Kyllä, luo kieliversio',
    'sv' => 'Ja, skapa språkversion',
    'en' => 'Yes, create language version',
    'it' => 'Sì, crea versione linguistica',
    'el' => 'Ναι, δημιουργία γλωσσικής έκδοσης',
],
'extra_images_add_button' => [
    'fi' => 'Lisää kuvia',
    'sv' => 'Lägg till bilder',
    'en' => 'Add images',
    'it' => 'Aggiungi immagini',
    'el' => 'Προσθήκη εικόνων',
],
'btn_add_language_version' => [
    'fi' => 'Tallenna ja lisää kieliversio',
    'sv' => 'Spara och lägg till språkversion',
    'en' => 'Save and add language version',
    'it' => 'Salva e aggiungi versione linguistica',
    'el' => 'Αποθήκευση και προσθήκη γλωσσικής έκδοσης',
],
'btn_add_language_version_title' => [
    'fi' => 'Tallenna ensin luonnoksena, luo sitten uusi kieliversio',
    'sv' => 'Spara först som utkast, skapa sedan ny språkversion',
    'en' => 'First save as draft, then create a new language version',
    'it' => 'Prima salva come bozza, poi crea una nuova versione linguistica',
    'el' => 'Πρώτα αποθηκεύστε ως πρόχειρο, στη συνέχεια δημιουργήστε νέα γλωσσική έκδοση',
],
'btn_send_bundle_review' => [
    'fi' => 'Lähetä kaikki (%d) tarkistettavaksi',
    'sv' => 'Skicka alla (%d) för granskning',
    'en' => 'Send all (%d) for review',
    'it' => 'Invia tutti (%d) per la revisione',
    'el' => 'Αποστολή όλων (%d) για έλεγχο',
],
'btn_close_form' => [
    'fi' => 'Sulje lomake',
    'sv' => 'Stäng formuläret',
    'en' => 'Close form',
    'it' => 'Chiudi modulo',
    'el' => 'Κλείσιμο φόρμας',
],
'btn_continue' => [
    'fi' => 'Jatka →',
    'sv' => 'Fortsätt →',
    'en' => 'Continue →',
    'it' => 'Continua →',
    'el' => 'Συνέχεια →',
],
'footer_merge_flash' => [
    'fi' => 'Yhdistä SafetyFlashiin',
    'sv' => 'Sammanfoga med SafetyFlash',
    'en' => 'Merge into SafetyFlash',
    'it' => 'Unisci a SafetyFlash',
    'el' => 'Σύνδεση στο SafetyFlash',
],
'btn_merge_flash' => [
    'fi' => 'Yhdistä valittu tiedote',
    'sv' => 'Sammanfoga valt meddelande',
    'en' => 'Merge selected flash',
    'it' => 'Unisci il SafetyFlash selezionato',
    'el' => 'Συγχώνευση επιλεγμένου SafetyFlash',
],
'btn_download_and_mark_athena' => [
    'fi' => 'Lataa PDF ja merkitse vietyksi',
    'sv' => 'Ladda ned PDF och markera som exporterad',
    'en' => 'Download PDF and mark as exported',
    'it' => 'Scarica PDF e segna come esportato',
    'el' => 'Λήψη PDF και σήμανση ως εξαγμένο',
],
'btn_already_exported_athena' => [
    'fi' => 'Olen jo vienyt sen',
    'sv' => 'Jag har redan exporterat det',
    'en' => 'I already exported it',
    'it' => 'L\'ho già esportato',
    'el' => 'Το έχω ήδη εξαγάγει',
],
'btn_remind_later' => [
    'fi' => 'Muistuta myöhemmin',
    'sv' => 'Påminn mig senare',
    'en' => 'Remind me later',
    'it' => 'Ricordamelo più tardi',
    'el' => 'Υπενθύμισέ μου αργότερα',
],
];