<?php
/**
 * General Terms - Common terms used across the application
 */
return [
'saving_flash' => [
    'fi' => 'Tallennetaan tiedotetta.. .',
    'sv' => 'Sparar meddelande...',
    'en' => 'Saving flash...',
    'it' => 'Salvataggio in corso...',
    'el' => 'Αποθήκευση ανακοίνωσης.. .',
],
'generating_preview' => [
    'fi' => 'Generoidaan esikatselukuvaa',
    'sv' => 'Genererar förhandsvisning',
    'en' => 'Generating preview image',
    'it' => 'Generazione anteprima',
    'el' => 'Δημιουργία προεπισκόπησης',
],
'db_error' => [
    'fi' => 'Tietokantavirhe.',
    'sv' => 'Databasfel.',
    'en' => 'Database error.',
    'it' => 'Errore del database.',
    'el' => 'Σφάλμα βάσης δεδομένων.',
],
'select_all' => [
    'fi' => 'Valitse kaikki',
    'sv' => 'Välj alla',
    'en' => 'Select all',
    'it' => 'Seleziona tutto',
    'el' => 'Επιλογή όλων',
],
'no_title' => [
    'fi' => '(Ei otsikkoa)',
    'sv' => '(Ingen titel)',
    'en' => '(No title)',
    'it' => '(Nessun titolo)',
    'el' => '(Χωρίς τίτλο)',
],
'processing_flash' => [
    'fi' => 'Safetyflashia prosessoidaan taustalla...',
    'sv' => 'Safetyflash bearbetas i bakgrunden...',
    'en' => 'Processing Safetyflash in the background...',
    'it' => 'Elaborazione Safetyflash in background.. .',
    'el' => 'Επεξεργασία Safetyflash στο παρασκήνιο...',
],
'cancel' => [
    'fi' => 'Peruuta',
    'sv' => 'Avbryt',
    'en' => 'Cancel',
    'it' => 'Annulla',
    'el' => 'Ακύρωση',
],
'image_uploaded' => [
    'fi' => 'Kuva ladattu',
    'sv' => 'Bild uppladdad',
    'en' => 'Image uploaded',
    'it' => 'Immagine caricata',
    'el' => 'Η εικόνα μεταφορτώθηκε',
],
'image_updated' => [
    'fi' => 'Kuva päivitetty',
    'sv' => 'Bild uppdaterad',
    'en' => 'Image updated',
    'it' => 'Immagine aggiornata',
    'el' => 'Η εικόνα ενημερώθηκε',
],
'image_deleted' => [
    'fi' => 'Kuva poistettu',
    'sv' => 'Bild borttagen',
    'en' => 'Image deleted',
    'it' => 'Immagine eliminata',
    'el' => 'Η εικόνα διαγράφηκε',
],
'edit_zoom_out' => [
    'fi' => 'Loitonna',
    'sv' => 'Zooma ut',
    'en' => 'Zoom out',
    'it' => 'Riduci',
    'el' => 'Σμίκρυνση',
],
'edit_zoom_in' => [
    'fi' => 'Lähennä',
    'sv' => 'Zooma in',
    'en' => 'Zoom in',
    'it' => 'Ingrandisci',
    'el' => 'Μεγέθυνση',
],
'edit_move_left' => [
    'fi' => 'Vasen',
    'sv' => 'Vänster',
    'en' => 'Left',
    'it' => 'Sinistra',
    'el' => 'Αριστερά',
],
'edit_move_right' => [
    'fi' => 'Oikea',
    'sv' => 'Höger',
    'en' => 'Right',
    'it' => 'Destra',
    'el' => 'Δεξιά',
],
'edit_move_up' => [
    'fi' => 'Ylös',
    'sv' => 'Upp',
    'en' => 'Up',
    'it' => 'Su',
    'el' => 'Επάνω',
],
'edit_move_down' => [
    'fi' => 'Alas',
    'sv' => 'Ner',
    'en' => 'Down',
    'it' => 'Giù',
    'el' => 'Κάτω',
],
'edit_reset' => [
    'fi' => 'Palauta',
    'sv' => 'Återställ',
    'en' => 'Reset',
    'it' => 'Ripristina',
    'el' => 'Επαναφορά',
],
'edit_close' => [
    'fi' => 'Sulje',
    'sv' => 'Stäng',
    'en' => 'Close',
    'it' => 'Chiudi',
    'el' => 'Κλείσιμο',
],
'selected_count_zero' => [
    'fi' => '0 valittu',
    'sv' => '0 valda',
    'en' => '0 selected',
    'it' => '0 selezionati',
    'el' => '0 επιλεγμένα',
],
'new_comments' => [
    'fi' => 'uutta kommenttia',
    'sv' => 'nya kommentarer',
    'en' => 'new comments',
    'it' => 'nuovi commenti',
    'el' => 'νέα σχόλια',
],
'bulk_delete_confirm_text' => [
    'fi' => 'Haluatko varmasti poistaa valitut tiedotteet?  Tämä poistaa myös kaikki liitetyt kuvat pysyvästi.',
    'sv' => 'Vill du verkligen ta bort de valda meddelandena? Detta tar även bort alla bifogade bilder permanent.',
    'en' => 'Are you sure you want to delete the selected bulletins? This will also permanently delete all attached images.',
    'it' => 'Sei sicuro di voler eliminare i bollettini selezionati? Questo eliminerà anche tutte le immagini allegate in modo permanente.',
    'el' => 'Είστε βέβαιοι ότι θέλετε να διαγράψετε τα επιλεγμένα δελτία; Αυτό θα διαγράψει επίσης όλες τις συνημμένες εικόνες μόνιμα.',
],
'deleting' => [
    'fi' => 'Poistetaan...',
    'sv' => 'Tar bort...',
    'en' => 'Deleting...',
    'it' => 'Eliminazione...',
    'el' => 'Διαγραφή...',
],
'delete_error' => [
    'fi' => 'Poistossa tapahtui virhe',
    'sv' => 'Ett fel uppstod vid borttagning',
    'en' => 'An error occurred while deleting',
    'it' => 'Si è verificato un errore durante l\'eliminazione',
    'el' => 'Παρουσιάστηκε σφάλμα κατά τη διαγραφή',
],
'CONFIRM_REMOVE_IMAGE' => [
    'fi' => 'Haluatko poistaa tämän kuvan? Kuva ja sen säädöt poistetaan.',
    'sv' => 'Vill du ta bort den här bilden? Bilden och dess inställningar tas bort.',
    'en' => 'Do you want to remove this image? The image and its settings will be removed.',
    'it' => 'Vuoi rimuovere questa immagine? L\'immagine e le sue impostazioni verranno rimosse.',
    'el' => 'Θέλετε να αφαιρέσετε αυτήν την εικόνα; Η εικόνα και οι ρυθμίσεις της θα αφαιρεθούν.',
],
'LABEL_PROMPT' => [
    'fi' => 'Kirjoita merkintä:',
    'sv' => 'Skriv anteckning:',
    'en' => 'Enter label:',
    'it' => 'Inserisci etichetta:',
    'el' => 'Εισάγετε σημείωση:',
],
'STATUS_CHANGED' => [
    'fi' => 'Tila muutettu',
    'sv' => 'Status ändrad',
    'en' => 'Status changed',
    'it' => 'Stato modificato',
    'el' => 'Η κατάσταση άλλαξε',
],
'CREATED' => [
    'fi' => 'Luotu',
    'sv' => 'Skapad',
    'en' => 'Created',
    'it' => 'Creato',
    'el' => 'Δημιουργήθηκε',
],
'INFO_REQUESTED' => [
    'fi' => 'Lisätietoa pyydetty',
    'sv' => 'Mer information begärd',
    'en' => 'Information requested',
    'it' => 'Informazioni richieste',
    'el' => 'Ζητήθηκαν πληροφορίες',
],
'COMMENT_ADDED' => [
    'fi' => 'Kommentti lisätty',
    'sv' => 'Kommentar tillagd',
    'en' => 'Comment added',
    'it' => 'Commento aggiunto',
    'el' => 'Προστέθηκε σχόλιο',
],
'SENT_TO_REVIEW' => [
    'fi' => 'Lähetetty tarkistukseen',
    'sv' => 'Skickat för granskning',
    'en' => 'Sent for review',
    'it' => 'Inviato per revisione',
    'el' => 'Εστάλη για έλεγχο',
],
'SENT_TO_COMMS' => [
    'fi' => 'Lähetetty viestintään',
    'sv' => 'Skickat till kommunikation',
    'en' => 'Sent to communications',
    'it' => 'Inviato alla comunicazione',
    'el' => 'Εστάλη στο τμήμα επικοινωνίας',
],
'TO_COMMS' => [
    'fi' => 'Lähetetty viestintään',
    'sv' => 'Skickat till kommunikation',
    'en' => 'Sent to communications',
    'it' => 'Inviato alla comunicazione',
    'el' => 'Εστάλη στο τμήμα επικοινωνίας',
],
'PUBLISHED' => [
    'fi' => 'Julkaistu',
    'sv' => 'Publicerad',
    'en' => 'Published',
    'it' => 'Pubblicato',
    'el' => 'Δημοσιεύτηκε',
],
'DELETED' => [
    'fi' => 'Poistettu',
    'sv' => 'Borttagen',
    'en' => 'Deleted',
    'it' => 'Eliminato',
    'el' => 'Διαγράφηκε',
],
'invalid_id' => [
    'fi' => 'Virheellinen tunniste.',
    'sv' => 'Ogiltigt ID.',
    'en' => 'Invalid ID.',
    'it' => 'ID non valido.',
    'el' => 'Μη έγκυρο αναγνωριστικό.',
],
'flash_not_found' => [
    'fi' => 'Safetyflashia ei löytynyt.',
    'sv' => 'Safetyflash hittades inte.',
    'en' => 'Safetyflash not found.',
    'it' => 'Safetyflash non trovato.',
    'el' => 'Δεν βρέθηκε το Safetyflash.',
],
'download_jpg' => [
    'fi' => 'Lataa JPG',
    'sv' => 'Ladda ner JPG',
    'en' => 'Download JPG',
    'it' => 'Scarica JPG',
    'el' => 'Λήψη JPG',
],
'download_preview' => [
    'fi' => 'Lataa JPG',
    'sv' => 'Ladda ner JPG',
    'en' => 'Download JPG',
    'it' => 'Scarica JPG',
    'el' => 'Λήψη JPG',
],
'download_card_1' => [
    'fi' => 'Lataa kortti 1',
    'sv' => 'Ladda ner kort 1',
    'en' => 'Download card 1',
    'it' => 'Scarica scheda 1',
    'el' => 'Λήψη κάρτας 1',
],
'no_results_hint' => [
    'fi' => 'Kokeile muuttaa suodattimia tai luo uusi tiedote.',
    'en' => 'Try adjusting your filters or create a new bulletin.',
    'sv' => 'Försök ändra filtren eller skapa ett nytt meddelande.',
    'it' => 'Prova a modificare i filtri o crea un nuovo bollettino.',
    'el' => 'Δοκιμάστε να αλλάξετε τα φίλτρα ή δημιουργήστε ένα νέο δελτίο.',
],
'download_card_2' => [
    'fi' => 'Lataa kortti 2',
    'sv' => 'Ladda ner kort 2',
    'en' => 'Download card 2',
    'it' => 'Scarica scheda 2',
    'el' => 'Λήψη κάρτας 2',
],
'investigation_added' => [
    'fi' => 'Tutkintatiedote lisätty',
    'sv' => 'Utredningsrapport tillagd',
    'en' => 'Investigation report added',
    'it' => 'Rapporto di indagine aggiunto',
    'el' => 'Προστέθηκε έκθεση έρευνας',
],
'type_changed' => [
    'fi' => 'Tyyppi muutettu',
    'sv' => 'Typ ändrad',
    'en' => 'Type changed',
    'it' => 'Tipo modificato',
    'el' => 'Ο τύπος άλλαξε',
],
'original_archived' => [
    'fi' => 'Alkuperäinen SafetyFlash arkistoitu',
    'sv' => 'Ursprunglig SafetyFlash arkiverad',
    'en' => 'Original SafetyFlash archived',
    'it' => 'SafetyFlash originale archiviato',
    'el' => 'Το αρχικό SafetyFlash αρχειοθετήθηκε',
],
'translations_archived' => [
    'fi' => 'Kieliversiot arkistoitu',
    'sv' => 'Språkversioner arkiverade',
    'en' => 'Translations archived',
    'it' => 'Traduzioni archiviate',
    'el' => 'Οι μεταφράσεις αρχειοθετήθηκαν',
],
'investigation_created' => [
    'fi' => 'Tutkintatiedote luotu',
    'sv' => 'Utredningsrapport skapad',
    'en' => 'Investigation report created',
    'it' => 'Rapporto di indagine creato',
    'el' => 'Δημιουργήθηκε έκθεση έρευνας',
],
'back_to_list' => [
    'fi' => 'Takaisin listaukseen',
    'sv' => 'Tillbaka till listan',
    'en' => 'Back to list',
    'it' => 'Torna alla lista',
    'el' => 'Πίσω στη λίστα',
],
'dangerous_situation' => [
    'fi' => 'Vaaratilanne',
    'sv' => 'Farlig situation',
    'en' => 'Dangerous situation',
    'it' => 'Situazione pericolosa',
    'el' => 'Επικίνδυνη κατάσταση',
],
'first_release' => [
    'fi' => 'Ensitiedote',
    'sv' => 'Första underrättelse',
    'en' => 'First release',
    'it' => 'Primo rilascio',
    'el' => 'Πρώτη δημοσίευση',
],
'investigation_report' => [
    'fi' => 'Tutkintatiedote',
    'sv' => 'Utredningsrapport',
    'en' => 'Investigation report',
    'it' => 'Rilascio dopo l\'indagine',
    'el' => 'Έκθεση έρευνας',
],
'month_names_short' => [
    'fi' => [
        'Tammi',
        'Helmi',
        'Maalis',
        'Huhti',
        'Touko',
        'Kesä',
        'Heinä',
        'Elo',
        'Syys',
        'Loka',
        'Marras',
        'Joulu',
    ],
    'sv' => [
        'Jan',
        'Feb',
        'Mar',
        'Apr',
        'Maj',
        'Jun',
        'Jul',
        'Aug',
        'Sep',
        'Okt',
        'Nov',
        'Dec',
    ],
    'en' => [
        'Jan',
        'Feb',
        'Mar',
        'Apr',
        'May',
        'Jun',
        'Jul',
        'Aug',
        'Sep',
        'Oct',
        'Nov',
        'Dec',
    ],
    'it' => [
        'Gen',
        'Feb',
        'Mar',
        'Apr',
        'Mag',
        'Giu',
        'Lug',
        'Ago',
        'Set',
        'Ott',
        'Nov',
        'Dic',
    ],
    'el' => [
        'Ιαν',
        'Φεβ',
        'Μαρ',
        'Απρ',
        'Μάι',
        'Ιούν',
        'Ιούλ',
        'Αύγ',
        'Σεπ',
        'Οκτ',
        'Νοέ',
        'Δεκ',
    ],
],
'no_results' => [
    'fi' => 'Ei tuloksia valituilla suodattimilla.',
    'sv' => 'Inga resultat med de valda filtren.',
    'en' => 'No results for the selected filters.',
    'it' => 'Nessun risultato con i filtri selezionati.',
    'el' => 'Δεν υπάρχουν αποτελέσματα για τα επιλεγμένα φίλτρα.',
],
'no_version' => [
    'fi' => 'ei kieliversiota',
    'sv' => 'ingen språkversion',
    'en' => 'no version',
    'it' => 'nessuna versione',
    'el' => 'δεν υπάρχει έκδοση',
],
'slider_help' => [
    'fi' => 'Klikkaa pääkuvaa tai pikkukuvaa ja säädä sen sijaintia sekä zoomia.',
    'sv' => 'Klicka på huvudbilden eller miniatyrbilden och justera dess position och zoom.',
    'en' => 'Click the main image or thumbnail and adjust its position and zoom.',
    'it' => 'Clicca sull\'immagine principale o sulla miniatura e regola la sua posizione e zoom.',
    'el' => 'Κάντε κλικ στην κύρια εικόνα ή τη μικρογραφία και ρυθμίστε τη θέση και το ζουμ της.',
],
'slider_reset' => [
    'fi' => 'Palauta oletukset',
    'sv' => 'Återställ standardvärden',
    'en' => 'Reset to defaults',
    'it' => 'Ripristina predefiniti',
    'el' => 'Επαναφορά προεπιλογών',
],
'image_selected' => [
    'fi' => 'Kuva valittu',
    'sv' => 'Bild vald',
    'en' => 'Image selected',
    'it' => 'Immagine selezionata',
    'el' => 'Επιλέχθηκε εικόνα',
],
'click_image_to_edit' => [
    'fi' => 'Klikkaa kuvaa muokataksesi',
    'sv' => 'Klicka på bilden för att redigera',
    'en' => 'Click image to edit',
    'it' => 'Clicca sull\'immagine per modificare',
    'el' => 'Κάντε κλικ στην εικόνα για επεξεργασία',
],
'common_yes' => [
    'fi' => 'Kyllä',
    'sv' => 'Ja',
    'en' => 'Yes',
    'it' => 'Sì',
    'el' => 'Ναι',
],
'common_no' => [
    'fi' => 'Ei',
    'sv' => 'Nej',
    'en' => 'No',
    'it' => 'No',
    'el' => 'Όχι',
],
'user_created_email_sent' => [
    'fi' => 'Käyttäjä luotu! Kirjautumistiedot lähetetty sähköpostiin.',
    'sv' => 'Användare skapad! Inloggningsuppgifter skickade via e-post.',
    'en' => 'User created! Login credentials sent via email.',
    'it' => 'Utente creato! Credenziali inviate via email.',
    'el' => 'Χρήστης δημιουργήθηκε! Τα διαπιστευτήρια στάλθηκαν μέσω email.',
],
'request_info_banner' => [
    'fi' => 'Vastuuhenkilö on pyytänyt lisätietoja. Täydennä tietoja ja lähetä uudelleen.',
    'sv' => 'Ansvarig har begärt mer information. Komplettera uppgifterna och skicka igen.',
    'en' => 'Responsible person has requested more information. Update the data and resend.',
    'it' => 'Il responsabile ha richiesto ulteriori informazioni. Aggiorna i dati e reinvia.',
    'el' => 'Ο υπεύθυνος ζήτησε περισσότερες πληροφορίες. Ενημερώστε τα στοιχεία και στείλτε ξανά.',
],
'logout_confirm_title' => [
    'fi' => 'Vahvista uloskirjautuminen',
    'sv' => 'Bekräfta utloggning',
    'en' => 'Confirm logout',
    'it' => 'Conferma disconnessione',
    'el' => 'Επιβεβαίωση αποσύνδεσης',
],
'logout_confirm_text' => [
    'fi' => 'Haluatko varmasti kirjautua ulos?',
    'sv' => 'Är du säker på att du vill logga ut?',
    'en' => 'Are you sure you want to log out?',
    'it' => 'Sei sicuro di voler uscire?',
    'el' => 'Θέλετε σίγουρα να αποσυνδεθείτε;',
],
'logout_confirm_cancel' => [
    'fi' => 'Peruuta',
    'sv' => 'Avbryt',
    'en' => 'Cancel',
    'it' => 'Annulla',
    'el' => 'Ακύρωση',
],
'logout_confirm_ok' => [
    'fi' => 'Kirjaudu ulos',
    'sv' => 'Logga ut',
    'en' => 'Log out',
    'it' => 'Esci',
    'el' => 'Αποσύνδεση',
],
'EDITED' => [
    'fi' => 'Muokattu',
    'sv' => 'Redigerad',
    'en' => 'Edited',
    'it' => 'Modificato',
    'el' => 'Επεξεργάστηκε',
],
'created' => [
    'fi' => 'Luotu',
    'sv' => 'Skapad',
    'en' => 'Created',
    'it' => 'Creato',
    'el' => 'Δημιουργήθηκε',
],
'edited' => [
    'fi' => 'Muokattu',
    'sv' => 'Redigerad',
    'en' => 'Edited',
    'it' => 'Modificato',
    'el' => 'Επεξεργάστηκε',
],
'state_changed' => [
    'fi' => 'Tila muutettu',
    'sv' => 'Status ändrad',
    'en' => 'Status changed',
    'it' => 'Stato modificato',
    'el' => 'Η κατάσταση άλλαξε',
],
'info_requested' => [
    'fi' => 'Lisätietoa pyydetty',
    'sv' => 'Mer information begärd',
    'en' => 'Information requested',
    'it' => 'Informazioni richieste',
    'el' => 'Ζητήθηκαν πληροφορίες',
],
'sent_to_review' => [
    'fi' => 'Lähetetty tarkistukseen',
    'sv' => 'Skickat för granskning',
    'en' => 'Sent for review',
    'it' => 'Inviato per revisione',
    'el' => 'Εστάλη για έλεγχο',
],
'sent_to_comms' => [
    'fi' => 'Lähetetty viestintään',
    'sv' => 'Skickat till kommunikation',
    'en' => 'Sent to communications',
    'it' => 'Inviato alla comunicazione',
    'el' => 'Εστάλη στο τμήμα επικοινωνίας',
],
'deleted' => [
    'fi' => 'Poistettu',
    'sv' => 'Borttagen',
    'en' => 'Deleted',
    'it' => 'Eliminato',
    'el' => 'Διαγράφηκε',
],
'type_red_desc' => [
    'fi' => 'Hoitoa vaativa tapaturma tai onnettomuus',
    'sv' => 'Olycka eller tillbud som kräver vård',
    'en' => 'Accident or incident requiring medical treatment',
    'it' => 'Infortunio o incidente che richiede cure mediche',
    'el' => 'Ατύχημα ή συμβάν που απαιτεί ιατρική φροντίδα',
],

'type_yellow_desc' => [
    'fi' => 'Kalustovaurio tai henkilövahinko ilman hoidon tarvetta',
    'sv' => 'Utrustningsskada eller personskada utan behov av vård',
    'en' => 'Equipment damage or personal injury without need for treatment',
    'it' => 'Danni alle attrezzature o infortunio senza necessità di cure',
    'el' => 'Ζημιά εξοπλισμού ή τραυματισμός χωρίς ανάγκη θεραπείας',
],
'site_detail_placeholder' => [
    'fi' => 'Esim. huoltohalli, murskaamo...',
    'sv' => 'T.ex. servicehall, kross...',
    'en' => 'E.g. maintenance hall, crusher...',
    'it' => 'Es. sala manutenzione, frantoio...',
    'el' => 'Π.χ. αίθουσα συντήρησης, θραυστήρας...',
],
'title_internal_placeholder' => [
    'fi' => 'Esim. Henkilön läheltä piti -tilanne kaivoksella',
    'sv' => 'T.ex. Nära ögat-situation för person vid gruvan',
    'en' => 'E.g. Near miss incident at the mine',
    'it' => 'Es. Quasi incidente alla miniera',
    'el' => 'Π.χ. Παραλίγο ατύχημα στο ορυχείο',
],
'description_placeholder' => [
    'fi' => 'Kerro tässä mitä tapahtui ja tämän hetkinen tilanne.',
    'sv' => 'Beskriv här vad som hände och nuläget.',
    'en' => 'Describe what happened and the current situation.',
    'it' => 'Descrivi cosa è successo e la situazione attuale.',
    'el' => 'Περιγράψτε τι συνέβη και την τρέχουσα κατάσταση.',
],
'root_causes_help' => [
    'fi' => 'Kirjaa selkeästi yksi juurisyy kullekin riville.',
    'sv' => 'Skriv tydligt en grundorsak per rad.',
    'en' => 'Write one root cause per line.',
    'it' => 'Scrivi una causa principale per riga.',
    'el' => 'Γράψτε μία αιτία ανά γραμμή.',
],
'actions_help' => [
    'fi' => 'Kirjaa konkreettiset toimenpiteet listana, yksi per rivi.',
    'sv' => 'Skriv konkreta åtgärder som lista, en per rad.',
    'en' => 'List concrete actions, one per line.',
    'it' => 'Elenca le azioni concrete, una per riga.',
    'el' => 'Καταγράψτε συγκεκριμένες ενέργειες, μία ανά γραμμή.',
],
'related_flash_placeholder' => [
    'fi' => 'Valitse tiedote...',
    'sv' => 'Välj meddelande...',
    'en' => 'Select flash...',
    'it' => 'Seleziona comunicazione...',
    'el' => 'Επιλέξτε ανακοίνωση...',
],
'related_flash_help' => [
    'fi' => 'Valitse ensitiedote tai vaaratilanne, jota tutkintatiedote täydentää.',
    'sv' => 'Välj den första underrättelsen eller farliga situationen som utredningsrapporten kompletterar.',
    'en' => 'Select the first release or dangerous situation that this investigation report supplements.',
    'it' => 'Seleziona il primo rilascio o la situazione pericolosa che questo rapporto di indagine integra.',
    'el' => 'Επιλέξτε την πρώτη δημοσίευση ή την επικίνδυνη κατάσταση που συμπληρώνει αυτή η έκθεση διερεύνησης.',
],
'copied_from_base_placeholder' => [
    'fi' => 'Kopioidaan pohjatiedotteesta – voit muokata tarvittaessa.',
    'sv' => 'Kopieras från basmeddelandet – du kan ändra vid behov.',
    'en' => 'Copied from base flash – you can edit if needed.',
    'it' => 'Copiato dalla comunicazione base – puoi modificare se necessario.',
    'el' => 'Αντιγράφεται από τη βασική ανακοίνωση – μπορείτε να επεξεργαστείτε αν χρειαστεί.',
],
'investigation_fields_help' => [
    'fi' => 'Nämä kentät kopioidaan valitusta ensitiedotteesta/vaaratilanteesta. Voit tarkentaa, jos tiedot ovat muuttuneet.',
    'sv' => 'Dessa fält kopieras från vald första underrättelse/farlig situation.  Du kan ändra om uppgifterna har ändrats.',
    'en' => 'These fields are copied from the selected first release/dangerous situation. You can update if the information has changed.',
    'it' => 'Questi campi vengono copiati dal primo rilascio/situazione pericolosa selezionato.  Puoi aggiornare se le informazioni sono cambiate.',
    'el' => 'Αυτά τα πεδία αντιγράφονται από την επιλεγμένη πρώτη δημοσίευση/επικίνδυνη κατάσταση. Μπορείτε να ενημερώσετε αν οι πληροφορίες έχουν αλλάξει.',
],
'short_text_placeholder' => [
    'fi' => 'Tiivis kuvaus, joka näkyy kortin otsikkona.',
    'sv' => 'Kort beskrivning som visas som kortets rubrik.',
    'en' => 'Brief description shown as the card title.',
    'it' => 'Breve descrizione mostrata come titolo della scheda.',
    'el' => 'Σύντομη περιγραφή που εμφανίζεται ως τίτλος κάρτας.',
],
'root_causes_placeholder' => [
    'fi' => '- Juurisyy 1 - Juurisyy 2',
    'sv' => '- Grundorsak 1 - Grundorsak 2',
    'en' => '- Root cause 1 - Root cause 2',
    'it' => '- Causa principale 1 - Causa principale 2',
    'el' => '- Αιτία 1 - Αιτία 2',
],
'actions_placeholder' => [
    'fi' => '- Toimenpide 1 - Toimenpide 2',
    'sv' => '- Åtgärd 1 - Åtgärd 2',
    'en' => '- Action 1 - Action 2',
    'it' => '- Azione 1 - Azione 2',
    'el' => '- Ενέργεια 1 - Ενέργεια 2',
],
'translation_target_lang' => [
    'fi' => 'Kohdekieli',
    'en' => 'Target language',
    'sv' => 'Målspråk',
    'it' => 'Lingua di destinazione',
    'el' => 'Γλώσσα στόχος',
],
'translation_help' => [
    'fi' => 'Käännä tekstit ja paina Tallenna.  Kuvat kopioidaan automaattisesti.',
    'en' => 'Translate the texts and press Save. Images are copied automatically.',
    'sv' => 'Översätt texterna och tryck Spara.  Bilder kopieras automatiskt.',
    'it' => 'Traduci i testi e premi Salva. Le immagini vengono copiate automaticamente.',
    'el' => 'Μεταφράστε τα κείμενα και πατήστε Αποθήκευση.  Οι εικόνες αντιγράφονται αυτόματα.',
],
'image_library_btn' => [
    'fi' => 'Kuvapankki',
    'en' => 'Image library',
    'sv' => 'Bildbank',
    'it' => 'Scegli dalla libreria',
    'el' => 'Επιλέξτε από τη βιβλιοθήκη',
],
'btn_upload' => [
    'fi' => 'Lataa',
    'sv' => 'Ladda upp',
    'en' => 'Upload',
    'it' => 'Carica',
    'el' => 'Μεταφόρτωση',
],
'image_library_help' => [
    'fi' => 'Valitse valmis hahmokuva tai pohja, johon voit lisätä merkintöjä.',
    'en' => 'Choose a ready-made figure or template to add annotations.',
    'sv' => 'Välj en färdig figur eller mall att lägga till markeringar på.',
    'it' => 'Scegli una figura o un modello pronto per aggiungere annotazioni.',
    'el' => 'Επιλέξτε μια έτοιμη φιγούρα ή πρότυπο για να προσθέσετε σημειώσεις.',
],
'image_library_title' => [
    'fi' => 'Kuvapankki',
    'en' => 'Image Library',
    'sv' => 'Bildbibliotek',
    'it' => 'Libreria immagini',
    'el' => 'Βιβλιοθήκη εικόνων',
],
'flash_comment' => [
    'fi' => 'Kommentti lisätty',
    'en' => 'Comment added',
    'sv' => 'Kommentar tillagd',
    'it' => 'Commento aggiunto',
    'el' => 'Προστέθηκε σχόλιο',
],
'flash_edit' => [
    'fi' => 'Tiedote muokattu',
    'en' => 'Flash edited',
    'sv' => 'Meddelande redigerat',
    'it' => 'Comunicazione modificata',
    'el' => 'Ανακοίνωση επεξεργάστηκε',
],
'flash_delete' => [
    'fi' => 'Tiedote poistettu',
    'en' => 'Flash deleted',
    'sv' => 'Meddelande borttaget',
    'it' => 'Comunicazione eliminata',
    'el' => 'Ανακοίνωση διαγράφηκε',
],
'flash_status_change' => [
    'fi' => 'Tilan muutos',
    'en' => 'Status changed',
    'sv' => 'Status ändrad',
    'it' => 'Stato modificato',
    'el' => 'Η κατάσταση άλλαξε',
],
'flash_send_review' => [
    'fi' => 'Lähetetty tarkistettavaksi',
    'en' => 'Sent for review',
    'sv' => 'Skickat för granskning',
    'it' => 'Inviato per revisione',
    'el' => 'Στάλθηκε για έλεγχο',
],
'flash_send_comms' => [
    'fi' => 'Lähetetty viestintään',
    'en' => 'Sent to communications',
    'sv' => 'Skickat till kommunikation',
    'it' => 'Inviato alla comunicazione',
    'el' => 'Στάλθηκε στο τμήμα επικοινωνίας',
],
'flash_publish' => [
    'fi' => 'Tiedote julkaistu',
    'en' => 'Flash published',
    'sv' => 'Meddelande publicerat',
    'it' => 'Comunicazione pubblicata',
    'el' => 'Ανακοίνωση δημοσιεύτηκε',
],
'flash_info_request' => [
    'fi' => 'Lisätietoja pyydetty',
    'en' => 'Information requested',
    'sv' => 'Mer information begärd',
    'it' => 'Informazioni richieste',
    'el' => 'Ζητήθηκαν πληροφορίες',
],
'login' => [
    'fi' => 'Kirjautuminen',
    'en' => 'Login',
    'sv' => 'Inloggning',
    'it' => 'Accesso',
    'el' => 'Σύνδεση',
],
'logout' => [
    'fi' => 'Uloskirjautuminen',
    'en' => 'Logout',
    'sv' => 'Utloggning',
    'it' => 'Disconnessione',
    'el' => 'Αποσύνδεση',
],
'user_create' => [
    'fi' => 'Käyttäjä luotu',
    'en' => 'User created',
    'sv' => 'Användare skapad',
    'it' => 'Utente creato',
    'el' => 'Χρήστης δημιουργήθηκε',
],
'user_update' => [
    'fi' => 'Käyttäjä päivitetty',
    'en' => 'User updated',
    'sv' => 'Användare uppdaterad',
    'it' => 'Utente aggiornato',
    'el' => 'Χρήστης ενημερώθηκε',
],
'user_delete' => [
    'fi' => 'Käyttäjä poistettu',
    'en' => 'User deleted',
    'sv' => 'Användare borttagen',
    'it' => 'Utente eliminato',
    'el' => 'Χρήστης διαγράφηκε',
],
'flash_to_comms' => [
    'fi' => 'Lähetetty viestintään',
    'en' => 'Sent to communications',
    'sv' => 'Skickat till kommunikation',
    'it' => 'Inviato alla comunicazione',
    'el' => 'Στάλθηκε στο τμήμα επικοινωνίας',
],
'user_password_reset' => [
    'fi' => 'Salasana nollattu',
    'en' => 'Password reset',
    'sv' => 'Lösenord återställt',
    'it' => 'Password reimpostata',
    'el' => 'Επαναφορά κωδικού',
],
'image_library_add' => [
    'fi' => 'Kuva lisätty kuvapankkiin',
    'en' => 'Image added to library',
    'sv' => 'Bild tillagd i bildbibliotek',
    'it' => 'Immagine aggiunta alla libreria',
    'el' => 'Εικόνα προστέθηκε στη βιβλιοθήκη',
],
'image_library_delete' => [
    'fi' => 'Kuva poistettu kuvapankista',
    'en' => 'Image deleted from library',
    'sv' => 'Bild borttagen från bildbibliotek',
    'it' => 'Immagine eliminata dalla libreria',
    'el' => 'Εικόνα διαγράφηκε από τη βιβλιοθήκη',
],
'image_library_toggle' => [
    'fi' => 'Kuvan näkyvyys muutettu',
    'en' => 'Image visibility changed',
    'sv' => 'Bildens synlighet ändrad',
    'it' => 'Visibilità immagine modificata',
    'el' => 'Η ορατότητα εικόνας άλλαξε',
],
'two_slides_notice_title' => [
    'fi' => 'Sisältö jaetaan kahdelle kortille',
    'sv' => 'Innehållet delas på två kort',
    'en' => 'Content will be split into two cards',
    'it' => 'Il contenuto sarà diviso in due schede',
    'el' => 'Το περιεχόμενο θα χωριστεί σε δύο κάρτες',
],
'two_slides_notice_text' => [
    'fi' => 'Tekstin määrän vuoksi tiedote näytetään kahdella dialla: yhteenveto ja juurisyyt/toimenpiteet.',
    'sv' => 'På grund av textmängden visas meddelandet på två bilder: sammanfattning och grundorsaker/åtgärder.',
    'en' => 'Due to the amount of text, the flash will be displayed on two slides: summary and root causes/actions.',
    'it' => 'A causa della quantità di testo, la comunicazione verrà visualizzata su due diapositive.',
    'el' => 'Λόγω του όγκου κειμένου, η ανακοίνωση θα εμφανιστεί σε δύο διαφάνειες.',
],
'login_success' => [
    'fi' => 'Kirjautuminen onnistui',
    'sv' => 'Inloggning lyckades',
    'en' => 'Login successful',
    'it' => 'Accesso riuscito',
    'el' => 'Επιτυχής σύνδεση',
],
'login_failed' => [
    'fi' => 'Kirjautuminen epäonnistui',
    'sv' => 'Inloggning misslyckades',
    'en' => 'Login failed',
    'it' => 'Accesso fallito',
    'el' => 'Αποτυχία σύνδεσης',
],
'flash_create' => [
    'fi' => 'Safetyflash luotu',
    'sv' => 'Safetyflash skapad',
    'en' => 'Safetyflash created',
    'it' => 'Safetyflash creato',
    'el' => 'Δημιουργήθηκε Safetyflash',
],
'flash_update' => [
    'fi' => 'Safetyflash muokattu',
    'sv' => 'Safetyflash uppdaterad',
    'en' => 'Safetyflash updated',
    'it' => 'Safetyflash aggiornato',
    'el' => 'Ενημερώθηκε Safetyflash',
],
'flash_bulk_delete' => [
    'fi' => 'Useita safetyflasheja poistettu',
    'sv' => 'Flera safetyflash raderade',
    'en' => 'Multiple safetyflashes deleted',
    'it' => 'Più safetyflash eliminati',
    'el' => 'Διαγράφηκαν πολλά Safetyflash',
],
'bulk_select_all' => [
    'fi' => 'Valitse kaikki',
    'sv' => 'Välj alla',
    'en' => 'Select all',
    'it' => 'Seleziona tutto',
    'el' => 'Επιλογή όλων',
],
'bulk_selected_suffix' => [
    'fi' => 'valittu',
    'sv' => 'valda',
    'en' => 'selected',
    'it' => 'selezionati',
    'el' => 'επιλεγμένα',
],
'bulk_delete' => [
    'fi' => 'Poista valitut',
    'sv' => 'Ta bort valda',
    'en' => 'Delete selected',
    'it' => 'Elimina selezionati',
    'el' => 'Διαγραφή επιλεγμένων',
],
'bulk_confirm_title' => [
    'fi' => 'Vahvista poisto',
    'sv' => 'Bekräfta borttagning',
    'en' => 'Confirm deletion',
    'it' => 'Conferma eliminazione',
    'el' => 'Επιβεβαίωση διαγραφής',
],
'bulk_confirm_text' => [
    'fi' => 'Haluatko varmasti poistaa valitut tiedotteet?  Tämä poistaa myös kaikki liitetyt kuvat pysyvästi.',
    'sv' => 'Vill du verkligen ta bort de valda meddelandena? Detta raderar även alla bifogade bilder permanent.',
    'en' => 'Are you sure you want to delete the selected alerts? This will also permanently delete all attached images.',
    'it' => 'Sei sicuro di voler eliminare gli avvisi selezionati? Questo eliminerà anche tutte le immagini allegate in modo permanente.',
    'el' => 'Είστε σίγουροι ότι θέλετε να διαγράψετε τις επιλεγμένες ειδοποιήσεις; Αυτό θα διαγράψει επίσης όλες τις συνημμένες εικόνες μόνιμα.',
],
'bulk_confirm_delete' => [
    'fi' => 'Poista pysyvästi',
    'sv' => 'Ta bort permanent',
    'en' => 'Delete permanently',
    'it' => 'Elimina definitivamente',
    'el' => 'Διαγραφή μόνιμα',
],
'bulk_deleting' => [
    'fi' => 'Poistetaan.. .',
    'sv' => 'Tar bort...',
    'en' => 'Deleting...',
    'it' => 'Eliminazione...',
    'el' => 'Διαγραφή...',
],
'bulk_confirm_title_users' => [
    'fi' => 'Vahvista toiminto',
    'sv' => 'Bekräfta åtgärd',
    'en' => 'Confirm action',
    'it' => 'Conferma azione',
    'el' => 'Επιβεβαίωση ενέργειας',
],
'confirmEnableEmails' => [
    'fi' => 'Otetaanko sähköpostit käyttöön valituille käyttäjille?',
    'sv' => 'Aktivera e-post för valda användare?',
    'en' => 'Enable emails for selected users?',
    'it' => 'Abilitare le email per gli utenti selezionati?',
    'el' => 'Ενεργοποίηση email για επιλεγμένους χρήστες;',
],
'confirmDisableEmails' => [
    'fi' => 'Poistetaanko sähköpostit käytöstä valituilla käyttäjillä?',
    'sv' => 'Inaktivera e-post för valda användare?',
    'en' => 'Disable emails for selected users?',
    'it' => 'Disabilitare le email per gli utenti selezionati?',
    'el' => 'Απενεργοποίηση email για επιλεγμένους χρήστες;',
],
'bulkSuccess' => [
    'fi' => 'Toiminto suoritettu onnistuneesti',
    'sv' => 'Åtgärden genomfördes framgångsrikt',
    'en' => 'Action completed successfully',
    'it' => 'Azione completata con successo',
    'el' => 'Η ενέργεια ολοκληρώθηκε επιτυχώς',
],
'user_not_found' => [
    'fi' => 'Käyttäjää ei löytynyt',
    'sv' => 'Användaren hittades inte',
    'en' => 'User not found',
    'it' => 'Utente non trovato',
    'el' => 'Ο χρήστης δεν βρέθηκε',
],
'inactive' => [
    'fi' => 'Käyttäjä ei ole aktiivinen',
    'sv' => 'Användaren är inte aktiv',
    'en' => 'User is not active',
    'it' => 'Utente non attivo',
    'el' => 'Ο χρήστης δεν είναι ενεργός',
],
'wrong_password' => [
    'fi' => 'Väärä salasana',
    'sv' => 'Fel lösenord',
    'en' => 'Wrong password',
    'it' => 'Password errata',
    'el' => 'Λάθος κωδικός',
],
'processing_safetyflash' => [
    'fi' => 'Safetyflashia prosessoidaan taustalla...',
    'sv' => 'Safetyflash bearbetas i bakgrunden...',
    'en' => 'Safetyflash is being processed in the background...',
    'it' => 'Safetyflash viene elaborata in background...',
    'el' => 'Το Safetyflash επεξεργάζεται στο παρασκήνιο...',
],
'type_green_desc' => [
    'fi' => 'Tutkinta valmis – toimenpiteet määritelty',
    'sv' => 'Utredning klar – åtgärder fastställda',
    'en' => 'Investigation complete – actions defined',
    'it' => 'Indagine completata – azioni definite',
    'el' => 'Έρευνα ολοκληρώθηκε – καθορίστηκαν ενέργειες',
],
'processing_complete' => [
    'fi' => 'Prosessointi valmis!',
    'sv' => 'Bearbetning klar!',
    'en' => 'Processing complete!',
    'it' => 'Elaborazione completata!',
    'el' => 'Η επεξεργασία ολοκληρώθηκε!',
],
'please_wait' => [
    'fi' => 'Odota hetki...',
    'sv' => 'Vänta...',
    'en' => 'Please wait...',
    'it' => 'Attendere...',
    'el' => 'Παρακαλώ περιμένετε...',
],
'saving_draft' => [
    'fi' => 'Tallennetaan luonnosta...',
    'sv' => 'Sparar utkast...',
    'en' => 'Saving draft...',
    'it' => 'Salvataggio bozza...',
    'el' => 'Αποθήκευση προσχεδίου...',
],
'starting_submission' => [
    'fi' => 'Käynnistetään lähetystä...',
    'sv' => 'Startar inlämning...',
    'en' => 'Starting submission...',
    'it' => 'Avvio invio...',
    'el' => 'Έναρξη υποβολής...',
],
'draft_saved' => [
    'fi' => 'Luonnos tallennettu.',
    'sv' => 'Utkast sparat.',
    'en' => 'Draft saved.',
    'it' => 'Bozza salvata.',
    'el' => 'Το πρόχειρο αποθηκεύτηκε.',
],
'sending_for_review' => [
    'fi' => 'Lähetetään tarkistettavaksi.',
    'sv' => 'Skickas för granskning.',
    'en' => 'Sending for review.',
    'it' => 'Invio per revisione.',
    'el' => 'Αποστολή για έλεγχο.',
],
'saving_changes' => [
    'fi' => 'Tallennetaan muutoksia...',
    'sv' => 'Sparar ändringar...',
    'en' => 'Saving changes...',
    'it' => 'Salvataggio modifiche...',
    'el' => 'Αποθήκευση αλλαγών...',
],
'changes_saved' => [
    'fi' => 'Muutokset tallennettu.',
    'sv' => 'Ändringar sparade.',
    'en' => 'Changes saved.',
    'it' => 'Modifiche salvate.',
    'el' => 'Αλλαγές αποθηκεύτηκαν.',
],
'processing_continues' => [
    'fi' => 'Prosessointi jatkuu taustalla.',
    'sv' => 'Bearbetning fortsätter i bakgrunden.',
    'en' => 'Processing continues in background.',
    'it' => 'L\'elaborazione continua in background.',
    'el' => 'Η επεξεργασία συνεχίζεται στο παρασκήνιο.',
],
'data_received_processing' => [
    'fi' => 'Tiedot vastaanotettu. Prosessointi jatkuu taustalla.',
    'sv' => 'Data mottagen. Bearbetning fortsätter i bakgrunden.',
    'en' => 'Data received. Processing continues in background.',
    'it' => 'Dati ricevuti. L\'elaborazione continua in background.',
    'el' => 'Τα δεδομένα ελήφθησαν. Η επεξεργασία συνεχίζεται στο παρασκήνιο.',
],
'save_failed' => [
    'fi' => 'Tallennus epäonnistui: ',
    'sv' => 'Spara misslyckades: ',
    'en' => 'Save failed: ',
    'it' => 'Salvataggio fallito: ',
    'el' => 'Αποτυχία αποθήκευσης: ',
],
'processing_failed' => [
    'fi' => 'Prosessointi epäonnistui.',
    'sv' => 'Bearbetning misslyckades.',
    'en' => 'Processing failed.',
    'it' => 'Elaborazione fallita.',
    'el' => 'Η επεξεργασία απέτυχε.',
],
'processing_error_refresh' => [
    'fi' => 'Virhe tilan tarkistuksessa. Ole hyvä ja päivitä sivu.',
    'sv' => 'Fel vid statuskontroll. Vänligen uppdatera sidan.',
    'en' => 'Error checking status. Please refresh the page.',
    'it' => 'Errore nel controllo dello stato. Aggiorna la pagina.',
    'el' => 'Σφάλμα ελέγχου κατάστασης. Ανανεώστε τη σελίδα.',
],
'LOG_FLASH_EDITED_NO_STATUS_CHANGE' => [
    'fi' => 'Tiedotetta muokattu (ei tilamuutosta)',
    'en' => 'Flash edited (no status change)',
    'sv' => 'Flash redigerad (ingen statusändring)',
    'it' => 'Flash modificato (nessun cambio di stato)',
    'el' => 'Το flash επεξεργάστηκε (χωρίς αλλαγή κατάστασης)',
],
'original_safetyflash' => [
    'fi' => 'Alkuperäinen SafetyFlash',
    'sv' => 'Ursprunglig SafetyFlash',
    'en' => 'Original SafetyFlash',
    'it' => 'SafetyFlash originale',
    'el' => 'Αρχικό SafetyFlash',
],
'language_version' => [
    'fi' => 'Kieliversio',
    'sv' => 'Språkversion',
    'en' => 'Language version',
    'it' => 'Versione linguistica',
    'el' => 'Γλωσσική έκδοση',
],
'delete_original_confirm_title' => [
    'fi' => 'Poista alkuperäinen SafetyFlash',
    'sv' => 'Ta bort ursprunglig SafetyFlash',
    'en' => 'Delete original SafetyFlash',
    'it' => 'Elimina SafetyFlash originale',
    'el' => 'Διαγραφή αρχικού SafetyFlash',
],
'delete_original_confirm_message' => [
    'fi' => 'Olet poistamassa alkuperäistä SafetyFlashia. Tämä poistaa myös kaikki kieliversiot.',
    'sv' => 'Du håller på att ta bort den ursprungliga SafetyFlash. Detta tar också bort alla språkversioner.',
    'en' => 'You are about to delete the original SafetyFlash. This will also delete all language versions.',
    'it' => 'Stai per eliminare il SafetyFlash originale. Questo eliminerà anche tutte le versioni linguistiche.',
    'el' => 'Πρόκειται να διαγράψετε το αρχικό SafetyFlash. Αυτό θα διαγράψει επίσης όλες τις γλωσσικές εκδόσεις.',
],
'delete_original_versions_count' => [
    'fi' => 'Kieliversioita poistetaan: %d',
    'sv' => 'Språkversioner som tas bort: %d',
    'en' => 'Language versions to be deleted: %d',
    'it' => 'Versioni linguistiche da eliminare: %d',
    'el' => 'Γλωσσικές εκδόσεις προς διαγραφή: %d',
],
'delete_translation_confirm_title' => [
    'fi' => 'Poista kieliversio',
    'sv' => 'Ta bort språkversion',
    'en' => 'Delete language version',
    'it' => 'Elimina versione linguistica',
    'el' => 'Διαγραφή γλωσσικής έκδοσης',
],
'delete_translation_confirm_message' => [
    'fi' => 'Olet poistamassa kieliversiota. Alkuperäinen SafetyFlash ja muut kieliversiot säilyvät.',
    'sv' => 'Du håller på att ta bort en språkversion. Den ursprungliga SafetyFlash och andra språkversioner bevaras.',
    'en' => 'You are about to delete a language version. The original SafetyFlash and other language versions will be preserved.',
    'it' => 'Stai per eliminare una versione linguistica. Il SafetyFlash originale e le altre versioni linguistiche saranno conservate.',
    'el' => 'Πρόκειται να διαγράψετε μια γλωσσική έκδοση. Το αρχικό SafetyFlash και οι άλλες γλωσσικές εκδόσεις θα διατηρηθούν.',
],
'delete_translation_which' => [
    'fi' => 'Poistettava kieliversio: %s',
    'sv' => 'Språkversion som tas bort: %s',
    'en' => 'Language version to be deleted: %s',
    'it' => 'Versione linguistica da eliminare: %s',
    'el' => 'Γλωσσική έκδοση προς διαγραφή: %s',
],
'archive_confirm_title' => [
    'fi' => 'Arkistoi SafetyFlash',
    'sv' => 'Arkivera SafetyFlash',
    'en' => 'Archive SafetyFlash',
    'it' => 'Archivia SafetyFlash',
    'el' => 'Αρχειοθέτηση SafetyFlash',
],
'archive_confirm_message' => [
    'fi' => 'Arkistoinnin jälkeen SafetyFlashia ei voi enää muokata. Teksti ja kuva säilyvät.',
    'sv' => 'Efter arkivering kan SafetyFlash inte längre redigeras. Text och bild bevaras.',
    'en' => 'After archiving, SafetyFlash cannot be edited anymore. Text and image will be preserved.',
    'it' => 'Dopo l\'archiviazione, SafetyFlash non può più essere modificato. Testo e immagine saranno conservati.',
    'el' => 'Μετά την αρχειοθέτηση, το SafetyFlash δεν μπορεί να επεξεργαστεί. Το κείμενο και η εικόνα θα διατηρηθούν.',
],
'archive_success' => [
    'fi' => 'SafetyFlash arkistoitu onnistuneesti',
    'sv' => 'SafetyFlash arkiverad',
    'en' => 'SafetyFlash archived successfully',
    'it' => 'SafetyFlash archiviato con successo',
    'el' => 'Το SafetyFlash αρχειοθετήθηκε επιτυχώς',
],
'archive_log_message' => [
    'fi' => 'SafetyFlash arkistoitu',
    'sv' => 'SafetyFlash arkiverad',
    'en' => 'SafetyFlash archived',
    'it' => 'SafetyFlash archiviato',
    'el' => 'Το SafetyFlash αρχειοθετήθηκε',
],
'archiving_in_progress' => [
    'fi' => 'Arkistoidaan...',
    'sv' => 'Arkiverar...',
    'en' => 'Archiving...',
    'it' => 'Archiviazione...',
    'el' => 'Αρχειοθέτηση...',
],
'cannot_edit_archived' => [
    'fi' => 'Arkistoitua SafetyFlashia ei voi muokata',
    'sv' => 'Arkiverad SafetyFlash kan inte redigeras',
    'en' => 'Archived SafetyFlash cannot be edited',
    'it' => 'SafetyFlash archiviato non può essere modificato',
    'el' => 'Το αρχειοθετημένο SafetyFlash δεν μπορεί να επεξεργαστεί',
],
'draft_recovery_title' => [
    'fi' => 'Sinulla on keskeneräinen SafetyFlash',
    'sv' => 'Du har ett ofullständigt SafetyFlash',
    'en' => 'You have an unfinished SafetyFlash',
    'it' => 'Hai un SafetyFlash incompleto',
    'el' => 'Έχετε ένα ημιτελές SafetyFlash',
],
'draft_recovery_message' => [
    'fi' => 'Valitse haluatko jatkaa vai aloittaa alusta.',
    'sv' => 'Välj om du vill fortsätta eller börja om.',
    'en' => 'Choose whether to continue or start over.',
    'it' => 'Scegli se continuare o ricominciare.',
    'el' => 'Επιλέξτε αν θέλετε να συνεχίσετε ή να ξεκινήσετε από την αρχή.',
],
'draft_continue' => [
    'fi' => 'Jatka',
    'sv' => 'Fortsätt',
    'en' => 'Continue',
    'it' => 'Continua',
    'el' => 'Συνέχεια',
],
'draft_discard' => [
    'fi' => 'Hylkää',
    'sv' => 'Kassera',
    'en' => 'Discard',
    'it' => 'Elimina',
    'el' => 'Απόρριψη',
],
'draft_start_new' => [
    'fi' => 'Hylkää kaikki ja aloita uusi',
    'sv' => 'Kassera alla och börja ny',
    'en' => 'Discard all and start new',
    'it' => 'Elimina tutto e inizia nuovo',
    'el' => 'Απόρριψη όλων και έναρξη νέου',
],
'autosave_saved' => [
    'fi' => 'Automaattitallennus suoritettu',
    'sv' => 'Autospar utförd',
    'en' => 'Autosave completed',
    'it' => 'Salvataggio automatico completato',
    'el' => 'Αυτόματη αποθήκευση ολοκληρώθηκε',
],
'rotate_phone' => [
    'fi' => 'Käännä puhelin pystyasentoon',
    'sv' => 'Vänd telefonen till stående läge',
    'en' => 'Rotate phone to portrait mode',
    'it' => 'Ruota il telefono in modalità verticale',
    'el' => 'Περιστρέψτε το τηλέφωνο σε κατακόρυφη λειτουργία',
],
'rotate_phone_hint' => [
    'fi' => 'Sovellus toimii parhaiten pystyasennossa',
    'sv' => 'Appen fungerar bäst i stående läge',
    'en' => 'The app works best in portrait mode',
    'it' => 'L\'app funziona meglio in modalità verticale',
    'el' => 'Η εφαρμογή λειτουργεί καλύτερα σε κατακόρυφη λειτουργία',
],
'translation_saved' => [
    'fi' => 'Kieliversio tallennettu!',
    'sv' => 'Språkversion sparad!',
    'en' => 'Language version saved!',
    'it' => 'Versione linguistica salvata!',
    'el' => 'Η γλωσσική έκδοση αποθηκεύτηκε!',
],
'inline_edit' => [
    'fi' => 'Pikamuokkaus',
    'sv' => 'Snabbredigering',
    'en' => 'Quick edit',
    'it' => 'Modifica rapida',
    'el' => 'Γρήγορη επεξεργασία',
],
'generating_image' => [
    'fi' => 'Generoidaan kuvaa...',
    'sv' => 'Genererar bild...',
    'en' => 'Generating image...',
    'it' => 'Generazione immagine...',
    'el' => 'Δημιουργία εικόνας...',
],
'save_translation_button' => [
    'fi' => 'Tallenna kieliversio',
    'sv' => 'Spara språkversion',
    'en' => 'Save language version',
    'it' => 'Salva versione linguistica',
    'el' => 'Αποθήκευση γλωσσικής έκδοσης',
],
'login_error' => [
    'fi' => 'Virheellinen sähköposti tai salasana.',
    'sv' => 'Felaktig e-post eller lösenord.',
    'en' => 'Invalid email or password.',
    'it' => 'Email o password non validi.',
    'el' => 'Λάθος email ή κωδικός.',
],
'error_rate_limit' => [
    'fi' => 'Liian monta kirjautumisyritystä. Odota {minutes} minuuttia ennen uutta yritystä.',
    'sv' => 'För många inloggningsförsök. Vänta {minutes} minuter innan du försöker igen.',
    'en' => 'Too many login attempts. Please wait {minutes} minutes before trying again.',
    'it' => 'Troppi tentativi di accesso. Attendere {minutes} minuti prima di riprovare.',
    'el' => 'Πολλές προσπάθειες σύνδεσης. Περιμένετε {minutes} λεπτά πριν προσπαθήσετε ξανά.',
],
'details' => [
    'fi' => 'Tiedot',
    'sv' => 'Detaljer',
    'en' => 'Details',
    'it' => 'Dettagli',
    'el' => 'Λεπτομέρειες',
],
'supervisor_approved' => [
    'fi' => 'Työmaavastaava hyväksynyt',
    'sv' => 'Godkänd av arbetsledare',
    'en' => 'Site manager approved',
    'it' => 'Approvato dal responsabile del sito',
    'el' => 'Εγκρίθηκε από υπεύθυνο εργοταξίου',
],
'title_short' => [
    'fi' => 'Lyhyt otsikko',
    'sv' => 'Kort rubrik',
    'en' => 'Short title',
    'it' => 'Titolo breve',
    'el' => 'Σύντομος τίτλος',
],
'summary' => [
    'fi' => 'Yhteenveto',
    'sv' => 'Sammanfattning',
    'en' => 'Summary',
    'it' => 'Riepilogo',
    'el' => 'Περίληψη',
],
'countries' => [
    'fi' => 'Maat',
    'sv' => 'Länder',
    'en' => 'Countries',
    'it' => 'Paesi',
    'el' => 'Χώρες',
],
'copy_image' => [
    'fi' => 'Kopioi kuva',
    'sv' => 'Kopiera bild',
    'en' => 'Copy image',
    'it' => 'Copia immagine',
    'el' => 'Αντιγραφή εικόνας',
],
'copying_image' => [
    'fi' => 'Kopioidaan...',
    'sv' => 'Kopierar...',
    'en' => 'Copying...',
    'it' => 'Copiando...',
    'el' => 'Αντιγραφή...',
],
'image_copied' => [
    'fi' => 'Kuva kopioitu leikepöydälle!',
    'sv' => 'Bilden kopierad till urklipp!',
    'en' => 'Image copied to clipboard!',
    'it' => 'Immagine copiata negli appunti!',
    'el' => 'Η εικόνα αντιγράφηκε στο πρόχειρο!',
],
'copy_failed' => [
    'fi' => 'Kopiointi epäonnistui',
    'sv' => 'Kopiering misslyckades',
    'en' => 'Copy failed',
    'it' => 'Copia fallita',
    'el' => 'Η αντιγραφή απέτυχε',
],
'add_category' => [
    'fi' => 'Lisää kategoria',
    'sv' => 'Lägg till kategori',
    'en' => 'Add Category',
    'it' => 'Aggiungi categoria',
    'el' => 'Προσθήκη κατηγορίας',
],
'category_name' => [
    'fi' => 'Kategorian nimi',
    'sv' => 'Kategorinamn',
    'en' => 'Category Name',
    'it' => 'Nome categoria',
    'el' => 'Όνομα κατηγορίας',
],
'category_type' => [
    'fi' => 'Tyyppi',
    'sv' => 'Typ',
    'en' => 'Type',
    'it' => 'Tipo',
    'el' => 'Τύπος',
],
'type_supervisor' => [
    'fi' => 'Työmaavastaava',
    'sv' => 'Platschef',
    'en' => 'Site Manager',
    'it' => 'Responsabile di cantiere',
    'el' => 'Υπεύθυνος εργοταξίου',
],
'type_safety_team' => [
    'fi' => 'Turvatiimi',
    'sv' => 'Säkerhetsteam',
    'en' => 'Safety Team',
    'it' => 'Team di sicurezza',
    'el' => 'Ομάδα ασφαλείας',
],
'type_communications' => [
    'fi' => 'Viestintä',
    'sv' => 'Kommunikation',
    'en' => 'Communications',
    'it' => 'Comunicazioni',
    'el' => 'Επικοινωνίες',
],
'category_worksite' => [
    'fi' => 'Työmaa',
    'sv' => 'Arbetsplats',
    'en' => 'Worksite',
    'it' => 'Cantiere',
    'el' => 'Εργοτάξιο',
],
'category_members' => [
    'fi' => 'Jäsenet',
    'sv' => 'Medlemmar',
    'en' => 'Members',
    'it' => 'Membri',
    'el' => 'Μέλη',
],
'members' => [
    'fi' => 'jäsentä',
    'sv' => 'medlemmar',
    'en' => 'members',
    'it' => 'membri',
    'el' => 'μέλη',
],
'approval_routing_title' => [
    'fi' => 'Valitse tarkistaja',
    'sv' => 'Välj granskare',
    'en' => 'Select reviewer',
    'it' => 'Seleziona revisore',
    'el' => 'Επιλέξτε ελεγκτή',
],
'approval_routing_help' => [
    'fi' => 'Hae ja valitse työmaavastaavat, joille SafetyFlash lähetetään tarkistettavaksi.',
    'sv' => 'Sök och välj de platschefer som SafetyFlash skickas till för granskning.',
    'en' => 'Search and select the site managers to whom the SafetyFlash will be sent for review.',
    'it' => 'Cerca e seleziona i responsabili di cantiere a cui verrà inviato il SafetyFlash per la revisione.',
    'el' => 'Αναζητήστε και επιλέξτε τους υπεύθυνους εργοταξίου στους οποίους θα σταλεί το SafetyFlash για έλεγχο.',
],
'auto_selected_approvers' => [
    'fi' => 'Automaattisesti valitut hyväksyjät',
    'sv' => 'Automatiskt valda godkännare',
    'en' => 'Automatically Selected Approvers',
    'it' => 'Approvatori selezionati automaticamente',
    'el' => 'Αυτόματα επιλεγμένοι εγκριτές',
],
'add_more_approvers' => [
    'fi' => 'Lisää vastaanottajia',
    'sv' => 'Lägg till mottagare',
    'en' => 'Add More Recipients',
    'it' => 'Aggiungi altri destinatari',
    'el' => 'Προσθήκη περισσότερων αποδεκτών',
],
'all_worksites' => [
    'fi' => 'Kaikki työmaat',
    'sv' => 'Alla arbetsplatser',
    'en' => 'All Worksites',
    'it' => 'Tutti i cantieri',
    'el' => 'Όλα τα εργοτάξια',
],
'no_supervisors_available' => [
    'fi' => 'Ei työmaavastaavia valitulla työmaalla',
    'sv' => 'Inga platschefer tillgängliga för vald arbetsplats',
    'en' => 'No site managers available for selected worksite',
    'it' => 'Nessun responsabile di cantiere disponibile per il cantiere selezionato',
    'el' => 'Δεν υπάρχουν διαθέσιμοι υπεύθυνοι εργοταξίου για το επιλεγμένο εργοτάξιο',
],
'comments_empty' => [
    'fi' => 'Ei vielä kommentteja. Ole ensimmäinen!',
    'sv' => 'Inga kommentarer ännu. Var först!',
    'en' => 'No comments yet. Be the first!',
    'it' => 'Nessun commento ancora. Sii il primo!',
    'el' => 'Δεν υπάρχουν σχόλια ακόμα. Γίνε ο πρώτος!',
],
'events_empty' => [
    'fi' => 'Ei tapahtumia',
    'sv' => 'Inga händelser',
    'en' => 'No events',
    'it' => 'Nessun evento',
    'el' => 'Δεν υπάρχουν γεγονότα',
],
'search_site_manager_placeholder' => [
    'fi' => 'Hae työmaavastaavaa nimellä tai työmaalla...',
    'sv' => 'Sök platschef efter namn eller arbetsplats...',
    'en' => 'Search site manager by name or worksite...',
    'it' => 'Cerca responsabile di cantiere per nome o cantiere...',
    'el' => 'Αναζήτηση υπεύθυνου εργοταξίου ανά όνομα ή εργοτάξιο...',
],
'start_search_site_manager' => [
    'fi' => 'Aloita hakemalla työmaavastaavan nimeä tai työmaata',
    'sv' => 'Börja söka efter platschefens namn eller arbetsplats',
    'en' => 'Start by searching for the site manager\'s name or worksite',
    'it' => 'Inizia cercando il nome del responsabile di cantiere o il cantiere',
    'el' => 'Ξεκινήστε αναζητώντας το όνομα του υπεύθυνου εργοταξίου ή το εργοτάξιο',
],
'site_managers_selected' => [
    'fi' => 'työmaavastaavaa valittu',
    'sv' => 'platschefer valda',
    'en' => 'site managers selected',
    'it' => 'responsabili di cantiere selezionati',
    'el' => 'υπεύθυνοι εργοταξίου επιλέχθηκαν',
],
'site_manager_singular' => [
    'fi' => 'työmaavastaava',
    'sv' => 'platschef',
    'en' => 'site manager',
    'it' => 'responsabile di cantiere',
    'el' => 'υπεύθυνος εργοταξίου',
],
'site_manager_role_label' => [
    'fi' => 'Työmaavastaava',
    'sv' => 'Platschef',
    'en' => 'Site Manager',
    'it' => 'Responsabile di cantiere',
    'el' => 'Υπεύθυνος εργοταξίου',
],
'validation_select_at_least_one_site_manager' => [
    'fi' => 'Valitse vähintään yksi työmaavastaava',
    'sv' => 'Välj minst en platschef',
    'en' => 'Select at least one site manager',
    'it' => 'Seleziona almeno un responsabile di cantiere',
    'el' => 'Επιλέξτε τουλάχιστον έναν υπεύθυνο εργοταξίου',
],
'site_managers_count' => [
    'fi' => 'työmaavastaavaa', // Partitive plural for counting
    'sv' => 'platschefer',
    'en' => 'site managers',
    'it' => 'responsabili di cantiere',
    'el' => 'υπεύθυνοι εργοταξίου',
],
'site_managers_selected_label' => [
    'fi' => 'valittu',
    'sv' => 'valda',
    'en' => 'selected',
    'it' => 'selezionati',
    'el' => 'επιλέχθηκαν',
],
'translation_mode_title' => [
    'fi' => 'Muokkaat SafetyFlashin kieliversiota',
    'sv' => 'Du redigerar SafetyFlashens språkversion',
    'en' => 'You are editing the SafetyFlash language version',
    'it' => 'Stai modificando la versione linguistica del SafetyFlash',
    'el' => 'Επεξεργάζεστε τη γλωσσική έκδοση του SafetyFlash',
],
'translation_mode_message' => [
    'fi' => 'Luot kieliversiota kielelle',
    'sv' => 'Du skapar en språkversion för',
    'en' => 'You are creating a language version for',
    'it' => 'Stai creando una versione linguistica per',
    'el' => 'Δημιουργείτε μια γλωσσική έκδοση για',
],
];