<?php
/**
 * Dashboard Terms - Dashboard page and statistics
 */
return [
'nav_dashboard' => [
    'fi' => 'Dashboard',
    'sv' => 'Dashboard',
    'en' => 'Dashboard',
    'it' => 'Dashboard',
    'el' => 'Πίνακας',
],
'dashboard_title' => [
    'fi' => 'Yleiskatsaus',
    'sv' => 'Översikt',
    'en' => 'Overview',
    'it' => 'Panoramica',
    'el' => 'Επισκόπηση',
],
'dashboard_stat_red' => [
    'fi' => 'Ensitiedote',
    'sv' => 'Första underrättelse',
    'en' => 'First release',
    'it' => 'Prima notifica',
    'el' => 'Πρώτη ειδοποίηση',
],
'dashboard_stat_yellow' => [
    'fi' => 'Vaaratilanne',
    'sv' => 'Farlig situation',
    'en' => 'Dangerous situation',
    'it' => 'Situazione pericolosa',
    'el' => 'Επικίνδυνη κατάσταση',
],
'dashboard_stat_green' => [
    'fi' => 'Tutkintatiedote',
    'sv' => 'Utredningsrapport',
    'en' => 'Investigation report',
    'it' => 'Rapporto di indagine',
    'el' => 'Έκθεση έρευνας',
],
'dashboard_stat_total' => [
    'fi' => 'Yhteensä',
    'sv' => 'Totalt',
    'en' => 'Total',
    'it' => 'Totale',
    'el' => 'Σύνολο',
],
'dashboard_pending_title' => [
    'fi' => 'Odottaa sinua',
    'sv' => 'Väntar på dig',
    'en' => 'Pending for you',
    'it' => 'In attesa',
    'el' => 'Αναμονή για εσάς',
],
'dashboard_pending_empty' => [
    'fi' => 'Ei odottavia tehtäviä',
    'sv' => 'Inga väntande uppgifter',
    'en' => 'No pending tasks',
    'it' => 'Nessuna attività in sospeso',
    'el' => 'Δεν υπάρχουν εκκρεμείς εργασίες',
],
'dashboard_recent_title' => [
    'fi' => 'Viimeisimmät julkaisut',
    'sv' => 'Senaste publiceringar',
    'en' => 'Recent publications',
    'it' => 'Pubblicazioni recenti',
    'el' => 'Πρόσφατες δημοσιεύσεις',
],
'dashboard_recent_empty' => [
    'fi' => 'Ei julkaistuja SafetyFlasheja',
    'sv' => 'Inga publicerade SafetyFlashes',
    'en' => 'No published SafetyFlashes',
    'it' => 'Nessun SafetyFlash pubblicato',
    'el' => 'Δεν υπάρχουν δημοσιευμένα SafetyFlash',
],
'dashboard_worksite_title' => [
    'fi' => 'Työmaakohtaisesti',
    'sv' => 'Per arbetsplats',
    'en' => 'By worksite',
    'it' => 'Per cantiere',
    'el' => 'Ανά εργοτάξιο',
],
'dashboard_show_all' => [
    'fi' => 'Näytä kaikki',
    'sv' => 'Visa alla',
    'en' => 'Show all',
    'it' => 'Mostra tutti',
    'el' => 'Εμφάνιση όλων',
],
'dashboard_continue' => [
    'fi' => 'Jatka',
    'sv' => 'Fortsätt',
    'en' => 'Continue',
    'it' => 'Continua',
    'el' => 'Συνέχεια',
],
'dashboard_open' => [
    'fi' => 'Avaa',
    'sv' => 'Öppna',
    'en' => 'Open',
    'it' => 'Apri',
    'el' => 'Άνοιγμα',
],
'time_ago_hours' => [
    'fi' => '{n} tuntia sitten',
    'sv' => '{n} timmar sedan',
    'en' => '{n} hours ago',
    'it' => '{n} ore fa',
    'el' => 'πριν {n} ώρες',
],
'time_ago_days' => [
    'fi' => '{n} päivää sitten',
    'sv' => '{n} dagar sedan',
    'en' => '{n} days ago',
    'it' => '{n} giorni fa',
    'el' => 'πριν {n} ημέρες',
],
'time_ago_yesterday' => [
    'fi' => 'eilen',
    'sv' => 'igår',
    'en' => 'yesterday',
    'it' => 'ieri',
    'el' => 'χθες',
],
'time_ago_today' => [
    'fi' => 'tänään',
    'sv' => 'idag',
    'en' => 'today',
    'it' => 'oggi',
    'el' => 'σήμερα',
],
'dashboard_original_type_title' => [
    'fi' => 'Tapaukset alkuperäisen tyypin mukaan',
    'sv' => 'Fall efter ursprunglig typ',
    'en' => 'Cases by original type',
    'it' => 'Casi per tipo originale',
    'el' => 'Περιπτώσεις ανά αρχικό τύπο',
],
'dashboard_original_type_subtitle' => [
    'fi' => 'Mukaan lukien tutkintatiedotteiksi muutetut tapaukset',
    'sv' => 'Inklusive fall som konverterats till utredningsrapporter',
    'en' => 'Including cases converted to investigation reports',
    'it' => 'Inclusi i casi convertiti in rapporti di indagine',
    'el' => 'Συμπεριλαμβανομένων των περιπτώσεων που μετατράπηκαν σε εκθέσεις έρευνας',
],
'dashboard_stat_original_red' => [
    'fi' => 'Ensitiedotteet',
    'sv' => 'Första underrättelser',
    'en' => 'First releases',
    'it' => 'Prime notifiche',
    'el' => 'Αρχικές αναφορές',
],
'dashboard_stat_original_yellow' => [
    'fi' => 'Vaaratilanteet',
    'sv' => 'Farliga situationer',
    'en' => 'Dangerous situations',
    'it' => 'Situazioni pericolose',
    'el' => 'Επικίνδυνες καταστάσεις',
],
'dashboard_published_title' => [
    'fi' => 'Julkaistut SafetyFlashit',
    'sv' => 'Publicerade SafetyFlashes',
    'en' => 'Published SafetyFlashes',
    'it' => 'SafetyFlash pubblicati',
    'el' => 'Δημοσιευμένα SafetyFlash',
],
'dashboard_active_now' => [
    'fi' => 'Aktiiviset nyt',
    'sv' => 'Aktiva nu',
    'en' => 'Active now',
    'it' => 'Attivi ora',
    'el' => 'Ενεργά τώρα',
],
'dashboard_archived_count' => [
    'fi' => 'arkistoitu',
    'sv' => 'arkiverad',
    'en' => 'archived',
    'it' => 'archiviato',
    'el' => 'αρχειοθετημένο',
],
'dashboard_stats_by_type' => [
    'fi' => 'Tilastot ilmoitustyypeittäin',
    'sv' => 'Statistik per anmälningstyp',
    'en' => 'Statistics by notification type',
    'it' => 'Statistiche per tipo di notifica',
    'el' => 'Στατιστικά ανά τύπο ειδοποίησης',
],
'dashboard_stats_by_type_legend' => [
    'fi' => 'Vaaratilanne / Ensitiedote',
    'sv' => 'Farlig situation / Första underrättelse',
    'en' => 'Dangerous situation / First release',
    'it' => 'Situazione pericolosa / Prima notifica',
    'el' => 'Επικίνδυνη κατάσταση / Πρώτη ειδοποίηση',
],
'dashboard_statistics' => [
    'fi' => 'Tilastot',
    'sv' => 'Statistik',
    'en' => 'Statistics',
    'it' => 'Statistiche',
    'el' => 'Στατιστικά',
],
'dashboard_time_filter_thismonth' => [
    'fi' => 'Tämä kk',
    'sv' => 'Denna mån',
    'en' => 'This month',
    'it' => 'Questo mese',
    'el' => 'Αυτός ο μήνας',
],
'dashboard_time_filter_3months' => [
    'fi' => '3 kk',
    'sv' => '3 mån',
    'en' => '3 months',
    'it' => '3 mesi',
    'el' => '3 μήνες',
],
'dashboard_time_filter_6months' => [
    'fi' => '6 kk',
    'sv' => '6 mån',
    'en' => '6 months',
    'it' => '6 mesi',
    'el' => '6 μήνες',
],
'dashboard_time_filter_thisyear' => [
    'fi' => 'Tämä vuosi',
    'sv' => 'Detta år',
    'en' => 'This year',
    'it' => 'Quest\'anno',
    'el' => 'Φέτος',
],
'dashboard_time_filter_all' => [
    'fi' => 'Kaikki',
    'sv' => 'Alla',
    'en' => 'All',
    'it' => 'Tutti',
    'el' => 'Όλα',
],
'dashboard_by_type' => [
    'fi' => 'Ilmoitustyypeittäin',
    'sv' => 'Per anmälningstyp',
    'en' => 'By notification type',
    'it' => 'Per tipo di notifica',
    'el' => 'Ανά τύπο ειδοποίησης',
],
'dashboard_by_worksite' => [
    'fi' => 'Työmaakohtaisesti',
    'sv' => 'Per arbetsplats',
    'en' => 'By worksite',
    'it' => 'Per cantiere',
    'el' => 'Ανά εργοτάξιο',
],
'dashboard_recent' => [
    'fi' => 'Viimeisimmät',
    'sv' => 'Senaste',
    'en' => 'Recent',
    'it' => 'Recenti',
    'el' => 'Πρόσφατα',
],
'dashboard_archived' => [
    'fi' => 'Arkistoitu',
    'sv' => 'Arkiverad',
    'en' => 'Archived',
    'it' => 'Archiviato',
    'el' => 'Αρχειοθετημένο',
],
'dashboard_no_data' => [
    'fi' => 'Ei tietoja',
    'sv' => 'Inga data',
    'en' => 'No data',
    'it' => 'Nessun dato',
    'el' => 'Δεν υπάρχουν δεδομένα',
],
'dashboard_show_less' => [
    'fi' => 'Näytä vähemmän',
    'sv' => 'Visa färre',
    'en' => 'Show less',
    'it' => 'Mostra meno',
    'el' => 'Εμφάνιση λιγότερων',
],
'dashboard_filter_month' => [
    'fi' => 'Kuukausi',
    'sv' => 'Månad',
    'en' => 'Month',
    'it' => 'Mese',
    'el' => 'Μήνας',
],
'dashboard_filter_year' => [
    'fi' => 'Vuosi',
    'sv' => 'År',
    'en' => 'Year',
    'it' => 'Anno',
    'el' => 'Έτος',
],
'dashboard_filter_select_month' => [
    'fi' => 'Valitse kuukausi',
    'sv' => 'Välj månad',
    'en' => 'Select month',
    'it' => 'Seleziona mese',
    'el' => 'Επιλέξτε μήνα',
],
'dashboard_filter_all_years' => [
    'fi' => 'Kaikki vuodet',
    'sv' => 'Alla år',
    'en' => 'All years',
    'it' => 'Tutti gli anni',
    'el' => 'Όλα τα έτη',
],
'dashboard_filter_quick' => [
    'fi' => 'Pikavalinnat',
    'sv' => 'Snabbval',
    'en' => 'Quick selections',
    'it' => 'Selezioni rapide',
    'el' => 'Γρήγορες επιλογές',
],

/* ---- Dashboard report ---- */
'dashboard_report_button' => [
    'fi' => 'Luo raportti',
    'sv' => 'Skapa rapport',
    'en' => 'Create report',
    'it' => 'Crea report',
    'el' => 'Δημιουργία αναφοράς',
],
'dashboard_report_modal_title' => [
    'fi' => 'Luo dashboard-raportti',
    'sv' => 'Skapa dashboard-rapport',
    'en' => 'Create dashboard report',
    'it' => 'Crea report dashboard',
    'el' => 'Δημιουργία αναφοράς πίνακα',
],
'dashboard_report_period' => [
    'fi' => 'Ajanjakso',
    'sv' => 'Tidsperiod',
    'en' => 'Period',
    'it' => 'Periodo',
    'el' => 'Περίοδος',
],
'dashboard_report_start_date' => [
    'fi' => 'Alkupäivä',
    'sv' => 'Startdatum',
    'en' => 'Start date',
    'it' => 'Data inizio',
    'el' => 'Ημερομηνία έναρξης',
],
'dashboard_report_end_date' => [
    'fi' => 'Loppupäivä',
    'sv' => 'Slutdatum',
    'en' => 'End date',
    'it' => 'Data fine',
    'el' => 'Ημερομηνία λήξης',
],
'dashboard_report_site_filter' => [
    'fi' => 'Työmaa',
    'sv' => 'Arbetsplats',
    'en' => 'Worksite',
    'it' => 'Cantiere',
    'el' => 'Εργοτάξιο',
],
'dashboard_report_all_sites' => [
    'fi' => 'Kaikki työmaat',
    'sv' => 'Alla arbetsplatser',
    'en' => 'All worksites',
    'it' => 'Tutti i cantieri',
    'el' => 'Όλα τα εργοτάξια',
],
'dashboard_report_content' => [
    'fi' => 'Raportin sisältö',
    'sv' => 'Rapportinnehåll',
    'en' => 'Report content',
    'it' => 'Contenuto del report',
    'el' => 'Περιεχόμενο αναφοράς',
],
'dashboard_report_include_stats' => [
    'fi' => 'Tilastot',
    'sv' => 'Statistik',
    'en' => 'Statistics',
    'it' => 'Statistiche',
    'el' => 'Στατιστικά',
],
'dashboard_report_include_worksites' => [
    'fi' => 'Työmaakohtaisesti',
    'sv' => 'Per arbetsplats',
    'en' => 'By worksite',
    'it' => 'Per cantiere',
    'el' => 'Ανά εργοτάξιο',
],
'dashboard_report_include_injuries' => [
    'fi' => 'Loukkaantumiskoonti',
    'sv' => 'Skadesammanfattning',
    'en' => 'Injury summary',
    'it' => 'Riepilogo infortuni',
    'el' => 'Σύνοψη τραυματισμών',
],
'dashboard_report_include_recent' => [
    'fi' => 'Viimeisimmät loukkaantumiset',
    'sv' => 'Senaste skador',
    'en' => 'Recent injuries',
    'it' => 'Infortuni recenti',
    'el' => 'Πρόσφατοι τραυματισμοί',
],
'dashboard_report_generate' => [
    'fi' => 'Luo raportti',
    'sv' => 'Skapa rapport',
    'en' => 'Create report',
    'it' => 'Crea report',
    'el' => 'Δημιουργία αναφοράς',
],
'dashboard_report_cancel' => [
    'fi' => 'Peruuta',
    'sv' => 'Avbryt',
    'en' => 'Cancel',
    'it' => 'Annulla',
    'el' => 'Ακύρωση',
],
'dashboard_report_generating' => [
    'fi' => 'Luodaan raporttia...',
    'sv' => 'Skapar rapport...',
    'en' => 'Creating report...',
    'it' => 'Creazione report...',
    'el' => 'Δημιουργία αναφοράς...',
],
'dashboard_report_title_pdf' => [
    'fi' => 'Dashboard-raportti',
    'sv' => 'Dashboard-rapport',
    'en' => 'Dashboard Report',
    'it' => 'Report Dashboard',
    'el' => 'Αναφορά Πίνακα',
],
'dashboard_report_period_label' => [
    'fi' => 'Raportin ajanjakso',
    'sv' => 'Rapportperiod',
    'en' => 'Report period',
    'it' => 'Periodo del report',
    'el' => 'Περίοδος αναφοράς',
],
'dashboard_report_generated_at' => [
    'fi' => 'Raportti luotu',
    'sv' => 'Rapport skapad',
    'en' => 'Report generated',
    'it' => 'Report generato',
    'el' => 'Αναφορά δημιουργήθηκε',
],
'dashboard_report_generated_by' => [
    'fi' => 'Luonut',
    'sv' => 'Skapad av',
    'en' => 'Created by',
    'it' => 'Creato da',
    'el' => 'Δημιουργήθηκε από',
],
'dashboard_report_all_time' => [
    'fi' => 'Kaikki ajat',
    'sv' => 'Alla tider',
    'en' => 'All time',
    'it' => 'Tutto il tempo',
    'el' => 'Όλη η περίοδος',
],
'dashboard_report_error' => [
    'fi' => 'Raportin luonti epäonnistui',
    'sv' => 'Rapporten kunde inte skapas',
    'en' => 'Failed to create report',
    'it' => 'Impossibile creare il report',
    'el' => 'Αποτυχία δημιουργίας αναφοράς',
],
'dashboard_report_select_content' => [
    'fi' => 'Valitse vähintään yksi sisältöosio.',
    'sv' => 'Välj minst ett innehållsavsnitt.',
    'en' => 'Please select at least one content section.',
    'it' => 'Seleziona almeno una sezione di contenuto.',
    'el' => 'Επιλέξτε τουλάχιστον μία ενότητα περιεχομένου.',
],

/* ---- Injury heatmap module ---- */
'dashboard_injury_title' => [
    'fi' => 'Loukkaantumiskoonti',
    'sv' => 'Skadesammanfattning',
    'en' => 'Injury summary',
    'it' => 'Riepilogo infortuni',
    'el' => 'Σύνοψη τραυματισμών',
],
'dashboard_injury_all_sites' => [
    'fi' => 'Kaikki työmaat',
    'sv' => 'Alla arbetsplatser',
    'en' => 'All worksites',
    'it' => 'Tutti i cantieri',
    'el' => 'Όλα τα εργοτάξια',
],
'dashboard_injury_chart_title' => [
    'fi' => 'Jakautuminen kehonosittain',
    'sv' => 'Fördelning per kroppsdel',
    'en' => 'Distribution by body part',
    'it' => 'Distribuzione per parte del corpo',
    'el' => 'Κατανομή ανά μέρος σώματος',
],
'dashboard_injury_recent_title' => [
    'fi' => 'Viimeisimmät loukkaantumiset',
    'sv' => 'Senaste skador',
    'en' => 'Recent injuries',
    'it' => 'Infortuni recenti',
    'el' => 'Πρόσφατοι τραυματισμοί',
],
'dashboard_injury_empty' => [
    'fi' => 'Ei loukkaantumisia valitulla ajanjaksolla',
    'sv' => 'Inga skador under vald period',
    'en' => 'No injuries in the selected period',
    'it' => 'Nessun infortunio nel periodo selezionato',
    'el' => 'Δεν υπάρχουν τραυματισμοί στην επιλεγμένη περίοδο',
],
'dashboard_injury_click_hint' => [
    'fi' => 'Klikkaa kehonosaa suodattaaksesi listaa',
    'sv' => 'Klicka på kroppsdel för att filtrera listan',
    'en' => 'Click a body part to filter the list',
    'it' => 'Clicca su una parte del corpo per filtrare la lista',
    'el' => 'Κάντε κλικ σε μέρος σώματος για φιλτράρισμα της λίστας',
],
'dashboard_injury_active_filter' => [
    'fi' => 'Suodatettu:',
    'sv' => 'Filtrerat:',
    'en' => 'Filtered:',
    'it' => 'Filtrato:',
    'el' => 'Φιλτραρισμένο:',
],
'dashboard_injury_no_match' => [
    'fi' => 'Ei tapauksia tälle kehonosalle',
    'sv' => 'Inga fall för denna kroppsdel',
    'en' => 'No cases for this body part',
    'it' => 'Nessun caso per questa parte del corpo',
    'el' => 'Δεν υπάρχουν περιπτώσεις για αυτό το μέρος σώματος',
],
'dashboard_injury_show_all_count' => [
    'fi' => 'Näytä kaikki {n}',
    'sv' => 'Visa alla {n}',
    'en' => 'Show all {n}',
    'it' => 'Mostra tutti {n}',
    'el' => 'Εμφάνιση όλων {n}',
],
'dashboard_injury_modal_title' => [
    'fi' => 'Kaikki loukkaantumiset',
    'sv' => 'Alla skador',
    'en' => 'All injuries',
    'it' => 'Tutti gli infortuni',
    'el' => 'Όλοι οι τραυματισμοί',
],
'dashboard_injury_modal_close' => [
    'fi' => 'Sulje',
    'sv' => 'Stäng',
    'en' => 'Close',
    'it' => 'Chiudi',
    'el' => 'Κλείσιμο',
],
'month_1' => [
    'fi' => 'Tammikuu',
    'sv' => 'Januari',
    'en' => 'January',
    'it' => 'Gennaio',
    'el' => 'Ιανουάριος',
],
'month_2' => [
    'fi' => 'Helmikuu',
    'sv' => 'Februari',
    'en' => 'February',
    'it' => 'Febbraio',
    'el' => 'Φεβρουάριος',
],
'month_3' => [
    'fi' => 'Maaliskuu',
    'sv' => 'Mars',
    'en' => 'March',
    'it' => 'Marzo',
    'el' => 'Μάρτιος',
],
'month_4' => [
    'fi' => 'Huhtikuu',
    'sv' => 'April',
    'en' => 'April',
    'it' => 'Aprile',
    'el' => 'Απρίλιος',
],
'month_5' => [
    'fi' => 'Toukokuu',
    'sv' => 'Maj',
    'en' => 'May',
    'it' => 'Maggio',
    'el' => 'Μάιος',
],
'month_6' => [
    'fi' => 'Kesäkuu',
    'sv' => 'Juni',
    'en' => 'June',
    'it' => 'Giugno',
    'el' => 'Ιούνιος',
],
'month_7' => [
    'fi' => 'Heinäkuu',
    'sv' => 'Juli',
    'en' => 'July',
    'it' => 'Luglio',
    'el' => 'Ιούλιος',
],
'month_8' => [
    'fi' => 'Elokuu',
    'sv' => 'Augusti',
    'en' => 'August',
    'it' => 'Agosto',
    'el' => 'Αύγουστος',
],
'month_9' => [
    'fi' => 'Syyskuu',
    'sv' => 'September',
    'en' => 'September',
    'it' => 'Settembre',
    'el' => 'Σεπτέμβριος',
],
'month_10' => [
    'fi' => 'Lokakuu',
    'sv' => 'Oktober',
    'en' => 'October',
    'it' => 'Ottobre',
    'el' => 'Οκτώβριος',
],
'month_11' => [
    'fi' => 'Marraskuu',
    'sv' => 'November',
    'en' => 'November',
    'it' => 'Novembre',
    'el' => 'Νοέμβριος',
],
'month_12' => [
    'fi' => 'Joulukuu',
    'sv' => 'December',
    'en' => 'December',
    'it' => 'Dicembre',
    'el' => 'Δεκέμβριος',
],
];