<?php
/**
 * Display & Playlist Terms - Xibo information display integration
 * TTL selectors, playlist status, and related terms
 */
return [
    // Display duration (Publish Modal)
    'display_duration_heading' => [
        'fi' => 'Näyttökesto infonäytöllä',
        'sv' => 'Visningstid på informationsskärm',
        'en' => 'Display duration on info screen',
        'it' => 'Durata di visualizzazione sul display',
        'el' => 'Διάρκεια εμφάνισης στην οθόνη πληροφοριών',
    ],
    'display_duration_description' => [
        'fi' => 'Valitse kuinka monta sekuntia tämä kuva näytetään Xibo-näytöillä',
        'sv' => 'Välj hur många sekunder denna bild visas på Xibo-skärmar',
        'en' => 'Select how many seconds this image is shown on Xibo screens',
        'it' => 'Seleziona quanti secondi questa immagine viene visualizzata sui display Xibo',
        'el' => 'Επιλέξτε πόσα δευτερόλεπτα θα εμφανίζεται αυτή η εικόνα στις οθόνες Xibo',
    ],
    'duration_10s' => ['fi' => '10 s', 'sv' => '10 s', 'en' => '10 s', 'it' => '10 s', 'el' => '10 δ'],
    'duration_15s' => ['fi' => '15 s', 'sv' => '15 s', 'en' => '15 s', 'it' => '15 s', 'el' => '15 δ'],
    'duration_20s' => ['fi' => '20 s', 'sv' => '20 s', 'en' => '20 s', 'it' => '20 s', 'el' => '20 δ'],
    'duration_30s' => ['fi' => '30 s', 'sv' => '30 s', 'en' => '30 s', 'it' => '30 s', 'el' => '30 δ'],
    'duration_45s' => ['fi' => '45 s', 'sv' => '45 s', 'en' => '45 s', 'it' => '45 s', 'el' => '45 δ'],
    'duration_60s' => ['fi' => '60 s', 'sv' => '60 s', 'en' => '60 s', 'it' => '60 s', 'el' => '60 δ'],

    // Per-language display selection (Publish Modal)
    'display_showing_lang_displays' => [
        'fi' => 'Näytetään tämän kielen näytöt',
        'sv' => 'Visar skärmar för detta språk',
        'en' => 'Showing displays for this language',
        'it' => 'Visualizzazione dei display per questa lingua',
        'el' => 'Εμφάνιση οθονών για αυτή τη γλώσσα',
    ],
    'display_per_language_info' => [
        'fi' => 'Jokaisella kieliversiolla on omat näyttövalintansa',
        'sv' => 'Varje språkversion har sina egna skärmval',
        'en' => 'Each language version has its own display selections',
        'it' => 'Ogni versione linguistica ha le proprie selezioni di display',
        'el' => 'Κάθε γλωσσική έκδοση έχει τις δικές της επιλογές οθόνης',
    ],

    // TTL Selector (Publish Modal)
    'display_ttl_heading' => [
        'fi' => 'Näkyvyysaika infonäytöillä',
        'sv' => 'Visningstid på informationsskärmar',
        'en' => 'Display time on info screens',
        'it' => 'Tempo di visualizzazione sui display',
        'el' => 'Χρόνος εμφάνισης στις οθόνες πληροφοριών',
    ],
    'display_ttl_description' => [
        'fi' => 'Valitse kuinka kauan flash näytetään Xibo-infonäytöillä',
        'sv' => 'Välj hur länge flash visas på Xibo-informationsskärmar',
        'en' => 'Select how long the flash is displayed on Xibo info screens',
        'it' => 'Seleziona per quanto tempo il flash viene visualizzato sui display Xibo',
        'el' => 'Επιλέξτε πόσο χρόνο θα εμφανίζεται το flash στις οθόνες Xibo',
    ],
    'ttl_no_limit' => [
        'fi' => 'Ei aikarajaa',
        'sv' => 'Ingen tidsgräns',
        'en' => 'No time limit',
        'it' => 'Nessun limite di tempo',
        'el' => 'Χωρίς χρονικό όριο',
    ],
    'ttl_1_week' => [
        'fi' => '1 viikko',
        'sv' => '1 vecka',
        'en' => '1 week',
        'it' => '1 settimana',
        'el' => '1 εβδομάδα',
    ],
    'ttl_2_weeks' => [
        'fi' => '2 viikkoa',
        'sv' => '2 veckor',
        'en' => '2 weeks',
        'it' => '2 settimane',
        'el' => '2 εβδομάδες',
    ],
    'ttl_1_month' => [
        'fi' => '1 kuukausi',
        'sv' => '1 månad',
        'en' => '1 month',
        'it' => '1 mese',
        'el' => '1 μήνας',
    ],
    'ttl_2_months' => [
        'fi' => '2 kuukautta',
        'sv' => '2 månader',
        'en' => '2 months',
        'it' => '2 mesi',
        'el' => '2 μήνες',
    ],
    'ttl_3_months' => [
        'fi' => '3 kuukautta',
        'sv' => '3 månader',
        'en' => '3 months',
        'it' => '3 mesi',
        'el' => '3 μήνες',
    ],
    'ttl_preview_default' => [
        'fi' => 'Vanhenee',
        'sv' => 'Utgår',
        'en' => 'Expires',
        'it' => 'Scade',
        'el' => 'Λήγει',
    ],
    
    // Playlist Status (View Page)
    'playlist_status_active' => [
        'fi' => 'Näytetään infonäytöillä',
        'sv' => 'Visas på informationsskärmar',
        'en' => 'Shown on info screens',
        'it' => 'Mostrato sui display',
        'el' => 'Εμφανίζεται στις οθόνες πληροφοριών',
    ],
    'playlist_status_expired' => [
        'fi' => 'Vanhentunut',
        'sv' => 'Utgången',
        'en' => 'Expired',
        'it' => 'Scaduto',
        'el' => 'Ληγμένο',
    ],
    'playlist_status_removed' => [
        'fi' => 'Poistettu ajolistasta',
        'sv' => 'Borttagen från spellistan',
        'en' => 'Removed from playlist',
        'it' => 'Rimosso dalla playlist',
        'el' => 'Αφαιρέθηκε από τη λίστα αναπαραγωγής',
    ],
    'playlist_expires_in_days' => [
        'fi' => 'Vanhenee %d päivän kuluttua',
        'sv' => 'Utgår om %d dagar',
        'en' => 'Expires in %d days',
        'it' => 'Scade tra %d giorni',
        'el' => 'Λήγει σε %d ημέρες',
    ],
    'playlist_expires_today' => [
        'fi' => 'Vanhenee tänään',
        'sv' => 'Utgår idag',
        'en' => 'Expires today',
        'it' => 'Scade oggi',
        'el' => 'Λήγει σήμερα',
    ],
    'playlist_no_expiry' => [
        'fi' => 'Ei vanhenemisaikaa',
        'sv' => 'Inget utgångsdatum',
        'en' => 'No expiration',
        'it' => 'Nessuna scadenza',
        'el' => 'Χωρίς λήξη',
    ],
    'playlist_expired_at' => [
        'fi' => 'Vanheni',
        'sv' => 'Utgick',
        'en' => 'Expired',
        'it' => 'Scaduto',
        'el' => 'Έληξε',
    ],
    'playlist_removed_at' => [
        'fi' => 'Poistettu',
        'sv' => 'Borttagen',
        'en' => 'Removed',
        'it' => 'Rimosso',
        'el' => 'Αφαιρέθηκε',
    ],
    
    // Action Buttons
    'btn_view_playlist' => [
        'fi' => 'Katso ajolista',
        'sv' => 'Visa spellista',
        'en' => 'View playlist',
        'it' => 'Visualizza playlist',
        'el' => 'Προβολή λίστας',
    ],
    'btn_playlist_prev' => [
        'fi' => 'Edellinen',
        'sv' => 'Föregående',
        'en' => 'Previous',
        'it' => 'Precedente',
        'el' => 'Προηγούμενο',
    ],
    'btn_playlist_next' => [
        'fi' => 'Seuraava',
        'sv' => 'Nästa',
        'en' => 'Next',
        'it' => 'Successivo',
        'el' => 'Επόμενο',
    ],
    'btn_playlist_pause' => [
        'fi' => 'Pysäytä',
        'sv' => 'Pausa',
        'en' => 'Pause',
        'it' => 'Pausa',
        'el' => 'Παύση',
    ],
    'btn_playlist_resume' => [
        'fi' => 'Jatka',
        'sv' => 'Fortsätt',
        'en' => 'Resume',
        'it' => 'Riprendi',
        'el' => 'Συνέχεια',
    ],
    'playlist_slide_counter' => [
        'fi' => '%d / %d',
        'sv' => '%d / %d',
        'en' => '%d / %d',
        'it' => '%d / %d',
        'el' => '%d / %d',
    ],
    'btn_remove_from_playlist' => [
        'fi' => 'Poista ajolistasta',
        'sv' => 'Ta bort från spellistan',
        'en' => 'Remove from playlist',
        'it' => 'Rimuovi dalla playlist',
        'el' => 'Αφαίρεση από τη λίστα',
    ],
    'btn_restore_to_playlist' => [
        'fi' => 'Palauta ajolistaan',
        'sv' => 'Återställ till spellistan',
        'en' => 'Restore to playlist',
        'it' => 'Ripristina nella playlist',
        'el' => 'Επαναφορά στη λίστα',
    ],
    
    // Confirmation Messages
    'confirm_remove_from_playlist' => [
        'fi' => 'Haluatko varmasti poistaa flashin infonäyttö-ajolistasta?',
        'sv' => 'Vill du verkligen ta bort flash från informationsskärmens spellista?',
        'en' => 'Are you sure you want to remove the flash from the info screen playlist?',
        'it' => 'Sei sicuro di voler rimuovere il flash dalla playlist del display?',
        'el' => 'Είστε βέβαιοι ότι θέλετε να αφαιρέσετε το flash από τη λίστα αναπαραγωγής;',
    ],
    'confirm_remove_playlist_title' => [
        'fi' => 'Poista ajolistasta',
        'sv' => 'Ta bort från spellistan',
        'en' => 'Remove from playlist',
        'it' => 'Rimuovi dalla playlist',
        'el' => 'Αφαίρεση από τη λίστα',
    ],
    
    // Success Messages
    'msg_removed_from_playlist' => [
        'fi' => 'Poistettu ajolistasta',
        'sv' => 'Borttagen från spellistan',
        'en' => 'Removed from playlist',
        'it' => 'Rimosso dalla playlist',
        'el' => 'Αφαιρέθηκε από τη λίστα',
    ],
    'msg_restored_to_playlist' => [
        'fi' => 'Palautettu playlistaan',
        'sv' => 'Återställd till spellistan',
        'en' => 'Restored to playlist',
        'it' => 'Ripristinato nella playlist',
        'el' => 'Επαναφέρθηκε στη λίστα',
    ],
    
    // Single language version publish
    'publish_language_version' => [
        'fi' => 'Julkaise kieliversio',
        'sv' => 'Publicera språkversion',
        'en' => 'Publish language version',
        'it' => 'Pubblica versione linguistica',
        'el' => 'Δημοσίευση γλωσσικής έκδοσης',
    ],
    'publish_single_description' => [
        'fi' => 'Tämä kieliversio on luonnos. Julkaise se erikseen omille infonäytöilleen.',
        'sv' => 'Denna språkversion är ett utkast. Publicera den separat till sina egna informationsskärmar.',
        'en' => 'This language version is a draft. Publish it separately to its own info displays.',
        'it' => 'Questa versione linguistica è una bozza. Pubblicala separatamente sui propri schermi informativi.',
        'el' => 'Αυτή η γλωσσική έκδοση είναι πρόχειρη. Δημοσιεύστε την ξεχωριστά στις δικές της οθόνες πληροφοριών.',
    ],
    'btn_publish_language_version' => [
        'fi' => 'Julkaise tämä kieliversio →',
        'sv' => 'Publicera denna språkversion →',
        'en' => 'Publish this language version →',
        'it' => 'Pubblica questa versione linguistica →',
        'el' => 'Δημοσίευση αυτής της γλωσσικής έκδοσης →',
    ],
    'language_versions' => [
        'fi' => 'Kieliversiot',
        'sv' => 'Språkversioner',
        'en' => 'Language versions',
        'it' => 'Versioni linguistiche',
        'el' => 'Γλωσσικές εκδόσεις',
    ],
    'state_published' => [
        'fi' => 'Julkaistu',
        'sv' => 'Publicerad',
        'en' => 'Published',
        'it' => 'Pubblicato',
        'el' => 'Δημοσιεύτηκε',
    ],
    'state_draft' => [
        'fi' => 'Luonnos',
        'sv' => 'Utkast',
        'en' => 'Draft',
        'it' => 'Bozza',
        'el' => 'Πρόχειρο',
    ],

    // Publish Modal Stepper Titles & Summary Labels
    'publish_step1_title' => [
        'fi' => 'Julkaisun asetukset',
        'sv' => 'Publiceringsinställningar',
        'en' => 'Publishing settings',
        'it' => 'Impostazioni di pubblicazione',
        'el' => 'Ρυθμίσεις δημοσίευσης',
    ],
    'publish_step2_title' => [
        'fi' => 'Työmaan infonäytöt',
        'sv' => 'Arbetsplatsens informationsskärmar',
        'en' => 'Worksite displays',
        'it' => 'Display del cantiere',
        'el' => 'Οθόνες εργοταξίου',
    ],
    'GRID_SELECTED' => [
    'fi' => 'Valittu',
    'en' => 'Selected',
    'sv' => 'Vald',
    'it' => 'Selezionato',
    'el' => 'Επιλεγμένο',
],

'GRID_SELECT_HINT' => [
    'fi' => 'Klikkaa valitaksesi tämän asettelun',
    'en' => 'Click to select this layout',
    'sv' => 'Klicka för att välja denna layout',
    'it' => 'Fai clic per selezionare questo layout',
    'el' => 'Κάντε κλικ για να επιλέξετε αυτή τη διάταξη',
],
    'publish_step3_title' => [
        'fi' => 'Aika-asetukset',
        'sv' => 'Tidsinställningar',
        'en' => 'Time settings',
        'it' => 'Impostazioni di tempo',
        'el' => 'Ρυθμίσεις χρόνου',
    ],
    'publish_step4_title' => [
        'fi' => 'Vahvista julkaisu',
        'sv' => 'Bekräfta publicering',
        'en' => 'Confirm publishing',
        'it' => 'Conferma pubblicazione',
        'el' => 'Επιβεβαίωση δημοσίευσης',
    ],
    'publish_summary_distribution' => [
        'fi' => 'Jakelu',
        'sv' => 'Distribution',
        'en' => 'Distribution',
        'it' => 'Distribuzione',
        'el' => 'Διανομή',
    ],
    'publish_summary_ttl' => [
        'fi' => 'Näkyvyysaika',
        'sv' => 'Visningstid',
        'en' => 'Display time',
        'it' => 'Tempo di visualizzazione',
        'el' => 'Χρόνος εμφάνισης',
    ],
    'publish_summary_duration' => [
        'fi' => 'Näyttökesto',
        'sv' => 'Visningstid per bild',
        'en' => 'Display duration',
        'it' => 'Durata visualizzazione',
        'el' => 'Διάρκεια εμφάνισης',
    ],
    'publish_summary_displays' => [
        'fi' => 'Infonäytöt',
        'sv' => 'Informationsskärmar',
        'en' => 'Info screens',
        'it' => 'Schermi informativi',
        'el' => 'Οθόνες πληροφοριών',
    ],
    'publish_step1_subtitle' => [
        'fi' => 'Haluatko julkaista tämän tiedotteen?',
        'sv' => 'Vill du publicera detta meddelande?',
        'en' => 'Do you want to publish this notice?',
        'it' => 'Vuoi pubblicare questo avviso?',
        'el' => 'Θέλετε να δημοσιεύσετε αυτήν την ανακοίνωση;',
    ],

    // Display Targets Status (View Page)
    'display_targets_heading' => [
        'fi' => 'Infonäyttökohteet',
        'sv' => 'Informationsskärmsmål',
        'en' => 'Info screen targets',
        'it' => 'Destinazioni display',
        'el' => 'Στόχοι οθόνης πληροφοριών',
    ],
    'display_targets_count' => [
        'fi' => '%d / %d aktiivinen',
        'sv' => '%d / %d aktiv',
        'en' => '%d / %d active',
        'it' => '%d / %d attivo',
        'el' => '%d / %d ενεργό',
    ],
    'display_target_active' => [
        'fi' => 'Aktiivinen — julkaistu tällä näytöllä',
        'sv' => 'Aktiv — publicerad på denna skärm',
        'en' => 'Active — published on this display',
        'it' => 'Attivo — pubblicato su questo display',
        'el' => 'Ενεργό — δημοσιευμένο σε αυτή την οθόνη',
    ],
    'display_target_preselected' => [
        'fi' => 'Esiasetettu — ei vielä julkaistu',
        'sv' => 'Förvald — inte publicerad ännu',
        'en' => 'Preselected — not yet published',
        'it' => 'Preselezionato — non ancora pubblicato',
        'el' => 'Προεπιλεγμένο — δεν έχει δημοσιευτεί ακόμα',
    ],

    // Log Messages
    'log_display_removed' => [
        'fi' => 'Poistettu infonäyttö-ajolistasta',
        'sv' => 'Borttagen från informationsskärmens spellista',
        'en' => 'Removed from info screen playlist',
        'it' => 'Rimosso dalla playlist del display',
        'el' => 'Αφαιρέθηκε από τη λίστα αναπαραγωγής',
    ],
    'log_display_restored' => [
        'fi' => 'Palautettu infonäyttö-playlistaan',
        'sv' => 'Återställd till informationsskärmens spellista',
        'en' => 'Restored to info screen playlist',
        'it' => 'Ripristinato nella playlist del display',
        'el' => 'Επαναφέρθηκε στη λίστα αναπαραγωγής',
    ],

    'footer_display_targets' => [
        'fi' => 'Infonäytöt',
        'sv' => 'Infoskärmar',
        'en' => 'Info screens',
        'it' => 'Display',
        'el' => 'Οθόνες',
    ],

    // Playlist Manager
    'playlist_manager_heading' => [
        'fi' => 'Ajolistan hallinta',
        'sv' => 'Hantera spellista',
        'en' => 'Manage playlist',
        'it' => 'Gestisci playlist',
        'el' => 'Διαχείριση λίστας',
    ],
    'playlist_reorder_saved' => [
        'fi' => 'Järjestys tallennettu',
        'sv' => 'Ordning sparad',
        'en' => 'Order saved',
        'it' => 'Ordine salvato',
        'el' => 'Η σειρά αποθηκεύτηκε',
    ],
    'playlist_empty' => [
        'fi' => 'Ajolista on tyhjä — ei aktiivisia flasheja tällä näytöllä',
        'sv' => 'Spellistan är tom — inga aktiva flash på denna skärm',
        'en' => 'Playlist is empty — no active flashes on this display',
        'it' => 'La playlist è vuota — nessun flash attivo su questo display',
        'el' => 'Η λίστα είναι κενή — κανένα ενεργό flash σε αυτήν την οθόνη',
    ],
    'settings_worksites_col_playlist' => [
        'fi' => 'Ajolista',
        'sv' => 'Spellista',
        'en' => 'Playlist',
        'it' => 'Playlist',
        'el' => 'Λίστα',
    ],
    'playlist_move_up' => [
        'fi' => 'Siirrä ylös',
        'sv' => 'Flytta upp',
        'en' => 'Move up',
        'it' => 'Sposta su',
        'el' => 'Μετακίνηση πάνω',
    ],
    'playlist_move_down' => [
        'fi' => 'Siirrä alas',
        'sv' => 'Flytta ner',
        'en' => 'Move down',
        'it' => 'Sposta giù',
        'el' => 'Μετακίνηση κάτω',
    ],
    'display_select_all' => [
        'fi' => 'Valitse kaikki',
        'sv' => 'Välj alla',
        'en' => 'Select all',
        'it' => 'Seleziona tutto',
        'el' => 'Επιλογή όλων',
    ],
    'display_all_screens' => [
        'fi' => 'Kaikki näytöt',
        'sv' => 'Alla skärmar',
        'en' => 'All screens',
        'it' => 'Tutti gli schermi',
        'el' => 'Όλες οι οθόνες',
    ],

    // Xibo integration code generator (Settings page)
    'xibo_code_heading' => [
        'fi' => 'Xibo-integraatiokoodi',
        'sv' => 'Xibo-integrationskod',
        'en' => 'Xibo integration code',
        'it' => 'Codice integrazione Xibo',
        'el' => 'Κωδικός ενσωμάτωσης Xibo',
    ],
    'xibo_instructions' => [
        'fi' => 'Kopioi URL ja liitä se Xibo CMS:n Webpage-widgetin URL-kenttään',
        'sv' => 'Kopiera URL och klistra in den i Xibo CMS Webpage-widgetens URL-fält',
        'en' => 'Copy the URL and paste it into the Xibo CMS Webpage widget URL field',
        'it' => 'Copia l\'URL e incollalo nel campo URL del widget Webpage di Xibo CMS',
        'el' => 'Αντιγράψτε το URL και επικολλήστε το στο πεδίο URL του widget Webpage του Xibo CMS',
    ],
    'xibo_webpage_url' => [
        'fi' => 'Webpage Widget URL',
        'sv' => 'Webpage Widget URL',
        'en' => 'Webpage Widget URL',
        'it' => 'Webpage Widget URL',
        'el' => 'Webpage Widget URL',
    ],
    'xibo_embedded_code' => [
        'fi' => 'Embedded Widget (JavaScript)',
        'sv' => 'Embedded Widget (JavaScript)',
        'en' => 'Embedded Widget (JavaScript)',
        'it' => 'Embedded Widget (JavaScript)',
        'el' => 'Embedded Widget (JavaScript)',
    ],
    'xibo_json_endpoint' => [
        'fi' => 'JSON API',
        'sv' => 'JSON API',
        'en' => 'JSON API',
        'it' => 'JSON API',
        'el' => 'JSON API',
    ],
    'btn_copy' => [
        'fi' => 'Kopioi',
        'sv' => 'Kopiera',
        'en' => 'Copy',
        'it' => 'Copia',
        'el' => 'Αντιγραφή',
    ],
    'msg_copied' => [
        'fi' => 'Kopioitu!',
        'sv' => 'Kopierat!',
        'en' => 'Copied!',
        'it' => 'Copiato!',
        'el' => 'Αντιγράφηκε!',
    ],
    'xibo_col_heading' => [
        'fi' => 'Xibo-koodi',
        'sv' => 'Xibo-kod',
        'en' => 'Xibo code',
        'it' => 'Codice Xibo',
        'el' => 'Κωδικός Xibo',
    ],
    'xibo_webpage_url_label' => [
        'fi' => 'Webpage Widget URL',
        'sv' => 'Webpage Widget URL',
        'en' => 'Webpage Widget URL',
        'it' => 'Webpage Widget URL',
        'el' => 'Webpage Widget URL',
    ],
    'xibo_embedded_html_label' => [
        'fi' => 'HTML-kenttä (Embedded Widget)',
        'sv' => 'HTML-fält (Embedded Widget)',
        'en' => 'HTML field (Embedded Widget)',
        'it' => 'Campo HTML (Embedded Widget)',
        'el' => 'Πεδίο HTML (Embedded Widget)',
    ],
    'xibo_embedded_css_label' => [
        'fi' => 'CSS-kenttä (Embedded Widget)',
        'sv' => 'CSS-fält (Embedded Widget)',
        'en' => 'CSS field (Embedded Widget)',
        'it' => 'Campo CSS (Embedded Widget)',
        'el' => 'Πεδίο CSS (Embedded Widget)',
    ],
    'xibo_copy_url' => [
        'fi' => 'Kopioi URL',
        'sv' => 'Kopiera URL',
        'en' => 'Copy URL',
        'it' => 'Copia URL',
        'el' => 'Αντιγραφή URL',
    ],
    'xibo_copy_html' => [
        'fi' => 'Kopioi HTML',
        'sv' => 'Kopiera HTML',
        'en' => 'Copy HTML',
        'it' => 'Copia HTML',
        'el' => 'Αντιγραφή HTML',
    ],
    'xibo_copy_css' => [
        'fi' => 'Kopioi CSS',
        'sv' => 'Kopiera CSS',
        'en' => 'Copy CSS',
        'it' => 'Copia CSS',
        'el' => 'Αντιγραφή CSS',
    ],
    'xibo_copied' => [
        'fi' => 'Kopioitu!',
        'sv' => 'Kopierat!',
        'en' => 'Copied!',
        'it' => 'Copiato!',
        'el' => 'Αντιγράφηκε!',
    ],
    'xibo_embedded_instructions' => [
        'fi' => 'Liitä HTML ja CSS Xibon Embedded Widget -kenttiin',
        'sv' => 'Klistra in HTML och CSS i Xibos Embedded Widget-fält',
        'en' => 'Paste HTML and CSS into the Xibo Embedded Widget fields',
        'it' => 'Incolla HTML e CSS nei campi Embedded Widget di Xibo',
        'el' => 'Επικολλήστε HTML και CSS στα πεδία Embedded Widget του Xibo',
    ],

    // Display Fallback Image (Settings)
    'display_fallback_heading' => [
        'fi' => 'Infonäyttöjen fallback-kuva',
        'sv' => 'Fallback-bild för skärmar',
        'en' => 'Fallback image for displays',
        'it' => 'Immagine di fallback per i display',
        'el' => 'Εφεδρική εικόνα για οθόνες',
    ],
    'display_fallback_description' => [
        'fi' => 'Näytetään kun ajolistassa ei ole flasheja. Suositeltu koko 1920×1080. Näkyy 5 sekuntia.',
        'sv' => 'Visas när spellistan inte har några flash. Rekommenderad storlek 1920×1080. Visas i 5 sekunder.',
        'en' => 'Shown when the playlist has no flashes. Recommended size 1920×1080. Displayed for 5 seconds.',
        'it' => 'Mostrata quando la playlist non ha flash. Dimensioni consigliate 1920×1080. Visualizzata per 5 secondi.',
        'el' => 'Εμφανίζεται όταν η λίστα δεν έχει flash. Συνιστώμενο μέγεθος 1920×1080. Εμφανίζεται για 5 δευτερόλεπτα.',
    ],
    'display_fallback_choose' => [
        'fi' => 'Valitse kuva...',
        'sv' => 'Välj bild...',
        'en' => 'Choose image...',
        'it' => 'Scegli immagine...',
        'el' => 'Επιλέξτε εικόνα...',
    ],
    'display_fallback_remove' => [
        'fi' => 'Poista',
        'sv' => 'Ta bort',
        'en' => 'Remove',
        'it' => 'Rimuovi',
        'el' => 'Αφαίρεση',
    ],
    'display_fallback_current' => [
        'fi' => 'Nykyinen kuva',
        'sv' => 'Nuvarande bild',
        'en' => 'Current image',
        'it' => 'Immagine attuale',
        'el' => 'Τρέχουσα εικόνα',
    ],
    'display_fallback_none' => [
        'fi' => 'Ei fallback-kuvaa asetettu',
        'sv' => 'Ingen fallback-bild inställd',
        'en' => 'No fallback image set',
        'it' => 'Nessuna immagine di fallback impostata',
        'el' => 'Δεν έχει οριστεί εφεδρική εικόνα',
    ],

    // Worksite API key column (Settings page)
    'settings_worksites_col_api_key' => [
        'fi' => 'API-avain',
        'sv' => 'API-nyckel',
        'en' => 'API key',
        'it' => 'Chiave API',
        'el' => 'Κλειδί API',
    ],
    'btn_copy_api_key' => [
        'fi' => 'Kopioi',
        'sv' => 'Kopiera',
        'en' => 'Copy',
        'it' => 'Copia',
        'el' => 'Αντιγραφή',
    ],
    'settings_worksites_no_api_key' => [
        'fi' => 'Ei avainta',
        'sv' => 'Ingen nyckel',
        'en' => 'No key',
        'it' => 'Nessuna chiave',
        'el' => 'Χωρίς κλειδί',
    ],

    // Export worksites
    'btn_export_worksites' => [
        'fi' => 'Vie työmaat',
        'sv' => 'Exportera arbetsplatser',
        'en' => 'Export worksites',
        'it' => 'Esporta cantieri',
        'el' => 'Εξαγωγή εργοταξίων',
    ],
    'btn_export_csv' => [
        'fi' => 'Lataa CSV',
        'sv' => 'Ladda ner CSV',
        'en' => 'Download CSV',
        'it' => 'Scarica CSV',
        'el' => 'Λήψη CSV',
    ],
    'btn_export_json' => [
        'fi' => 'Lataa JSON',
        'sv' => 'Ladda ner JSON',
        'en' => 'Download JSON',
        'it' => 'Scarica JSON',
        'el' => 'Λήψη JSON',
    ],
'playlist_nav_label' => [
    'fi' => 'Työmaanäytöt',
    'sv' => 'Arbetsplatsskärmar',
    'en' => 'Worksite screens',
    'it' => 'Schermi del cantiere',
    'el' => 'Οθόνες εργοταξίου',
],
'display_targets_modal_title' => [
    'fi' => 'Työmaanäyttöasetukset',
    'sv' => 'Arbetsplatsens visningsinställningar',
    'en' => 'Worksite display settings',
    'it' => 'Impostazioni di visualizzazione del cantiere',
    'el' => 'Ρυθμίσεις προβολής εργοταξίου',
],
'display_tab_timing' => [
    'fi' => 'Kestoasetukset',
    'sv' => 'Tidsinställningar',
    'en' => 'Timing settings',
    'it' => 'Impostazioni di durata',
    'el' => 'Ρυθμίσεις χρονισμού',
],
'display_tab_targets' => [
    'fi' => 'Infonäyttökohteet',
    'sv' => 'Visningsenheter',
    'en' => 'Display targets',
    'it' => 'Destinazioni display',
    'el' => 'Στόχοι οθόνης',
],
'display_ttl_current_label' => [
    'fi' => 'Nykyinen',
    'sv' => 'Nuvarande',
    'en' => 'Current',
    'it' => 'Attuale',
    'el' => 'Τρέχουσα',
],
'display_ttl_new_label' => [
    'fi' => 'Uusi valinta',
    'sv' => 'Nytt val',
    'en' => 'New selection',
    'it' => 'Nuova selezione',
    'el' => 'Νέα επιλογή',
],
'display_ttl_expires_prefix' => [
    'fi' => 'Poistuu',
    'sv' => 'Försvinner',
    'en' => 'Expires',
    'it' => 'Scade',
    'el' => 'Λήγει',
],
'display_ttl_days_left' => [
    'fi' => 'pv jäljellä',
    'sv' => 'dagar kvar',
    'en' => 'days left',
    'it' => 'giorni rimanenti',
    'el' => 'ημέρες απομένουν',
],
'display_ttl_no_limit' => [
    'fi' => 'Näkyy toistaiseksi',
    'sv' => 'Visas tills vidare',
    'en' => 'Displayed indefinitely',
    'it' => 'Visualizzato a tempo indeterminato',
    'el' => 'Εμφανίζεται επ\' αόριστον',
],
'display_ttl_not_on_displays' => [
    'fi' => 'Ei näytöillä',
    'sv' => 'Inte på skärmar',
    'en' => 'Not on displays',
    'it' => 'Non sui display',
    'el' => 'Δεν εμφανίζεται',
],
'display_ttl_will_remove' => [
    'fi' => 'SafetyFlash poistetaan kaikilta infonäytöiltä tallennuksen jälkeen',
    'sv' => 'SafetyFlash tas bort från alla skärmar efter sparning',
    'en' => 'SafetyFlash will be removed from all displays after saving',
    'it' => 'SafetyFlash verrà rimosso da tutti i display dopo il salvataggio',
    'el' => 'Το SafetyFlash θα αφαιρεθεί από όλες τις οθόνες μετά την αποθήκευση',
],
'display_btn_remove_from_displays' => [
    'fi' => 'Poista näytöiltä',
    'sv' => 'Ta bort från skärmar',
    'en' => 'Remove from displays',
    'it' => 'Rimuovi dai display',
    'el' => 'Αφαίρεση από τις οθόνες',
],
'display_ttl_after_save' => [
    'fi' => 'tallennuksen jälkeen',
    'sv' => 'efter sparning',
    'en' => 'after saving',
    'it' => 'dopo il salvataggio',
    'el' => 'μετά την αποθήκευση',
],
'display_ttl_preview_label' => [
    'fi' => 'Poistuu näkyvistä',
    'sv' => 'Försvinner från visning',
    'en' => 'Disappears from display',
    'it' => 'Scompare dalla visualizzazione',
    'el' => 'Εξαφανίζεται από την οθόνη',
],
'display_ttl_preview_no_limit' => [
    'fi' => 'Näkyy toistaiseksi',
    'sv' => 'Visas tills vidare',
    'en' => 'Displayed indefinitely',
    'it' => 'Visualizzato a tempo indeterminato',
    'el' => 'Εμφανίζεται επ\' αόριστον',
],
];
