<?php
/**
 * Form Terms - Form fields, validation, steps, labels
 */
return [
'step1_short' => [
    'fi' => 'Tyyppi',
    'sv' => 'Typ',
    'en' => 'Type',
    'it' => 'Tipo',
    'el' => 'Τύπος',
],
'step2_short' => [
    'fi' => 'Paikka ja aika',
    'sv' => 'Plats och tid',
    'en' => 'Location and time',
    'it' => 'Luogo e ora',
    'el' => 'Τοποθεσία και χρόνος',
],
'step3_short' => [
    'fi' => 'Sisältö',
    'sv' => 'Innehåll',
    'en' => 'Content',
    'it' => 'Contenuto',
    'el' => 'Περιεχόμενο',
],
'step4_short' => [
    'fi' => 'Kuvat',
    'sv' => 'Bilder',
    'en' => 'Images',
    'it' => 'Immagini',
    'el' => 'Εικόνες',
],
'step5_short' => [
    'fi' => 'Asettelu',
    'sv' => 'Layout',
    'en' => 'Layout',
    'it' => 'Layout',
    'el' => 'Διάταξη',
],
'step6_short' => [
    'fi' => 'Lähetä',
    'sv' => 'Skicka',
    'en' => 'Submit',
    'it' => 'Invia',
    'el' => 'Υποβολή',
],
'form_progress_label' => [
    'fi' => 'Lomakkeen edistyminen',
    'sv' => 'Formulärets framsteg',
    'en' => 'Form progress',
    'it' => 'Avanzamento del modulo',
    'el' => 'Πρόοδος φόρμας',
],
'step1_heading' => [
    'fi' => '1. Valitse tiedotteen tyyppi',
    'sv' => '1. Välj meddelandetyp',
    'en' => '1. Choose flash type',
    'it' => '1. Scegli il tipo di comunicazione',
    'el' => '1. Επιλέξτε τύπο ανακοίνωσης',
],
'step2_heading' => [
    'fi' => '2. Paikka ja aika',
    'sv' => '2. Plats och tid',
    'en' => '2. Location and time',
    'it' => '2. Luogo e ora',
    'el' => '2. Τοποθεσία και χρόνος',
],
'step3_heading' => [
    'fi' => '3. Sisältö',
    'sv' => '3. Innehåll',
    'en' => '3. Content',
    'it' => '3. Contenuto',
    'el' => '3. Περιεχόμενο',
],
'step4_heading' => [
    'fi' => '4. Kuvat',
    'sv' => '4. Bilder',
    'en' => '4. Images',
    'it' => '4. Immagini',
    'el' => '4. Εικόνες',
],
'step5_heading' => [
    'fi' => 'Vaihe 5: Asettelu',
    'sv' => 'Steg 5: Layout',
    'en' => 'Step 5: Layout',
    'it' => 'Fase 5: Layout',
    'el' => 'Βήμα 5: Διάταξη',
],
'GRID_SELECTED' => [
    'fi' => 'Valittu',
    'en' => 'Selected',
    'sv' => 'Vald',
    'it' => 'Selezionato',
    'el' => 'Επιλεγμένο',
],

'GRID_SELECT_HINT' => [
    'fi' => 'Klikkaa valitaksesi tämän asettelun',
    'en' => 'Click to select this layout',
    'sv' => 'Klicka för att välja denna layout',
    'it' => 'Fai clic per selezionare questo layout',
    'el' => 'Κάντε κλικ για να επιλέξετε αυτή τη διάταξη',
],
'step6_heading' => [
    'fi' => 'Vaihe 6: Esikatselu ja lähetys',
    'sv' => 'Steg 6: Förhandsgranskning och skicka',
    'en' => 'Step 6: Preview and submit',
    'it' => 'Fase 6: Anteprima e invio',
    'el' => 'Βήμα 6: Προεπισκόπηση και υποβολή',
],
'step2_help' => [
    'fi' => 'Valitse työmaa, tarkempi sijainti ja tapahtuma-aika.  Tarvittaessa lisätietoja voi tarkentaa seuraavissa vaiheissa.',
    'sv' => 'Välj arbetsplats, närmare plats och tidpunkt. Vid behov kan du lägga till mer information i följande steg.',
    'en' => 'Select worksite, specific location and time. Additional details can be added in the following steps if needed.',
    'it' => 'Seleziona cantiere, posizione specifica e orario. Ulteriori dettagli possono essere aggiunti nei passaggi successivi se necessario.',
    'el' => 'Επιλέξτε εργοτάξιο, συγκεκριμένη τοποθεσία και ώρα. Επιπλέον λεπτομέρειες μπορούν να προστεθούν στα επόμενα βήματα αν χρειαστεί.',
],
'step4_help' => [
    'fi' => 'Lataa vähintään yksi kuva. Suosittelemme kuvan ottamista vaaka-asennossa — pystykuvissa kohde jää helposti liian pieneksi. Kuvan rajausta ja asemointia voi säätää muokkaustilassa.',
    'sv' => 'Ladda upp minst en bild. Vi rekommenderar att bilden tas i liggande format — i stående bilder blir motivet lätt för litet. Bildens beskärning och placering kan justeras i redigeringsläget.',
    'en' => 'Upload at least one image. We recommend using landscape orientation — in portrait images the subject may appear too small. The image cropping and positioning can be adjusted in edit mode.',
    'it' => 'Carica almeno un\'immagine. Si consiglia di utilizzare il formato orizzontale — nelle immagini verticali il soggetto può risultare troppo piccolo. Il ritaglio e il posizionamento dell\'immagine possono essere regolati in modalità di modifica.',
    'el' => 'Ανεβάστε τουλάχιστον μία εικόνα. Συνιστούμε τη χρήση οριζόντιου προσανατολισμού — στις κάθετες εικόνες το θέμα μπορεί να εμφανίζεται πολύ μικρό. Η περικοπή και η τοποθέτηση της εικόνας μπορούν να ρυθμιστούν στη λειτουργία επεξεργασίας.',
],
'img_main_label' => [
    'fi' => 'Pääkuva',
    'sv' => 'Huvudbild',
    'en' => 'Main image',
    'it' => 'Immagine principale',
    'el' => 'Κύρια εικόνα',
],
'img_2_label' => [
    'fi' => 'Lisäkuva 1',
    'sv' => 'Extrabild 1',
    'en' => 'Extra image 1',
    'it' => 'Immagine extra 1',
    'el' => 'Επιπλέον εικόνα 1',
],
'img_3_label' => [
    'fi' => 'Lisäkuva 2',
    'sv' => 'Extrabild 2',
    'en' => 'Extra image 2',
    'it' => 'Immagine extra 2',
    'el' => 'Επιπλέον εικόνα 2',
],
'log_comment_label' => [
    'fi' => 'Kommentti',
    'en' => 'Comment',
    'sv' => 'Kommentar',
    'it' => 'Commento',
    'el' => 'Σχόλιο',
],
'log_return_reason_label' => [
    'fi' => 'Palautteen syy',
    'en' => 'Reason for return',
    'sv' => 'Anledning till återkoppling',
    'it' => 'Motivo del reso',
    'el' => 'Λόγος επιστροφής',
],
'log_message_to_comms_label' => [
    'fi' => 'Viesti viestinnälle',
    'en' => 'Message to communications',
    'sv' => 'Meddelande till kommunikation',
    'it' => 'Messaggio alla comunicazione',
    'el' => 'Μήνυμα προς επικοινωνία',
],
'root_causes_label' => [
    'fi' => 'Juurisyyt',
    'sv' => 'Grundorsaker',
    'en' => 'Root causes',
    'it' => 'Cause radice',
    'el' => 'Βαθύτερες αιτίες',
],
'actions_label' => [
    'fi' => 'Toimenpiteet',
    'sv' => 'Åtgärder',
    'en' => 'Corrective actions',
    'it' => 'Azioni correttive',
    'el' => 'Διορθωτικές ενέργειες',
],
'root_cause_label' => [
    'fi' => 'Juurisyyt',
    'sv' => 'Rotorsaker',
    'en' => 'Root causes',
    'it' => 'Cause radice',
    'el' => 'Βαθύτερες αιτίες',
],
'site_label' => [
    'fi' => 'Työmaa',
    'sv' => 'Arbetsplats',
    'en' => 'Worksite',
    'it' => 'Cantiere',
    'el' => 'Εργοτάξιο',
],
'when_label' => [
    'fi' => 'Milloin?',
    'sv' => 'När?',
    'en' => 'When?',
    'it' => 'Quando?',
    'el' => 'Πότε;',
],
'filter_search_label' => [
    'fi' => 'Vapaa sanahaku',
    'sv' => 'Fritextsökning',
    'en' => 'Free text search',
    'it' => 'Ricerca libera',
    'el' => 'Αναζήτηση ελεύθερου κειμένου',
],
'date_timespan_header' => [
    'fi' => '📅 Aikaväli',
    'sv' => '📅 Tidsperiod',
    'en' => '📅 Time range',
    'it' => '📅 Intervallo di tempo',
    'el' => '📅 Χρονικό διάστημα',
],
'date_preset_all' => [
    'fi' => 'Kaikki ajat',
    'sv' => 'Alla tider',
    'en' => 'All time',
    'it' => 'Tutto il tempo',
    'el' => 'Όλοι οι χρόνοι',
],
'date_preset_7days' => [
    'fi' => 'Viimeiset 7 päivää',
    'sv' => 'Senaste 7 dagar',
    'en' => 'Last 7 days',
    'it' => 'Ultimi 7 giorni',
    'el' => 'Τελευταίες 7 ημέρες',
],
'date_preset_7days_short' => [
    'fi' => 'Viim. 7 pv',
    'sv' => 'Senaste 7 d',
    'en' => 'Last 7 d',
    'it' => 'Ultimi 7 g',
    'el' => 'Τελ. 7 η',
],
'date_preset_30days' => [
    'fi' => 'Viimeiset 30 päivää',
    'sv' => 'Senaste 30 dagar',
    'en' => 'Last 30 days',
    'it' => 'Ultimi 30 giorni',
    'el' => 'Τελευταίες 30 ημέρες',
],
'date_preset_30days_short' => [
    'fi' => 'Viim. 30 pv',
    'sv' => 'Senaste 30 d',
    'en' => 'Last 30 d',
    'it' => 'Ultimi 30 g',
    'el' => 'Τελ. 30 η',
],
'date_preset_month' => [
    'fi' => 'Tämä kuukausi',
    'sv' => 'Denna månad',
    'en' => 'This month',
    'it' => 'Questo mese',
    'el' => 'Αυτός ο μήνας',
],
'date_preset_month_short' => [
    'fi' => 'Tämä kk',
    'sv' => 'Denna mån',
    'en' => 'This month',
    'it' => 'Questo mese',
    'el' => 'Αυτός μήν',
],
'date_preset_custom' => [
    'fi' => 'Mukautettu aikaväli...',
    'sv' => 'Anpassat intervall...',
    'en' => 'Custom range...',
    'it' => 'Intervallo personalizzato...',
    'el' => 'Προσαρμοσμένο διάστημα...',
],
'date_from' => [
    'fi' => 'Alkaen',
    'sv' => 'Från',
    'en' => 'From',
    'it' => 'Da',
    'el' => 'Από',
],
'date_to' => [
    'fi' => 'Päättyen',
    'sv' => 'Till',
    'en' => 'To',
    'it' => 'A',
    'el' => 'Έως',
],
'date_clear' => [
    'fi' => 'Tyhjennä',
    'sv' => 'Rensa',
    'en' => 'Clear',
    'it' => 'Cancella',
    'el' => 'Καθαρισμός',
],
'date_preset_year' => [
    'fi' => 'Tämä vuosi',
    'sv' => 'Detta år',
    'en' => 'This year',
    'it' => 'Quest\'anno',
    'el' => 'Φέτος',
],
'date_month_header' => [
    'fi' => 'Kuukausi',
    'sv' => 'Månad',
    'en' => 'Month',
    'it' => 'Mese',
    'el' => 'Μήνας',
],
'modal_comment_label' => [
    'fi' => 'Kommentti',
    'sv' => 'Kommentar',
    'en' => 'Comment',
    'it' => 'Commento',
    'el' => 'Σχόλιο',
],
'modal_request_label' => [
    'fi' => 'Palautteen syy',
    'sv' => 'Anledning till återkoppling',
    'en' => 'Reason for feedback',
    'it' => 'Motivo del feedback',
    'el' => 'Λόγος ανατροφοδότησης',
],
'modal_to_comms_label' => [
    'fi' => 'Viesti viestinnälle',
    'sv' => 'Meddelande till kommunikation',
    'en' => 'Message to communications',
    'it' => 'Messaggio alla comunicazione',
    'el' => 'Μήνυμα προς το τμήμα επικοινωνίας',
],
'layout_label' => [
    'fi' => 'Kuvien asettelu',
    'sv' => 'Bildlayout',
    'en' => 'Image layout',
    'it' => 'Disposizione immagini',
    'el' => 'Διάταξη εικόνων',
],
'btn_upload' => [
    'fi' => 'Lataa',
    'sv' => 'Ladda upp',
    'en' => 'Upload',
    'it' => 'Carica',
    'el' => 'Μεταφόρτωση',
],
'slider_zoom_label' => [
    'fi' => 'Zoom',
    'sv' => 'Zoom',
    'en' => 'Zoom',
    'it' => 'Zoom',
    'el' => 'Ζουμ',
],
'slider_position_x_label' => [
    'fi' => 'Sijainti X',
    'sv' => 'Position X',
    'en' => 'Position X',
    'it' => 'Posizione X',
    'el' => 'Θέση X',
],
'slider_position_y_label' => [
    'fi' => 'Sijainti Y',
    'sv' => 'Position Y',
    'en' => 'Position Y',
    'it' => 'Posizione Y',
    'el' => 'Θέση Y',
],
'settings_worksites_add_label' => [
    'fi' => 'Uusi työmaa:',
    'sv' => 'Ny arbetsplats:',
    'en' => 'New worksite:',
    'it' => 'Nuovo cantiere:',
    'el' => 'Νέο εργοτάξιο:',
],
'lang_selection_label' => [
    'fi' => 'Safetyflashin kieli / Language of Safetyflash',
    'sv' => 'Safetyflashens språk / Language of Safetyflash',
    'en' => 'Safetyflash language',
    'it' => 'Lingua del Safetyflash',
    'el' => 'Γλώσσα του Safetyflash',
],
'type_selection_label' => [
    'fi' => 'Valitse Safetyflash-tyyppi',
    'sv' => 'Välj Safetyflash-typ',
    'en' => 'Choose Safetyflash type',
    'it' => 'Scegli il tipo di Safetyflash',
    'el' => 'Επιλέξτε τύπο Safetyflash',
],
'site_detail_label' => [
    'fi' => 'Tarkempi sijainti',
    'sv' => 'Närmare plats',
    'en' => 'Specific location',
    'it' => 'Posizione specifica',
    'el' => 'Συγκεκριμένη τοποθεσία',
],
'related_flash_label' => [
    'fi' => 'Mihin tapahtumaan tutkinta liittyy? ',
    'sv' => 'Vilken händelse gäller utredningen?',
    'en' => 'Which incident does this investigation relate to?',
    'it' => 'A quale incidente si riferisce questa indagine?',
    'el' => 'Σε ποιο περιστατικό αναφέρεται αυτή η έρευνα;',
],
'title_internal_label' => [
    'fi' => 'Otsikko (vain järjestelmää varten)',
    'sv' => 'Rubrik (endast för systemet)',
    'en' => 'Title (system only)',
    'it' => 'Titolo (solo per il sistema)',
    'el' => 'Τίτλος (μόνο για το σύστημα)',
],
'preview_label' => [
    'fi' => 'Esikatselu',
    'en' => 'Preview',
    'sv' => 'Förhandsgranskning',
    'it' => 'Anteprima',
    'el' => 'Προεπισκόπηση',
],
'short_title_label' => [
    'fi' => 'Lyhyt kuvaus',
    'en' => 'Short description',
    'sv' => 'Kort beskrivning',
    'it' => 'Breve descrizione',
    'el' => 'Σύντομη περιγραφή',
],
'description_label' => [
    'fi' => 'Kuvaus',
    'en' => 'Description',
    'sv' => 'Beskrivning',
    'it' => 'Descrizione',
    'el' => 'Περιγραφή',
],
'validation_fill_missing' => [
    'fi' => 'Täytä puuttuvat tiedot:',
    'sv' => 'Fyll i saknad information:',
    'en' => 'Fill in missing information:',
    'it' => 'Compila le informazioni mancanti:',
    'el' => 'Συμπληρώστε τις ελλείπουσες πληροφορίες:',
],
'validation_select_language' => [
    'fi' => 'Valitse kieli',
    'sv' => 'Välj språk',
    'en' => 'Select language',
    'it' => 'Seleziona lingua',
    'el' => 'Επιλέξτε γλώσσα',
],
'validation_select_type' => [
    'fi' => 'Valitse tiedotteen tyyppi',
    'sv' => 'Välj typ av meddelande',
    'en' => 'Select flash type',
    'it' => 'Seleziona tipo di flash',
    'el' => 'Επιλέξτε τύπο flash',
],
'validation_select_worksite' => [
    'fi' => 'Valitse työmaa',
    'sv' => 'Välj arbetsplats',
    'en' => 'Select worksite',
    'it' => 'Seleziona cantiere',
    'el' => 'Επιλέξτε εργοτάξιο',
],
'validation_enter_event_time' => [
    'fi' => 'Syötä tapahtuma-aika',
    'sv' => 'Ange händelsetid',
    'en' => 'Enter event time',
    'it' => 'Inserisci orario evento',
    'el' => 'Εισάγετε ώρα συμβάντος',
],
'validation_time_not_future' => [
    'fi' => 'Tapahtuma-aika ei voi olla tulevaisuudessa',
    'sv' => 'Händelsetiden kan inte vara i framtiden',
    'en' => 'Event time cannot be in the future',
    'it' => 'L\'orario dell\'evento non può essere nel futuro',
    'el' => 'Η ώρα συμβάντος δεν μπορεί να είναι στο μέλλον',
],
'validation_select_base_or_worksite' => [
    'fi' => 'Valitse alkuperäinen tiedote tai syötä työmaa',
    'sv' => 'Välj originalmeddelande eller ange arbetsplats',
    'en' => 'Select base flash or enter worksite',
    'it' => 'Seleziona flash di base o inserisci cantiere',
    'el' => 'Επιλέξτε βασικό flash ή εισάγετε εργοτάξιο',
],
'validation_enter_title' => [
    'fi' => 'Syötä sisäinen otsikko',
    'sv' => 'Ange intern rubrik',
    'en' => 'Enter internal title',
    'it' => 'Inserisci titolo interno',
    'el' => 'Εισάγετε εσωτερικό τίτλο',
],
'validation_enter_short_desc' => [
    'fi' => 'Syötä lyhyt kuvaus',
    'sv' => 'Ange kort beskrivning',
    'en' => 'Enter short description',
    'it' => 'Inserisci breve descrizione',
    'el' => 'Εισάγετε σύντομη περιγραφή',
],
'validation_short_desc_too_long' => [
    'fi' => 'Lyhyt kuvaus on liian pitkä (max 85 merkkiä)',
    'sv' => 'Kort beskrivning är för lång (max 85 tecken)',
    'en' => 'Short description is too long (max 85 characters)',
    'it' => 'La breve descrizione è troppo lunga (max 85 caratteri)',
    'el' => 'Η σύντομη περιγραφή είναι πολύ μεγάλη (μέγ. 85 χαρακτήρες)',
],
'validation_enter_description' => [
    'fi' => 'Syötä tapahtuvan kuvaus',
    'sv' => 'Ange händelsebeskrivning',
    'en' => 'Enter event description',
    'it' => 'Inserisci descrizione evento',
    'el' => 'Εισάγετε περιγραφή συμβάντος',
],
'validation_desc_too_long' => [
    'fi' => 'Kuvaus on liian pitkä (max 950 merkkiä)',
    'sv' => 'Beskrivningen är för lång (max 950 tecken)',
    'en' => 'Description is too long (max 950 characters)',
    'it' => 'La descrizione è troppo lunga (max 950 caratteri)',
    'el' => 'Η περιγραφή είναι πολύ μεγάλη (μέγ. 950 χαρακτήρες)',
],
'validation_root_causes_too_long' => [
    'fi' => 'Juurisyyt-teksti on liian pitkä (max 1500 merkkiä)',
    'sv' => 'Grundorsaker-texten är för lång (max 1500 tecken)',
    'en' => 'Root causes text is too long (max 1500 characters)',
    'it' => 'Il testo delle cause principali è troppo lungo (max 1500 caratteri)',
    'el' => 'Το κείμενο των βασικών αιτιών είναι πολύ μεγάλο (μέγ. 1500 χαρακτήρες)',
],
'validation_actions_too_long' => [
    'fi' => 'Toimenpiteet-teksti on liian pitkä (max 1500 merkkiä)',
    'sv' => 'Åtgärder-texten är för lång (max 1500 tecken)',
    'en' => 'Actions text is too long (max 1500 characters)',
    'it' => 'Il testo delle azioni è troppo lungo (max 1500 caratteri)',
    'el' => 'Το κείμενο των ενεργειών είναι πολύ μεγάλο (μέγ. 1500 χαρακτήρες)',
],
'validation_image_required' => [
    'fi' => 'Lisää vähintään yksi kuva',
    'sv' => 'Lägg till minst en bild',
    'en' => 'Add at least one image',
    'it' => 'Aggiungi almeno un\'immagine',
    'el' => 'Προσθέστε τουλάχιστον μία εικόνα',
],
'card_1_label' => [
    'fi' => 'Kortti 1',
    'sv' => 'Kort 1',
    'en' => 'Card 1',
    'it' => 'Scheda 1',
    'el' => 'Κάρτα 1',
],
'card_2_label' => [
    'fi' => 'Kortti 2',
    'sv' => 'Kort 2',
    'en' => 'Card 2',
    'it' => 'Scheda 2',
    'el' => 'Κάρτα 2',
],
'email_comment_label' => [
    'fi' => 'Kommentti',
    'sv' => 'Kommentar',
    'en' => 'Comment',
    'it' => 'Commento',
    'el' => 'Σχόλιο',
],
'email_welcome_password_label' => [
    'fi' => 'Kirjautumissalasanasi:',
    'sv' => 'Ditt inloggningslösenord:',
    'en' => 'Your login password:',
    'it' => 'La tua password di accesso:',
    'el' => 'Ο κωδικός πρόσβασής σας:',
],
'preview_site_label' => [
    'fi' => 'Työmaa:',
    'sv' => 'Arbetsplats:',
    'en' => 'Worksite:',
    'it' => 'Cantiere:',
    'el' => 'Εργοτάξιο:',
],
'preview_when_label' => [
    'fi' => 'Milloin:',
    'sv' => 'När:',
    'en' => 'When:',
    'it' => 'Quando:',
    'el' => 'Πότε:',
],
'preview_description_label' => [
    'fi' => 'Mitä tapahtui:',
    'sv' => 'Vad hände:',
    'en' => 'What happened:',
    'it' => 'Cosa è successo:',
    'el' => 'Τι συνέβη:',
],
'preview_root_causes_label' => [
    'fi' => 'Juurisyyt:',
    'sv' => 'Rotorsaker:',
    'en' => 'Root causes:',
    'it' => 'Cause radice:',
    'el' => 'Βαθύτερες αιτίες:',
],
'preview_actions_label' => [
    'fi' => 'Toimenpiteet:',
    'sv' => 'Åtgärder:',
    'en' => 'Corrective actions:',
    'it' => 'Azioni correttive:',
    'el' => 'Διορθωτικές ενέργειες:',
],
'validation_fill_required' => [
    'fi' => 'Täytä pakolliset kentät',
    'sv' => 'Fyll i obligatoriska fält',
    'en' => 'Fill in required fields',
    'it' => 'Compila i campi obbligatori',
    'el' => 'Συμπληρώστε τα υποχρεωτικά πεδία',
],
'log_countries_label' => [
    'fi' => 'Maat',
    'sv' => 'Länder',
    'en' => 'Countries',
    'it' => 'Paesi',
    'el' => 'Χώρες',
],
'occurred_at' => [
    'fi' => 'Muokattu',
    'sv' => 'Redigerad',
    'en' => 'Modified',
    'it' => 'Modificato',
    'el' => 'Τροποποιήθηκε',
],
'log_supervisor_message_label' => [
    'fi' => 'Viesti työmaavastaavalta',
    'sv' => 'Meddelande från arbetsledaren',
    'en' => 'Message from Site Manager',
    'it' => 'Messaggio dal responsabile del sito',
    'el' => 'Μήνυμα από υπεύθυνο εργοταξίου',
],
'modal_send_safety_message_label' => [
    'fi' => 'Viesti turvatiimille (valinnainen)',
    'sv' => 'Meddelande till säkerhetsteamet (valfritt)',
    'en' => 'Message to safety team (optional)',
    'it' => 'Messaggio al team di sicurezza (facoltativo)',
    'el' => 'Μήνυμα στην ομάδα ασφαλείας (προαιρετικό)',
],
'validation_email_invalid' => [
    'fi' => 'Anna kelvollinen sähköpostiosoite',
    'en' => 'Enter a valid email address',
    'sv' => 'Ange en giltig e-postadress',
    'it' => 'Inserisci un indirizzo email valido',
    'el' => 'Εισαγάγετε μια έγκυρη διεύθυνση email',
],
'validation_min_length' => [
    'fi' => 'Vähintään {n} merkkiä',
    'en' => 'At least {n} characters',
    'sv' => 'Minst {n} tecken',
    'it' => 'Almeno {n} caratteri',
    'el' => 'Τουλάχιστον {n} χαρακτήρες',
],
'validation_required' => [
    'fi' => 'Pakollinen kenttä',
    'en' => 'Required field',
    'sv' => 'Obligatoriskt fält',
    'it' => 'Campo obbligatorio',
    'el' => 'Υποχρεωτικό πεδίο',
],
'feedback_title_label' => [
    'fi' => 'Otsikko',
    'sv' => 'Titel',
    'en' => 'Title',
    'it' => 'Titolo',
    'el' => 'Τίτλος',
],
'feedback_category_label' => [
    'fi' => 'Kategoria',
    'sv' => 'Kategori',
    'en' => 'Category',
    'it' => 'Categoria',
    'el' => 'Κατηγορία',
],
'feedback_description_label' => [
    'fi' => 'Kuvaus',
    'sv' => 'Beskrivning',
    'en' => 'Description',
    'it' => 'Descrizione',
    'el' => 'Περιγραφή',
],
'feedback_admin_notes_label' => [
    'fi' => 'Admin-muistiinpanot',
    'sv' => 'Admin-anteckningar',
    'en' => 'Admin Notes',
    'it' => 'Note amministratore',
    'el' => 'Σημειώσεις διαχειριστή',
],
'time_just_now' => [
    'fi' => 'Juuri nyt',
    'sv' => 'Just nu',
    'en' => 'Just now',
    'it' => 'Proprio ora',
    'el' => 'Μόλις τώρα',
],
'standalone_investigation_label' => [
    'fi' => 'Luo itsenäinen tutkintatiedote (ilman pohjaa)',
    'sv' => 'Skapa en fristående utredningsrapport (utan grund)',
    'en' => 'Create standalone investigation report (without base)',
    'it' => 'Crea rapporto di indagine indipendente (senza base)',
    'el' => 'Δημιουργία αυτόνομης αναφοράς έρευνας (χωρίς βάση)',
],
'standalone_investigation_help' => [
    'fi' => 'Valitse tämä jos haluat luoda tutkintatiedotteen ilman ensitiedotetta tai vaaratilannetiedotetta pohjana.',
    'sv' => 'Välj detta om du vill skapa en utredningsrapport utan en första rapport eller en farlig situation som grund.',
    'en' => 'Select this if you want to create an investigation report without a first report or danger situation as a base.',
    'it' => 'Seleziona questo se vuoi creare un rapporto di indagine senza una prima relazione o una situazione pericolosa come base.',
    'el' => 'Επιλέξτε αυτό εάν θέλετε να δημιουργήσετε μια αναφορά έρευνας χωρίς μια πρώτη αναφορά ή μια επικίνδυνη κατάσταση ως βάση.',
],
'validation_select_base_or_standalone' => [
    'fi' => 'Valitse pohja tai itsenäinen tutkintatiedote',
    'sv' => 'Välj grund eller fristående utredningsrapport',
    'en' => 'Select base or standalone investigation',
    'it' => 'Seleziona base o indagine indipendente',
    'el' => 'Επιλέξτε βάση ή αυτόνομη έρευνα',
],
// Lisää tämä olemassa olevaan form.php tiedostoon

'select_inspector_title' => [
    'fi' => 'Valitse tarkistaja',
    'sv' => 'Välj granskare',
    'en' => 'Select reviewer',
    'it' => 'Seleziona revisore',
    'el' => 'Επιλέξτε ελεγκτή',
],

'worksite_supervisors_label_prefix' => [
    'fi' => 'Työmaan',
    'sv' => 'Arbetsplatsens',
    'en' => 'Worksite',
    'it' => 'Responsabili del cantiere',
    'el' => 'Υπεύθυνοι εργοταξίου',
],

'worksite_supervisors_label_suffix' => [
    'fi' => 'työmaavastaavat:',
    'sv' => 'ansvariga:',
    'en' => 'sitemanagers:',
    'it' => ':',
    'el' => ':',
],

'search_other_worksites_label' => [
    'fi' => 'Hae muilta työmailta:',
    'sv' => 'Sök från andra arbetsplatser:',
    'en' => 'Search from other worksites:',
    'it' => 'Cerca da altri cantieri:',
    'el' => 'Αναζήτηση από άλλα εργοτάξια:',
],

'search_name_or_worksite_placeholder' => [
    'fi' => 'Hae nimellä tai työmaalla...',
    'sv' => 'Sök med namn eller arbetsplats...',
    'en' => 'Search by name or worksite...',
    'it' => 'Cerca per nome o cantiere...',
    'el' => 'Αναζήτηση με όνομα ή εργοτάξιο...',
],

'selected_label' => [
    'fi' => 'valittu',
    'sv' => 'vald',
    'en' => 'selected',
    'it' => 'selezionato',
    'el' => 'επιλεγμένο',
],

'content_exceeds_single_slide' => [
    'fi' => 'Sisältö ylittää suositellun pituuden. Tiedote jaetaan kahdelle dialle.',
    'sv' => 'Innehållet överskrider rekommenderad längd. Meddelandet delas på två sidor.',
    'en' => 'Content exceeds recommended length. Report will be split into two slides.',
    'it' => 'Il contenuto supera la lunghezza consigliata. Il rapporto sarà diviso in due slide.',
    'el' => 'Το περιεχόμενο υπερβαίνει το συνιστώμενο μήκος. Η αναφορά θα χωριστεί σε δύο διαφάνειες.',
],
'two_slides_notice_title' => [
    'fi' => 'Huomio',
    'sv' => 'Observera',
    'en' => 'Notice',
    'it' => 'Avviso',
    'el' => 'Ειδοποίηση',
],
'two_slides_notice_text' => [
    'fi' => 'Sisältö ylittää suositellun pituuden. Tiedote jaetaan kahdelle dialle.',
    'sv' => 'Innehållet överskrider rekommenderad längd. Meddelandet delas på två sidor.',
    'en' => 'Content exceeds recommended length. Report will be split into two slides.',
    'it' => 'Il contenuto supera la lunghezza consigliata. Il rapporto sarà diviso in due slide.',
    'el' => 'Το περιεχόμενο υπερβαίνει το συνιστώμενο μήκος. Η αναφορά θα χωριστεί σε δύο διαφάνειες.',
],
'submission_comment_label' => [
    'fi' => 'Viesti hyväksyjälle (valinnainen)',
    'sv' => 'Meddelande till granskaren (valfritt)',
    'en' => 'Message to reviewer (optional)',
    'it' => 'Messaggio al revisore (opzionale)',
    'el' => 'Μήνυμα προς τον ελεγκτή (προαιρετικό)',
],
'submission_comment_placeholder' => [
    'fi' => 'Lisää tarvittaessa lisätietoja käsittelijöille (työmaavastaava, turvatiimi ja viestintä)',
    'sv' => 'Lägg vid behov till ytterligare information för handläggare (arbetsplatsansvarig, säkerhetsteam och kommunikation)',
    'en' => 'Add additional information for the handlers if needed (site manager, safetyteam and communications)',
    'it' => 'Aggiungi, se necessario, ulteriori informazioni per i responsabili (responsabile del sito, team di sicurezza e comunicazione)',
    'el' => 'Προσθέστε, εάν χρειάζεται, επιπλέον πληροφορίες για τους υπεύθυνους (υπεύθυνος εργοταξίου, ομάδα ασφάλειας και επικοινωνία)',
],
'submission_comment_help' => [
    'fi' => 'Viesti näkyy hyväksyjälle sähköpostissa ja SafetyFlashin kommenteissa.',
    'sv' => 'Meddelandet visas för granskaren i e-post och i SafetyFlash-kommentarer.',
    'en' => 'The message will be shown to the reviewer in email and SafetyFlash comments.',
    'it' => 'Il messaggio verrà mostrato al revisore nell\'email e nei commenti SafetyFlash.',
    'el' => 'Το μήνυμα θα εμφανιστεί στον ελεγκτή στο email και στα σχόλια SafetyFlash.',
],
'submit_confirm_modal_title' => [
    'fi' => 'Vahvista lähetys',
    'sv' => 'Bekräfta sändning',
    'en' => 'Confirm submission',
    'it' => 'Conferma invio',
    'el' => 'Επιβεβαίωση αποστολής',
],
'submit_confirm_modal_intro' => [
    'fi' => 'SafetyFlash lähetetään seuraavalle työmaavastaavalle tarkistettavaksi:',
    'sv' => 'SafetyFlash skickas till följande platschef för granskning:',
    'en' => 'SafetyFlash will be sent to the following site manager for review:',
    'it' => 'Il SafetyFlash verrà inviato al seguente responsabile di cantiere per la revisione:',
    'el' => 'Το SafetyFlash θα σταλεί στον παρακάτω υπεύθυνο εργοταξίου για έλεγχο:',
],
'submit_confirm_modal_back_help' => [
    'fi' => 'Voit muokata valintoja palaamalla takaisin.',
    'sv' => 'Du kan redigera valen genom att gå tillbaka.',
    'en' => 'You can edit your selections by going back.',
    'it' => 'Puoi modificare le selezioni tornando indietro.',
    'el' => 'Μπορείτε να επεξεργαστείτε τις επιλογές επιστρέφοντας πίσω.',
],
'submission_comment_badge' => [
    'fi' => 'Lisätiedot',
    'sv' => 'Tilläggsinformation',
    'en' => 'Additional information',
    'it' => 'Informazioni aggiuntive',
    'el' => 'Πρόσθετες πληροφορίες',
],
'font_size_label' => [
    'fi' => 'Tekstin koko',
    'sv' => 'Textstorlek',
    'en' => 'Text size',
    'it' => 'Dimensione testo',
    'el' => 'Μέγεθος κειμένου',
],
'font_size_auto' => [
    'fi' => 'Auto',
    'sv' => 'Auto',
    'en' => 'Auto',
    'it' => 'Auto',
    'el' => 'Auto',
],
'font_size_decrease' => [
    'fi' => 'Pienennä tekstiä',
    'sv' => 'Minska textstorleken',
    'en' => 'Decrease text size',
    'it' => 'Riduci dimensione testo',
    'el' => 'Μείωση μεγέθους κειμένου',
],
'font_size_increase' => [
    'fi' => 'Suurenna tekstiä',
    'sv' => 'Öka textstorleken',
    'en' => 'Increase text size',
    'it' => 'Aumenta dimensione testo',
    'el' => 'Αύξηση μεγέθους κειμένου',
],
'layout_mode_label' => [
    'fi' => 'Korttijako',
    'sv' => 'Kortlayout',
    'en' => 'Card layout',
    'it' => 'Layout scheda',
    'el' => 'Διάταξη καρτών',
],
'layout_mode_auto' => [
    'fi' => 'Automaattinen',
    'sv' => 'Automatisk',
    'en' => 'Automatic',
    'it' => 'Automatico',
    'el' => 'Αυτόματο',
],
'layout_mode_force_single' => [
    'fi' => 'Pakota 1 korttiin',
    'sv' => 'Tvinga till 1 kort',
    'en' => 'Force to 1 card',
    'it' => 'Forza su 1 scheda',
    'el' => 'Επιβολή σε 1 κάρτα',
],
'layout_mode_force_double' => [
    'fi' => 'Pakota 2 korttia',
    'sv' => 'Tvinga 2 kort',
    'en' => 'Force 2 cards',
    'it' => 'Forza 2 schede',
    'el' => 'Εξανάγκασε 2 κάρτες',
],
'layout_mode_help' => [
    'fi' => 'Valitse haluatko automaattisen jaon, pyrkiä yhdelle kortille tai pakottaa tutkintatiedotteen kahdelle kortille.',
    'sv' => 'Välj automatisk delning, försök med ett kort eller tvinga undersökningsrapporten till två kort.',
    'en' => 'Choose automatic split, try to fit on one card, or force the investigation report onto two cards.',
    'it' => 'Scegli divisione automatica, prova a usare una sola scheda o forza il rapporto di indagine su due schede.',
    'el' => 'Επίλεξε αυτόματο διαχωρισμό, προσπάθεια για μία κάρτα ή εξαναγκασμό της αναφοράς διερεύνησης σε δύο κάρτες.',
],
'two_slides_notice_title_attention' => [
    'fi' => 'Huomio',
    'sv' => 'Observera',
    'en' => 'Notice',
    'it' => 'Avviso',
    'el' => 'Ειδοποίηση',
],
'two_slides_notice_title_warning' => [
    'fi' => 'Varoitus',
    'sv' => 'Varning',
    'en' => 'Warning',
    'it' => 'Avvertenza',
    'el' => 'Προειδοποίηση',
],
'two_slides_notice_text_auto' => [
    'fi' => 'Sisältö ei mahdu valituilla asetuksilla yhdelle kortille. Tutkintatiedote jaetaan automaattisesti kahdelle kortille.',
    'sv' => 'Innehållet ryms inte på ett kort med de valda inställningarna. Undersökningsrapporten delas automatiskt på två kort.',
    'en' => 'The content does not fit on one card with the selected settings. The investigation report is automatically split into two cards.',
    'it' => 'Il contenuto non entra in una sola scheda con le impostazioni selezionate. Il rapporto di indagine viene diviso automaticamente in due schede.',
    'el' => 'Το περιεχόμενο δεν χωρά σε μία κάρτα με τις επιλεγμένες ρυθμίσεις. Η αναφορά διερεύνησης χωρίζεται αυτόματα σε δύο κάρτες.',
],
'two_slides_notice_text_force_double' => [
    'fi' => 'Tutkintatiedote näytetään pakotetusti kahdella kortilla. Voit suurentaa fonttia, jos haluat hyödyntää kahden kortin tilan paremmin.',
    'sv' => 'Undersökningsrapporten visas med två kort enligt ditt val. Du kan öka textstorleken för att utnyttja utrymmet bättre.',
    'en' => 'The investigation report is forced to two cards. You can increase the font size to make better use of the two-card layout.',
    'it' => 'Il rapporto di indagine viene mostrato forzatamente su due schede. Puoi aumentare la dimensione del testo per sfruttare meglio lo spazio.',
    'el' => 'Η αναφορά διερεύνησης εμφανίζεται υποχρεωτικά σε δύο κάρτες. Μπορείς να αυξήσεις το μέγεθος γραμματοσειράς για καλύτερη αξιοποίηση του χώρου.',
],
'two_slides_notice_text_force_single_fallback' => [
    'fi' => 'Valinta “Pyri 1 korttiin” ei riittänyt nykyisellä sisällöllä. Tutkintatiedote näytetään silti kahdella kortilla. Kokeile pienempää fonttia tai lyhennä sisältöä.',
    'sv' => 'Valet ”Försök med 1 kort” räckte inte för nuvarande innehåll. Undersökningsrapporten visas ändå på två kort. Prova mindre textstorlek eller kortare innehåll.',
    'en' => 'The “Try 1 card” option was not enough for the current content. The investigation report is still shown on two cards. Try a smaller font or shorten the content.',
    'it' => 'L’opzione “Prova 1 scheda” non è sufficiente per il contenuto attuale. Il rapporto di indagine viene comunque mostrato su due schede. Prova un carattere più piccolo o accorcia il contenuto.',
    'el' => 'Η επιλογή “Προσπάθησε για 1 κάρτα” δεν ήταν αρκετή για το τρέχον περιεχόμενο. Η αναφορά διερεύνησης εξακολουθεί να εμφανίζεται σε δύο κάρτες. Δοκίμασε μικρότερη γραμματοσειρά ή συντόμευσε το περιεχόμενο.',
],
'two_slides_notice_text_single_success' => [
    'fi' => 'Tutkintatiedote mahtuu nykyisillä asetuksilla yhdelle kortille.',
    'sv' => 'Undersökningsrapporten ryms med de nuvarande inställningarna på ett kort.',
    'en' => 'The investigation report fits on one card with the current settings.',
    'it' => 'Il rapporto di indagine entra in una sola scheda con le impostazioni attuali.',
    'el' => 'Η αναφορά διερεύνησης χωρά σε μία κάρτα με τις τρέχουσες ρυθμίσεις.',
],
'editing_this_flash' => [
    'fi' => 'muokkaa tätä tiedotetta',
    'sv' => 'redigerar denna notis',
    'en' => 'is editing this flash',
    'it' => 'sta modificando questo avviso',
    'el' => 'επεξεργάζεται αυτή την ειδοποίηση',
],
'started' => [
    'fi' => 'aloitettu',
    'sv' => 'startade',
    'en' => 'started',
    'it' => 'iniziato',
    'el' => 'ξεκίνησε',
],
'ago' => [
    'fi' => 'sitten',
    'sv' => 'sedan',
    'en' => 'ago',
    'it' => 'fa',
    'el' => 'πριν',
],
'continue_anyway' => [
    'fi' => 'Jatka silti',
    'sv' => 'Fortsätt ändå',
    'en' => 'Continue anyway',
    'it' => 'Continua comunque',
    'el' => 'Συνέχεια ούτως ή άλλως',
],
'preview_loading_highres' => [
    'fi' => 'Ladataan tarkempaa esikatselua...',
    'sv' => 'Laddar en mer detaljerad förhandsvisning...',
    'en' => 'Loading higher quality preview...',
    'it' => 'Caricamento dell’anteprima ad alta qualità...',
    'el' => 'Φόρτωση προεπισκόπησης υψηλότερης ποιότητας...',
],
'preview_help_text' => [

    'fi' => 'Klikkaa esikatselukuvaa avataksesi sen suuremmaksi. Voit tarkastella kuvaa tarkemmin zoomaamalla ja muuttamalla tarvittaessa tekstin fonttikokoa.',

    'sv' => 'Klicka på förhandsgranskningsbilden för att öppna den större. Du kan granska bilden närmare genom att zooma och vid behov ändra textens teckenstorlek.',

    'en' => 'Click the preview image to open a larger view. You can examine the image more closely by zooming and adjust the text size if needed.',

    'it' => 'Fare clic sull’immagine di anteprima per aprrirla in dimensioni maggiori. È possibile esaminarla più da vicino utilizzando lo zoom e, se necessario, modificare la dimensione del testo.',

    'el' => 'Κάντε κλικ στην εικόνα προεπισκόπησης για να την ανοίξετε σε μεγαλύτερο μέγεθος. Μπορείτε να τη δείτε πιο αναλυτικά με ζουμ και να αλλάξετε το μέγεθος του κειμένου αν χρειάζεται.'

],
'bundle_members_label' => [
    'fi' => 'Tässä nipussa on mukana kieliversiot:',
    'sv' => 'Detta paket innehåller språkversioner:',
    'en' => 'This bundle includes language versions:',
    'it' => 'Questo pacchetto include versioni linguistiche:',
    'el' => 'Αυτό το πακέτο περιλαμβάνει γλωσσικές εκδόσεις:',
],
'bundle_confirm_sending_label' => [
    'fi' => 'Tarkistukseen lähetetään seuraavat kieliversiot:',
    'sv' => 'Följande språkversioner skickas för granskning:',
    'en' => 'The following language versions will be sent for review:',
    'it' => 'Le seguenti versioni linguistiche verranno inviate per la revisione:',
    'el' => 'Οι ακόλουθες γλωσσικές εκδόσεις θα σταλούν για έλεγχο:',
],
'add_language_modal_title' => [
    'fi' => 'Lisää kieliversio',
    'sv' => 'Lägg till språkversion',
    'en' => 'Add language version',
    'it' => 'Aggiungi versione linguistica',
    'el' => 'Προσθήκη γλωσσικής έκδοσης',
],
'add_language_modal_intro' => [
    'fi' => 'Nykyinen versio tallennetaan luonnokseksi. Valitse kieli uudelle kieliversiolle:',
    'sv' => 'Den nuvarande versionen sparas som utkast. Välj språk för den nya språkversionen:',
    'en' => 'The current version will be saved as a draft. Select the language for the new language version:',
    'it' => 'La versione corrente verrà salvata come bozza. Seleziona la lingua per la nuova versione linguistica:',
    'el' => 'Η τρέχουσα έκδοση θα αποθηκευτεί ως πρόχειρο. Επιλέξτε γλώσσα για τη νέα γλωσσική έκδοση:',
],
'add_language_all_used' => [
    'fi' => 'Kaikki tuetut kieliversiot on jo luotu.',
    'sv' => 'Alla stödda språkversioner har redan skapats.',
    'en' => 'All supported language versions have already been created.',
    'it' => 'Tutte le versioni linguistiche supportate sono già state create.',
    'el' => 'Όλες οι υποστηριζόμενες γλωσσικές εκδόσεις έχουν ήδη δημιουργηθεί.',
],
'source_flash_from_label' => [
    'fi' => 'Tiedotteesta',
    'sv' => 'Från meddelandet',
    'en' => 'From flash',
    'it' => 'Dal flash',
    'el' => 'Από flash',
],
'form_lang_locked_meta_heading' => [
    'fi' => 'Perustiedot (lukittu)',
    'sv' => 'Grunddata (låst)',
    'en' => 'Basic information (locked)',
    'it' => 'Informazioni di base (bloccato)',
    'el' => 'Βασικές πληροφορίες (κλειδωμένες)',
],
'form_lang_base_column_heading' => [
    'fi' => 'Pohjakieli',
    'sv' => 'Källspråk',
    'en' => 'Source language',
    'it' => 'Lingua di origine',
    'el' => 'Γλώσσα πηγής',
],
'form_lang_target_column_heading' => [
    'fi' => 'Käännös',
    'sv' => 'Översättning',
    'en' => 'Translation',
    'it' => 'Traduzione',
    'el' => 'Μετάφραση',
],
'form_lang_info_text' => [
    'fi' => 'Tämä näkymä on tarkoitettu käännösten ja kielenhuollon tekemiseen valmiille safetyflashille. Perustiedot (tyyppi, työmaa, tapahtuma-aika, kuvat) on lukittu pohjatiedotteen mukaisiksi, eikä niitä muuteta.',
    'sv' => 'Den här vyn är avsedd för att göra översättningar och språklig bearbetning av en färdig SafetyFlash. Grundläggande information (typ, arbetsplats, händelsetid, bilder) är låst enligt källtiedote och ändras inte.',
    'en' => 'This view is intended for making translations and language editing of a completed SafetyFlash. Basic information (type, worksite, event time, images) is locked according to the source flash and will not be changed.',
    'it' => 'Questa vista è destinata alla creazione di traduzioni e alla revisione linguistica di un SafetyFlash completato. Le informazioni di base (tipo, cantiere, ora dell\'evento, immagini) sono bloccate in base al flash di origine e non verranno modificate.',
    'el' => 'Αυτή η προβολή προορίζεται για τη δημιουργία μεταφράσεων και γλωσσική επεξεργασία ενός ολοκληρωμένου SafetyFlash. Οι βασικές πληροφορίες (τύπος, εργοτάξιο, ώρα συμβάντος, εικόνες) είναι κλειδωμένες σύμφωνα με το αρχικό flash και δεν θα αλλάξουν.',
],
];
