<?php
/**
 * Images and Layouts - Image editing, layouts, annotations, library
 */
return [
'img_edit_heading' => [
    'fi' => 'Kuvan muokkaus',
    'sv' => 'Bildredigering',
    'en' => 'Image editing',
    'it' => 'Modifica immagine',
    'el' => 'Επεξεργασία εικόνας',
],
'anno_help_short' => [
    'fi' => 'Valitse ikoni ja klikkaa kuvaa',
    'sv' => 'Välj ikon och klicka på bilden',
    'en' => 'Select icon and click on image',
    'it' => 'Seleziona l\'icona e clicca sull\'immagine',
    'el' => 'Επιλέξτε εικονίδιο και κάντε κλικ στην εικόνα',
],
'anno_title' => [
    'fi' => 'Merkinnät',
    'sv' => 'Markeringar',
    'en' => 'Annotations',
    'it' => 'Annotazioni',
    'el' => 'Σημειώσεις',
],
'anno_rotate_45' => [
    'fi' => 'Käännä 45°',
    'sv' => 'Rotera 45°',
    'en' => 'Rotate 45°',
    'it' => 'Ruota 45°',
    'el' => 'Περιστροφή 45°',
],
'anno_size_down' => [
    'fi' => 'Pienennä',
    'sv' => 'Förminska',
    'en' => 'Decrease size',
    'it' => 'Riduci',
    'el' => 'Μείωση μεγέθους',
],
'anno_size_up' => [
    'fi' => 'Suurenna',
    'sv' => 'Förstora',
    'en' => 'Increase size',
    'it' => 'Ingrandisci',
    'el' => 'Αύξηση μεγέθους',
],
'anno_delete_selected' => [
    'fi' => 'Poista',
    'sv' => 'Ta bort',
    'en' => 'Delete',
    'it' => 'Elimina',
    'el' => 'Διαγραφή',
],
'anno_add_text' => [
    'fi' => 'Lisää teksti',
    'sv' => 'Lägg till text',
    'en' => 'Add text',
    'it' => 'Aggiungi testo',
    'el' => 'Προσθήκη κειμένου',
],
'anno_text_placeholder' => [
    'fi' => 'Kirjoita teksti… (Enter = uusi rivi)',
    'sv' => 'Skriv text… (Enter = ny rad)',
    'en' => 'Write text… (Enter = new line)',
    'it' => 'Scrivi testo… (Invio = nuova riga)',
    'el' => 'Γράψτε κείμενο… (Enter = νέα γραμμή)',
],
'anno_help' => [
    'fi' => 'Klikkaa ensin haluamaasi ikonia, sitten klikkaa kuvaa lisätäksesi merkinnän. Voit muuttaa kokoa, kiertää ja siirtää merkintää.',
    'sv' => 'Klicka först på önskad ikon, klicka sedan på bilden för att lägga till markeringen. Du kan ändra storlek, rotera och flytta markeringen.',
    'en' => 'Click on an icon first, then click on the image to add the annotation. You can resize, rotate and move the annotation.',
    'it' => 'Clicca prima sull\'icona desiderata, poi clicca sull\'immagine per aggiungere l\'annotazione.  Puoi ridimensionare, ruotare e spostare l\'annotazione.',
    'el' => 'Κάντε κλικ πρώτα στο επιθυμητό εικονίδιο και μετά κάντε κλικ στην εικόνα για να προσθέσετε τη σημείωση. Μπορείτε να αλλάξετε το μέγεθος, να περιστρέψετε και να μετακινήσετε τη σημείωση.',
],
'img_edit_help' => [
    'fi' => 'Rajaa ja säädä kuvan koko, zoom ja sijainti. Lisää tarvittaessa merkintöjä.',
    'sv' => 'Justera bildens storlek, zoom och position. Lägg till markeringar vid behov.',
    'en' => 'Adjust image size, zoom and position. Add annotations if needed.',
    'it' => 'Regola dimensione, zoom e posizione dell’immagine. Aggiungi marcature se necessario.',
    'el' => 'Ρύθμισε μέγεθος, ζουμ και θέση της εικόνας. Πρόσθεσε σημειώσεις αν χρειάζεται.',
],
'anno_rotate' => [
    'fi' => 'Käännä',
    'sv' => 'Rotera',
    'en' => 'Rotate',
    'it' => 'Ruota',
    'el' => 'Περιστροφή',
],
'anno_delete' => [
    'fi' => 'Poista',
    'sv' => 'Ta bort',
    'en' => 'Delete',
    'it' => 'Elimina',
    'el' => 'Διαγραφή',
],
'anno_arrow' => [
    'fi' => 'Nuoli',
    'sv' => 'Pil',
    'en' => 'Arrow',
    'it' => 'Freccia',
    'el' => 'Βέλος',
],
'anno_circle' => [
    'fi' => 'Ympyrä',
    'sv' => 'Cirkel',
    'en' => 'Circle',
    'it' => 'Cerchio',
    'el' => 'Κύκλος',
],
'anno_crash' => [
    'fi' => 'Törmäys',
    'sv' => 'Krasch',
    'en' => 'Crash',
    'it' => 'Impatto',
    'el' => 'Σύγκρουση',
],
'anno_warning' => [
    'fi' => 'Varoitus',
    'sv' => 'Varning',
    'en' => 'Warning',
    'it' => 'Avviso',
    'el' => 'Προειδοποίηση',
],
'anno_injury' => [
    'fi' => 'Vamma',
    'sv' => 'Skada',
    'en' => 'Injury',
    'it' => 'Infortunio',
    'el' => 'Τραυματισμός',
],
'anno_cross' => [
    'fi' => 'Risti',
    'sv' => 'Kryss',
    'en' => 'Cross',
    'it' => 'Croce',
    'el' => 'Σταυρός',
],
'anno_text' => [
    'fi' => 'Teksti',
    'sv' => 'Text',
    'en' => 'Text',
    'it' => 'Testo',
    'el' => 'Κείμενο',
],
'anno_blur' => [
    'fi' => 'Sumennus',
    'sv' => 'Oskärpa',
    'en' => 'Blur',
    'it' => 'Sfocatura',
    'el' => 'Θόλωμα',
],
'grid_heading' => [
    'fi' => 'Kuvien asettelu',
    'sv' => 'Bildlayout',
    'en' => 'Image layout',
    'it' => 'Layout immagini',
    'el' => 'Διάταξη εικόνων',
],
'grid_help' => [
    'fi' => 'Valitse asettelu valituille kuville.',
    'sv' => 'Välj layout för de valda bilderna.',
    'en' => 'Choose a layout for the selected images.',
    'it' => 'Scegli un layout per le immagini selezionate.',
    'el' => 'Επίλεξε διάταξη για τις επιλεγμένες εικόνες.',
],
'grid_layout_1' => [
    'fi' => 'Asettelu 1',
    'sv' => 'Layout 1',
    'en' => 'Layout 1',
    'it' => 'Layout 1',
    'el' => 'Διάταξη 1',
],
'grid_layout_2a' => [
    'fi' => 'Asettelu 1',
    'sv' => 'Layout 1',
    'en' => 'Layout 1',
    'it' => 'Layout 1',
    'el' => 'Διάταξη 1',
],
'grid_layout_2b' => [
    'fi' => 'Asettelu 2',
    'sv' => 'Layout 2',
    'en' => 'Layout 2',
    'it' => 'Layout 2',
    'el' => 'Διάταξη 2',
],
'grid_layout_3a' => [
    'fi' => 'Asettelu 1',
    'sv' => 'Layout 1',
    'en' => 'Layout 1',
    'it' => 'Layout 1',
    'el' => 'Διάταξη 1',
],
'grid_layout_3b' => [
    'fi' => 'Asettelu 2',
    'sv' => 'Layout 2',
    'en' => 'Layout 2',
    'it' => 'Layout 2',
    'el' => 'Διάταξη 2',
],
'grid_layout_3c' => [
    'fi' => 'Asettelu 3',
    'sv' => 'Layout 3',
    'en' => 'Layout 3',
    'it' => 'Layout 3',
    'el' => 'Διάταξη 3',
],
'IMAGE_EDIT_MAIN' => [
    'fi' => 'Kuvan muokkaus: Pääkuva',
    'sv' => 'Bildredigering: Huvudbild',
    'en' => 'Edit image: Main image',
    'it' => 'Modifica immagine: Immagine principale',
    'el' => 'Επεξεργασία εικόνας: Κύρια εικόνα',
],
'IMAGE_EDIT_EXTRA_PREFIX' => [
    'fi' => 'Kuvan muokkaus: Lisäkuva',
    'sv' => 'Bildredigering: Extrabild',
    'en' => 'Edit image: Additional image',
    'it' => 'Modifica immagine: Immagine aggiuntiva',
    'el' => 'Επεξεργασία εικόνας: Πρόσθετη εικόνα',
],
'IMAGE_SAVED' => [
    'fi' => 'Kuva tallennettu',
    'sv' => 'Bild sparad',
    'en' => 'Image saved',
    'it' => 'Immagine salvata',
    'el' => 'Η εικόνα αποθηκεύτηκε',
],
'layout_auto' => [
    'fi' => 'Valitse asettelu automaattisesti',
    'sv' => 'Välj layout automatiskt',
    'en' => 'Choose layout automatically',
    'it' => 'Scegli layout automaticamente',
    'el' => 'Επιλογή διάταξης αυτόματα',
],
'layout_main_only' => [
    'fi' => 'Vain pääkuva',
    'sv' => 'Endast huvudbild',
    'en' => 'Main image only',
    'it' => 'Solo immagine principale',
    'el' => 'Μόνο κύρια εικόνα',
],
'layout_two_main_large' => [
    'fi' => 'Pääkuva ylhäällä, lisäkuva alla',
    'sv' => 'Huvudbild överst, extrabild under',
    'en' => 'Main image on top, secondary below',
    'it' => 'Immagine principale in alto, secondaria sotto',
    'el' => 'Κύρια εικόνα επάνω, δευτερεύουσα από κάτω',
],
'layout_two_even' => [
    'fi' => 'Kaksi kuvaa vierekkäin',
    'sv' => 'Två bilder bredvid varandra',
    'en' => 'Two images side by side',
    'it' => 'Due immagini affiancate',
    'el' => 'Δύο εικόνες δίπλα δίπλα',
],
'layout_three_main' => [
    'fi' => 'Pääkuva + kaksi pienempää',
    'sv' => 'Huvudbild + två mindre',
    'en' => 'Main + two smaller images',
    'it' => 'Principale + due più piccole',
    'el' => 'Κύρια + δύο μικρότερες',
],
'layout_three_even' => [
    'fi' => 'Kolme kuvaa tasajakona',
    'sv' => 'Tre bilder i jämn fördelning',
    'en' => 'Three images, even layout',
    'it' => 'Tre immagini in layout uniforme',
    'el' => 'Τρεις εικόνες σε ομοιόμορφη διάταξη',
],
'layout_three_overlay' => [
    'fi' => 'Pääkuva, pikkukuvat kulmassa',
    'sv' => 'Huvudbild med miniatyrer i hörnet',
    'en' => 'Main image with thumbnails in the corner',
    'it' => 'Principale con miniature nell’angolo',
    'el' => 'Κύρια εικόνα με μικρογραφίες στη γωνία',
],
'library_upload_heading' => [
    'fi' => 'Lisää uusi kuva',
    'sv' => 'Lägg till ny bild',
    'en' => 'Add new image',
    'it' => 'Aggiungi nuova immagine',
    'el' => 'Προσθήκη νέας εικόνας',
],
'library_label_image' => [
    'fi' => 'Kuvatiedosto',
    'sv' => 'Bildfil',
    'en' => 'Image file',
    'it' => 'File immagine',
    'el' => 'Αρχείο εικόνας',
],
'library_label_title' => [
    'fi' => 'Otsikko',
    'sv' => 'Rubrik',
    'en' => 'Title',
    'it' => 'Titolo',
    'el' => 'Τίτλος',
],
'library_label_category' => [
    'fi' => 'Kategoria',
    'sv' => 'Kategori',
    'en' => 'Category',
    'it' => 'Categoria',
    'el' => 'Κατηγορία',
],
'library_label_description' => [
    'fi' => 'Kuvaus (valinnainen)',
    'sv' => 'Beskrivning (valfritt)',
    'en' => 'Description (optional)',
    'it' => 'Descrizione (facoltativa)',
    'el' => 'Περιγραφή (προαιρετικό)',
],
'library_cat_all' => [
    'fi' => 'Kaikki',
    'en' => 'All',
    'sv' => 'Alla',
    'it' => 'Tutti',
    'el' => 'Όλα',
],
'library_cat_body' => [
    'fi' => 'Hahmokuvat',
    'en' => 'Body figures',
    'sv' => 'Kroppsfigurer',
    'it' => 'Figure del corpo',
    'el' => 'Σχήματα σώματος',
],
'library_cat_warning' => [
    'fi' => 'Varoitusmerkit',
    'en' => 'Warning signs',
    'sv' => 'Varningsskyltar',
    'it' => 'Segnali di avvertimento',
    'el' => 'Προειδοποιητικά σήματα',
],
'library_cat_equipment' => [
    'fi' => 'Laitteet',
    'en' => 'Equipment',
    'sv' => 'Utrustning',
    'it' => 'Attrezzature',
    'el' => 'Εξοπλισμός',
],
'library_cat_template' => [
    'fi' => 'Pohjat',
    'en' => 'Templates',
    'sv' => 'Mallar',
    'it' => 'Modelli',
    'el' => 'Πρότυπα',
],
'library_select_btn' => [
    'fi' => 'Valitse kuva',
    'en' => 'Select image',
    'sv' => 'Välj bild',
    'it' => 'Seleziona immagine',
    'el' => 'Επιλέξτε εικόνα',
],
'library_no_images' => [
    'fi' => 'Ei kuvia tässä kategoriassa.',
    'en' => 'No images in this category.',
    'sv' => 'Inga bilder i denna kategori.',
    'it' => 'Nessuna immagine in questa categoria.',
    'el' => 'Δεν υπάρχουν εικόνες σε αυτή την κατηγορία.',
],
'library_loading' => [
    'fi' => 'Ladataan kuvia...',
    'en' => 'Loading images...',
    'sv' => 'Laddar bilder...',
    'it' => 'Caricamento immagini...',
    'el' => 'Φόρτωση εικόνων...',
],
'library_filter_label_show' => [
    'fi' => 'Näytä:',
    'sv' => 'Visa:',
    'en' => 'Show:',
    'it' => 'Mostra:',
    'el' => 'Εμφάνιση:',
],
'library_badge_hidden' => [
    'fi' => 'Piilotettu',
    'sv' => 'Dold',
    'en' => 'Hidden',
    'it' => 'Nascosto',
    'el' => 'Κρυφό',
],
'library_action_hide' => [
    'fi' => 'Piilota',
    'sv' => 'Dölj',
    'en' => 'Hide',
    'it' => 'Nascondi',
    'el' => 'Απόκρυψη',
],
'library_action_show' => [
    'fi' => 'Näytä',
    'sv' => 'Visa',
    'en' => 'Show',
    'it' => 'Mostra',
    'el' => 'Εμφάνιση',
],
'library_empty' => [
    'fi' => 'Ei kuvia.',
    'sv' => 'Inga bilder.',
    'en' => 'No images.',
    'it' => 'Nessuna immagine.',
    'el' => 'Δεν υπάρχουν εικόνες.',
],
'library_empty_in_category' => [
    'fi' => 'Ei kuvia tässä kategoriassa.',
    'sv' => 'Inga bilder i den här kategorin.',
    'en' => 'No images in this category.',
    'it' => 'Nessuna immagine in questa categoria.',
    'el' => 'Δεν υπάρχουν εικόνες σε αυτή την κατηγορία.',
],
'library_delete_heading' => [
    'fi' => 'Poista kuva',
    'sv' => 'Ta bort bild',
    'en' => 'Delete image',
    'it' => 'Elimina immagine',
    'el' => 'Διαγραφή εικόνας',
],
'library_delete_confirm' => [
    'fi' => 'Haluatko varmasti poistaa kuvan',
    'sv' => 'Är du säker på att du vill ta bort bilden',
    'en' => 'Are you sure you want to delete the image',
    'it' => 'Sei sicuro di voler eliminare l\'immagine',
    'el' => 'Είστε σίγουροι ότι θέλετε να διαγράψετε την εικόνα',
],
'library_delete_help' => [
    'fi' => 'Kuva poistetaan pysyvästi kuvapankista.',
    'sv' => 'Bilden tas bort permanent från bildbiblioteket.',
    'en' => 'The image will be permanently removed from the library.',
    'it' => 'L\'immagine verrà rimossa definitivamente dalla libreria.',
    'el' => 'Η εικόνα θα αφαιρεθεί μόνιμα από τη βιβλιοθήκη.',
],
// Extra images upload terms
'extra_img_max_limit' => [
    'fi' => 'Maksimimäärä lisäkuvia on {n}',
    'sv' => 'Maximalt antal extra bilder är {n}',
    'en' => 'Maximum number of extra images is {n}',
    'it' => 'Il numero massimo di immagini extra è {n}',
    'el' => 'Ο μέγιστος αριθμός επιπλέον εικόνων είναι {n}',
],
'extra_img_invalid_type' => [
    'fi' => 'Virheellinen tiedostomuoto. Sallitut: JPEG, PNG, GIF, WEBP, HEIC, HEIF',
    'sv' => 'Ogiltigt filformat. Tillåtna: JPEG, PNG, GIF, WEBP, HEIC, HEIF',
    'en' => 'Invalid file format. Allowed: JPEG, PNG, GIF, WEBP, HEIC, HEIF',
    'it' => 'Formato file non valido. Consentiti: JPEG, PNG, GIF, WEBP, HEIC, HEIF',
    'el' => 'Μη έγκυρη μορφή αρχείου. Επιτρέπονται: JPEG, PNG, GIF, WEBP, HEIC, HEIF',
],
'extra_img_too_large' => [
    'fi' => 'Tiedosto on liian suuri. Maksimikoko: 20MB',
    'sv' => 'Filen är för stor. Maxstorlek: 20MB',
    'en' => 'File is too large. Max size: 20MB',
    'it' => 'Il file è troppo grande. Dimensione massima: 20MB',
    'el' => 'Το αρχείο είναι πολύ μεγάλο. Μέγιστο μέγεθος: 20MB',
],
'extra_img_upload_failed' => [
    'fi' => 'Lataus epäonnistui',
    'sv' => 'Uppladdningen misslyckades',
    'en' => 'Upload failed',
    'it' => 'Caricamento fallito',
    'el' => 'Η μεταφόρτωση απέτυχε',
],
'btn_upload' => [
    'fi' => 'Lataa',
    'sv' => 'Ladda upp',
    'en' => 'Upload',
    'it' => 'Carica',
    'el' => 'Μεταφόρτωση',
],
'extra_img_processing' => [
    'fi' => 'Prosessoidaan...',
    'sv' => 'Bearbetar...',
    'en' => 'Processing...',
    'it' => 'Elaborazione...',
    'el' => 'Επεξεργασία...',
],
'extra_img_remove' => [
    'fi' => 'Poista kuva',
    'sv' => 'Ta bort bild',
    'en' => 'Remove image',
    'it' => 'Rimuovi immagine',
    'el' => 'Αφαίρεση εικόνας',
],
'extra_img_add_btn' => [
    'fi' => 'Lisää kuvia',
    'sv' => 'Lägg till bilder',
    'en' => 'Add images',
    'it' => 'Aggiungi immagini',
    'el' => 'Προσθήκη εικόνων',
],
'extra_img_drop_here' => [
    'fi' => 'Pudota kuvat tähän',
    'sv' => 'Släpp bilderna här',
    'en' => 'Drop images here',
    'it' => 'Rilascia le immagini qui',
    'el' => 'Αποθέστε τις εικόνες εδώ',
],
'extra_img_heic_placeholder' => [
    'fi' => 'HEIC/HEIF',
    'sv' => 'HEIC/HEIF',
    'en' => 'HEIC/HEIF',
    'it' => 'HEIC/HEIF',
    'el' => 'HEIC/HEIF',
],
'extra_img_max_reached' => [
    'fi' => 'Maksimimäärä saavutettu',
    'sv' => 'Maxgräns nådd',
    'en' => 'Maximum reached',
    'it' => 'Massimo raggiunto',
    'el' => 'Συμπληρώθηκε το μέγιστο',
],
'extra_img_delete_confirm' => [
    'fi' => 'Haluatko varmasti poistaa tämän kuvan?',
    'sv' => 'Är du säker på att du vill ta bort den här bilden?',
    'en' => 'Are you sure you want to delete this image?',
    'it' => 'Sei sicuro di voler eliminare questa immagine?',
    'el' => 'Είστε βέβαιοι ότι θέλετε να διαγράψετε αυτή την εικόνα;',
],
'extra_images_title' => [
    'fi' => 'Liitekuvat',
    'sv' => 'Extra bilder',
    'en' => 'Extra Images',
    'it' => 'Immagini extra',
    'el' => 'Επιπλέον εικόνες',
],
'extra_images_description' => [
    'fi' => 'Liitekuvat eivät näy esikatselukuvassa. Ne tallentuvat Safetyflash-tiedotteelle ja ovat nähtävissä Kuvat-välilehdellä. Kuvia voi lisätä myös jälkikäteen.',
    'sv' => 'Bilagda bilder visas inte i förhandsgranskningsbilden. De sparas i Safetyflash-meddelandet och kan ses under fliken Bilder. Bilder kan också läggas till i efterhand.',
    'en' => 'Attachment images are not shown in the preview image. They are saved with the Safetyflash report and can be viewed in the Images tab. Images can also be added later.',
    'it' => 'Le immagini allegate non vengono mostrate nell’immagine di anteprima. Vengono salvate nella segnalazione Safetyflash e sono visibili nella scheda Immagini. È possibile aggiungere immagini anche in un secondo momento.',
    'el' => 'Οι συνημμένες εικόνες δεν εμφανίζονται στην εικόνα προεπισκόπησης. Αποθηκεύονται στην αναφορά Safetyflash και είναι διαθέσιμες στην καρτέλα Εικόνες. Οι εικόνες μπορούν επίσης να προστεθούν αργότερα.',
],
'extra_images_add_button' => [
    'fi' => 'Lisää kuvia',
    'sv' => 'Lägg till bilder',
    'en' => 'Add images',
    'it' => 'Aggiungi immagini',
    'el' => 'Προσθήκη εικόνων',
],
'activity_tab_images' => [
    'fi' => 'Media',
    'sv' => 'Media',
    'en' => 'Media',
    'it' => 'Media',
    'el' => 'Πολυμέσα',
],
'images_loading' => [
    'fi' => 'Ladataan kuvia...',
    'sv' => 'Laddar bilder...',
    'en' => 'Loading images...',
    'it' => 'Caricamento immagini...',
    'el' => 'Φόρτωση εικόνων...',
],
'no_images_message' => [
    'fi' => 'Ei kuvia saatavilla.',
    'sv' => 'Inga bilder tillgängliga.',
    'en' => 'No images available.',
    'it' => 'Nessuna immagine disponibile.',
    'el' => 'Δεν υπάρχουν διαθέσιμες εικόνες.',
],
'images_loading_error' => [
    'fi' => 'Kuvien lataus epäonnistui.',
    'sv' => 'Bildladdningen misslyckades.',
    'en' => 'Failed to load images.',
    'it' => 'Caricamento immagini non riuscito.',
    'el' => 'Η φόρτωση των εικόνων απέτυχε.',
],
'delete_error' => [
    'fi' => 'Virhe poistettaessa',
    'sv' => 'Fel vid borttagning',
    'en' => 'Error deleting',
    'it' => 'Errore durante l\'eliminazione',
    'el' => 'Σφάλμα κατά τη διαγραφή',
],
'unknown_error' => [
    'fi' => 'Tuntematon virhe',
    'sv' => 'Okänt fel',
    'en' => 'Unknown error',
    'it' => 'Errore sconosciuto',
    'el' => 'Άγνωστο σφάλμα',
],
'delete_success' => [
    'fi' => 'Kuva poistettu',
    'sv' => 'Bild borttagen',
    'en' => 'Image deleted',
    'it' => 'Immagine eliminata',
    'el' => 'Η εικόνα διαγράφηκε',
],
// Upload modal terms
'add_images_btn' => [
    'fi' => 'Lisää kuvia',
    'sv' => 'Lägg till bilder',
    'en' => 'Add images',
    'it' => 'Aggiungi immagini',
    'el' => 'Προσθήκη εικόνων',
],
'upload_modal_title' => [
    'fi' => 'Lisää kuvia',
    'sv' => 'Lägg till bilder',
    'en' => 'Add images',
    'it' => 'Aggiungi immagini',
    'el' => 'Προσθήκη εικόνων',
],
'upload_drag_text' => [
    'fi' => 'Vedä ja pudota kuvia tähän',
    'sv' => 'Dra och släpp bilder här',
    'en' => 'Drag and drop images here',
    'it' => 'Trascina e rilascia le immagini qui',
    'el' => 'Σύρετε και αποθέστε εικόνες εδώ',
],
'upload_drop_here' => [
    'fi' => 'Pudota tähän',
    'sv' => 'Släpp här',
    'en' => 'Drop here',
    'it' => 'Rilascia qui',
    'el' => 'Αποθέστε εδώ',
],
'upload_browse_btn' => [
    'fi' => 'Lataa koneelta',
    'sv' => 'Ladda från datorn',
    'en' => 'Upload from computer',
    'it' => 'Carica dal computer',
    'el' => 'Μεταφόρτωση από τον υπολογιστή',
],
'upload_camera_btn' => [
    'fi' => 'Ota kuva',
    'sv' => 'Ta bild',
    'en' => 'Take photo',
    'it' => 'Scatta foto',
    'el' => 'Τραβήξτε φωτογραφία',
],
'upload_success' => [
    'fi' => 'Kuva ladattu onnistuneesti',
    'sv' => 'Bild uppladdad',
    'en' => 'Image uploaded successfully',
    'it' => 'Immagine caricata con successo',
    'el' => 'Η εικόνα μεταφορτώθηκε με επιτυχία',
],
'upload_error' => [
    'fi' => 'Lataus epäonnistui',
    'sv' => 'Uppladdningen misslyckades',
    'en' => 'Upload failed',
    'it' => 'Caricamento fallito',
    'el' => 'Η μεταφόρτωση απέτυχε',
],
'upload_retrying' => [
    'fi' => 'Yritetään uudelleen...',
    'sv' => 'Försöker igen...',
    'en' => 'Retrying...',
    'it' => 'Nuovo tentativo...',
    'el' => 'Γίνεται νέα προσπάθεια...',
],
'no_images' => [
    'fi' => 'Ei kuvia',
    'sv' => 'Inga bilder',
    'en' => 'No images',
    'it' => 'Nessuna immagine',
    'el' => 'Δεν υπάρχουν εικόνες',
],
'main_images_title' => [
    'fi' => 'Pääkuvat',
    'sv' => 'Huvudbilder',
    'en' => 'Main Images',
    'it' => 'Immagini principali',
    'el' => 'Κύριες εικόνες',
],
'select_image_files' => [
    'fi' => 'Valitse kuvatiedostoja',
    'sv' => 'Välj bildfiler',
    'en' => 'Select image files',
    'it' => 'Seleziona file immagine',
    'el' => 'Επιλέξτε αρχεία εικόνας',
],
'images_uploading' => [
    'fi' => '{count} / {total} kuvaa ladattu',
    'sv' => '{count} / {total} bilder uppladdade',
    'en' => '{count} / {total} images uploaded',
    'it' => '{count} / {total} immagini caricate',
    'el' => '{count} / {total} εικόνες μεταφορτώθηκαν',
],
'images_upload_partial' => [
    'fi' => '{failed} / {total} kuvan lataus epäonnistui',
    'sv' => '{failed} / {total} bilduppladdningar misslyckades',
    'en' => '{failed} / {total} image uploads failed',
    'it' => '{failed} / {total} caricamenti immagine non riusciti',
    'el' => '{failed} / {total} μεταφορτώσεις εικόνων απέτυχαν',
],
'crop_guide_text' => [
    'fi' => 'Katkoviiva (1:1) näyttää neliökuvissa näkyvän alueen. Tummennettu reuna-alue näkyy 16:9-vaaka-asettelussa.',
    'sv' => 'Den streckade linjen (1:1) visar det synliga området i kvadratiska bilder. Det nedtonade kantområdet syns i 16:9-liggande layout.',
    'en' => 'The dashed line (1:1) shows the visible area in square images. The dimmed edge area is visible in 16:9 landscape layout.',
    'it' => 'La linea tratteggiata (1:1) mostra l\'area visibile nelle immagini quadrate. L\'area oscurata ai bordi è visibile nel layout 16:9 orizzontale.',
    'el' => 'Η διακεκομμένη γραμμή (1:1) δείχνει την ορατή περιοχή σε τετράγωνες εικόνες. Η σκοτεινή περιοχή στις άκρες είναι ορατή σε οριζόντια διάταξη 16:9.',
],
'crop_guide_label' => [
    'fi' => 'Rajausopas',
    'sv' => 'Beskärningsguide',
    'en' => 'Crop guide',
    'it' => 'Guida al ritaglio',
    'el' => 'Οδηγός περικοπής',
],
'crop_guide_annotations_hint' => [
    'fi' => 'Merkintöjä voi lisätä myös kevyesti tummennetulle alueelle — ne näkyvät vaaka-asettelussa.',
    'sv' => 'Markeringar kan läggas till även på det lätt nedtonade området — de syns i liggande layout.',
    'en' => 'Annotations can also be placed on the slightly dimmed area — they will be visible in landscape layouts.',
    'it' => 'Le annotazioni possono essere aggiunte anche nell\'area leggermente oscurata — saranno visibili nel layout orizzontale.',
    'el' => 'Οι σημειώσεις μπορούν να προστεθούν και στην ελαφρώς σκοτεινή περιοχή — θα είναι ορατές στη οριζόντια διάταξη.',
],
'crop_guide_show_more' => [
    'fi' => 'Näytä lisäohjeet',
    'sv' => 'Visa mer info',
    'en' => 'Show more tips',
    'it' => 'Mostra altri suggerimenti',
    'el' => 'Εμφάνιση περισσότερων συμβουλών',
],
'crop_guide_details' => [
    'fi' => 'Yksi kuva → asemoi kohde 1:1-neliön sisälle|Useampi kuva → kuvat näkyvät 16:9-alueella, asemoi koko alueelle|Merkintöjä voi lisätä myös tummennetulle alueelle|Palauta-painike asemoi kuvan automaattisesti reunasta reunaan|Tallenna, tarkista esikatselusta ja palaa tarvittaessa säätämään',
    'sv' => 'En bild → placera motivet inom 1:1-rutan|Flera bilder → bilderna visas i 16:9-format, placera över hela ytan|Markeringar kan läggas till även i det nedtonade området|Återställ-knappen placerar bilden automatiskt från kant till kant|Spara, granska i förhandsgranskningen och återkom för justeringar',
    'en' => 'One image → position the subject within the 1:1 square|Multiple images → images display in 16:9, position across the full area|Annotations can be placed on the dimmed area too|Reset button automatically fits the image edge to edge|Save, check the preview and return to adjust if needed',
    'it' => 'Una immagine → posiziona il soggetto nel quadrato 1:1|Più immagini → le immagini vengono mostrate in 16:9, posiziona su tutta l\'area|Le annotazioni possono essere aggiunte anche nell\'area oscurata|Il pulsante Ripristina posiziona automaticamente l\'immagine da bordo a bordo|Salva, controlla l\'anteprima e torna per modificare se necessario',
    'el' => 'Μία εικόνα → τοποθετήστε το θέμα εντός του τετραγώνου 1:1|Πολλές εικόνες → οι εικόνες εμφανίζονται σε 16:9, τοποθετήστε σε ολόκληρη την περιοχή|Σημειώσεις μπορούν να προστεθούν και στη σκοτεινή περιοχή|Το κουμπί Επαναφορά τοποθετεί αυτόματα την εικόνα από άκρη σε άκρη|Αποθηκεύστε, ελέγξτε την προεπισκόπηση και επιστρέψτε για ρυθμίσεις',
],
'extra_images_add_button' => [
    'fi' => 'Lisää kuvia',
    'sv' => 'Lägg till bilder',
    'en' => 'Add images',
    'it' => 'Aggiungi immagini',
    'el' => 'Προσθήκη εικόνων',
],
// Video upload terms
'add_video_btn' => [
    'fi' => 'Lisää video',
    'sv' => 'Lägg till video',
    'en' => 'Add video',
    'it' => 'Aggiungi video',
    'el' => 'Προσθήκη βίντεο',
],
'video_modal_title' => [
    'fi' => 'Videotoisto',
    'sv' => 'Videouppspelning',
    'en' => 'Video player',
    'it' => 'Riproduzione video',
    'el' => 'Αναπαραγωγή βίντεο',
],
'video_upload_invalid_type' => [
    'fi' => 'Virheellinen videomuoto. Sallitut: MP4, WebM, OGG, MOV',
    'sv' => 'Ogiltigt videoformat. Tillåtna: MP4, WebM, OGG, MOV',
    'en' => 'Invalid video format. Allowed: MP4, WebM, OGG, MOV',
    'it' => 'Formato video non valido. Consentiti: MP4, WebM, OGG, MOV',
    'el' => 'Μη έγκυρη μορφή βίντεο. Επιτρεπόμενες: MP4, WebM, OGG, MOV',
],
'video_upload_too_large' => [
    'fi' => 'Videotiedosto on liian suuri. Maksimikoko: 200 Mt',
    'sv' => 'Videofilen är för stor. Maxstorlek: 200 MB',
    'en' => 'Video file is too large. Maximum size: 200 MB',
    'it' => 'Il file video è troppo grande. Dimensione massima: 200 MB',
    'el' => 'Το αρχείο βίντεο είναι πολύ μεγάλο. Μέγιστο μέγεθος: 200 MB',
],
'video_upload_success' => [
    'fi' => 'Video ladattu onnistuneesti',
    'sv' => 'Video uppladdad',
    'en' => 'Video uploaded successfully',
    'it' => 'Video caricato con successo',
    'el' => 'Το βίντεο μεταφορτώθηκε με επιτυχία',
],
'no_media_message' => [
    'fi' => 'Ei mediaa saatavilla.',
    'sv' => 'Inget media tillgängligt.',
    'en' => 'No media available.',
    'it' => 'Nessun media disponibile.',
    'el' => 'Δεν υπάρχουν διαθέσιμα πολυμέσα.',
],
'media_loading' => [
    'fi' => 'Ladataan mediaa...',
    'sv' => 'Laddar media...',
    'en' => 'Loading media...',
    'it' => 'Caricamento media...',
    'el' => 'Φόρτωση πολυμέσων...',
],
'extra_videos_title' => [
    'fi' => 'Lisävideot',
    'sv' => 'Extra videor',
    'en' => 'Extra videos',
    'it' => 'Video aggiuntivi',
    'el' => 'Επιπλέον βίντεο',
],
];

