<?php
/**
 * List Page - Filtering, search, pagination, list operations
 */
return [
'list_filters' => [
    'fi' => 'Suodattimet',
    'sv' => 'Filter',
    'en' => 'Filters',
    'it' => 'Filtri',
    'el' => 'Φίλτρα',
],
'list_heading' => [
    'fi' => 'Safetyflash-lista',
    'sv' => 'Safetyflash-lista',
    'en' => 'Safetyflash list',
    'it' => 'Elenco Safetyflash',
    'el' => 'Λίστα Safetyflash',
],
'filter_all' => [
    'fi' => 'Kaikki',
    'sv' => 'Alla',
    'en' => 'All',
    'it' => 'Tutti',
    'el' => 'Όλα',
],
'filter_apply' => [
    'fi' => 'Käytä suodattimia',
    'sv' => 'Använd filter',
    'en' => 'Apply filters',
    'it' => 'Applica filtri',
    'el' => 'Εφαρμογή φίλτρων',
],
'filter_clear' => [
    'fi' => 'Tyhjennä suodattimet',
    'sv' => 'Rensa filter',
    'en' => 'Clear filters',
    'it' => 'Pulisci filtri',
    'el' => 'Καθαρισμός φίλτρων',
],
'filter_date_from' => [
    'fi' => 'Alkaen',
    'sv' => 'Från',
    'en' => 'From',
    'it' => 'Da',
    'el' => 'Από',
],
'filter_date_to' => [
    'fi' => 'Päättyen',
    'sv' => 'Till',
    'en' => 'To',
    'it' => 'A',
    'el' => 'Έως',
],
'filter_search_placeholder' => [
    'fi' => 'Hae otsikosta, kuvauksesta...',
    'sv' => 'Sök i rubrik, beskrivning...',
    'en' => 'Search in title, description...',
    'it' => 'Cerca nel titolo, descrizione...',
    'el' => 'Αναζήτηση σε τίτλο, περιγραφή...',
],
'filter_site' => [
    'fi' => 'Työmaa',
    'sv' => 'Arbetsplats',
    'en' => 'Worksite',
    'it' => 'Cantiere',
    'el' => 'Εργοτάξιο',
],
'filter_state' => [
    'fi' => 'Tila',
    'sv' => 'Status',
    'en' => 'Status',
    'it' => 'Stato',
    'el' => 'Κατάσταση',
],
'filter_type' => [
    'fi' => 'Tyyppi',
    'sv' => 'Typ',
    'en' => 'Type',
    'it' => 'Tipo',
    'el' => 'Τύπος',
],
'filter_only_originals' => [
    'fi' => 'Vain alkuperäiset',
    'sv' => 'Endast original',
    'en' => 'Originals only',
    'it' => 'Solo originali',
    'el' => 'Μόνο πρωτότυπα',
],
'filter_chip_only_originals' => [
    'fi' => 'Alkuperäiset',
    'sv' => 'Original',
    'en' => 'Originals',
    'it' => 'Originali',
    'el' => 'Πρωτότυπα',
],
'filter_original_type' => [
    'fi' => 'Alkuperäinen tyyppi',
    'sv' => 'Ursprunglig typ',
    'en' => 'Original type',
    'it' => 'Tipo originale',
    'el' => 'Αρχικός τύπος',
],
'filter_chip_original_type_all' => [
    'fi' => 'Alkuperäinen tyyppi',
    'sv' => 'Ursprunglig typ',
    'en' => 'Original type',
    'it' => 'Tipo originale',
    'el' => 'Αρχικός τύπος',
],
'filter_archived' => [
    'fi' => 'Arkistoidut',
    'sv' => 'Arkiverade',
    'en' => 'Archived',
    'it' => 'Archiviati',
    'el' => 'Αρχειοθετημένα',
],
'filter_show_active' => [
    'fi' => 'Vain aktiiviset',
    'sv' => 'Endast aktiva',
    'en' => 'Active only',
    'it' => 'Solo attivi',
    'el' => 'Μόνο ενεργά',
],
'filter_reset' => [
    'fi' => 'Nollaa suodattimet',
    'sv' => 'Återställ filter',
    'en' => 'Reset filters',
    'it' => 'Ripristina filtri',
    'el' => 'Επαναφορά φίλτρων',
],
'filter_search' => [
    'fi' => 'Hae',
    'sv' => 'Sök',
    'en' => 'Search',
    'it' => 'Cerca',
    'el' => 'Αναζήτηση',
],
'filter_chip_archived_active' => [
    'fi' => 'Aktiiviset',
    'sv' => 'Aktiva',
    'en' => 'Active',
    'it' => 'Attivi',
    'el' => 'Ενεργά',
],
'filter_chip_archived_only' => [
    'fi' => 'Arkistoidut',
    'sv' => 'Arkiverade',
    'en' => 'Archived',
    'it' => 'Archiviati',
    'el' => 'Αρχειοθετημένα',
],
'filter_chip_archived_all' => [
    'fi' => 'Kaikki',
    'sv' => 'Alla',
    'en' => 'All',
    'it' => 'Tutti',
    'el' => 'Όλα',
],
'filter_chip_type_all' => [
    'fi' => 'Kaikki tyypit',
    'sv' => 'Alla typer',
    'en' => 'All types',
    'it' => 'Tutti i tipi',
    'el' => 'Όλοι οι τύποι',
],
'filter_chip_state_all' => [
    'fi' => 'Kaikki tilat',
    'sv' => 'Alla statusar',
    'en' => 'All statuses',
    'it' => 'Tutti gli stati',
    'el' => 'Όλες οι καταστάσεις',
],
'filter_chip_site_all' => [
    'fi' => 'Kaikki työmaat',
    'sv' => 'Alla arbetsplatser',
    'en' => 'All worksites',
    'it' => 'Tutti i cantieri',
    'el' => 'Όλα τα εργοτάξια',
],
'filter_chip_date' => [
    'fi' => 'Päivämäärä',
    'sv' => 'Datum',
    'en' => 'Date',
    'it' => 'Data',
    'el' => 'Ημερομηνία',
],
'filter_search_input' => [
    'fi' => 'Haku',
    'sv' => 'Sök',
    'en' => 'Search',
    'it' => 'Cerca',
    'el' => 'Αναζήτηση',
],
'filter_clear_all' => [
    'fi' => 'Tyhjennä',
    'sv' => 'Rensa',
    'en' => 'Clear',
    'it' => 'Cancella',
    'el' => 'Καθαρισμός',
],
'filter_results_count' => [
    'fi' => 'Näytetään {visible} / {total} tulosta',
    'sv' => 'Visar {visible} / {total} resultat',
    'en' => 'Showing {visible} / {total} results',
    'it' => 'Mostrando {visible} / {total} risultati',
    'el' => 'Εμφάνιση {visible} / {total} αποτελεσμάτων',
],
'filter_no_results' => [
    'fi' => 'Ei tuloksia – kokeile muuttaa suodattimia',
    'sv' => 'Inga resultat – försök ändra filter',
    'en' => 'No results – try changing filters',
    'it' => 'Nessun risultato – prova a modificare i filtri',
    'el' => 'Δεν υπάρχουν αποτελέσματα – δοκιμάστε να αλλάξετε τα φίλτρα',
],
'filter_done' => [
    'fi' => 'Valmis',
    'sv' => 'Klar',
    'en' => 'Done',
    'it' => 'Fatto',
    'el' => 'Τέλος',
],
'pagination_prev' => [
    'fi' => 'Edellinen',
    'sv' => 'Föregående',
    'en' => 'Previous',
    'it' => 'Precedente',
    'el' => 'Προηγούμενο',
],
'pagination_next' => [
    'fi' => 'Seuraava',
    'sv' => 'Nästa',
    'en' => 'Next',
    'it' => 'Successivo',
    'el' => 'Επόμενο',
],
'pagination_page' => [
    'fi' => 'Sivu',
    'en' => 'Page',
    'sv' => 'Sida',
    'it' => 'Pagina',
    'el' => 'Σελίδα',
],
'pagination_of' => [
    'fi' => '/',
    'en' => 'of',
    'sv' => 'av',
    'it' => 'di',
    'el' => 'από',
],
'lang_fallback_notice' => [
    'fi' => 'Ei käännöstä kielellesi - näytetään alkuperäinen',
    'sv' => 'Ingen översättning för ditt språk - visar original',
    'en' => 'No translation for your language - showing original',
    'it' => 'Nessuna traduzione per la tua lingua - mostra originale',
    'el' => 'Δεν υπάρχει μετάφραση για τη γλώσσα σας - εμφανίζεται το πρωτότυπο',
],
'sort_by' => [
    'fi' => 'Järjestä',
    'sv' => 'Sortera',
    'en' => 'Sort by',
    'it' => 'Ordina per',
    'el' => 'Ταξινόμηση',
],
'sort_created' => [
    'fi' => 'Luotu',
    'sv' => 'Skapad',
    'en' => 'Created',
    'it' => 'Creato',
    'el' => 'Δημιουργήθηκε',
],
'sort_occurred' => [
    'fi' => 'Tapahtuma-aika',
    'sv' => 'Händelsetid',
    'en' => 'Occurred',
    'it' => 'Accaduto',
    'el' => 'Συνέβη',
],
'sort_updated' => [
    'fi' => 'Muokattu',
    'sv' => 'Ändrad',
    'en' => 'Modified',
    'it' => 'Modificato',
    'el' => 'Τροποποιήθηκε',
],
'sort_newest' => [
    'fi' => 'uusin',
    'sv' => 'nyaste',
    'en' => 'newest',
    'it' => 'più recente',
    'el' => 'νεότερο',
],
'sort_oldest' => [
    'fi' => 'vanhin',
    'sv' => 'äldsta',
    'en' => 'oldest',
    'it' => 'più vecchio',
    'el' => 'παλαιότερο',
],
'editing_indicator' => [
    'fi' => '{name} muokkaa...',
    'sv' => '{name} redigerar...',
    'en' => '{name} is editing...',
    'it' => '{name} sta modificando...',
    'el' => '{name} επεξεργάζεται...',
],
];