<?php
/**
 * Log Events and Audit Trail - Activity logs, audit records
 */
return [
'log_param_countries' => [
    'fi' => 'Maat',
    'sv' => 'Länder',
    'en' => 'Countries',
    'it' => 'Paesi',
    'el' => 'Χώρες',
],
'log_status_set' => [
    'fi' => 'Tila asetettu',
    'en' => 'Status set',
    'sv' => 'Status satt',
    'it' => 'Stato impostato',
    'el' => 'Η κατάσταση ορίστηκε',
],
'log_group_deleted' => [
    'fi' => 'Safetyflash-ryhmä poistettu',
    'en' => 'Safetyflash group deleted',
    'sv' => 'Safetyflash-grupp raderad',
    'it' => 'Gruppo Safetyflash eliminato',
    'el' => 'Η ομάδα Safetyflash διαγράφηκε',
],
'log_version_deleted' => [
    'fi' => 'Kieliversio poistettu',
    'en' => 'Language version deleted',
    'sv' => 'Språkversion raderad',
    'it' => 'Versione linguistica eliminata',
    'el' => 'Η γλωσσική έκδοση διαγράφηκε',
],
'log_inline_edit' => [
    'fi' => '{role} muokkasi tiedotetta.  Tila: {state}',
    'sv' => '{role} redigerade meddelandet. Status: {state}',
    'en' => '{role} edited the flash.  Status: {state}',
    'it' => '{role} ha modificato il flash. Stato: {state}',
    'el' => '{role} επεξεργάστηκε το flash. Κατάσταση: {state}',
],
'log_lang_version_suffix' => [
    'fi' => ' (kieliversio:  {lang})',
    'en' => ' (language version: {lang})',
    'sv' => ' (språkversion: {lang})',
    'it' => ' (versione linguistica: {lang})',
    'el' => ' (γλωσσική έκδοση: {lang})',
],
'log_title' => [
    'fi' => 'Lokitiedot',
    'sv' => 'Logg',
    'en' => 'Log',
    'it' => 'Log',
    'el' => 'Καταγραφή',
],
'log_empty' => [
    'fi' => 'Ei lokitietoja.',
    'sv' => 'Inga loggposter.',
    'en' => 'No log entries.',
    'it' => 'Nessuna voce di log.',
    'el' => 'Δεν υπάρχουν καταχωρήσεις καταγραφής.',
],
'log_show_more' => [
    'fi' => 'Näytä lisää',
    'sv' => 'Visa mer',
    'en' => 'Show more',
    'it' => 'Mostra di più',
    'el' => 'Εμφάνιση περισσότερων',
],
'log_show_less' => [
    'fi' => 'Näytä vähemmän',
    'sv' => 'Visa mindre',
    'en' => 'Show less',
    'it' => 'Mostra meno',
    'el' => 'Εμφάνιση λιγότερων',
],
'log_system_user' => [
    'fi' => 'Järjestelmä',
    'sv' => 'System',
    'en' => 'System',
    'it' => 'Sistema',
    'el' => 'Σύστημα',
],
'audit_log_heading' => [
    'fi' => 'Tapahtumaloki',
    'sv' => 'Aktivitetslogg',
    'en' => 'Activity Log',
    'it' => 'Registro attività',
    'el' => 'Καταγραφή δραστηριοτήτων',
],
'audit_log_total' => [
    'fi' => 'Yhteensä',
    'sv' => 'Totalt',
    'en' => 'Total',
    'it' => 'Totale',
    'el' => 'Σύνολο',
],
'audit_log_events' => [
    'fi' => 'tapahtumaa',
    'sv' => 'händelser',
    'en' => 'events',
    'it' => 'eventi',
    'el' => 'συμβάντα',
],
'audit_filter_action' => [
    'fi' => 'Toiminto',
    'sv' => 'Åtgärd',
    'en' => 'Action',
    'it' => 'Azione',
    'el' => 'Ενέργεια',
],
'audit_filter_user' => [
    'fi' => 'Käyttäjä',
    'sv' => 'Användare',
    'en' => 'User',
    'it' => 'Utente',
    'el' => 'Χρήστης',
],
'audit_filter_user_placeholder' => [
    'fi' => 'Sähköposti tai ID',
    'sv' => 'E-post eller ID',
    'en' => 'Email or ID',
    'it' => 'Email o ID',
    'el' => 'Email ή ID',
],
'audit_filter_ip' => [
    'fi' => 'IP-osoite',
    'sv' => 'IP-adress',
    'en' => 'IP Address',
    'it' => 'Indirizzo IP',
    'el' => 'Διεύθυνση IP',
],
'audit_filter_date_from' => [
    'fi' => 'Alkaen',
    'sv' => 'Från',
    'en' => 'From',
    'it' => 'Da',
    'el' => 'Από',
],
'audit_filter_date_to' => [
    'fi' => 'Päättyen',
    'sv' => 'Till',
    'en' => 'To',
    'it' => 'A',
    'el' => 'Έως',
],
'audit_btn_filter' => [
    'fi' => 'Suodata',
    'sv' => 'Filtrera',
    'en' => 'Filter',
    'it' => 'Filtra',
    'el' => 'Φιλτράρισμα',
],
'audit_btn_clear' => [
    'fi' => 'Tyhjennä',
    'sv' => 'Rensa',
    'en' => 'Clear',
    'it' => 'Pulisci',
    'el' => 'Καθαρισμός',
],
'audit_col_time' => [
    'fi' => 'Aika',
    'sv' => 'Tid',
    'en' => 'Time',
    'it' => 'Ora',
    'el' => 'Ώρα',
],
'audit_col_user' => [
    'fi' => 'Käyttäjä',
    'sv' => 'Användare',
    'en' => 'User',
    'it' => 'Utente',
    'el' => 'Χρήστης',
],
'audit_col_action' => [
    'fi' => 'Toiminto',
    'sv' => 'Åtgärd',
    'en' => 'Action',
    'it' => 'Azione',
    'el' => 'Ενέργεια',
],
'audit_col_target' => [
    'fi' => 'Kohde',
    'sv' => 'Mål',
    'en' => 'Target',
    'it' => 'Obiettivo',
    'el' => 'Στόχος',
],
'audit_col_ip' => [
    'fi' => 'IP',
    'sv' => 'IP',
    'en' => 'IP',
    'it' => 'IP',
    'el' => 'IP',
],
'audit_col_details' => [
    'fi' => 'Tiedot',
    'sv' => 'Detaljer',
    'en' => 'Details',
    'it' => 'Dettagli',
    'el' => 'Λεπτομέρειες',
],
'audit_no_results' => [
    'fi' => 'Ei tapahtumia',
    'sv' => 'Inga händelser',
    'en' => 'No events',
    'it' => 'Nessun evento',
    'el' => 'Καμία καταγραφή',
],
'audit_details_title' => [
    'fi' => 'Lisätiedot',
    'sv' => 'Detaljer',
    'en' => 'Details',
    'it' => 'Dettagli',
    'el' => 'Λεπτομέρειες',
],
'audit_worksite_activated' => [
    'fi' => 'Työmaa aktivoitu',
    'sv' => 'Arbetsplats aktiverad',
    'en' => 'Worksite activated',
    'it' => 'Cantiere attivato',
    'el' => 'Ενεργοποίηση εργοταξίου',
],
'audit_worksite_deactivated' => [
    'fi' => 'Työmaa passivoitu',
    'sv' => 'Arbetsplats inaktiverad',
    'en' => 'Worksite deactivated',
    'it' => 'Cantiere disattivato',
    'el' => 'Απενεργοποίηση εργοταξίου',
],
'log_flash_edited' => [
    'fi' => 'Tiedote muokattu',
    'en' => 'Flash edited',
    'sv' => 'Flash redigerad',
    'it' => 'Flash modificato',
    'el' => 'Το flash επεξεργάστηκε',
],
'log_flash_edited_no_status_change' => [
    'fi' => 'Tiedotetta muokattu (ei tilamuutosta)',
    'sv' => 'Meddelande redigerat (ingen statusändring)',
    'en' => 'Flash edited (no status change)',
    'it' => 'Comunicazione modificata (nessun cambio di stato)',
    'el' => 'Ανακοίνωση επεξεργάστηκε (χωρίς αλλαγή κατάστασης)',
],
'log_status_prefix' => [
    'fi' => 'Tila',
    'sv' => 'Status',
    'en' => 'Status',
    'it' => 'Stato',
    'el' => 'Κατάσταση',
],
'log_state_changed' => [
    'fi' => 'Tila muutettu',
    'sv' => 'Status ändrad',
    'en' => 'Status changed',
    'it' => 'Stato modificato',
    'el' => 'Η κατάσταση άλλαξε',
],
'log_published_direct' => [
    'fi' => 'Julkaistu suoraan ilman viestinnän toimintoja',
    'sv' => 'Publicerad direkt utan kommunikationens funktioner',
    'en' => 'Published directly without communications actions',
    'it' => 'Pubblicato direttamente senza le funzioni della comunicazione',
    'el' => 'Δημοσιεύτηκε απευθείας χωρίς λειτουργίες επικοινωνίας',
],
'log_type_changed' => [
    'fi' => 'Tyyppi muutettu',
    'sv' => 'Typ ändrad',
    'en' => 'Type changed',
    'it' => 'Tipo modificato',
    'el' => 'Ο τύπος άλλαξε',
],
'log_title_changed' => [
    'fi' => 'Otsikko muutettu',
    'sv' => 'Rubrik ändrad',
    'en' => 'Title changed',
    'it' => 'Titolo modificato',
    'el' => 'Ο τίτλος άλλαξε',
],
'log_summary_changed' => [
    'fi' => 'Yhteenveto muutettu',
    'sv' => 'Sammanfattning ändrad',
    'en' => 'Summary changed',
    'it' => 'Riepilogo modificato',
    'el' => 'Η περίληψη άλλαξε',
],
'log_description_changed' => [
    'fi' => 'Kuvaus muutettu',
    'sv' => 'Beskrivning ändrad',
    'en' => 'Description changed',
    'it' => 'Descrizione modificata',
    'el' => 'Η περιγραφή άλλαξε',
],
'log_site_changed' => [
    'fi' => 'Työmaa muutettu',
    'sv' => 'Arbetsplats ändrad',
    'en' => 'Worksite changed',
    'it' => 'Cantiere modificato',
    'el' => 'Το εργοτάξιο άλλαξε',
],
'log_occurred_at_changed' => [
    'fi' => 'Tapahtuma-aika muutettu',
    'sv' => 'Tidpunkt ändrad',
    'en' => 'Time of incident changed',
    'it' => 'Data/ora evento modificata',
    'el' => 'Ο χρόνος συμβάντος άλλαξε',
],
'log_root_causes_changed' => [
    'fi' => 'Juurisyyt muutettu',
    'sv' => 'Grundorsaker ändrade',
    'en' => 'Root causes changed',
    'it' => 'Cause radice modificate',
    'el' => 'Οι βασικές αιτίες άλλαξαν',
],
'root_causes' => [
    'fi' => 'Juurisyyt',
    'sv' => 'Grundorsaker',
    'en' => 'Root causes',
    'it' => 'Cause principali',
    'el' => 'Βασικές αιτίες',
],
'log_actions_changed' => [
    'fi' => 'Toimenpiteet muutettu',
    'sv' => 'Åtgärder ändrade',
    'en' => 'Actions changed',
    'it' => 'Azioni modificate',
    'el' => 'Οι ενέργειες άλλαξαν',
],
'log_not_set' => [
    'fi' => 'ei asetettu',
    'sv' => 'ej inställd',
    'en' => 'not set',
    'it' => 'non impostato',
    'el' => 'δεν έχει οριστεί',
],
'log_investigation_added' => [
    'fi' => 'Tutkintatiedote lisätty',
    'sv' => 'Utredningsrapport tillagd',
    'en' => 'Investigation report added',
    'it' => 'Rapporto di indagine aggiunto',
    'el' => 'Προστέθηκε αναφορά έρευνας',
],
'log_investigation_created' => [
    'fi' => 'Tutkintatiedote luotu',
    'sv' => 'Utredningsrapport skapad',
    'en' => 'Investigation report created',
    'it' => 'Rapporto di indagine creato',
    'el' => 'Δημιουργήθηκε αναφορά έρευνας',
],
'log_translations_archived' => [
    'fi' => 'Kieliversiot arkistoitu',
    'sv' => 'Språkversioner arkiverade',
    'en' => 'Language versions archived',
    'it' => 'Versioni linguistiche archiviate',
    'el' => 'Γλωσσικές εκδόσεις αρχειοθετήθηκαν',
],
'log_original_archived' => [
    'fi' => 'Alkuperäinen sisältö arkistoitu',
    'sv' => 'Originalinnehåll arkiverat',
    'en' => 'Original content archived',
    'it' => 'Contenuto originale archiviato',
    'el' => 'Αρχικό περιεχόμενο αρχειοθετήθηκε',
],
'log_translation_saved' => [
    'fi' => 'Kieliversio {lang} tallennettu',
    'sv' => 'Språkversion {lang} sparad',
    'en' => 'Language version {lang} saved',
    'it' => 'Versione linguistica {lang} salvata',
    'el' => 'Η γλωσσική έκδοση {lang} αποθηκεύτηκε',
],
'log_translation_created' => [
    'fi' => 'Kieliversio luotu',
    'sv' => 'Språkversion skapad',
    'en' => 'Language version created',
    'it' => 'Versione linguistica creata',
    'el' => 'Δημιουργήθηκε γλωσσική έκδοση',
],
'log_flash_group_deleted' => [
    'fi' => 'Safetyflash-ryhmä (ID %d) poistettu käyttäjän toimesta.',
    'sv' => 'Safetyflash-grupp (ID %d) raderad av användaren.',
    'en' => 'Safetyflash group (ID %d) deleted by user.',
    'it' => 'Gruppo Safetyflash (ID %d) eliminato dall\'utente.',
    'el' => 'Η ομάδα Safetyflash (ID %d) διαγράφηκε από τον χρήστη.',
],
'log_translation_deleted' => [
    'fi' => 'Kieliversio (ID %d) poistettu käyttäjän toimesta.',
    'sv' => 'Språkversion (ID %d) raderad av användaren.',
    'en' => 'Language version (ID %d) deleted by user.',
    'it' => 'Versione linguistica (ID %d) eliminata dall\'utente.',
    'el' => 'Η γλωσσική έκδοση (ID %d) διαγράφηκε από τον χρήστη.',
],
'log_role_edited_flash' => [
    'fi' => '{role} muokkasi tiedotetta{lang_info}.  Tila säilyy:  {status}',
    'sv' => '{role} redigerade meddelandet{lang_info}. Status kvarstår: {status}',
    'en' => '{role} edited the flash{lang_info}. Status remains: {status}',
    'it' => '{role} ha modificato la comunicazione{lang_info}.  Stato rimane: {status}',
    'el' => '{role} επεξεργάστηκε την ανακοίνωση{lang_info}. Η κατάσταση παραμένει: {status}',
],
'log_language_version' => [
    'fi' => 'kieliversio',
    'sv' => 'språkversion',
    'en' => 'language version',
    'it' => 'versione linguistica',
    'el' => 'γλωσσική έκδοση',
],
'log_distribution_sent' => [
    'fi' => 'Lähetetty jakeluryhmille',
    'sv' => 'Skickat till distributionsgrupper',
    'en' => 'Sent to distribution groups',
    'it' => 'Inviato ai gruppi di distribuzione',
    'el' => 'Εστάλη στις ομάδες διανομής',
],
'log_recipients_count' => [
    'fi' => 'vastaanottajaa',
    'sv' => 'mottagare',
    'en' => 'recipients',
    'it' => 'destinatari',
    'el' => 'παραλήπτες',
],
'log_edited_no_status' => [
    'fi' => 'Tiedotetta muokattu (tila säilyy)',
    'sv' => 'Meddelandet redigerat (status oförändrad)',
    'en' => 'Flash edited (status unchanged)',
    'it' => 'Flash modificato (stato invariato)',
    'el' => 'Το flash επεξεργάστηκε (η κατάσταση παραμένει)',
],
'log_type_changed_prefix' => [
    'fi' => 'Tyyppi muutettu',
    'en' => 'Type changed',
    'sv' => 'Typ ändrad',
    'it' => 'Tipo modificato',
    'el' => 'Ο τύπος άλλαξε',
],
'log_investigation_added_prefix' => [
    'fi' => 'Tutkintatiedote lisätty.  Tyyppi muutettu',
    'en' => 'Investigation report added. Type changed',
    'sv' => 'Utredningsrapport tillagd. Typ ändrad',
    'it' => 'Rapporto di indagine aggiunto. Tipo modificato',
    'el' => 'Προστέθηκε αναφορά έρευνας. Ο τύπος άλλαξε',
],
'log_comms_edited' => [
    'fi' => 'muokkasi tiedotetta',
    'en' => 'edited flash',
    'sv' => 'redigerade flash',
    'it' => 'ha modificato il flash',
    'el' => 'επεξεργάστηκε το flash',
],
'log_lang_version' => [
    'fi' => 'kieliversio',
    'en' => 'language version',
    'sv' => 'språkversion',
    'it' => 'versione linguistica',
    'el' => 'γλωσσική έκδοση',
],
'log_status_remains' => [
    'fi' => 'Tila säilyy',
    'en' => 'Status remains',
    'sv' => 'Status förblir',
    'it' => 'Lo stato rimane',
    'el' => 'Η κατάσταση παραμένει',
],
'log_role_comms' => [
    'fi' => 'Viestintä',
    'en' => 'Communications',
    'sv' => 'Kommunikation',
    'it' => 'Comunicazioni',
    'el' => 'Επικοινωνίες',
],
'log_role_safety' => [
    'fi' => 'Turvatiimi',
    'en' => 'Safety team',
    'sv' => 'Säkerhetsteam',
    'it' => 'Team sicurezza',
    'el' => 'Ομάδα ασφαλείας',
],
'log_role_admin' => [
    'fi' => 'Admin',
    'en' => 'Admin',
    'sv' => 'Admin',
    'it' => 'Admin',
    'el' => 'Admin',
],
'log_created' => [
    'fi' => 'Luotu',
    'sv' => 'Skapad',
    'en' => 'Created',
    'it' => 'Creato',
    'el' => 'Δημιουργήθηκε',
],
'log_param_details' => [
    'fi' => 'Tiedot',
    'sv' => 'Detaljer',
    'en' => 'Details',
    'it' => 'Dettagli',
    'el' => 'Λεπτομέρειες',
],
'log_sent_to_supervisor' => [
    'fi' => 'Lähetetty työmaavastaavalle',
    'sv' => 'Skickad till platschef',
    'en' => 'Sent to supervisor',
    'it' => 'Inviato al supervisore',
    'el' => 'Στάλθηκε στον επόπτη',
],
'log_supervisor_approved' => [
    'fi' => 'Tymaavastaava hyväksyi',
    'sv' => 'Platschefen godkände',
    'en' => 'Supervisor approved',
    'it' => 'Supervisore approvato',
    'el' => 'Ο επόπτης ενέκρινε',
],
'activity_tab_comments' => [
    'fi' => 'Kommentit',
    'sv' => 'Kommentarer',
    'en' => 'Comments',
    'it' => 'Commenti',
    'el' => 'Σχόλια',
],
'activity_tab_events' => [
    'fi' => 'Tapahtumat',
    'sv' => 'Händelser',
    'en' => 'Events',
    'it' => 'Eventi',
    'el' => 'Γεγονότα',
],
'activity_tab_all' => [
    'fi' => 'Kaikki',
    'sv' => 'Alla',
    'en' => 'All',
    'it' => 'Tutti',
    'el' => 'Όλα',
],
'activity_empty' => [
    'fi' => 'Ei toimintaa',
    'sv' => 'Ingen aktivitet',
    'en' => 'No activity',
    'it' => 'Nessuna attività',
    'el' => 'Δεν υπάρχει δραστηριότητα',
],
'display_targets_preselected' => [
    'fi' => 'Infonäyttökohteet esivalittu',
    'sv' => 'Informationsskärmsmål förvalda',
    'en' => 'Display targets preselected',
    'it' => 'Destinazioni display preselezionate',
    'el' => 'Προεπιλεγμένοι στόχοι οθόνης',
],
'sent_to_supervisor' => [
    'fi' => 'Lähetetty työmaavastaavalle',
    'sv' => 'Skickat till platschef',
    'en' => 'Sent to site manager',
    'it' => 'Inviato al responsabile di cantiere',
    'el' => 'Εστάλη στον υπεύθυνο εργοταξίου',
],
'submission_comment' => [
    'fi' => 'Saateviesti',
    'sv' => 'Följebrev',
    'en' => 'Submission note',
    'it' => 'Nota di invio',
    'el' => 'Σημείωση υποβολής',
],
'updated' => [
    'fi' => 'Päivitetty',
    'sv' => 'Uppdaterad',
    'en' => 'Updated',
    'it' => 'Aggiornato',
    'el' => 'Ενημερώθηκε',
],
'log_image_changed' => [
    'fi' => 'Kuva muutettu',
    'sv' => 'Bild ändrad',
    'en' => 'Image changed',
    'it' => 'Immagine modificata',
    'el' => 'Η εικόνα άλλαξε',
],
'log_original_type_changed' => [
    'fi' => 'Alkuperäinen tyyppi muutettu',
    'sv' => 'Ursprunglig typ ändrad',
    'en' => 'Original type changed',
    'it' => 'Tipo originale modificato',
    'el' => 'Ο αρχικός τύπος άλλαξε',
],
'log_settings_updated' => [
    'fi' => 'Järjestelmäasetukset päivitetty',
    'sv' => 'Systeminställningar uppdaterade',
    'en' => 'System settings updated',
    'it' => 'Impostazioni di sistema aggiornate',
    'el' => 'Οι ρυθμίσεις συστήματος ενημερώθηκαν',
],
'log_original_flash_merged' => [
    'fi' => 'Alkuperäinen SafetyFlash "{title}" (ID {id}, tyyppi {type}, tila {state}) yhdistettiin tutkintatiedotteeseen. Yhdistäjä: {user}.',
    'sv' => 'Den ursprungliga SafetyFlashen "{title}" (ID {id}, typ {type}, status {state}) sammanfogades med utredningsrapporten. Sammanfogad av: {user}.',
    'en' => 'Original SafetyFlash "{title}" (ID {id}, type {type}, state {state}) was merged into the investigation report. Merged by: {user}.',
    'it' => 'Il SafetyFlash originale "{title}" (ID {id}, tipo {type}, stato {state}) è stato unito al rapporto di indagine. Unito da: {user}.',
    'el' => 'Το αρχικό SafetyFlash "{title}" (ID {id}, τύπος {type}, κατάσταση {state}) συνδέθηκε με την αναφορά έρευνας. Εκτελέστηκε από: {user}.',
],
'log_title_short_changed' => [
    'fi' => 'Lyhyt otsikko muutettu',
    'sv' => 'Kort rubrik ändrad',
    'en' => 'Short title changed',
    'it' => 'Titolo breve modificato',
    'el' => 'Ο σύντομος τίτλος άλλαξε',
],
'log_site_detail_changed' => [
    'fi' => 'Työmaan tarkennus muutettu',
    'sv' => 'Arbetsplatsdetalj ändrad',
    'en' => 'Worksite detail changed',
    'it' => 'Dettaglio cantiere modificato',
    'el' => 'Η λεπτομέρεια εργοταξίου άλλαξε',
],
'log_image_1_changed' => [
    'fi' => 'Kuva 1 vaihdettu',
    'sv' => 'Bild 1 ändrad',
    'en' => 'Image 1 changed',
    'it' => 'Immagine 1 modificata',
    'el' => 'Η εικόνα 1 άλλαξε',
],
'log_image_2_changed' => [
    'fi' => 'Kuva 2 vaihdettu',
    'sv' => 'Bild 2 ändrad',
    'en' => 'Image 2 changed',
    'it' => 'Immagine 2 modificata',
    'el' => 'Η εικόνα 2 άλλαξε',
],
'log_image_3_changed' => [
    'fi' => 'Kuva 3 vaihdettu',
    'sv' => 'Bild 3 ändrad',
    'en' => 'Image 3 changed',
    'it' => 'Immagine 3 modificata',
    'el' => 'Η εικόνα 3 άλλαξε',
],
'log_image_1_repositioned' => [
    'fi' => 'Kuva 1 asemoitu uudelleen',
    'sv' => 'Bild 1 omplacerad',
    'en' => 'Image 1 repositioned',
    'it' => 'Immagine 1 riposizionata',
    'el' => 'Η εικόνα 1 επανατοποθετήθηκε',
],
'log_image_2_repositioned' => [
    'fi' => 'Kuva 2 asemoitu uudelleen',
    'sv' => 'Bild 2 omplacerad',
    'en' => 'Image 2 repositioned',
    'it' => 'Immagine 2 riposizionata',
    'el' => 'Η εικόνα 2 επανατοποθετήθηκε',
],
'log_image_3_repositioned' => [
    'fi' => 'Kuva 3 asemoitu uudelleen',
    'sv' => 'Bild 3 omplacerad',
    'en' => 'Image 3 repositioned',
    'it' => 'Immagine 3 riposizionata',
    'el' => 'Η εικόνα 3 επανατοποθετήθηκε',
],
'log_image_caption_1_changed' => [
    'fi' => 'Kuvateksti 1 muutettu',
    'sv' => 'Bildtext 1 ändrad',
    'en' => 'Image caption 1 changed',
    'it' => 'Didascalia immagine 1 modificata',
    'el' => 'Η λεζάντα εικόνας 1 άλλαξε',
],
'log_image_caption_2_changed' => [
    'fi' => 'Kuvateksti 2 muutettu',
    'sv' => 'Bildtext 2 ändrad',
    'en' => 'Image caption 2 changed',
    'it' => 'Didascalia immagine 2 modificata',
    'el' => 'Η λεζάντα εικόνας 2 άλλαξε',
],
'log_image_caption_3_changed' => [
    'fi' => 'Kuvateksti 3 muutettu',
    'sv' => 'Bildtext 3 ändrad',
    'en' => 'Image caption 3 changed',
    'it' => 'Didascalia immagine 3 modificata',
    'el' => 'Η λεζάντα εικόνας 3 άλλαξε',
],
'log_annotations_changed' => [
    'fi' => 'Kuvan merkintöjä muokattu',
    'sv' => 'Bildmarkeringar ändrade',
    'en' => 'Image annotations changed',
    'it' => 'Annotazioni immagine modificate',
    'el' => 'Οι σημειώσεις εικόνας άλλαξαν',
],
'log_grid_layout_changed' => [
    'fi' => 'Asettelu muutettu',
    'sv' => 'Layout ändrad',
    'en' => 'Layout changed',
    'it' => 'Layout modificato',
    'el' => 'Η διάταξη άλλαξε',
],
'log_appearance_changed' => [
    'fi' => 'Ulkoasuasetukset muutettu',
    'sv' => 'Utseendeinställningar ändrade',
    'en' => 'Appearance settings changed',
    'it' => 'Impostazioni aspetto modificate',
    'el' => 'Οι ρυθμίσεις εμφάνισης άλλαξαν',
],
'log_sent_to_safety_team' => [
    'fi' => 'Lähetetty turvatiimille',
    'sv' => 'Skickad till säkerhetsteamet',
    'en' => 'Sent to safety team',
    'it' => 'Inviato al team di sicurezza',
    'el' => 'Στάλθηκε στην ομάδα ασφαλείας',
],
'log_role_supervisor' => [
    'fi' => 'Työmaavastaava',
    'sv' => 'Platschef',
    'en' => 'Site Manager',
    'it' => 'Responsabile di cantiere',
    'el' => 'Υπεύθυνος εργοταξίου',
],
'log_returned_for_corrections' => [
    'fi' => 'Palautettu korjattavaksi',
    'sv' => 'Returnerad för korrigering',
    'en' => 'Returned for corrections',
    'it' => 'Restituito per correzioni',
    'el' => 'Επιστράφηκε για διορθώσεις',
],
'log_sent_to_comms' => [
    'fi' => 'Lähetetty viestintään',
    'sv' => 'Skickad till kommunikation',
    'en' => 'Sent to communications',
    'it' => 'Inviato alle comunicazioni',
    'el' => 'Στάλθηκε στις επικοινωνίες',
],
'flash_deleted_success' => [
    'fi' => 'Tiedote poistettu onnistuneesti.',
    'sv' => 'Meddelandet har raderats.',
    'en' => 'Flash deleted successfully.',
    'it' => 'Flash eliminato con successo.',
    'el' => 'Το flash διαγράφηκε επιτυχώς.',
],
'log_bundle_language_created' => [
    'fi' => 'Kieliversio luotu (bundle)',
    'sv' => 'Språkversion skapad (bundle)',
    'en' => 'Language version created (bundle)',
    'it' => 'Versione linguistica creata (bundle)',
    'el' => 'Γλωσσική έκδοση δημιουργήθηκε (bundle)',
],
'log_display_targets_preselected' => [
    'fi' => 'Infonäyttökohteet esivalittu',
    'sv' => 'Informationsskärmsmål förvalda',
    'en' => 'Display targets preselected',
    'it' => 'Destinazioni display preselezionate',
    'el' => 'Προεπιλεγμένοι στόχοι οθόνης',
],
'settings_updated' => [
    'fi' => 'Asetukset päivitetty',
    'sv' => 'Inställningar uppdaterade',
    'en' => 'Settings updated',
    'it' => 'Impostazioni aggiornate',
    'el' => 'Οι ρυθμίσεις ενημερώθηκαν',
],
'flash_info_request' => [
    'fi' => 'Palautettu korjattavaksi',
    'sv' => 'Returnerad för korrigering',
    'en' => 'Returned for corrections',
    'it' => 'Restituito per correzioni',
    'el' => 'Επιστράφηκε για διορθώσεις',
],
'flash_to_comms' => [
    'fi' => 'Lähetetty viestintään',
    'sv' => 'Skickad till kommunikation',
    'en' => 'Sent to communications',
    'it' => 'Inviato alle comunicazioni',
    'el' => 'Στάλθηκε στις επικοινωνίες',
],
'flash_publish_direct' => [
    'fi' => 'Julkaistu suoraan',
    'sv' => 'Publicerad direkt',
    'en' => 'Published directly',
    'it' => 'Pubblicato direttamente',
    'el' => 'Δημοσιεύτηκε απευθείας',
],
'log_comment_label' => [
    'fi' => 'Kommentti',
    'sv' => 'Kommentar',
    'en' => 'Comment',
    'it' => 'Commento',
    'el' => 'Σχόλιο',
],
'log_return_reason_label' => [
    'fi' => 'Palautuksen syy',
    'sv' => 'Orsak till retur',
    'en' => 'Return reason',
    'it' => 'Motivo del reso',
    'el' => 'Λόγος επιστροφής',
],
'log_message_to_comms_label' => [
    'fi' => 'Viesti viestinnälle',
    'sv' => 'Meddelande till kommunikation',
    'en' => 'Message to communications',
    'it' => 'Messaggio alle comunicazioni',
    'el' => 'Μήνυμα στις επικοινωνίες',
],
'log_supervisor_message_label' => [
    'fi' => 'Työmaavastaavan viesti',
    'sv' => 'Platschefens meddelande',
    'en' => 'Supervisor message',
    'it' => 'Messaggio del supervisore',
    'el' => 'Μήνυμα επόπτη',
],
'log_info_requested' => [
    'fi' => 'Lisätietoja pyydetty',
    'sv' => 'Mer information begärd',
    'en' => 'Information requested',
    'it' => 'Informazioni richieste',
    'el' => 'Ζητήθηκαν πληροφορίες',
],
'log_sent_to_review' => [
    'fi' => 'Lähetetty tarkistettavaksi',
    'sv' => 'Skickad för granskning',
    'en' => 'Sent for review',
    'it' => 'Inviato per revisione',
    'el' => 'Στάλθηκε για αξιολόγηση',
],
'log_comment_added' => [
    'fi' => 'Kommentti lisätty',
    'sv' => 'Kommentar tillagd',
    'en' => 'Comment added',
    'it' => 'Commento aggiunto',
    'el' => 'Προστέθηκε σχόλιο',
],
'log_submission_comment' => [
    'fi' => 'Saateviesti',
    'sv' => 'Följebrev',
    'en' => 'Submission note',
    'it' => 'Nota di invio',
    'el' => 'Σημείωση υποβολής',
],
'log_updated' => [
    'fi' => 'Päivitetty',
    'sv' => 'Uppdaterad',
    'en' => 'Updated',
    'it' => 'Aggiornato',
    'el' => 'Ενημερώθηκε',
],
'audit_target_type' => [
    'fi' => 'Kohteen tyyppi',
    'sv' => 'Måltyp',
    'en' => 'Target type',
    'it' => 'Tipo di obiettivo',
    'el' => 'Τύπος στόχου',
],
'audit_target_id' => [
    'fi' => 'Kohteen ID',
    'sv' => 'Mål-ID',
    'en' => 'Target ID',
    'it' => 'ID obiettivo',
    'el' => 'ID στόχου',
],
'audit_request_uri' => [
    'fi' => 'Sivu (URI)',
    'sv' => 'Sida (URI)',
    'en' => 'Page (URI)',
    'it' => 'Pagina (URI)',
    'el' => 'Σελίδα (URI)',
],
'audit_request_method' => [
    'fi' => 'Pyyntö (Method)',
    'sv' => 'Begäran (Metod)',
    'en' => 'Request (Method)',
    'it' => 'Richiesta (Metodo)',
    'el' => 'Αίτημα (Μέθοδος)',
],
'audit_user_agent' => [
    'fi' => 'Selain/laite',
    'sv' => 'Webbläsare/enhet',
    'en' => 'Browser/device',
    'it' => 'Browser/dispositivo',
    'el' => 'Πρόγραμμα περιήγησης/συσκευή',
],
'audit_email' => [
    'fi' => 'Sähköposti',
    'sv' => 'E-post',
    'en' => 'Email',
    'it' => 'Email',
    'el' => 'Email',
],
'audit_reason' => [
    'fi' => 'Syy',
    'sv' => 'Orsak',
    'en' => 'Reason',
    'it' => 'Motivo',
    'el' => 'Λόγος',
],
'audit_attempted_email' => [
    'fi' => 'Yritetty sähköposti',
    'sv' => 'Försökt e-post',
    'en' => 'Attempted email',
    'it' => 'Email tentata',
    'el' => 'Δοκιμασμένο email',
],
'audit_locked_until' => [
    'fi' => 'Lukittu saakka',
    'sv' => 'Låst till',
    'en' => 'Locked until',
    'it' => 'Bloccato fino a',
    'el' => 'Κλειδωμένο μέχρι',
],
'audit_val_wrong_password' => [
    'fi' => 'Väärä salasana',
    'sv' => 'Fel lösenord',
    'en' => 'Wrong password',
    'it' => 'Password errata',
    'el' => 'Λάθος κωδικός',
],
'audit_val_user_not_found' => [
    'fi' => 'Käyttäjää ei löytynyt',
    'sv' => 'Användaren hittades inte',
    'en' => 'User not found',
    'it' => 'Utente non trovato',
    'el' => 'Ο χρήστης δεν βρέθηκε',
],
'audit_val_inactive' => [
    'fi' => 'Käyttäjätili ei ole aktiivinen',
    'sv' => 'Användarkontot är inaktivt',
    'en' => 'User account is inactive',
    'it' => 'L\'account utente è inattivo',
    'el' => 'Ο λογαριασμός χρήστη είναι ανενεργός',
],
'audit_val_csrf' => [
    'fi' => 'Istunto vanhentunut (CSRF)',
    'sv' => 'Sessionen har gått ut (CSRF)',
    'en' => 'Session expired (CSRF)',
    'it' => 'Sessione scaduta (CSRF)',
    'el' => 'Η συνεδρία έληξε (CSRF)',
],
'audit_val_rate_limit' => [
    'fi' => 'Liikaa yrityksiä (Rate limit)',
    'sv' => 'För många försök (Rate limit)',
    'en' => 'Too many attempts (Rate limit)',
    'it' => 'Troppi tentativi (Rate limit)',
    'el' => 'Πάρα πολλές προσπάθειες (Rate limit)',
],
'log_athena_exported' => [
    'fi' => 'Vei tutkintatiedotteen raportin Athenaan',
    'sv' => 'Exporterade utredningsrapporten till Athena',
    'en' => 'Exported the investigation report to Athena',
    'it' => 'Ha esportato il rapporto di indagine su Athena',
    'el' => 'Εξήγαγε την αναφορά έρευνας στο Athena',
],
'log_athena_marked_done' => [
    'fi' => 'Merkitsi tutkintatiedotteen viedyksi Athenaan',
    'sv' => 'Markerade utredningsrapporten som exporterad till Athena',
    'en' => 'Marked the investigation report as exported to Athena',
    'it' => 'Ha contrassegnato il rapporto di indagine come esportato su Athena',
    'el' => 'Σήμανε την αναφορά έρευνας ως εξαγμένη στο Athena',
],
];
