<?php
/**
 * Modal Dialogs and Confirmations - Modal windows, confirmation dialogs
 */
return [
'confirm_delete_title' => [
    'fi' => 'Vahvista poisto',
    'sv' => 'Bekräfta borttagning',
    'en' => 'Confirm deletion',
    'it' => 'Conferma eliminazione',
    'el' => 'Επιβεβαίωση διαγραφής',
],
'confirm_remove_image_title' => [
    'fi' => 'Poista kuva',
    'sv' => 'Ta bort bild',
    'en' => 'Delete image',
    'it' => 'Elimina immagine',
    'el' => 'Διαγραφή εικόνας',
],
'confirm_remove_image_text' => [
    'fi' => 'Haluatko poistaa tämän kuvan? Kuva ja sen säädöt poistetaan.',
    'sv' => 'Vill du ta bort den här bilden? Bilden och dess justeringar tas bort.',
    'en' => 'Do you want to remove this image? The image and its adjustments will be removed.',
    'it' => 'Vuoi rimuovere questa immagine? L\'immagine e le sue regolazioni verranno rimosse.',
    'el' => 'Θέλετε να αφαιρέσετε αυτή την εικόνα; Η εικόνα και οι ρυθμίσεις της θα αφαιρεθούν.',
],
'modal_edit_title' => [
    'fi' => 'Muokkaa tiedotetta',
    'sv' => 'Redigera meddelande',
    'en' => 'Edit flash',
    'it' => 'Modifica comunicazione',
    'el' => 'Επεξεργασία ανακοίνωσης',
],
'modal_edit_text' => [
    'fi' => 'Siirryt muokkaamaan tätä tiedotetta.',
    'sv' => 'Du går vidare till redigering av detta meddelande.',
    'en' => 'You will proceed to edit this flash.',
    'it' => 'Procederai alla modifica di questa comunicazione.',
    'el' => 'Θα μεταβείς στην επεξεργασία αυτής της ανακοίνωσης.',
],
'modal_comment_title' => [
    'fi' => 'Lisää kommentti',
    'sv' => 'Lägg till kommentar',
    'en' => 'Add comment',
    'it' => 'Aggiungi commento',
    'el' => 'Προσθήκη σχολίου',
],
'modal_comment_placeholder' => [
    'fi' => 'Kirjoita kommenttisi tähän',
    'sv' => 'Skriv din kommentar här',
    'en' => 'Write your comment here',
    'it' => 'Scrivi qui il tuo commento',
    'el' => 'Γράψτε εδώ το σχόλιό σας',
],
'modal_request_title' => [
    'fi' => 'Palauta korjattavaksi',
    'sv' => 'Skicka tillbaka för korrigering',
    'en' => 'Return for corrections',
    'it' => 'Rimanda per correzioni',
    'el' => 'Επιστροφή για διόρθωση',
],
'modal_request_placeholder' => [
    'fi' => 'Kerro tarkasti, mitä tulee korjata tai täydentää.',
    'sv' => 'Beskriv tydligt vad som ska korrigeras eller kompletteras.',
    'en' => 'Describe exactly what needs to be corrected or completed.',
    'it' => 'Descrivi esattamente cosa deve essere corretto o completato.',
    'el' => 'Περιγράψτε με ακρίβεια τι πρέπει να διορθωθεί ή να συμπληρωθεί.',
],
'modal_to_comms_title' => [
    'fi' => 'Lähetä viestintään',
    'sv' => 'Skicka till kommunikation',
    'en' => 'Send to communications',
    'it' => 'Invia alla comunicazione',
    'el' => 'Αποστολή στο τμήμα επικοινωνίας',
],
'modal_to_comms_placeholder' => [
    'fi' => 'Kuvaile, mitä viestinnän tulisi tehdä tämän tiedotteen kanssa',
    'sv' => 'Beskriv vad kommunikationen ska göra med detta meddelande',
    'en' => 'Describe what communications should do with this flash',
    'it' => 'Descrivi cosa dovrebbe fare la comunicazione con questa comunicazione',
    'el' => 'Περιγράψτε τι πρέπει να κάνει το τμήμα επικοινωνίας με αυτή την ανακοίνωση',
],
'comms_step1_languages' => [
    'fi' => 'Kieliversiot',
    'sv' => 'Språkversioner',
    'en' => 'Language versions',
    'it' => 'Versioni linguistiche',
    'el' => 'Γλωσσικές εκδόσεις',
],
'comms_step1_languages_help' => [
    'fi' => 'Valitse mitkä käännökset tehdään',
    'sv' => 'Välj vilka översättningar som ska göras',
    'en' => 'Select which translations to make',
    'it' => 'Seleziona quali traduzioni fare',
    'el' => 'Επιλέξτε ποιες μεταφράσεις να γίνουν',
],
'comms_step3_distribution' => [
    'fi' => 'Jakelu',
    'sv' => 'Distribution',
    'en' => 'Distribution',
    'it' => 'Distribuzione',
    'el' => 'Διανομή',
],
'comms_step3_distribution_help' => [
    'fi' => 'Valitse maat, joiden jakelulistoille SafetyFlash lähetetään julkaisun yhteydessä',
    'sv' => 'Välj länder vars distributionslistor SafetyFlash skickas till vid publicering',
    'en' => 'Select countries whose distribution lists SafetyFlash will be sent to upon publishing',
    'it' => 'Seleziona i paesi alle cui liste di distribuzione verrà inviato SafetyFlash alla pubblicazione',
    'el' => 'Επιλέξτε χώρες στις λίστες διανομής των οποίων θα σταλεί το SafetyFlash κατά τη δημοσίευση',
],
'comms_distribution_none_default' => [
    'fi' => 'Ei valintaa oletuksena – klikkaa lippua valitaksesi',
    'sv' => 'Inget val som standard – klicka på en flagga för att välja',
    'en' => 'No selection by default – click a flag to select',
    'it' => 'Nessuna selezione predefinita – clicca su una bandiera per selezionare',
    'el' => 'Καμία επιλογή από προεπιλογή – κάντε κλικ σε μια σημαία για να επιλέξετε',
],
'modal_publish_title' => [
    'fi' => 'Julkaise tiedote',
    'sv' => 'Publicera meddelande',
    'en' => 'Publish flash',
    'it' => 'Pubblica comunicazione',
    'el' => 'Δημοσίευση ανακοίνωσης',
],
'modal_publish_text' => [
    'fi' => 'Haluatko julkaista tämän tiedotteen?',
    'sv' => 'Vill du publicera detta meddelande på skärmarna?',
    'en' => 'Do you want to publish this flash to the screens?',
    'it' => 'Vuoi pubblicare questa comunicazione sugli schermi?',
    'el' => 'Θέλεις να δημοσιεύσεις αυτή την ανακοίνωση στις οθόνες;',
],
'modal_publish_direct_title' => [
    'fi' => 'Julkaise ilman viestinnän toimintoja',
    'sv' => 'Publicera utan kommunikationens funktioner',
    'en' => 'Publish without communications actions',
    'it' => 'Pubblica senza le funzioni della comunicazione',
    'el' => 'Δημοσίευση χωρίς λειτουργίες επικοινωνίας',
],
'modal_publish_direct_text' => [
    'fi' => 'Tätä toimintoa voidaan käyttää poikkeustilanteissa, joissa ensitiedote tai vaaratilannetiedote on jo aloitettu, mutta tutkinta valmistuu ennen tiedotteen julkaisua. Tällöin prosessia voidaan nopeuttaa ohittamalla viestinnän kielenhuoltovaihe, jotta tiedote saadaan tutkintatiedotteen pohjaksi. Tiedote julkaistaan tällöin vain SafetyFlash-sovelluksessa, eikä sitä lähetetä infonäytöille tai sähköpostitse.',
    
    'sv' => 'Denna funktion kan användas i undantagssituationer där ett första meddelande eller ett risklägesmeddelande redan har påbörjats, men utredningen blir klar innan meddelandet publiceras. Processen kan då påskyndas genom att kommunikationens språkgranskningssteg hoppas över, så att meddelandet kan fungera som underlag för ett undersökningsmeddelande. Meddelandet publiceras då endast i SafetyFlash-applikationen och skickas inte till informationsskärmar eller via e-post.',
    
    'en' => 'This function can be used in exceptional situations where a first release or a dangerous situation notice has already been started, but the investigation is completed before the notice is published. In such cases, the process can be accelerated by bypassing the communications language review step so that the notice can serve as the basis for an investigation report. The flash is published only in the SafetyFlash application and is not sent to info screens or via email.',
    
    'it' => 'Questa funzione può essere utilizzata in situazioni eccezionali in cui è già stato avviato un primo comunicato o un avviso di situazione pericolosa, ma l’indagine si conclude prima della pubblicazione. In questi casi il processo può essere accelerato saltando la fase di revisione linguistica della comunicazione, così che il comunicato possa fungere da base per un rapporto di indagine. Il comunicato viene pubblicato solo nell’applicazione SafetyFlash e non viene inviato agli schermi informativi né tramite e-mail.',
    
    'el' => 'Η λειτουργία αυτή μπορεί να χρησιμοποιηθεί σε εξαιρετικές περιπτώσεις όπου έχει ήδη ξεκινήσει ένα αρχικό δελτίο ή μια ειδοποίηση επικίνδυνης κατάστασης, αλλά η διερεύνηση ολοκληρώνεται πριν από τη δημοσίευση. Σε αυτή την περίπτωση η διαδικασία μπορεί να επιταχυνθεί παρακάμπτοντας το στάδιο γλωσσικής επιμέλειας της επικοινωνίας, ώστε το δελτίο να χρησιμοποιηθεί ως βάση για δελτίο διερεύνησης. Το δελτίο δημοσιεύεται μόνο στην εφαρμογή SafetyFlash και δεν αποστέλλεται στις οθόνες πληροφοριών ούτε μέσω ηλεκτρονικού ταχυδρομείου.',
],
'modal_publish_direct_label' => [
    'fi' => 'Perustelu',
    'sv' => 'Motivering',
    'en' => 'Reason',
    'it' => 'Motivazione',
    'el' => 'Αιτιολόγηση',
],
'modal_publish_direct_placeholder' => [
    'fi' => 'Kirjoita perustelu suoralle julkaisulle',
    'sv' => 'Skriv en motivering för direktpublicering',
    'en' => 'Write the reason for direct publishing',
    'it' => 'Scrivi la motivazione della pubblicazione diretta',
    'el' => 'Γράψτε την αιτιολόγηση για την άμεση δημοσίευση',
],
'modal_publish_direct_help' => [
    'fi' => 'Tämä viesti tallennetaan kommentteihin poikkeusratkaisun perusteluksi.',
    'sv' => 'Detta meddelande sparas i kommentarerna som motivering till undantagslösningen.',
    'en' => 'This message will be saved in the comments as the reason for the exception.',
    'it' => 'Questo messaggio verrà salvato nei commenti come motivazione della soluzione eccezionale.',
    'el' => 'Αυτό το μήνυμα θα αποθηκευτεί στα σχόλια ως αιτιολόγηση της κατ’ εξαίρεση λύσης.',
],
'modal_delete_title' => [
    'fi' => 'Poista tiedote',
    'sv' => 'Ta bort meddelande',
    'en' => 'Delete flash',
    'it' => 'Elimina comunicazione',
    'el' => 'Διαγραφή ανακοίνωσης',
],
'modal_delete_text' => [
    'fi' => 'Haluatko varmasti poistaa tämän tiedotteen?',
    'sv' => 'Vill du verkligen ta bort detta meddelande?',
    'en' => 'Are you sure you want to delete this flash?',
    'it' => 'Vuoi davvero eliminare questa comunicazione?',
    'el' => 'Είσαι βέβαιος ότι θέλεις να διαγράψεις αυτή την ανακοίνωση;',
],
'modal_translation_title' => [
    'fi' => 'Luo kieliversio',
    'en' => 'Create language version',
    'sv' => 'Skapa språkversion',
    'it' => 'Crea versione linguistica',
    'el' => 'Δημιουργία γλωσσικής έκδοσης',
],
'confirm_submit_title' => [
    'fi' => 'Vahvista lähetys',
    'sv' => 'Bekräfta sändning',
    'en' => 'Confirm submission',
    'it' => 'Conferma invio',
    'el' => 'Επιβεβαίωση υποβολής',
],
'confirm_submit_text' => [
    'fi' => 'Oletko varma, että haluat lähettää tiedotteen tarkistettavaksi?',
    'sv' => 'Är du säker på att du vill skicka meddelandet för granskning?',
    'en' => 'Are you sure you want to send this flash for review?',
    'it' => 'Sei sicuro di voler inviare questa comunicazione per la revisione?',
    'el' => 'Είστε βέβαιοι ότι θέλετε να στείλετε αυτή την ανακοίνωση για έλεγχο;',
],
'confirm_submit_help' => [
    'fi' => 'Tiedotetta voi vielä muokata ennen julkaisua.',
    'sv' => 'Meddelandet kan fortfarande redigeras innan publicering.',
    'en' => 'The flash can still be edited before publishing.',
    'it' => 'La comunicazione può ancora essere modificata prima della pubblicazione.',
    'el' => 'Η ανακοίνωση μπορεί ακόμα να επεξεργαστεί πριν τη δημοσίευση.',
],
'modal_send_supervisor_title' => [
    'fi' => 'Lähetä työmaavastaavalle',
    'sv' => 'Skicka till platschef',
    'en' => 'Send to Site Manager',
    'it' => 'Invia al responsabile di cantiere',
    'el' => 'Αποστολή στον υπεύθυνο εργοταξίου',
],
'modal_send_supervisor_confirm' => [
    'fi' => 'Haluatko varmasti lähettää SafetyFlashin työmaavastaavalle?',
    'sv' => 'Vill du verkligen skicka SafetyFlash till platschefen?',
    'en' => 'Are you sure you want to send the SafetyFlash to the site manager?',
    'it' => 'Sei sicuro di voler inviare il SafetyFlash al responsabile di cantiere?',
    'el' => 'Είστε σίγουροι ότι θέλετε να στείλετε το SafetyFlash στον υπεύθυνο εργοταξίου;',
],
'modal_send_safety_title' => [
    'fi' => 'Lähetä turvatiimille',
    'sv' => 'Skicka till säkerhetsteamet',
    'en' => 'Send to Safety Team',
    'it' => 'Invia al team di sicurezza',
    'el' => 'Αποστολή στην ομάδα ασφαλείας',
],
'modal_send_safety_placeholder' => [
    'fi' => 'Kirjoita viestisi tähän...',
    'sv' => 'Skriv ditt meddelande här...',
    'en' => 'Write your message here...',
    'it' => 'Scrivi il tuo messaggio qui...',
    'el' => 'Γράψτε το μήνυμά σας εδώ...',
],
'modal_comment_edit_title' => [
    'fi' => 'Muokkaa kommenttia',
    'sv' => 'Redigera kommentar',
    'en' => 'Edit comment',
    'it' => 'Modifica commento',
    'el' => 'Επεξεργασία σχολίου',
],
'modal_comment_reply_title' => [
    'fi' => 'Vastaa kommenttiin',
    'sv' => 'Svara på kommentar',
    'en' => 'Reply to comment',
    'it' => 'Rispondi al commento',
    'el' => 'Απάντηση στο σχόλιο',
],

// Step 2: Xibo screens
'comms_step2_screens' => [
    'fi' => 'Xibo-näytöt',
    'sv' => 'Xibo-skärmar',
    'en' => 'Xibo screens',
    'it' => 'Schermi Xibo',
    'el' => 'Οθόνες Xibo',
],
'comms_step2_screens_help' => [
    'fi' => 'Valitse työmaanäytöt jossa SafetyFlash esitetään',
    'sv' => 'Välj arbetsplatsskärmar där SafetyFlash visas',
    'en' => 'Select worksite screens where SafetyFlash will be displayed',
    'it' => 'Seleziona gli schermi del cantiere dove verrà visualizzato SafetyFlash',
    'el' => 'Επιλέξτε οθόνες εργοταξίου όπου θα εμφανίζεται το SafetyFlash',
],
'comms_screens_all' => [
    'fi' => 'Kaikki näytöt',
    'sv' => 'Alla skärmar',
    'en' => 'All screens',
    'it' => 'Tutti gli schermi',
    'el' => 'Όλες οι οθόνες',
],
'comms_screens_all_hint' => [
    'fi' => 'Lähetä kaikkiin Xibo-näyttöihin',
    'sv' => 'Skicka till alla Xibo-skärmar',
    'en' => 'Send to all Xibo screens',
    'it' => 'Invia a tutti gli schermi Xibo',
    'el' => 'Αποστολή σε όλες τις οθόνες Xibo',
],
'comms_screens_select' => [
    'fi' => 'Valitse',
    'sv' => 'Välj',
    'en' => 'Select',
    'it' => 'Seleziona',
    'el' => 'Επιλέξτε',
],
'comms_screens_selected' => [
    'fi' => 'Valitut työmaat',
    'sv' => 'Valda arbetsplatser',
    'en' => 'Selected worksites',
    'it' => 'Cantieri selezionati',
    'el' => 'Επιλεγμένα εργοτάξια',
],
'comms_screens_selected_hint' => [
    'fi' => 'Valitse työmaat erikseen',
    'sv' => 'Välj arbetsplatser separat',
    'en' => 'Select worksites separately',
    'it' => 'Seleziona i cantieri separatamente',
    'el' => 'Επιλέξτε εργοτάξια ξεχωριστά',
],
'comms_select_worksites' => [
    'fi' => 'Valitse työmaat',
    'sv' => 'Välj arbetsplatser',
    'en' => 'Select worksites',
    'it' => 'Seleziona cantieri',
    'el' => 'Επιλέξτε εργοτάξια',
],
'comms_worksites_placeholder' => [
    'fi' => 'Työmaat ladataan...',
    'sv' => 'Laddar arbetsplatser...',
    'en' => 'Loading worksites...',
    'it' => 'Caricamento cantieri...',
    'el' => 'Φόρτωση εργοταξίων...',
],
'comms_select_countries' => [
    'fi' => 'Valitse maat',
    'sv' => 'Välj länder',
    'en' => 'Select countries',
    'it' => 'Seleziona paesi',
    'el' => 'Επιλέξτε χώρες',
],
'comms_or_search_worksites' => [
    'fi' => 'tai valitse yksittäiset työmaat',
    'sv' => 'eller välj enskilda arbetsplatser',
    'en' => 'or select individual worksites',
    'it' => 'o seleziona singoli cantieri',
    'el' => 'ή επιλέξτε μεμονωμένα εργοτάξια',
],
'comms_search_hint' => [
    'fi' => 'Työmaat näkyvät vasta kun haet',
    'sv' => 'Arbetsplatser visas först när du söker',
    'en' => 'Worksites appear only when you search',
    'it' => 'I cantieri appaiono solo quando cerchi',
    'el' => 'Τα εργοτάξια εμφανίζονται μόνο όταν αναζητάτε',
],
'comms_your_selection' => [
    'fi' => 'Valintasi',
    'sv' => 'Ditt val',
    'en' => 'Your selection',
    'it' => 'La tua selezione',
    'el' => 'Η επιλογή σας',
],
'country_finland' => [
    'fi' => 'Suomi',
    'sv' => 'Finland',
    'en' => 'Finland',
    'it' => 'Finlandia',
    'el' => 'Φινλανδία',
],
'country_italy' => [
    'fi' => 'Italia',
    'sv' => 'Italien',
    'en' => 'Italy',
    'it' => 'Italia',
    'el' => 'Ιταλία',
],
'country_greece' => [
    'fi' => 'Kreikka',
    'sv' => 'Grekland',
    'en' => 'Greece',
    'it' => 'Grecia',
    'el' => 'Ελλάδα',
],
'comms_all_countries' => [
    'fi' => 'Kaikki maat',
    'sv' => 'Alla länder',
    'en' => 'All countries',
    'it' => 'Tutti i paesi',
    'el' => 'Όλες οι χώρες',
],
'comms_worksites_count' => [
    'fi' => 'työmaata',
    'sv' => 'arbetsplatser',
    'en' => 'worksites',
    'it' => 'cantieri',
    'el' => 'εργοτάξια',
],
'comms_worksite_count_single' => [
    'fi' => 'työmaa',
    'sv' => 'arbetsplats',
    'en' => 'worksite',
    'it' => 'cantiere',
    'el' => 'εργοτάξιο',
],

// Step 3: Distribution (simplified)
'comms_step3_wider_distribution' => [
    'fi' => 'Laajempi jakelu',
    'sv' => 'Bredare distribution',
    'en' => 'Wider distribution',
    'it' => 'Distribuzione più ampia',
    'el' => 'Ευρύτερη διανομή',
],
'comms_step3_wider_distribution_help' => [
    'fi' => 'Lähetä SafetyFlash myös laajemmalle jakelulistalle',
    'sv' => 'Skicka SafetyFlash även till bredare distributionslista',
    'en' => 'Send SafetyFlash also to wider distribution list',
    'it' => 'Invia SafetyFlash anche alla lista di distribuzione più ampia',
    'el' => 'Στείλτε το SafetyFlash και στην ευρύτερη λίστα διανομής',
],
'comms_wider_distribution_yes' => [
    'fi' => 'Kyllä, lähetä laajempaan jakeluun',
    'sv' => 'Ja, skicka till bredare distribution',
    'en' => 'Yes, send to wider distribution',
    'it' => 'Sì, invia alla distribuzione più ampia',
    'el' => 'Ναι, αποστολή σε ευρύτερη διανομή',
],
'comms_wider_distribution_no' => [
    'fi' => 'Ei, vain valitut näytöt',
    'sv' => 'Nej, endast valda skärmar',
    'en' => 'No, selected screens only',
    'it' => 'No, solo schermi selezionati',
    'el' => 'Όχι, μόνο επιλεγμένες οθόνες',
],
'comms_wider_distribution_label' => [
    'fi' => 'Lähetä laajempaan jakeluun',
    'sv' => 'Skicka till bredare distribution',
    'en' => 'Send to wider distribution',
    'it' => 'Invia alla distribuzione più ampia',
    'el' => 'Αποστολή σε ευρύτερη διανομή',
],
'comms_search_worksites' => [
    'fi' => 'Hae työmaata...',
    'sv' => 'Sök arbetsplats...',
    'en' => 'Search worksite...',
    'it' => 'Cerca cantiere...',
    'el' => 'Αναζήτηση εργοταξίου...',
],
'comms_no_worksites' => [
    'fi' => 'Ei työmaita saatavilla',
    'sv' => 'Inga arbetsplatser tillgängliga',
    'en' => 'No worksites available',
    'it' => 'Nessun cantiere disponibile',
    'el' => 'Δεν υπάρχουν διαθέσιμα εργοτάξια',
],

// Step 4: Summary
'comms_step4_summary' => [
    'fi' => 'Yhteenveto',
    'sv' => 'Sammanfattning',
    'en' => 'Summary',
    'it' => 'Riepilogo',
    'el' => 'Περίληψη',
],
'comms_summary_title' => [
    'fi' => 'Yhteenveto',
    'sv' => 'Sammanfattning',
    'en' => 'Summary',
    'it' => 'Riepilogo',
    'el' => 'Περίληψη',
],
'comms_summary_languages' => [
    'fi' => 'Kieliversiot',
    'sv' => 'Språkversioner',
    'en' => 'Language versions',
    'it' => 'Versioni linguistiche',
    'el' => 'Γλωσσικές εκδόσεις',
],
'comms_summary_screens' => [
    'fi' => 'Xibo-näytöt',
    'sv' => 'Xibo-skärmar',
    'en' => 'Xibo screens',
    'it' => 'Schermi Xibo',
    'el' => 'Οθόνες Xibo',
],
'comms_summary_distribution' => [
    'fi' => 'Laajempi jakelu',
    'sv' => 'Bredare distribution',
    'en' => 'Wider distribution',
    'it' => 'Distribuzione più ampia',
    'el' => 'Ευρύτερη διανομή',
],
'comms_summary_none' => [
    'fi' => 'Ei valintoja',
    'sv' => 'Inga val',
    'en' => 'No selections',
    'it' => 'Nessuna selezione',
    'el' => 'Δεν υπάρχουν επιλογές',
],
'comms_summary_worksites' => [
    'fi' => 'työmaata',
    'sv' => 'arbetsplatser',
    'en' => 'worksites',
    'it' => 'cantieri',
    'el' => 'εργοτάξια',
],
'comms_summary_no_distribution' => [
    'fi' => 'Ei laajempaa jakelua',
    'sv' => 'Ingen bredare distribution',
    'en' => 'No wider distribution',
    'it' => 'Nessuna distribuzione più ampia',
    'el' => 'Χωρίς ευρύτερη διανομή',
],
'comms_summary_yes' => [
    'fi' => 'Kyllä',
    'sv' => 'Ja',
    'en' => 'Yes',
    'it' => 'Sì',
    'el' => 'Ναι',
],
'comms_summary_no' => [
    'fi' => 'Ei',
    'sv' => 'Nej',
    'en' => 'No',
    'it' => 'No',
    'el' => 'Όχι',
],
'comms_error_no_languages' => [
    'fi' => 'Valitse vähintään yksi kieliversio',
    'sv' => 'Välj minst en språkversion',
    'en' => 'Select at least one language version',
    'it' => 'Seleziona almeno una versione linguistica',
    'el' => 'Επιλέξτε τουλάχιστον μία γλωσσική έκδοση',
],
'modal_to_comms_label' => [
    'fi' => 'Viesti viestintätiimille (valinnainen)',
    'sv' => 'Meddelande till kommunikationsteamet (valfritt)',
    'en' => 'Message to communications team (optional)',
    'it' => 'Messaggio al team di comunicazione (opzionale)',
    'el' => 'Μήνυμα στην ομάδα επικοινωνίας (προαιρετικό)',
],
'btn_send_comms' => [
    'fi' => 'Lähetä viestintään',
    'sv' => 'Skicka till kommunikation',
    'en' => 'Send to communications',
    'it' => 'Invia alla comunicazione',
    'el' => 'Αποστολή στην επικοινωνία',
],
'btn_select_all' => [
    'fi' => 'Valitse kaikki',
    'sv' => 'Välj alla',
    'en' => 'Select all',
    'it' => 'Seleziona tutto',
    'el' => 'Επιλογή όλων',
],
'btn_clear' => [
    'fi' => 'Tyhjennä',
    'sv' => 'Rensa',
    'en' => 'Clear',
    'it' => 'Cancella',
    'el' => 'Εκκαθάριση',
],
'selected' => [
    'fi' => 'valittu',
    'sv' => 'valda',
    'en' => 'selected',
    'it' => 'selezionati',
    'el' => 'επιλεγμένα',
],
'comms_select_targets' => [
    'fi' => 'Valitse kohteet',
    'sv' => 'Välj mål',
    'en' => 'Select targets',
    'it' => 'Seleziona destinazioni',
    'el' => 'Επιλέξτε στόχους',
],
'btn_clear_selections' => [
    'fi' => 'Tyhjennä valinnat',
    'sv' => 'Rensa val',
    'en' => 'Clear selections',
    'it' => 'Cancella selezioni',
    'el' => 'Εκκαθάριση επιλογών',
],
'clear_all_selections' => [
    'fi' => 'Tyhjennä kaikki',
    'sv' => 'Rensa alla',
    'en' => 'Clear all',
    'it' => 'Cancella tutto',
    'el' => 'Εκκαθάριση όλων',
],
'modal_translation_confirm_title' => [
    'fi' => 'Luo kieliversio',
    'sv' => 'Skapa språkversion',
    'en' => 'Create language version',
    'it' => 'Crea versione linguistica',
    'el' => 'Δημιουργία γλωσσικής έκδοσης',
],
'modal_translation_confirm_message' => [
    'fi' => 'Haluatko luoda kieliversion tälle SafetyFlashille?',
    'sv' => 'Vill du skapa en språkversion för denna SafetyFlash?',
    'en' => 'Do you want to create a language version for this SafetyFlash?',
    'it' => 'Vuoi creare una versione linguistica per questo SafetyFlash?',
    'el' => 'Θέλετε να δημιουργήσετε μια γλωσσική έκδοση για αυτό το SafetyFlash;',
],
'confirm_source_flash_label' => [
    'fi' => 'Lähdetiedote',
    'sv' => 'Källmeddelande',
    'en' => 'Source flash',
    'it' => 'Comunicazione di origine',
    'el' => 'Πηγαία ανακοίνωση',
],
'confirm_target_language' => [
    'fi' => 'Kohdekieli',
    'sv' => 'Målspråk',
    'en' => 'Target language',
    'it' => 'Lingua di destinazione',
    'el' => 'Γλώσσα στόχος',
],
'confirm_site_label' => [
    'fi' => 'Työmaa',
    'sv' => 'Arbetsplats',
    'en' => 'Worksite',
    'it' => 'Cantiere',
    'el' => 'Εργοτάξιο',
],
'confirm_type_label' => [
    'fi' => 'Tyyppi',
    'sv' => 'Typ',
    'en' => 'Type',
    'it' => 'Tipo',
    'el' => 'Τύπος',
],
'type_red' => [
    'fi' => 'Ensitiedote',
    'sv' => 'Första underrättelse',
    'en' => 'First notification',
    'it' => 'Prima notifica',
    'el' => 'Πρώτη ειδοποίηση',
],
'type_yellow' => [
    'fi' => 'Vaaratilanne',
    'sv' => 'Farlig situation',
    'en' => 'Dangerous situation',
    'it' => 'Situazione pericolosa',
    'el' => 'Επικίνδυνη κατάσταση',
],
'type_green' => [
    'fi' => 'Tutkintatiedote',
    'sv' => 'Utredningsrapport',
    'en' => 'Investigation report',
    'it' => 'Rapporto di indagine',
    'el' => 'Έκθεση έρευνας',
],
'confirm_creating_translation' => [
    'fi' => 'Luodaan...',
    'sv' => 'Skapar...',
    'en' => 'Creating...',
    'it' => 'Creazione in corso...',
    'el' => 'Δημιουργία...',
],
'form_close_confirm_title' => [
    'fi' => 'Poistu lomakkeelta?',
    'sv' => 'Lämna formuläret?',
    'en' => 'Leave form?',
    'it' => 'Uscire dal modulo?',
    'el' => 'Έξοδος από τη φόρμα;',
],
'form_close_confirm_text' => [
    'fi' => 'Haluatko varmasti poistua? Tallentamattomat muutokset menetetään.',
    'sv' => 'Är du säker på att du vill lämna? Osparade ändringar går förlorade.',
    'en' => 'Are you sure you want to leave? Unsaved changes will be lost.',
    'it' => 'Sei sicuro di voler uscire? Le modifiche non salvate andranno perse.',
    'el' => 'Είστε σίγουροι ότι θέλετε να φύγετε; Οι μη αποθηκευμένες αλλαγές θα χαθούν.',
],
'form_close_confirm_leave' => [
    'fi' => 'Poistu',
    'sv' => 'Lämna',
    'en' => 'Leave',
    'it' => 'Esci',
    'el' => 'Έξοδος',
],
'modal_merge_flash_title' => [
    'fi' => 'Yhdistä SafetyFlashiin',
    'sv' => 'Sammanfoga med SafetyFlash',
    'en' => 'Merge into SafetyFlash',
    'it' => 'Unisci a SafetyFlash',
    'el' => 'Σύνδεση στο SafetyFlash',
],
'modal_merge_flash_text' => [
    'fi' => 'Valitse olemassa oleva Ensitiedote tai Vaaratilanne. Valittu tiedote liitetään tämän tutkintatiedotteen alkuperäiseksi tiedotteeksi. Toiminto lokitetaan tutkintatiedotteen tapahtumiin.',
    'sv' => 'Välj ett befintligt Förstameddelande eller en Farlig situation. Det valda meddelandet kopplas som ursprungligt meddelande till denna utredningsrapport. Åtgärden loggas i utredningsrapportens händelser.',
    'en' => 'Select an existing First Release or Dangerous Situation. The selected flash will be linked as the original flash for this investigation report. The action will be logged in the investigation report activity log.',
    'it' => 'Seleziona un First Release o una Dangerous Situation esistente. Il SafetyFlash selezionato verrà collegato come comunicazione originale a questo rapporto di indagine. L’azione verrà registrata nel log eventi del rapporto di indagine.',
    'el' => 'Επιλέξτε ένα υπάρχον First Release ή Dangerous Situation. Το επιλεγμένο SafetyFlash θα συνδεθεί ως αρχική ανακοίνωση σε αυτήν την αναφορά έρευνας. Η ενέργεια θα καταγραφεί στο ιστορικό γεγονότων της αναφοράς έρευνας.',
],
'modal_merge_flash_search_placeholder' => [
    'fi' => 'Hae otsikolla, yhteenvedolla tai työmaalla',
    'sv' => 'Sök med rubrik, sammanfattning eller arbetsplats',
    'en' => 'Search by title, summary or worksite',
    'it' => 'Cerca per titolo, riepilogo o cantiere',
    'el' => 'Αναζήτηση με τίτλο, σύνοψη ή εργοτάξιο',
],
'modal_merge_flash_loading' => [
    'fi' => 'Ladataan tiedotteita...',
    'sv' => 'Laddar meddelanden...',
    'en' => 'Loading flashes...',
    'it' => 'Caricamento SafetyFlash...',
    'el' => 'Φόρτωση SafetyFlash...',
],
'modal_merge_flash_empty' => [
    'fi' => 'Sopivia tiedotteita ei löytynyt.',
    'sv' => 'Inga lämpliga meddelanden hittades.',
    'en' => 'No matching flashes found.',
    'it' => 'Nessun SafetyFlash corrispondente trovato.',
    'el' => 'Δεν βρέθηκαν κατάλληλα SafetyFlash.',
],
'modal_merge_flash_confirm_text' => [
    'fi' => 'Valittu tiedote liitetään tämän tutkintatiedotteen alkuperäiseksi tiedotteeksi. Alkuperäisen tiedotteen kommentit, lokit ja mahdolliset muut liitännäiset siirretään tutkintatiedotteen jatkumoon. Toiminto lokitetaan.',
    'sv' => 'Det valda meddelandet kopplas som ursprungligt meddelande till denna utredningsrapport. Kommentarer, loggar och relaterad data från originalmeddelandet flyttas till utredningsrapportens kedja. Åtgärden loggas.',
    'en' => 'The selected flash will be linked as the original flash for this investigation report. Comments, logs and related data from the original flash will be moved into the investigation report chain. The action will be logged.',
    'it' => 'Il SafetyFlash selezionato verrà collegato come comunicazione originale di questo rapporto di indagine. Commenti, log e dati correlati verranno trasferiti nella catena del rapporto di indagine. L’azione verrà registrata.',
    'el' => 'Το επιλεγμένο SafetyFlash θα συνδεθεί ως αρχική ανακοίνωση αυτής της αναφοράς έρευνας. Σχόλια, καταγραφές και σχετικά δεδομένα θα μεταφερθούν στην αλυσίδα της αναφοράς έρευνας. Η ενέργεια θα καταγραφεί.',
],
'modal_merge_flash_success' => [
    'fi' => 'SafetyFlash yhdistetty tutkintatiedotteeseen',
    'sv' => 'SafetyFlash sammanfogad med utredningsrapporten',
    'en' => 'SafetyFlash merged into investigation report',
    'it' => 'SafetyFlash unito al rapporto di indagine',
    'el' => 'Το SafetyFlash συνδέθηκε με την αναφορά έρευνας',
],
'modal_merge_flash_title' => [
    'fi' => 'Yhdistä SafetyFlashiin',
    'sv' => 'Sammanfoga med SafetyFlash',
    'en' => 'Merge into SafetyFlash',
    'it' => 'Unisci a SafetyFlash',
    'el' => 'Σύνδεση στο SafetyFlash',
],
'modal_merge_flash_text' => [
    'fi' => 'Valitse olemassa oleva Ensitiedote tai Vaaratilanne. Valittu tiedote liitetään tämän tutkintatiedotteen alkuperäiseksi tiedotteeksi. Toiminto lokitetaan tutkintatiedotteen tapahtumiin.',
    'sv' => 'Välj ett befintligt Förstameddelande eller en Farlig situation. Det valda meddelandet kopplas som ursprungligt meddelande till denna utredningsrapport. Åtgärden loggas i utredningsrapportens händelser.',
    'en' => 'Select an existing First Release or Dangerous Situation. The selected flash will be linked as the original flash for this investigation report. The action will be logged in the investigation report activity log.',
    'it' => 'Seleziona un First Release o una Dangerous Situation esistente. Il SafetyFlash selezionato verrà collegato come comunicazione originale a questo rapporto di indagine. L’azione verrà registrata nel log eventi del rapporto di indagine.',
    'el' => 'Επιλέξτε ένα υπάρχον First Release ή Dangerous Situation. Το επιλεγμένο SafetyFlash θα συνδεθεί ως αρχική ανακοίνωση σε αυτήν την αναφορά έρευνας. Η ενέργεια θα καταγραφεί στο ιστορικό γεγονότων της αναφοράς έρευνας.',
],
'modal_merge_flash_search_placeholder' => [
    'fi' => 'Hae otsikolla, yhteenvedolla tai työmaalla',
    'sv' => 'Sök med rubrik, sammanfattning eller arbetsplats',
    'en' => 'Search by title, summary or worksite',
    'it' => 'Cerca per titolo, riepilogo o cantiere',
    'el' => 'Αναζήτηση με τίτλο, σύνοψη ή εργοτάξιο',
],
'modal_merge_flash_loading' => [
    'fi' => 'Ladataan tiedotteita...',
    'sv' => 'Laddar meddelanden...',
    'en' => 'Loading flashes...',
    'it' => 'Caricamento SafetyFlash...',
    'el' => 'Φόρτωση SafetyFlash...',
],
'modal_merge_flash_empty' => [
    'fi' => 'Sopivia tiedotteita ei löytynyt.',
    'sv' => 'Inga lämpliga meddelanden hittades.',
    'en' => 'No matching flashes found.',
    'it' => 'Nessun SafetyFlash corrispondente trovato.',
    'el' => 'Δεν βρέθηκαν κατάλληλα SafetyFlash.',
],
'modal_merge_flash_confirm_text' => [
    'fi' => 'Valittu tiedote liitetään tämän tutkintatiedotteen alkuperäiseksi tiedotteeksi. Alkuperäisen tiedotteen kommentit, lokit ja mahdolliset muut liitännäiset siirretään tutkintatiedotteen jatkumoon. Toiminto lokitetaan.',
    'sv' => 'Det valda meddelandet kopplas som ursprungligt meddelande till denna utredningsrapport. Kommentarer, loggar och relaterad data från originalmeddelandet flyttas till utredningsrapportens kedja. Åtgärden loggas.',
    'en' => 'The selected flash will be linked as the original flash for this investigation report. Comments, logs and related data from the original flash will be moved into the investigation report chain. The action will be logged.',
    'it' => 'Il SafetyFlash selezionato verrà collegato come comunicazione originale di questo rapporto di indagine. Commenti, log e dati correlati verranno trasferiti nella catena del rapporto di indagine. L’azione verrà registrata.',
    'el' => 'Το επιλεγμένο SafetyFlash θα συνδεθεί ως αρχική ανακοίνωση αυτής της αναφοράς έρευνας. Σχόλια, καταγραφές και σχετικά δεδομένα θα μεταφερθούν στην αλυσίδα της αναφοράς έρευνας. Η ενέργεια θα καταγραφεί.',
],
'modal_merge_flash_success' => [
    'fi' => 'SafetyFlash yhdistetty tutkintatiedotteeseen',
    'sv' => 'SafetyFlash sammanfogad med utredningsrapporten',
    'en' => 'SafetyFlash merged into investigation report',
    'it' => 'SafetyFlash unito al rapporto di indagine',
    'el' => 'Το SafetyFlash συνδέθηκε με την αναφορά έρευνας',
],
'modal_merge_flash_occurred_label' => [
    'fi' => 'Ajankohta',
    'sv' => 'Tidpunkt',
    'en' => 'Occurred',
    'it' => 'Data e ora',
    'el' => 'Χρόνος συμβάντος',
],
'modal_merge_flash_creator_label' => [
    'fi' => 'Tekijä',
    'sv' => 'Skapad av',
    'en' => 'Created by',
    'it' => 'Creato da',
    'el' => 'Δημιουργήθηκε από',
],
'modal_athena_reminder_title' => [
    'fi' => 'Muista viedä raportti Athenaan',
    'sv' => 'Kom ihåg att exportera rapporten till Athena',
    'en' => 'Remember to export the report to Athena',
    'it' => 'Ricordati di esportare il rapporto su Athena',
    'el' => 'Θυμήσου να εξαγάγεις την αναφορά στο Athena',
],
'modal_athena_reminder_text' => [
    'fi' => 'Tiedote on julkaistu. Ladathan PDF-raportin ja viet sen Athenaan (sisäinen intratiedostopankki), jotta muut käyttäjät tietävät tiedotteen löytyvän sieltä.',
    'sv' => 'Meddelandet har publicerats. Ladda ned PDF-rapporten och exportera den till Athena (internt intranätarkiv) så att övriga användare vet att meddelandet finns där.',
    'en' => 'The flash has been published. Please download the PDF report and upload it to Athena (internal intranet file bank) so other users know it is available there.',
    'it' => 'Il comunicato è stato pubblicato. Scarica il report PDF e caricalo su Athena (archivio intranet interno) in modo che gli altri utenti sappiano che è disponibile lì.',
    'el' => 'Η ανακοίνωση έχει δημοσιευτεί. Κατεβάστε την αναφορά PDF και μεταφορτώστε την στο Athena (εσωτερική τράπεζα αρχείων intranet) ώστε οι άλλοι χρήστες να γνωρίζουν ότι είναι διαθέσιμη εκεί.',
],
'modal_athena_reminder_already_exported_text' => [
    'fi' => 'Jos olet jo vienyt tämän tiedotteen Athenaan, voit merkitä sen tehdyksi alla olevalla painikkeella.',
    'sv' => 'Om du redan har exporterat detta meddelande till Athena kan du markera det som gjort med knappen nedan.',
    'en' => 'If you have already exported this flash to Athena, you can mark it as done with the button below.',
    'it' => 'Se hai già esportato questo comunicato su Athena, puoi contrassegnarlo come fatto con il pulsante qui sotto.',
    'el' => 'Εάν έχεις ήδη εξαγάγει αυτή την ανακοίνωση στο Athena, μπορείς να την επισημάνεις ως ολοκληρωμένη με το παρακάτω κουμπί.',
],
'badge_athena_modal_title' => [
    'fi' => 'Muista viedä raportti Athenaan',
    'sv' => 'Kom ihåg att exportera rapporten till Athena',
    'en' => 'Remember to export the report to Athena',
    'it' => 'Ricordati di esportare il rapporto su Athena',
    'el' => 'Θυμήσου να εξαγάγεις την αναφορά στο Athena',
],
'badge_athena_modal_description' => [
    'fi' => 'Tiedote on julkaistu. Ladathan PDF-raportin ja viet sen Athenaan (sisäinen intratiedostopankki), jotta muut käyttäjät tietävät tiedotteen löytyvän sieltä.',
    'sv' => 'Meddelandet har publicerats. Ladda ned PDF-rapporten och exportera den till Athena (internt intranätarkiv) så att övriga användare vet att meddelandet finns där.',
    'en' => 'The announcement has been published. Please download the PDF report and upload it to Athena (internal intranet file bank) so other users know it is available there.',
    'it' => 'Il comunicato è stato pubblicato. Scarica il report PDF e caricalo su Athena (archivio intranet interno) in modo che gli altri utenti sappiano che è disponibile lì.',
    'el' => 'Η ανακοίνωση έχει δημοσιευτεί. Κατεβάστε την αναφορά PDF και μεταφορτώστε την στο Athena (εσωτερική τράπεζα αρχείων intranet) ώστε οι άλλοι χρήστες να γνωρίζουν ότι είναι διαθέσιμη εκεί.',
],
];