<?php
/**
 * Settings Page - User settings, worksites, profiles, roles
 */
return [
'worksite_created' => [
    'fi' => 'Työmaa luotu',
    'sv' => 'Arbetsplats skapad',
    'en' => 'Worksite created',
    'it' => 'Cantiere creato',
    'el' => 'Εργοτάξιο δημιουργήθηκε',
],
'worksite_updated' => [
    'fi' => 'Työmaa päivitetty',
    'sv' => 'Arbetsplats uppdaterad',
    'en' => 'Worksite updated',
    'it' => 'Cantiere aggiornato',
    'el' => 'Εργοτάξιο ενημερώθηκε',
],
'worksite_deleted' => [
    'fi' => 'Työmaa poistettu',
    'sv' => 'Arbetsplats borttagen',
    'en' => 'Worksite deleted',
    'it' => 'Cantiere eliminato',
    'el' => 'Εργοτάξιο διαγράφηκε',
],
'settings_heading' => [
    'fi' => 'Asetukset',
    'sv' => 'Inställningar',
    'en' => 'Settings',
    'it' => 'Impostazioni',
    'el' => 'Ρυθμίσεις',
],
'settings_worksites_col_flashes' => [
    'fi' => 'Ajolistat',
    'sv' => 'Spellistor',
    'en' => 'Playlists',
    'it' => 'Playlist',
    'el' => 'Λίστες αναπαραγωγής',
],
'settings_tab_users' => [
    'fi' => 'Käyttäjät',
    'sv' => 'Användare',
    'en' => 'Users',
    'it' => 'Utenti',
    'el' => 'Χρήστες',
],
'settings_worksites_heading' => [
    'fi' => 'Työmaiden hallinta',
    'sv' => 'Hantering av arbetsplatser',
    'en' => 'Worksite management',
    'it' => 'Gestione cantieri',
    'el' => 'Διαχείριση εργοταξίων',
],
'settings_worksites_col_name' => [
    'fi' => 'Nimi',
    'sv' => 'Namn',
    'en' => 'Name',
    'it' => 'Nome',
    'el' => 'Όνομα',
],
'settings_worksites_col_active' => [
    'fi' => 'Aktiivinen',
    'sv' => 'Aktiv',
    'en' => 'Active',
    'it' => 'Attivo',
    'el' => 'Ενεργό',
],
'settings_worksites_col_show_in_lists' => [
    'fi' => 'Työmaalistoissa',
    'sv' => 'Arbetsplatslistor',
    'en' => 'Worksite lists',
    'it' => 'Liste cantieri',
    'el' => 'Λίστες εργοταξίων',
],
'settings_worksites_col_show_in_displays' => [
    'fi' => 'Infonäyttövalinnoissa',
    'sv' => 'Skärmval',
    'en' => 'Display targets',
    'it' => 'Selezioni schermi',
    'el' => 'Επιλογές οθονών',
],
'settings_worksites_col_actions' => [
    'fi' => 'Toiminnot',
    'sv' => 'Åtgärder',
    'en' => 'Actions',
    'it' => 'Azioni',
    'el' => 'Ενέργειες',
],
'settings_worksites_action_disable' => [
    'fi' => 'Passivoi',
    'sv' => 'Inaktivera',
    'en' => 'Deactivate',
    'it' => 'Disattiva',
    'el' => 'Απενεργοποίηση',
],
'settings_worksites_action_enable' => [
    'fi' => 'Aktivoi',
    'sv' => 'Aktivera',
    'en' => 'Activate',
    'it' => 'Attiva',
    'el' => 'Ενεργοποίηση',
],
'settings_worksites_empty' => [
    'fi' => 'Ei työmaita. Lisää ensimmäinen työmaa yllä olevalla lomakkeella.',
    'sv' => 'Inga arbetsplatser. Lägg till den första arbetsplatsen med formuläret ovan.',
    'en' => 'No worksites. Add the first worksite using the form above.',
    'it' => 'Nessun cantiere. Aggiungi il primo cantiere con il modulo sopra.',
    'el' => 'Δεν υπάρχουν εργοτάξια. Προσθέστε το πρώτο εργοτάξιο από την παραπάνω φόρμα.',
],
'settings_worksites_site_type' => [
    'fi' => 'Työmaan tyyppi',
    'sv' => 'Arbetsplatstyp',
    'en' => 'Site type',
    'it' => 'Tipo di cantiere',
    'el' => 'Τύπος εργοταξίου',
],
'site_type_unspecified' => [
    'fi' => 'Määrittämätön',
    'sv' => 'Ospecificerad',
    'en' => 'Unspecified',
    'it' => 'Non specificato',
    'el' => 'Μη καθορισμένο',
],
'site_type_tunnel' => [
    'fi' => 'Tunnelityömaa',
    'sv' => 'Tunnelarbetsplats',
    'en' => 'Tunnel worksite',
    'it' => 'Cantiere tunnel',
    'el' => 'Εργοτάξιο τούνελ',
],
'site_type_opencast' => [
    'fi' => 'Avolouhos',
    'sv' => 'Dagbrott',
    'en' => 'Opencast',
    'it' => 'Cava a cielo aperto',
    'el' => 'Ανοικτό ορυχείο',
],
'site_type_other' => [
    'fi' => 'Muut toimipisteet',
    'sv' => 'Övriga arbetsplatser',
    'en' => 'Other sites',
    'it' => 'Altri siti',
    'el' => 'Άλλοι χώροι',
],
'settings_worksites_action_edit' => [
    'fi' => 'Muokkaa',
    'sv' => 'Redigera',
    'en' => 'Edit',
    'it' => 'Modifica',
    'el' => 'Επεξεργασία',
],
'settings_worksites_show_in_lists_label' => [
    'fi' => 'Näytä työmaalistoissa',
    'sv' => 'Visa i arbetsplatslistor',
    'en' => 'Show in worksite lists',
    'it' => 'Mostra nelle liste cantieri',
    'el' => 'Εμφάνιση στις λίστες εργοταξίων',
],
'settings_worksites_show_in_displays_label' => [
    'fi' => 'Näytä infonäyttövalinnoissa',
    'sv' => 'Visa i skärmval',
    'en' => 'Show in display targets',
    'it' => 'Mostra nelle selezioni schermo',
    'el' => 'Εμφάνιση στις επιλογές οθονών',
],
'settings_worksites_action_toggle_lists' => [
    'fi' => 'Työmaalistat',
    'sv' => 'Arbetsplatslistor',
    'en' => 'Worksite lists',
    'it' => 'Liste cantieri',
    'el' => 'Λίστες εργοταξίων',
],
'settings_worksites_action_toggle_displays' => [
    'fi' => 'Infonäytöt',
    'sv' => 'Skärmval',
    'en' => 'Display targets',
    'it' => 'Selezioni schermo',
    'el' => 'Επιλογές οθονών',
],
'settings_worksites_edit_title' => [
    'fi' => 'Muokkaa työmaata',
    'sv' => 'Redigera arbetsplats',
    'en' => 'Edit worksite',
    'it' => 'Modifica cantiere',
    'el' => 'Επεξεργασία εργοταξίου',
],
'users_heading' => [
    'fi' => 'Käyttäjien hallinta',
    'sv' => 'Användarhantering',
    'en' => 'User management',
    'it' => 'Gestione utenti',
    'el' => 'Διαχείριση χρηστών',
],
'users_add_button' => [
    'fi' => 'Lisää käyttäjä',
    'sv' => 'Lägg till användare',
    'en' => 'Add user',
    'it' => 'Aggiungi utente',
    'el' => 'Προσθήκη χρήστη',
],
'users_col_name' => [
    'fi' => 'Nimi',
    'sv' => 'Namn',
    'en' => 'Name',
    'it' => 'Nome',
    'el' => 'Όνομα',
],
'users_col_email' => [
    'fi' => 'Sähköposti',
    'sv' => 'E-post',
    'en' => 'Email',
    'it' => 'Email',
    'el' => 'Email',
],
'users_col_role' => [
    'fi' => 'Rooli',
    'sv' => 'Roll',
    'en' => 'Role',
    'it' => 'Ruolo',
    'el' => 'Ρόλος',
],
'users_col_home_worksite' => [
    'fi' => 'Kotityömaa',
    'sv' => 'Hemmearbetsplats',
    'en' => 'Home worksite',
    'it' => 'Cantiere principale',
    'el' => 'Κύριο εργοτάξιο',
],
'users_col_created' => [
    'fi' => 'Luotu',
    'sv' => 'Skapad',
    'en' => 'Created',
    'it' => 'Creato',
    'el' => 'Δημιουργήθηκε',
],
'users_col_last_login' => [
    'fi' => 'Viimeksi kirjautunut',
    'sv' => 'Senaste inloggning',
    'en' => 'Last login',
    'it' => 'Ultimo accesso',
    'el' => 'Τελευταία σύνδεση',
],
'users_last_login_never' => [
    'fi' => 'Ei koskaan',
    'sv' => 'Aldrig',
    'en' => 'Never',
    'it' => 'Mai',
    'el' => 'Ποτέ',
],
'users_col_actions' => [
    'fi' => 'Toiminnot',
    'sv' => 'Åtgärder',
    'en' => 'Actions',
    'it' => 'Azioni',
    'el' => 'Ενέργειες',
],
'users_home_worksite_none' => [
    'fi' => 'Ei määritelty',
    'sv' => 'Ej angiven',
    'en' => 'Not set',
    'it' => 'Non impostato',
    'el' => 'Δεν έχει οριστεί',
],
'users_action_edit' => [
    'fi' => 'Muokkaa',
    'sv' => 'Redigera',
    'en' => 'Edit',
    'it' => 'Modifica',
    'el' => 'Επεξεργασία',
],
'users_action_reset_pass' => [
    'fi' => 'Nollaa salasana',
    'sv' => 'Återställ lösenord',
    'en' => 'Reset password',
    'it' => 'Reimposta password',
    'el' => 'Επαναφορά κωδικού',
],
'users_action_delete' => [
    'fi' => 'Poista',
    'sv' => 'Ta bort',
    'en' => 'Delete',
    'it' => 'Elimina',
    'el' => 'Διαγραφή',
],
'users_modal_add_title' => [
    'fi' => 'Lisää uusi käyttäjä',
    'sv' => 'Lägg till ny användare',
    'en' => 'Add new user',
    'it' => 'Aggiungi nuovo utente',
    'el' => 'Προσθήκη νέου χρήστη',
],
'users_label_first_name' => [
    'fi' => 'Etunimi',
    'sv' => 'Förnamn',
    'en' => 'First name',
    'it' => 'Nome',
    'el' => 'Όνομα',
],
'users_label_last_name' => [
    'fi' => 'Sukunimi',
    'sv' => 'Efternamn',
    'en' => 'Last name',
    'it' => 'Cognome',
    'el' => 'Επώνυμο',
],
'users_label_email' => [
    'fi' => 'Sähköposti',
    'sv' => 'E-post',
    'en' => 'Email',
    'it' => 'Email',
    'el' => 'Email',
],
'users_label_role' => [
    'fi' => 'Rooli',
    'sv' => 'Roll',
    'en' => 'Role',
    'it' => 'Ruolo',
    'el' => 'Ρόλος',
],
'users_label_home_worksite' => [
    'fi' => 'Kotityömaa',
    'sv' => 'Hemmearbetsplats',
    'en' => 'Home worksite',
    'it' => 'Cantiere principale',
    'el' => 'Κύριο εργοτάξιο',
],
'users_label_password_new' => [
    'fi' => 'Uusi salasana (jätä tyhjäksi, jos ei muuteta)',
    'sv' => 'Nytt lösenord (lämna tomt om ingen ändring)',
    'en' => 'New password (leave blank if no change)',
    'it' => 'Nuova password (lasciare vuoto se non si modifica)',
    'el' => 'Νέος κωδικός (αφήστε κενό αν δεν αλλάξει)',
],
'users_delete_title' => [
    'fi' => 'Vahvista poisto',
    'sv' => 'Bekräfta borttagning',
    'en' => 'Confirm deletion',
    'it' => 'Conferma eliminazione',
    'el' => 'Επιβεβαίωση διαγραφής',
],
'users_delete_text' => [
    'fi' => 'Haluatko varmasti poistaa käyttäjän',
    'sv' => 'Är du säker på att du vill ta bort användaren',
    'en' => 'Are you sure you want to delete user',
    'it' => 'Sei sicuro di voler eliminare l\'utente',
    'el' => 'Είστε βέβαιοι ότι θέλετε να διαγράψετε τον χρήστη',
],
'users_reset_title' => [
    'fi' => 'Salasanan nollaus',
    'sv' => 'Återställning av lösenord',
    'en' => 'Password reset',
    'it' => 'Reimpostazione password',
    'el' => 'Επαναφορά κωδικού',
],
'users_reset_text_prefix' => [
    'fi' => 'Uusi salasana lähetetään osoitteeseen',
    'sv' => 'Nytt lösenord skickas till',
    'en' => 'A new password will be sent to',
    'it' => 'Una nuova password verrà inviata a',
    'el' => 'Ένας νέος κωδικός θα σταλεί στη διεύθυνση',
],
'users_reset_text_suffix' => [
    'fi' => '. Haluatko jatkaa?',
    'sv' => '. Vill du fortsätta?',
    'en' => '. Do you want to continue?',
    'it' => '. Vuoi continuare?',
    'el' => '. Θέλετε να συνεχίσετε;',
],
'worksite_inactive' => [
    'fi' => 'passivoitu',
    'sv' => 'inaktiv',
    'en' => 'inactive',
    'it' => 'inattivo',
    'el' => 'ανενεργό',
],
'users_filter_role' => [
    'fi' => 'Rooli',
    'sv' => 'Roll',
    'en' => 'Role',
    'it' => 'Ruolo',
    'el' => 'Ρόλος',
],
'users_filter_worksite' => [
    'fi' => 'Kotityömaa',
    'sv' => 'Hemarbetsplats',
    'en' => 'Home worksite',
    'it' => 'Cantiere',
    'el' => 'Εργοτάξιο',
],
'users_filter_search' => [
    'fi' => 'Hae nimellä tai sähköpostilla',
    'sv' => 'Sök med namn eller e-post',
    'en' => 'Search by name or email',
    'it' => 'Cerca per nome o email',
    'el' => 'Αναζήτηση με όνομα ή email',
],
'users_filter_login_status' => [
    'fi' => 'Kirjautumistila',
    'sv' => 'Inloggningsstatus',
    'en' => 'Login status',
    'it' => 'Stato accesso',
    'el' => 'Κατάσταση σύνδεσης',
],
'users_filter_login_all' => [
    'fi' => 'Kaikki',
    'sv' => 'Alla',
    'en' => 'All',
    'it' => 'Tutti',
    'el' => 'Όλα',
],
'users_filter_login_active' => [
    'fi' => 'Kirjautuneet',
    'sv' => 'Inloggade',
    'en' => 'Logged in',
    'it' => 'Connessi',
    'el' => 'Συνδεδεμένοι',
],
'users_filter_login_never' => [
    'fi' => 'Ei koskaan',
    'sv' => 'Aldrig',
    'en' => 'Never',
    'it' => 'Mai',
    'el' => 'Ποτέ',
],
'users_filter_clear' => [
    'fi' => 'Tyhjennä',
    'sv' => 'Rensa',
    'en' => 'Clear',
    'it' => 'Cancella',
    'el' => 'Εκκαθάριση',
],
'users_filter_toggle' => [
    'fi' => 'Suodattimet',
    'sv' => 'Filter',
    'en' => 'Filters',
    'it' => 'Filtri',
    'el' => 'Φίλτρα',
],
'users_auto_password_info' => [
    'fi' => 'Salasana generoidaan automaattisesti ja lähetetään käyttäjän sähköpostiin.',
    'sv' => 'Lösenordet genereras automatiskt och skickas till användarens e-post.',
    'en' => 'Password will be generated automatically and sent to the user\'s email.',
    'it' => 'La password verrà generata automaticamente e inviata all\'email dell\'utente.',
    'el' => 'Ο κωδικός πρόσβασης θα δημιουργηθεί αυτόματα και θα σταλεί στο email του χρήστη.',
],
'lang_selection_help' => [
    'fi' => 'Valitse kieli, jolla Safetyflash luodaan.  Käännökset tehdään myöhemmin.',
    'sv' => 'Välj språket för Safetyflash.  Översättningar görs senare.',
    'en' => 'Choose the language for this Safetyflash.  Translations will be done later.',
    'it' => 'Scegli la lingua per questo Safetyflash. Le traduzioni verranno fatte in seguito.',
    'el' => 'Επιλέξτε τη γλώσσα για αυτό το Safetyflash. Οι μεταφράσεις θα γίνουν αργότερα.',
],
'worksite_select_placeholder' => [
    'fi' => 'Valitse työmaa.. .',
    'sv' => 'Välj arbetsplats...',
    'en' => 'Select worksite...',
    'it' => 'Seleziona cantiere...',
    'el' => 'Επιλέξτε εργοτάξιο...',
],
'profile_heading' => [
    'fi' => 'Oma profiili',
    'sv' => 'Min profil',
    'en' => 'My Profile',
    'it' => 'Il mio profilo',
    'el' => 'Το προφίλ μου',
],
'profile_personal_info' => [
    'fi' => 'Henkilötiedot',
    'sv' => 'Personuppgifter',
    'en' => 'Personal Information',
    'it' => 'Informazioni personali',
    'el' => 'Προσωπικά στοιχεία',
],
'profile_role_readonly' => [
    'fi' => 'Roolia ei voi muuttaa itse. Ota yhteyttä ylläpitäjään.',
    'sv' => 'Rollen kan inte ändras själv. Kontakta administratören.',
    'en' => 'Role cannot be changed. Contact administrator.',
    'it' => 'Il ruolo non può essere modificato. Contatta l’amministratore.',
    'el' => 'Ο ρόλος δεν μπορεί να αλλάξει. Επικοινωνήστε με τον διαχειριστή.',
],
'profile_worksite_heading' => [
    'fi' => 'Kotityömaa',
    'sv' => 'Hemarbetsplats',
    'en' => 'Home Worksite',
    'it' => 'Cantiere principale',
    'el' => 'Κύριο εργοτάξιο',
],
'profile_worksite_help' => [
    'fi' => 'Kotityömaa suodattaa listan automaattisesti kun avaat sen.',
    'sv' => 'Hemarbetsplats filtrerar listan automatiskt när du öppnar den.',
    'en' => 'Home worksite automatically filters the list when you open it.',
    'it' => 'Il cantiere principale filtra automaticamente la lista all’apertura.',
    'el' => 'Το κύριο εργοτάξιο φιλτράρει αυτόματα τη λίστα όταν την ανοίγετε.',
],
'profile_password_heading' => [
    'fi' => 'Vaihda salasana',
    'sv' => 'Byt lösenord',
    'en' => 'Change Password',
    'it' => 'Cambia password',
    'el' => 'Αλλαγή κωδικού',
],
'profile_current_password' => [
    'fi' => 'Nykyinen salasana',
    'sv' => 'Nuvarande lösenord',
    'en' => 'Current Password',
    'it' => 'Password attuale',
    'el' => 'Τρέχων κωδικός',
],
'profile_new_password' => [
    'fi' => 'Uusi salasana',
    'sv' => 'Nytt lösenord',
    'en' => 'New Password',
    'it' => 'Nuova password',
    'el' => 'Νέος κωδικός',
],
'profile_confirm_password' => [
    'fi' => 'Vahvista uusi salasana',
    'sv' => 'Bekräfta nytt lösenord',
    'en' => 'Confirm New Password',
    'it' => 'Conferma la nuova password',
    'el' => 'Επιβεβαίωση νέου κωδικού',
],
'profile_change_password' => [
    'fi' => 'Vaihda salasana',
    'sv' => 'Byt lösenord',
    'en' => 'Change Password',
    'it' => 'Cambia password',
    'el' => 'Αλλαγή κωδικού',
],
'profile_passwords_mismatch' => [
    'fi' => 'Salasanat eivät täsmää',
    'sv' => 'Lösenorden matchar inte',
    'en' => 'Passwords do not match',
    'it' => 'Le password non coincidono',
    'el' => 'Οι κωδικοί δεν ταιριάζουν',
],
'settings_tab_worksites' => [
    'fi' => 'Työmaat',
    'sv' => 'Arbetsplatser',
    'en' => 'Worksites',
    'it' => 'Cantieri',
    'el' => 'Εργοτάξια',
],
'settings_tab_audit_log' => [
    'fi' => 'Tapahtumaloki',
    'sv' => 'Aktivitetslogg',
    'en' => 'Activity Log',
    'it' => 'Registro attività',
    'el' => 'Καταγραφή δραστηριοτήτων',
],
'users_js_add_user' => [
    'fi' => 'Lisää käyttäjä',
    'sv' => 'Lägg till användare',
    'en' => 'Add user',
    'it' => 'Aggiungi utente',
    'el' => 'Προσθήκη χρήστη',
],
'users_js_edit_user' => [
    'fi' => 'Muokkaa käyttäjää',
    'sv' => 'Redigera användare',
    'en' => 'Edit user',
    'it' => 'Modifica utente',
    'el' => 'Επεξεργασία χρήστη',
],
'users_js_error_network' => [
    'fi' => 'Verkkovirhe.',
    'sv' => 'Nätverksfel.',
    'en' => 'Network error.',
    'it' => 'Errore di rete.',
    'el' => 'Σφάλμα δικτύου.',
],
'users_js_error_delete' => [
    'fi' => 'Virhe poistossa',
    'sv' => 'Fel vid borttagning',
    'en' => 'Delete error',
    'it' => 'Errore di eliminazione',
    'el' => 'Σφάλμα διαγραφής',
],
'users_js_error_save' => [
    'fi' => 'Virhe tallennuksessa',
    'sv' => 'Fel vid sparande',
    'en' => 'Save error',
    'it' => 'Errore di salvataggio',
    'el' => 'Σφάλμα αποθήκευσης',
],
'users_js_error_reset' => [
    'fi' => 'Virhe salasanan resetoinnissa',
    'sv' => 'Fel vid återställning av lösenord',
    'en' => 'Password reset error',
    'it' => 'Errore di reset della password',
    'el' => 'Σφάλμα επαναφοράς κωδικού',
],
'users_js_new_password_prefix' => [
    'fi' => 'Uusi salasana: ',
    'sv' => 'Nytt lösenord: ',
    'en' => 'New password: ',
    'it' => 'Nuova password: ',
    'el' => 'Νέος κωδικός: ',
],
'settings_tab_image_library' => [
    'fi' => 'Kuvapankki',
    'sv' => 'Bildbank',
    'en' => 'Image Library',
    'it' => 'Libreria immagini',
    'el' => 'Βιβλιοθήκη εικόνων',
],
'settings_image_library_heading' => [
    'fi' => 'Kuvapankin hallinta',
    'sv' => 'Hantera bildbank',
    'en' => 'Image Library Management',
    'it' => 'Gestione libreria immagini',
    'el' => 'Διαχείριση βιβλιοθήκης εικόνων',
],
'settings_image_library_help' => [
    'fi' => 'Lisää kuvia, joita käyttäjät voivat valita tiedotteisiin. Esimerkiksi hahmokuvia loukkaantumiskohtien merkintään.',
    'sv' => 'Lägg till bilder som användare kan välja för meddelanden. Till exempel kroppsbilder för att markera skadeområden.',
    'en' => 'Add images that users can select for bulletins. For example, body figures for marking injury locations.',
    'it' => 'Aggiungi immagini che gli utenti possono scegliere per i bollettini. Ad esempio figure del corpo per indicare i punti di infortunio.',
    'el' => 'Προσθέστε εικόνες που μπορούν να επιλέξουν οι χρήστες για τα δελτία. Π.χ. φιγούρες σώματος για σήμανση τραυματισμών.',
],
'password_reset' => [
    'fi' => 'Salasana nollattu',
    'en' => 'Password reset',
    'sv' => 'Lösenord återställt',
    'it' => 'Password reimpostata',
    'el' => 'Επαναφορά κωδικού',
],
'profile_update' => [
    'fi' => 'Profiili päivitetty',
    'en' => 'Profile updated',
    'sv' => 'Profil uppdaterad',
    'it' => 'Profilo aggiornato',
    'el' => 'Προφίλ ενημερώθηκε',
],
'password_change' => [
    'fi' => 'Salasana vaihdettu',
    'en' => 'Password changed',
    'sv' => 'Lösenord ändrat',
    'it' => 'Password modificata',
    'el' => 'Ο κωδικός άλλαξε',
],
'worksite_create' => [
    'fi' => 'Työmaa luotu',
    'en' => 'Worksite created',
    'sv' => 'Arbetsplats skapad',
    'it' => 'Cantiere creato',
    'el' => 'Εργοτάξιο δημιουργήθηκε',
],
'worksite_update' => [
    'fi' => 'Työmaa päivitetty',
    'en' => 'Worksite updated',
    'sv' => 'Arbetsplats uppdaterad',
    'it' => 'Cantiere aggiornato',
    'el' => 'Εργοτάξιο ενημερώθηκε',
],
'worksite_delete' => [
    'fi' => 'Työmaa poistettu',
    'en' => 'Worksite deleted',
    'sv' => 'Arbetsplats borttagen',
    'it' => 'Cantiere eliminato',
    'el' => 'Εργοτάξιο διαγράφηκε',
],
'settings_update' => [
    'fi' => 'Asetukset päivitetty',
    'en' => 'Settings updated',
    'sv' => 'Inställningar uppdaterade',
    'it' => 'Impostazioni aggiornate',
    'el' => 'Ρυθμίσεις ενημερώθηκαν',
],
'worksite_added' => [
    'fi' => 'Työmaa lisätty.',
    'sv' => 'Arbetsplats tillagd.',
    'en' => 'Worksite added.',
    'it' => 'Cantiere aggiunto.',
    'el' => 'Το εργοτάξιο προστέθηκε.',
],
'worksite_enabled' => [
    'fi' => 'Työmaa aktivoitu.',
    'sv' => 'Arbetsplats aktiverad.',
    'en' => 'Worksite activated.',
    'it' => 'Cantiere attivato.',
    'el' => 'Το εργοτάξιο ενεργοποιήθηκε.',
],
'worksite_disabled' => [
    'fi' => 'Työmaa passivoitu.',
    'sv' => 'Arbetsplats inaktiverad.',
    'en' => 'Worksite deactivated.',
    'it' => 'Cantiere disattivato.',
    'el' => 'Το εργοτάξιο απενεργοποιήθηκε.',
],
'role_comms' => [
    'fi' => 'Viestintä',
    'sv' => 'Kommunikation',
    'en' => 'Communications',
    'it' => 'Comunicazione',
    'el' => 'Επικοινωνία',
],
'role_safety' => [
    'fi' => 'Turvatiimi',
    'sv' => 'Säkerhetsteam',
    'en' => 'Safety team',
    'it' => 'Team sicurezza',
    'el' => 'Ομάδα ασφαλείας',
],
'role_admin' => [
    'fi' => 'Admin',
    'sv' => 'Admin',
    'en' => 'Admin',
    'it' => 'Admin',
    'el' => 'Διαχειριστής',
],
'role_user' => [
    'fi' => 'Käyttäjä',
    'sv' => 'Användare',
    'en' => 'User',
    'it' => 'Utente',
    'el' => 'Χρήστης',
],
'role_safety_team' => [
    'fi' => 'Turvatiimi',
    'sv' => 'Säkerhetsteam',
    'en' => 'Safety team',
    'it' => 'Team sicurezza',
    'el' => 'Ομάδα ασφαλείας',
],
'role_distribution_fi' => [
    'fi' => 'Safetyflash jakelu (Suomi)',
    'sv' => 'SafetyFlash-distribution (Finland)',
    'en' => 'SafetyFlash distribution (Finland)',
    'it' => 'Distribuzione SafetyFlash (Finlandia)',
    'el' => 'Διανομή SafetyFlash (Φινλανδία)',
],
'role_distribution_sv' => [
    'fi' => 'Safetyflash jakelu (Ruotsi)',
    'sv' => 'SafetyFlash-distribution (Sverige)',
    'en' => 'SafetyFlash distribution (Sweden)',
    'it' => 'Distribuzione SafetyFlash (Svezia)',
    'el' => 'Διανομή SafetyFlash (Σουηδία)',
],
'role_distribution_en' => [
    'fi' => 'Safetyflash jakelu (Englanti)',
    'sv' => 'SafetyFlash-distribution (Engelska)',
    'en' => 'SafetyFlash distribution (English)',
    'it' => 'Distribuzione SafetyFlash (Inglese)',
    'el' => 'Διανομή SafetyFlash (Αγγλικά)',
],
'role_distribution_it' => [
    'fi' => 'Safetyflash jakelu (Italia)',
    'sv' => 'SafetyFlash-distribution (Italien)',
    'en' => 'SafetyFlash distribution (Italy)',
    'it' => 'Distribuzione SafetyFlash (Italia)',
    'el' => 'Διανομή SafetyFlash (Ιταλία)',
],
'role_distribution_el' => [
    'fi' => 'Safetyflash jakelu (Kreikka)',
    'sv' => 'SafetyFlash-distribution (Grekland)',
    'en' => 'SafetyFlash distribution (Greece)',
    'it' => 'Distribuzione SafetyFlash (Grecia)',
    'el' => 'Διανομή SafetyFlash (Ελλάδα)',
],
'country_name_fi' => [
    'fi' => 'Suomi',
    'sv' => 'Finland',
    'en' => 'Finland',
    'it' => 'Finlandia',
    'el' => 'Φινλανδία',
],
'country_name_sv' => [
    'fi' => 'Ruotsi',
    'sv' => 'Sverige',
    'en' => 'Sweden',
    'it' => 'Svezia',
    'el' => 'Σουηδία',
],
'country_name_en' => [
    'fi' => 'Englanti',
    'sv' => 'Engelska',
    'en' => 'English',
    'it' => 'Inglese',
    'el' => 'Αγγλικά',
],
'country_name_it' => [
    'fi' => 'Italia',
    'sv' => 'Italien',
    'en' => 'Italy',
    'it' => 'Italia',
    'el' => 'Ιταλία',
],
'country_name_el' => [
    'fi' => 'Kreikka',
    'sv' => 'Grekland',
    'en' => 'Greece',
    'it' => 'Grecia',
    'el' => 'Ελλάδα',
],
'country_finland' => [
    'fi' => 'Suomi',
    'sv' => 'Finland',
    'en' => 'Finland',
    'it' => 'Finlandia',
    'el' => 'Φινλανδία',
],
'country_sweden' => [
    'fi' => 'Ruotsi',
    'sv' => 'Sverige',
    'en' => 'Sweden',
    'it' => 'Svezia',
    'el' => 'Σουηδία',
],
'country_uk' => [
    'fi' => 'Iso-Britannia',
    'sv' => 'Storbritannien',
    'en' => 'United Kingdom',
    'it' => 'Regno Unito',
    'el' => 'Ηνωμένο Βασίλειο',
],
'country_italy' => [
    'fi' => 'Italia',
    'sv' => 'Italien',
    'en' => 'Italy',
    'it' => 'Italia',
    'el' => 'Ιταλία',
],
'country_greece' => [
    'fi' => 'Kreikka',
    'sv' => 'Grekland',
    'en' => 'Greece',
    'it' => 'Grecia',
    'el' => 'Ελλάδα',
],
'lang_name_fi' => [
    'fi' => 'Suomi',
    'sv' => 'Finska',
    'en' => 'Finnish',
    'it' => 'Finlandese',
    'el' => 'Φινλανδικά',
],
'lang_name_sv' => [
    'fi' => 'Ruotsi',
    'sv' => 'Svenska',
    'en' => 'Swedish',
    'it' => 'Svedese',
    'el' => 'Σουηδικά',
],
'lang_name_en' => [
    'fi' => 'Englanti',
    'sv' => 'Engelska',
    'en' => 'English',
    'it' => 'Inglese',
    'el' => 'Αγγλικά',
],
'lang_name_it' => [
    'fi' => 'Italia',
    'sv' => 'Italienska',
    'en' => 'Italian',
    'it' => 'Italiano',
    'el' => 'Ιταλικά',
],
'lang_name_el' => [
    'fi' => 'Kreikka',
    'sv' => 'Grekiska',
    'en' => 'Greek',
    'it' => 'Greco',
    'el' => 'Ελληνικά',
],
'session_expiring_title' => [
    'fi' => 'Istuntosi on vanhenemassa',
    'sv' => 'Din session håller på att löpa ut',
    'en' => 'Your session is expiring',
    'it' => 'La tua sessione sta per scadere',
    'el' => 'Η συνεδρία σας λήγει',
],
'session_expiring_message' => [
    'fi' => 'Istuntosi vanhenee pian. Haluatko jatkaa?',
    'sv' => 'Din session löper snart ut. Vill du fortsätta?',
    'en' => 'Your session will expire soon. Do you want to continue?',
    'it' => 'La tua sessione scadrà presto. Vuoi continuare?',
    'el' => 'Η συνεδρία σας θα λήξει σύντομα. Θέλετε να συνεχίσετε;',
],
'session_continue' => [
    'fi' => 'Jatka istuntoa',
    'sv' => 'Fortsätt sessionen',
    'en' => 'Continue session',
    'it' => 'Continua sessione',
    'el' => 'Συνέχεια συνεδρίας',
],
'session_invalidated_message' => [
    'fi' => 'Istuntosi on vanhentunut. Kirjaudu uudelleen sisään.',
    'en' => 'Your session has expired. Please log in again.',
    'sv' => 'Din session har upphört. Logga in igen.',
    'it' => 'La tua sessione è scaduta. Accedi di nuovo.',
    'el' => 'Η συνεδρία σας έχει λήξει. Συνδεθείτε ξανά.',
],
'role_categories_title' => [
    'fi' => 'Roolikategoriat',
    'sv' => 'Rollkategorier',
    'en' => 'Role Categories',
    'it' => 'Categorie di ruolo',
    'el' => 'Κατηγορίες ρόλων',
],
'worksite_placeholder' => [
    'fi' => 'Esim: Siilinjärvi (tyhjä = kaikki työmaat)',
    'sv' => 'T.ex: Siilinjärvi (tom = alla arbetsplatser)',
    'en' => 'E.g.: Siilinjärvi (empty = all worksites)',
    'it' => 'Es: Siilinjärvi (vuoto = tutti i cantieri)',
    'el' => 'Π.χ: Siilinjärvi (κενό = όλα τα εργοτάξια)',
],
'worksite_help' => [
    'fi' => 'Jätä tyhjäksi, jos kategoria koskee kaikkia työmaita',
    'sv' => 'Lämna tomt om kategorin gäller alla arbetsplatser',
    'en' => 'Leave empty if category applies to all worksites',
    'it' => 'Lascia vuoto se la categoria si applica a tutti i cantieri',
    'el' => 'Αφήστε κενό εάν η κατηγορία ισχύει για όλα τα εργοτάξια',
],
'password_modal_title' => [
    'fi' => 'Uusi salasana luotu',
    'en' => 'New password created',
    'sv' => 'Nytt lösenord skapat',
    'it' => 'Nuova password creata',
    'el' => 'Δημιουργήθηκε νέος κωδικός πρόσβασης',
],
'password_modal_warning' => [
    'fi' => 'Kopioi salasana turvalliseen paikkaan. Tämä ikkuna sulkeutuu automaattisesti.',
    'en' => 'Copy the password to a safe location. This window will close automatically.',
    'sv' => 'Kopiera lösenordet till en säker plats. Detta fönster stängs automatiskt.',
    'it' => 'Copia la password in un luogo sicuro. Questa finestra si chiuderà automaticamente.',
    'el' => 'Αντιγράψτε τον κωδικό πρόσβασης σε ασφαλή τοποθεσία. Αυτό το παράθυρο θα κλείσει αυτόματα.',
],
'password_copy_button' => [
    'fi' => 'Kopioi',
    'en' => 'Copy',
    'sv' => 'Kopiera',
    'it' => 'Copia',
    'el' => 'Αντιγραφή',
],
'password_copied' => [
    'fi' => 'Kopioitu!',
    'en' => 'Copied!',
    'sv' => 'Kopierat!',
    'it' => 'Copiato!',
    'el' => 'Αντιγράφηκε!',
],
'password_show' => [
    'fi' => 'Näytä',
    'en' => 'Show',
    'sv' => 'Visa',
    'it' => 'Mostra',
    'el' => 'Εμφάνιση',
],
'password_hide' => [
    'fi' => 'Piilota',
    'en' => 'Hide',
    'sv' => 'Dölj',
    'it' => 'Nascondi',
    'el' => 'Απόκρυψη',
],
'password_closes_in' => [
    'fi' => 'Sulkeutuu:',
    'en' => 'Closes in:',
    'sv' => 'Stängs om:',
    'it' => 'Si chiude tra:',
    'el' => 'Κλείνει σε:',
],
'users_show_deleted' => [
    'fi' => 'Näytä poistetut',
    'en' => 'Show deleted',
    'sv' => 'Visa raderade',
    'it' => 'Mostra eliminati',
    'el' => 'Εμφάνιση διαγραμμένων',
],
'users_action_reactivate' => [
    'fi' => 'Aktivoi uudelleen',
    'en' => 'Reactivate',
    'sv' => 'Återaktivera',
    'it' => 'Riattiva',
    'el' => 'Επανενεργοποίηση',
],
'users_reactivated' => [
    'fi' => 'Käyttäjä aktivoitu uudelleen',
    'en' => 'User reactivated',
    'sv' => 'Användare återaktiverad',
    'it' => 'Utente riattivato',
    'el' => 'Ο χρήστης επανενεργοποιήθηκε',
],
'users_loading' => [
    'fi' => 'Ladataan...',
    'en' => 'Loading...',
    'sv' => 'Laddar...',
    'it' => 'Caricamento...',
    'el' => 'Φόρτωση...',
],
'users_no_results' => [
    'fi' => 'Ei käyttäjiä hakuehdoilla',
    'en' => 'No users match the filters',
    'sv' => 'Inga användare matchar filtren',
    'it' => 'Nessun utente corrisponde ai filtri',
    'el' => 'Κανένας χρήστης δεν ταιριάζει με τα φίλτρα',
],

// Email Notification Settings
'email_notifications_label' => [
    'fi' => 'Sähköposti-ilmoitukset',
    'en' => 'Email notifications',
    'sv' => 'E-postmeddelanden',
    'it' => 'Notifiche email',
    'el' => 'Ειδοποιήσεις email',
],
'profile_notifications_heading' => [
    'fi' => 'Ilmoitusasetukset',
    'en' => 'Notification Settings',
    'sv' => 'Aviseringsinställningar',
    'it' => 'Impostazioni notifiche',
    'el' => 'Ρυθμίσεις ειδοποιήσεων',
],
'profile_tab_basics' => [
    'fi' => 'Perustiedot',
    'en' => 'Basic Info',
    'sv' => 'Grundläggande information',
    'it' => 'Informazioni di base',
    'el' => 'Βασικές πληροφορίες',
],
'profile_tab_settings' => [
    'fi' => 'Asetukset',
    'en' => 'Settings',
    'sv' => 'Inställningar',
    'it' => 'Impostazioni',
    'el' => 'Ρυθμίσεις',
],
'profile_tab_password' => [
    'fi' => 'Salasana',
    'en' => 'Password',
    'sv' => 'Lösenord',
    'it' => 'Password',
    'el' => 'Κωδικός',
],
'email_notifications_enabled' => [
    'fi' => 'Käytössä',
    'en' => 'Enabled',
    'sv' => 'Aktiverad',
    'it' => 'Abilitato',
    'el' => 'Ενεργοποιημένο',
],
'email_notifications_disabled' => [
    'fi' => 'Pois käytöstä',
    'en' => 'Disabled',
    'sv' => 'Inaktiverad',
    'it' => 'Disabilitato',
    'el' => 'Απενεργοποιημένο',
],
'bulk_disable_emails' => [
    'fi' => 'Poista sähköpostit käytöstä',
    'en' => 'Disable emails',
    'sv' => 'Inaktivera e-post',
    'it' => 'Disabilita email',
    'el' => 'Απενεργοποίηση email',
],
'bulk_enable_emails' => [
    'fi' => 'Ota sähköpostit käyttöön',
    'en' => 'Enable emails',
    'sv' => 'Aktivera e-post',
    'it' => 'Abilita email',
    'el' => 'Ενεργοποίηση email',
],

// Email Log View
'settings_tab_email_logs' => [
    'fi' => 'Sähköpostiloki',
    'en' => 'Email Log',
    'sv' => 'E-postlogg',
    'it' => 'Log email',
    'el' => 'Αρχείο email',
],
'email_log_title' => [
    'fi' => 'Sähköpostiloki',
    'en' => 'Email Log',
    'sv' => 'E-postlogg',
    'it' => 'Log email',
    'el' => 'Αρχείο email',
],
'email_log_time' => [
    'fi' => 'Aika',
    'en' => 'Time',
    'sv' => 'Tid',
    'it' => 'Ora',
    'el' => 'Ώρα',
],
'email_log_recipient' => [
    'fi' => 'Vastaanottaja',
    'en' => 'Recipient',
    'sv' => 'Mottagare',
    'it' => 'Destinatario',
    'el' => 'Παραλήπτης',
],
'email_log_subject' => [
    'fi' => 'Aihe',
    'en' => 'Subject',
    'sv' => 'Ämne',
    'it' => 'Oggetto',
    'el' => 'Θέμα',
],
'email_log_status' => [
    'fi' => 'Tila',
    'en' => 'Status',
    'sv' => 'Status',
    'it' => 'Stato',
    'el' => 'Κατάσταση',
],
'email_log_flash_id' => [
    'fi' => 'Flash ID',
    'en' => 'Flash ID',
    'sv' => 'Flash ID',
    'it' => 'Flash ID',
    'el' => 'Flash ID',
],
'email_log_error' => [
    'fi' => 'Virhe',
    'en' => 'Error',
    'sv' => 'Fel',
    'it' => 'Errore',
    'el' => 'Σφάλμα',
],
'email_status_sent' => [
    'fi' => 'Lähetetty',
    'en' => 'Sent',
    'sv' => 'Skickad',
    'it' => 'Inviato',
    'el' => 'Απεστάλη',
],
'email_status_failed' => [
    'fi' => 'Epäonnistui',
    'en' => 'Failed',
    'sv' => 'Misslyckades',
    'it' => 'Fallito',
    'el' => 'Απέτυχε',
],
'email_status_skipped' => [
    'fi' => 'Ohitettu',
    'en' => 'Skipped',
    'sv' => 'Överhoppad',
    'it' => 'Saltato',
    'el' => 'Παραλείφθηκε',
],
'email_log_filter_date_from' => [
    'fi' => 'Alkaen',
    'en' => 'From',
    'sv' => 'Från',
    'it' => 'Da',
    'el' => 'Από',
],
'email_log_filter_date_to' => [
    'fi' => 'Päättyen',
    'en' => 'To',
    'sv' => 'Till',
    'it' => 'A',
    'el' => 'Έως',
],
'email_log_filter_status' => [
    'fi' => 'Suodata tilalla',
    'en' => 'Filter by status',
    'sv' => 'Filtrera efter status',
    'it' => 'Filtra per stato',
    'el' => 'Φιλτράρισμα κατά κατάσταση',
],
'email_log_filter_recipient' => [
    'fi' => 'Hae vastaanottajalla',
    'en' => 'Search by recipient',
    'sv' => 'Sök efter mottagare',
    'it' => 'Cerca per destinatario',
    'el' => 'Αναζήτηση κατά παραλήπτη',
],
'email_log_no_results' => [
    'fi' => 'Ei lokimerkintöjä',
    'en' => 'No log entries',
    'sv' => 'Inga loggposter',
    'it' => 'Nessuna voce di log',
    'el' => 'Δεν υπάρχουν καταχωρίσεις',
],
'email_log_apply_filters' => [
    'fi' => 'Käytä suodattimia',
    'en' => 'Apply filters',
    'sv' => 'Använd filter',
    'it' => 'Applica filtri',
    'el' => 'Εφαρμογή φίλτρων',
],
'email_log_clear_filters' => [
    'fi' => 'Tyhjennä suodattimet',
    'en' => 'Clear filters',
    'sv' => 'Rensa filter',
    'it' => 'Cancella filtri',
    'el' => 'Καθαρισμός φίλτρων',
],
'bulk_action_select' => [
    'fi' => 'Valitse toiminto',
    'en' => 'Select action',
    'sv' => 'Välj åtgärd',
    'it' => 'Seleziona azione',
    'el' => 'Επιλογή ενέργειας',
],
'bulk_action_apply' => [
    'fi' => 'Suorita',
    'en' => 'Apply',
    'sv' => 'Utför',
    'it' => 'Applica',
    'el' => 'Εφαρμογή',
],
'bulk_action_no_users_selected' => [
    'fi' => 'Valitse käyttäjiä ensin',
    'en' => 'Select users first',
    'sv' => 'Välj användare först',
    'it' => 'Seleziona prima gli utenti',
    'el' => 'Επιλέξτε πρώτα χρήστες',
],
'bulk_action_success' => [
    'fi' => 'Toiminto suoritettu onnistuneesti',
    'en' => 'Action completed successfully',
    'sv' => 'Åtgärden slutfördes',
    'it' => 'Azione completata con successo',
    'el' => 'Η ενέργεια ολοκληρώθηκε επιτυχώς',
],
'additional_roles' => [
    'fi' => 'Lisäroolit',
    'sv' => 'Ytterligare roller',
    'en' => 'Additional roles',
    'it' => 'Ruoli aggiuntivi',
    'el' => 'Επιπλέον ρόλοι',
],
'additional_roles_help' => [
    'fi' => 'Valitse roolit, joiden sähköpostit käyttäjä saa pääroolinsa lisäksi.',
    'sv' => 'Välj roller vars e-post användaren får utöver sin huvudroll.',
    'en' => 'Select roles whose emails the user will receive in addition to their main role.',
    'it' => 'Seleziona i ruoli le cui email l\'utente riceverà oltre al ruolo principale.',
    'el' => 'Επιλέξτε ρόλους των οποίων τα email θα λαμβάνει ο χρήστης εκτός από τον κύριο ρόλο.',
],
'additional_roles_saved' => [
    'fi' => 'Lisäroolit tallennettu',
    'sv' => 'Ytterligare roller sparade',
    'en' => 'Additional roles saved',
    'it' => 'Ruoli aggiuntivi salvati',
    'el' => 'Οι επιπλέον ρόλοι αποθηκεύτηκαν',
],
'email_resend_button' => [
    'fi' => 'Lähetä uudelleen',
    'sv' => 'Skicka igen',
    'en' => 'Resend',
    'it' => 'Invia di nuovo',
    'el' => 'Επαναποστολή',
],
'email_resend_confirm' => [
    'fi' => 'Haluatko lähettää sähköpostin uudelleen kaikille ryhmän jäsenille?',
    'sv' => 'Vill du skicka e-postmeddelandet igen till alla gruppmedlemmar?',
    'en' => 'Do you want to resend the email to all group members?',
    'it' => 'Vuoi inviare nuovamente l\'email a tutti i membri del gruppo?',
    'el' => 'Θέλετε να ξαναστείλετε το email σε όλα τα μέλη της ομάδας;',
],
'email_resend_success' => [
    'fi' => 'Sähköposti lähetetty {count} vastaanottajalle',
    'sv' => 'E-post skickad till {count} mottagare',
    'en' => 'Email sent to {count} recipient(s)',
    'it' => 'Email inviata a {count} destinatario/i',
    'el' => 'Το email στάλθηκε σε {count} παραλήπτη/ες',
],
'email_resend_error' => [
    'fi' => 'Virhe lähettäessä uudelleen',
    'sv' => 'Fel vid omsändning',
    'en' => 'Error resending email',
    'it' => 'Errore durante il reinvio',
    'el' => 'Σφάλμα κατά την επαναποστολή',
],
'email_resend_no_flash' => [
    'fi' => 'SafetyFlash-tietoa ei löytynyt',
    'sv' => 'SafetyFlash-information hittades inte',
    'en' => 'SafetyFlash information not found',
    'it' => 'Informazioni SafetyFlash non trovate',
    'el' => 'Οι πληροφορίες SafetyFlash δεν βρέθηκαν',
],

// Send to Communications Modal - Stepper
'comms_step_languages' => [
    'fi' => 'Kieliversiot',
    'sv' => 'Språkversioner',
    'en' => 'Language versions',
    'it' => 'Versioni linguistiche',
    'el' => 'Γλωσσικές εκδόσεις',
],
'comms_step_languages_desc' => [
    'fi' => 'Valitse mitkä käännökset tehdään',
    'sv' => 'Välj vilka översättningar som ska göras',
    'en' => 'Select which translations to make',
    'it' => 'Seleziona quali traduzioni fare',
    'el' => 'Επιλέξτε ποιες μεταφράσεις να γίνουν',
],
'comms_step_displays' => [
    'fi' => 'Xibo-näytöt',
    'sv' => 'Xibo-skärmar',
    'en' => 'Xibo displays',
    'it' => 'Display Xibo',
    'el' => 'Οθόνες Xibo',
],
'comms_step_displays_desc' => [
    'fi' => 'Millä työmailla näytetään',
    'sv' => 'På vilka arbetsplatser ska det visas',
    'en' => 'Which worksites to display on',
    'it' => 'Su quali cantieri mostrare',
    'el' => 'Σε ποια εργοτάξια να εμφανιστεί',
],
'comms_step_distribution' => [
    'fi' => 'Jakelu',
    'sv' => 'Distribution',
    'en' => 'Distribution',
    'it' => 'Distribuzione',
    'el' => 'Διανομή',
],
'comms_step_distribution_desc' => [
    'fi' => 'Kenelle sähköposti-ilmoitus lähetetään',
    'sv' => 'Till vem e-postaviseringen skickas',
    'en' => 'Who to send email notification to',
    'it' => 'A chi inviare la notifica email',
    'el' => 'Σε ποιον να σταλεί ειδοποίηση email',
],
'comms_step_message' => [
    'fi' => 'Viesti',
    'sv' => 'Meddelande',
    'en' => 'Message',
    'it' => 'Messaggio',
    'el' => 'Μήνυμα',
],
'comms_step_summary' => [
    'fi' => 'Yhteenveto',
    'sv' => 'Sammanfattning',
    'en' => 'Summary',
    'it' => 'Riepilogo',
    'el' => 'Σύνοψη',
],
'comms_all_displays' => [
    'fi' => 'Kaikki näytöt',
    'sv' => 'Alla skärmar',
    'en' => 'All displays',
    'it' => 'Tutti i display',
    'el' => 'Όλες οι οθόνες',
],
'comms_select_worksites' => [
    'fi' => 'Valitse työmaat',
    'sv' => 'Välj arbetsplatser',
    'en' => 'Select worksites',
    'it' => 'Seleziona cantieri',
    'el' => 'Επιλέξτε εργοτάξια',
],
'comms_wide_distribution' => [
    'fi' => 'Laaja jakelu',
    'sv' => 'Bred distribution',
    'en' => 'Wide distribution',
    'it' => 'Distribuzione ampia',
    'el' => 'Ευρεία διανομή',
],
'comms_wide_distribution_desc' => [
    'fi' => 'Kaikki jakeluryhmät',
    'sv' => 'Alla distributionsgrupper',
    'en' => 'All distribution groups',
    'it' => 'Tutti i gruppi di distribuzione',
    'el' => 'Όλες οι ομάδες διανομής',
],
'comms_targeted_distribution' => [
    'fi' => 'Kohdennettu',
    'sv' => 'Riktad',
    'en' => 'Targeted',
    'it' => 'Mirato',
    'el' => 'Στοχευμένη',
],
'comms_targeted_distribution_desc' => [
    'fi' => 'Vain valitut maat',
    'sv' => 'Endast valda länder',
    'en' => 'Only selected countries',
    'it' => 'Solo paesi selezionati',
    'el' => 'Μόνο επιλεγμένες χώρες',
],
'comms_btn_next' => [
    'fi' => 'Seuraava',
    'sv' => 'Nästa',
    'en' => 'Next',
    'it' => 'Successivo',
    'el' => 'Επόμενο',
],
'comms_btn_back' => [
    'fi' => 'Takaisin',
    'sv' => 'Tillbaka',
    'en' => 'Back',
    'it' => 'Indietro',
    'el' => 'Πίσω',
],
'comms_btn_send' => [
    'fi' => 'Lähetä',
    'sv' => 'Skicka',
    'en' => 'Send',
    'it' => 'Invia',
    'el' => 'Αποστολή',
],
'comms_message_optional' => [
    'fi' => 'Valinnainen viesti viestintätiimille',
    'sv' => 'Valfritt meddelande till kommunikationsteamet',
    'en' => 'Optional message for communications team',
    'it' => 'Messaggio opzionale per il team di comunicazione',
    'el' => 'Προαιρετικό μήνυμα για την ομάδα επικοινωνίας',
],
'comms_validation_select_language' => [
    'fi' => 'Valitse vähintään yksi kieli',
    'sv' => 'Välj minst ett språk',
    'en' => 'Select at least one language',
    'it' => 'Seleziona almeno una lingua',
    'el' => 'Επιλέξτε τουλάχιστον μία γλώσσα',
],
'comms_validation_select_worksite' => [
    'fi' => 'Valitse vähintään yksi työmaa',
    'sv' => 'Välj minst en arbetsplats',
    'en' => 'Select at least one worksite',
    'it' => 'Seleziona almeno un cantiere',
    'el' => 'Επιλέξτε τουλάχιστον ένα εργοτάξιο',
],
'settings_tab_system' => [
    'fi' => 'Järjestelmä',
    'sv' => 'System',
    'en' => 'System',
    'it' => 'Sistema',
    'el' => 'Σύστημα',
],
'settings_list_page' => [
    'fi' => 'Lista-sivu',
    'sv' => 'Listsida',
    'en' => 'List page',
    'it' => 'Pagina elenco',
    'el' => 'Σελίδα λίστας',
],
'settings_editing_indicator' => [
    'fi' => 'Näytä muokkaus-indikaattori',
    'sv' => 'Visa redigeringsindikator',
    'en' => 'Show editing indicator',
    'it' => 'Mostra indicatore di modifica',
    'el' => 'Εμφάνιση ένδειξης επεξεργασίας',
],
'settings_editing_indicator_desc' => [
    'fi' => 'Näyttää listalla reaaliaikaisesti kuka muokkaa mitäkin SafetyFlashia',
    'sv' => 'Visar i realtid vem som redigerar vilken SafetyFlash i listan',
    'en' => 'Shows in real-time who is editing which SafetyFlash on the list',
    'it' => 'Mostra in tempo reale chi sta modificando quale SafetyFlash nella lista',
    'el' => 'Εμφανίζει σε πραγματικό χρόνο ποιος επεξεργάζεται ποιο SafetyFlash στη λίστα',
],
'settings_polling_interval' => [
    'fi' => 'Päivitysväli',
    'sv' => 'Uppdateringsintervall',
    'en' => 'Polling interval',
    'it' => 'Intervallo di aggiornamento',
    'el' => 'Διάστημα ενημέρωσης',
],
'settings_lock_timeout' => [
    'fi' => 'Lukituksen vanhenemisaika',
    'sv' => 'Låsningens utgångstid',
    'en' => 'Lock timeout',
    'it' => 'Timeout blocco',
    'el' => 'Χρόνος λήξης κλειδώματος',
],
'seconds' => [
    'fi' => 'sekuntia',
    'sv' => 'sekunder',
    'en' => 'seconds',
    'it' => 'secondi',
    'el' => 'δευτερόλεπτα',
],
'minutes' => [
    'fi' => 'minuuttia',
    'sv' => 'minuter',
    'en' => 'minutes',
    'it' => 'minuti',
    'el' => 'λεπτά',
],
'saving' => [
    'fi' => 'Tallennetaan...',
    'sv' => 'Sparar...',
    'en' => 'Saving...',
    'it' => 'Salvataggio...',
    'el' => 'Αποθήκευση...',
],
'saved' => [
    'fi' => 'Tallennettu!',
    'sv' => 'Sparat!',
    'en' => 'Saved!',
    'it' => 'Salvato!',
    'el' => 'Αποθηκεύτηκε!',
],
'save_error' => [
    'fi' => 'Tallennus epäonnistui',
    'sv' => 'Misslyckades med att spara',
    'en' => 'Save failed',
    'it' => 'Salvataggio fallito',
    'el' => 'Αποτυχία αποθήκευσης',
],

// Email Settings Tab
'settings_tab_email_settings' => [
    'fi' => 'Sähköposti',
    'sv' => 'E-post',
    'en' => 'Email',
    'it' => 'Email',
    'el' => 'Email',
],
'settings_smtp_host' => [
    'fi' => 'SMTP-palvelin',
    'sv' => 'SMTP-server',
    'en' => 'SMTP server',
    'it' => 'Server SMTP',
    'el' => 'Διακομιστής SMTP',
],
'settings_smtp_host_placeholder' => [
    'fi' => 'esim. mail.tapojarvi.online',
    'sv' => 't.ex. mail.tapojarvi.online',
    'en' => 'e.g. mail.tapojarvi.online',
    'it' => 'es. mail.tapojarvi.online',
    'el' => 'π.χ. mail.tapojarvi.online',
],
'settings_smtp_port' => [
    'fi' => 'SMTP-portti',
    'sv' => 'SMTP-port',
    'en' => 'SMTP port',
    'it' => 'Porta SMTP',
    'el' => 'Θύρα SMTP',
],
'settings_smtp_encryption' => [
    'fi' => 'Salaus',
    'sv' => 'Kryptering',
    'en' => 'Encryption',
    'it' => 'Crittografia',
    'el' => 'Κρυπτογράφηση',
],
'settings_smtp_encryption_none' => [
    'fi' => 'Ei salausta',
    'sv' => 'Ingen kryptering',
    'en' => 'No encryption',
    'it' => 'Nessuna crittografia',
    'el' => 'Χωρίς κρυπτογράφηση',
],
'settings_smtp_encryption_tls' => [
    'fi' => 'TLS',
    'sv' => 'TLS',
    'en' => 'TLS',
    'it' => 'TLS',
    'el' => 'TLS',
],
'settings_smtp_encryption_ssl' => [
    'fi' => 'SSL',
    'sv' => 'SSL',
    'en' => 'SSL',
    'it' => 'SSL',
    'el' => 'SSL',
],
'settings_smtp_username' => [
    'fi' => 'Käyttäjätunnus',
    'sv' => 'Användarnamn',
    'en' => 'Username',
    'it' => 'Nome utente',
    'el' => 'Όνομα χρήστη',
],
'settings_smtp_password' => [
    'fi' => 'Salasana',
    'sv' => 'Lösenord',
    'en' => 'Password',
    'it' => 'Password',
    'el' => 'Κωδικός πρόσβασης',
],
'settings_smtp_password_hint' => [
    'fi' => 'Jätä tyhjäksi jos et halua muuttaa',
    'sv' => 'Lämna tomt om du inte vill ändra',
    'en' => 'Leave empty if you don\'t want to change',
    'it' => 'Lascia vuoto se non vuoi modificare',
    'el' => 'Αφήστε κενό αν δεν θέλετε να αλλάξετε',
],
'settings_smtp_from_email' => [
    'fi' => 'Lähettäjän osoite',
    'sv' => 'Avsändarens adress',
    'en' => 'From address',
    'it' => 'Indirizzo mittente',
    'el' => 'Διεύθυνση αποστολέα',
],
'settings_smtp_from_name' => [
    'fi' => 'Lähettäjän nimi',
    'sv' => 'Avsändarens namn',
    'en' => 'From name',
    'it' => 'Nome mittente',
    'el' => 'Όνομα αποστολέα',
],
'settings_email_heading' => [
    'fi' => 'Sähköpostiasetukset',
    'sv' => 'E-postinställningar',
    'en' => 'Email Settings',
    'it' => 'Impostazioni email',
    'el' => 'Ρυθμίσεις email',
],
'settings_smtp_settings' => [
    'fi' => 'SMTP-asetukset',
    'sv' => 'SMTP-inställningar',
    'en' => 'SMTP Settings',
    'it' => 'Impostazioni SMTP',
    'el' => 'Ρυθμίσεις SMTP',
],
'settings_test_email' => [
    'fi' => 'Testaa sähköpostin lähetys',
    'sv' => 'Testa e-postsändning',
    'en' => 'Test email sending',
    'it' => 'Testa invio email',
    'el' => 'Δοκιμή αποστολής email',
],
'settings_test_email_desc' => [
    'fi' => 'Lähetä testisähköposti varmistaaksesi että asetukset toimivat.',
    'sv' => 'Skicka ett testmeddelande för att bekräfta att inställningarna fungerar.',
    'en' => 'Send a test email to verify that the settings work.',
    'it' => 'Invia un\'email di prova per verificare che le impostazioni funzionino.',
    'el' => 'Στείλτε ένα δοκιμαστικό email για να επιβεβαιώσετε ότι οι ρυθμίσεις λειτουργούν.',
],
'settings_test_email_placeholder' => [
    'fi' => 'Syötä testiosoite',
    'sv' => 'Ange testadress',
    'en' => 'Enter test address',
    'it' => 'Inserisci indirizzo di prova',
    'el' => 'Εισαγάγετε δοκιμαστική διεύθυνση',
],
'settings_send_test' => [
    'fi' => 'Lähetä testiviesti',
    'sv' => 'Skicka testmeddelande',
    'en' => 'Send test message',
    'it' => 'Invia messaggio di prova',
    'el' => 'Αποστολή δοκιμαστικού μηνύματος',
],
'settings_test_success' => [
    'fi' => 'Testisähköposti lähetetty onnistuneesti!',
    'sv' => 'Testmeddelandet skickades!',
    'en' => 'Test email sent successfully!',
    'it' => 'Email di prova inviata con successo!',
    'el' => 'Το δοκιμαστικό email στάλθηκε επιτυχώς!',
],
'settings_test_failed' => [
    'fi' => 'Lähetys epäonnistui',
    'sv' => 'Sändningen misslyckades',
    'en' => 'Sending failed',
    'it' => 'Invio fallito',
    'el' => 'Αποτυχία αποστολής',
],
'settings_test_sending' => [
    'fi' => 'Lähetetään...',
    'sv' => 'Skickar...',
    'en' => 'Sending...',
    'it' => 'Invio in corso...',
    'el' => 'Αποστολή...',
],
'users_label_language' => [
    'fi' => 'Kieli',
    'sv' => 'Språk',
    'en' => 'Language',
    'it' => 'Lingua',
    'el' => 'Γλώσσα',
],
'users_language_help' => [
    'fi' => 'Valitse käyttäjän kieli. Vaikuttaa sovelluksen kieleen ja sähköposteihin.',
    'sv' => 'Välj användarens språk. Påverkar applikationens språk och e-postmeddelanden.',
    'en' => 'Select user language. Affects application language and emails.',
    'it' => 'Seleziona la lingua dell\'utente. Influisce sulla lingua dell\'applicazione e sulle email.',
    'el' => 'Επιλέξτε τη γλώσσα χρήστη. Επηρεάζει τη γλώσσα της εφαρμογής και τα email.',
],
'users_role_categories_heading' => [
    'fi' => 'Työmaavastaavuudet',
    'sv' => 'Arbetsplatsansvar',
    'en' => 'Site Manager Assignments',
    'it' => 'Incarichi responsabile cantiere',
    'el' => 'Αναθέσεις υπευθύνου εργοταξίου',
],
'users_role_categories_help' => [
    'fi' => 'Valitse mihin työmaihin henkilö on työmaavastaava, hyväksyjä tai tarkastaja SafetyFlasheille. Tämä on erillinen pääroolin valinnasta.',
    'sv' => 'Välj till vilka arbetsplatser personen är arbetsplatsansvarig, godkännare eller granskare för SafetyFlasher. Detta är separat från huvudrollvalet.',
    'en' => 'Select which worksites the person is site manager, approver or reviewer for SafetyFlashes. This is separate from the main role selection.',
    'it' => 'Seleziona per quali cantieri la persona è responsabile, approvatore o revisore per SafetyFlash. Questo è separato dalla selezione del ruolo principale.',
    'el' => 'Επιλέξτε σε ποια εργοτάξια το άτομο είναι υπεύθυνος, εγκριτής ή αξιολογητής για SafetyFlash. Αυτό είναι ξεχωριστό από την επιλογή κύριου ρόλου.',
],
'profile_language_heading' => [
    'fi' => 'Kieli',
    'sv' => 'Språk',
    'en' => 'Language',
    'it' => 'Lingua',
    'el' => 'Γλώσσα',
],
'profile_language_label' => [
    'fi' => 'Sovelluksen ja sähköpostien kieli',
    'sv' => 'Applikations- och e-postspråk',
    'en' => 'Application and email language',
    'it' => 'Lingua dell\'applicazione e delle email',
    'el' => 'Γλώσσα εφαρμογής και email',
],
'profile_language_help' => [
    'fi' => 'Valitse kieli jota käytät sovelluksessa ja sähköposteissa.',
    'sv' => 'Välj det språk du använder i applikationen och i e-postmeddelanden.',
    'en' => 'Select the language you use in the application and emails.',
    'it' => 'Seleziona la lingua che usi nell\'applicazione e nelle email.',
    'el' => 'Επιλέξτε τη γλώσσα που χρησιμοποιείτε στην εφαρμογή και στα email.',
],
'role_type_site_manager' => [
    'fi' => 'Työmaavastaava',
    'sv' => 'Arbetsplatsansvarig',
    'en' => 'Site Manager',
    'it' => 'Responsabile cantiere',
    'el' => 'Υπεύθυνος εργοταξίου',
],
'role_type_approver' => [
    'fi' => 'Hyväksyjä',
    'sv' => 'Godkännare',
    'en' => 'Approver',
    'it' => 'Approvatore',
    'el' => 'Εγκριτής',
],
'role_type_reviewer' => [
    'fi' => 'Tarkastaja',
    'sv' => 'Granskare',
    'en' => 'Reviewer',
    'it' => 'Revisore',
    'el' => 'Αξιολογητής',
],
'search_worksite_placeholder' => [
    'fi' => '🔍 Hae työmaata tai roolia...',
    'sv' => '🔍 Sök arbetsplats eller roll...',
    'en' => '🔍 Search worksite or role...',
    'it' => '🔍 Cerca cantiere o ruolo...',
    'el' => '🔍 Αναζήτηση εργοταξίου ή ρόλου...',
],
'no_assignments_selected' => [
    'fi' => 'Ei valittuja työmaavastaavuuksia',
    'sv' => 'Inga valda arbetsplatsansvar',
    'en' => 'No site assignments selected',
    'it' => 'Nessun incarico selezionato',
    'el' => 'Δεν έχουν επιλεγεί αναθέσεις',
],
'no_search_results' => [
    'fi' => 'Ei tuloksia',
    'sv' => 'Inga resultat',
    'en' => 'No results',
    'it' => 'Nessun risultato',
    'el' => 'Κανένα αποτέλεσμα',
],
'worksite_global' => [
    'fi' => 'Globaali',
    'sv' => 'Global',
    'en' => 'Global',
    'it' => 'Globale',
    'el' => 'Καθολική',
],
'email_notifications_help' => [
    'fi' => 'Valitse saako käyttäjä sähköposti-ilmoituksia järjestelmästä.',
    'sv' => 'Välj om användaren får e-postmeddelanden från systemet.',
    'en' => 'Choose whether the user receives email notifications from the system.',
    'it' => 'Scegli se l\'utente riceve notifiche email dal sistema.',
    'el' => 'Επιλέξτε εάν ο χρήστης λαμβάνει ειδοποιήσεις email από το σύστημα.',
],
'email_notifications_enabled' => [
    'fi' => 'Sähköposti-ilmoitukset käytössä',
    'sv' => 'E-postmeddelanden aktiverade',
    'en' => 'Email notifications enabled',
    'it' => 'Notifiche email abilitate',
    'el' => 'Οι ειδοποιήσεις email ενεργοποιήθηκαν',
],
'search_role_placeholder' => [
    'fi' => '🔍 Hae roolia...',
    'sv' => '🔍 Sök roll...',
    'en' => '🔍 Search role...',
    'it' => '🔍 Cerca ruolo...',
    'el' => '🔍 Αναζήτηση ρόλου...',
],
'no_additional_roles_selected' => [
    'fi' => 'Ei valittuja lisärooleja',
    'sv' => 'Inga ytterligare roller valda',
    'en' => 'No additional roles selected',
    'it' => 'Nessun ruolo aggiuntivo selezionato',
    'el' => 'Δεν επιλέχθηκαν πρόσθετοι ρόλοι',
],
'additional_roles' => [
    'fi' => 'Lisäroolit',
    'sv' => 'Ytterligare roller',
    'en' => 'Additional Roles',
    'it' => 'Ruoli aggiuntivi',
    'el' => 'Πρόσθετοι ρόλοι',
],
'additional_roles_help' => [
    'fi' => 'Valitse roolit, joiden sähköpostit käyttäjä saa pääroolinsa lisäksi.',
    'sv' => 'Välj roller vars e-postmeddelanden användaren får utöver sin huvudroll.',
    'en' => 'Select roles whose emails the user receives in addition to their main role.',
    'it' => 'Seleziona i ruoli le cui email l\'utente riceve oltre al suo ruolo principale.',
    'el' => 'Επιλέξτε ρόλους των οποίων τα email λαμβάνει ο χρήστης εκτός από τον κύριο ρόλο του.',
],
'users_status_inactive' => [
'fi' => 'Ei aktiivinen',
'sv' => 'Inte aktiv',
'en' => 'Not active',
'it' => 'Non attivo',
'el' => 'Μη ενεργός',
],
];
