<?php
/**
 * Status and Workflow States - Publication states, status changes
 */
return [
'publish_send_to_distribution' => [
    'fi' => 'Lähetä jakelulistalle',
    'sv' => 'Skicka till distributionslistan',
    'en' => 'Send to distribution list',
    'it' => 'Invia alla lista di distribuzione',
    'el' => 'Αποστολή στη λίστα διανομής',
],
'publish_send_to_distribution_hint' => [
    'fi' => 'Lähettää sähköpostin laajemmalle vastaanottajaryhmälle',
    'sv' => 'Skickar e-post till en bredare mottagargrupp',
    'en' => 'Sends email to a broader recipient group',
    'it' => 'Invia email a un gruppo più ampio di destinatari',
    'el' => 'Αποστέλλει email σε ευρύτερη ομάδα παραληπτών',
],
'publish_personal_injury' => [
    'fi' => 'Henkilövahinkoja tapahtunut',
    'sv' => 'Personskador har inträffat',
    'en' => 'Personal injuries occurred',
    'it' => 'Si sono verificati infortuni',
    'el' => 'Σημειώθηκαν τραυματισμοί',
],
'publish_personal_injury_hint' => [
    'fi' => 'Lisää varoituksen sähköpostin otsikkoon',
    'sv' => 'Lägger till en varning i e-postens ämnesrad',
    'en' => 'Adds a warning to the email subject line',
    'it' => 'Aggiunge un avviso nell\'oggetto dell\'email',
    'el' => 'Προσθέτει προειδοποίηση στο θέμα του email',
],
'publish_subject_preview' => [
    'fi' => 'Sähköpostin otsikko',
    'sv' => 'E-postens ämne',
    'en' => 'Email subject',
    'it' => 'Oggetto email',
    'el' => 'Θέμα email',
],
'publish_select_languages' => [
    'fi' => 'Valitse lähetettävät kieliversiot',
    'sv' => 'Välj språkversioner att skicka',
    'en' => 'Select language versions to send',
    'it' => 'Seleziona le versioni linguistiche da inviare',
    'el' => 'Επιλέξτε εκδόσεις γλώσσας για αποστολή',
],
'publish_all_versions_info' => [
    'fi' => 'Julkaisu julkaisee kaikki kieliversiot kerralla.',
    'sv' => 'Publicering publicerar alla språkversioner samtidigt.',
    'en' => 'Publishing will publish all language versions at once.',
    'it' => 'La pubblicazione pubblicherà tutte le versioni linguistiche contemporaneamente.',
    'el' => 'Η δημοσίευση θα δημοσιεύσει όλες τις γλωσσικές εκδόσεις ταυτόχρονα.',
],
'status_changed' => [
    'fi' => 'Tila muutettu',
    'sv' => 'Status ändrad',
    'en' => 'Status changed',
    'it' => 'Stato modificato',
    'el' => 'Η κατάσταση άλλαξε',
],
'published' => [
    'fi' => 'Julkaistu',
    'sv' => 'Publicerad',
    'en' => 'Published',
    'it' => 'Pubblicato',
    'el' => 'Δημοσιεύτηκε',
],
'status_processing' => [
    'fi' => 'Prosessoidaan',
    'sv' => 'Bearbetas',
    'en' => 'Processing',
    'it' => 'In elaborazione',
    'el' => 'Επεξεργασία',
],
'publish_select_countries' => [
    'fi' => 'Valitse kohdemaat',
    'sv' => 'Välj målländer',
    'en' => 'Select target countries',
    'it' => 'Seleziona paesi di destinazione',
    'el' => 'Επιλέξτε χώρες-στόχους',
],
'publish_country_default' => [
    'fi' => 'oletuksena valittu',
    'sv' => 'vald som standard',
    'en' => 'selected by default',
    'it' => 'selezionato di default',
    'el' => 'επιλεγμένο από προεπιλογή',
],
'status_generating_image' => [
    'fi' => 'Generoidaan kuvaa.. .',
    'sv' => 'Genererar bild...',
    'en' => 'Generating image...',
    'it' => 'Generazione immagine...',
    'el' => 'Δημιουργία εικόνας...',
],
'status_saving' => [
    'fi' => 'Tallennetaan...',
    'sv' => 'Sparar...',
    'en' => 'Saving...',
    'it' => 'Salvataggio...',
    'el' => 'Αποθήκευση...',
],
'status_uploading' => [
    'fi' => 'Ladataan...',
    'sv' => 'Laddar upp...',
    'en' => 'Uploading...',
    'it' => 'Caricamento...',
    'el' => 'Μεταφόρτωση...',
],
'status_archived' => [
    'fi' => 'Arkistoitu',
    'sv' => 'Arkiverad',
    'en' => 'Archived',
    'it' => 'Archiviato',
    'el' => 'Αρχειοθετημένο',
],
'archived' => [
    'fi' => 'Arkistoitu',
    'sv' => 'Arkiverad',
    'en' => 'Archived',
    'it' => 'Archiviato',
    'el' => 'Αρχειοθετήθηκε',
],
'status_pending_supervisor' => [
    'fi' => 'Työmaavastaavan tarkistuksessa',
    'sv' => 'Under platsansvarigs granskning',
    'en' => 'In Site Supervisor Review',
    'it' => 'In verifica del responsabile del sito',
    'el' => 'Σε έλεγχο από τον υπεύθυνο εργοταξίου',
],
];