<?php
/**
 * Updates / Changelog terms
 */
return [
'nav_updates' => [
    'fi' => 'Päivitykset',
    'sv' => 'Uppdateringar',
    'en' => 'Updates',
    'it' => 'Aggiornamenti',
    'el' => 'Ενημερώσεις',
],
'updates_title' => [
    'fi' => 'Päivitykset',
    'sv' => 'Uppdateringar',
    'en' => 'Updates',
    'it' => 'Aggiornamenti',
    'el' => 'Ενημερώσεις',
],
'updates_description' => [
    'fi' => 'Täältä löydät tiedot sovelluksen uusimmista muutoksista, parannuksista ja uusista ominaisuuksista.',
    'sv' => 'Här hittar du information om de senaste ändringarna, förbättringarna och nya funktionerna i applikationen.',
    'en' => 'Here you can find information about the latest changes, improvements, and new features in the application.',
    'it' => 'Qui puoi trovare informazioni sulle ultime modifiche, miglioramenti e nuove funzionalità dell\'applicazione.',
    'el' => 'Εδώ μπορείτε να βρείτε πληροφορίες για τις τελευταίες αλλαγές, βελτιώσεις και νέες λειτουργίες της εφαρμογής.',
],
'updates_empty' => [
    'fi' => 'Ei vielä päivityksiä.',
    'sv' => 'Inga uppdateringar ännu.',
    'en' => 'No updates yet.',
    'it' => 'Nessun aggiornamento ancora.',
    'el' => 'Δεν υπάρχουν ακόμη ενημερώσεις.',
],
'settings_tab_updates' => [
    'fi' => 'Päivitykset',
    'sv' => 'Uppdateringar',
    'en' => 'Updates',
    'it' => 'Aggiornamenti',
    'el' => 'Ενημερώσεις',
],
'admin_updates_heading' => [
    'fi' => 'Päivitysten hallinta',
    'sv' => 'Hantering av uppdateringar',
    'en' => 'Manage Updates',
    'it' => 'Gestione aggiornamenti',
    'el' => 'Διαχείριση ενημερώσεων',
],
'admin_updates_new' => [
    'fi' => 'Uusi päivitys',
    'sv' => 'Ny uppdatering',
    'en' => 'New update',
    'it' => 'Nuovo aggiornamento',
    'el' => 'Νέα ενημέρωση',
],
'admin_updates_edit' => [
    'fi' => 'Muokkaa päivitystä',
    'sv' => 'Redigera uppdatering',
    'en' => 'Edit update',
    'it' => 'Modifica aggiornamento',
    'el' => 'Επεξεργασία ενημέρωσης',
],
'admin_updates_delete_confirm' => [
    'fi' => 'Haluatko varmasti poistaa tämän päivityksen?',
    'sv' => 'Vill du verkligen ta bort den här uppdateringen?',
    'en' => 'Are you sure you want to delete this update?',
    'it' => 'Sei sicuro di voler eliminare questo aggiornamento?',
    'el' => 'Είστε βέβαιοι ότι θέλετε να διαγράψετε αυτήν την ενημέρωση;',
],
'admin_updates_saved' => [
    'fi' => 'Päivitys tallennettu.',
    'sv' => 'Uppdatering sparad.',
    'en' => 'Update saved.',
    'it' => 'Aggiornamento salvato.',
    'el' => 'Η ενημέρωση αποθηκεύτηκε.',
],
'admin_updates_deleted' => [
    'fi' => 'Päivitys poistettu.',
    'sv' => 'Uppdatering borttagen.',
    'en' => 'Update deleted.',
    'it' => 'Aggiornamento eliminato.',
    'el' => 'Η ενημέρωση διαγράφηκε.',
],
'admin_updates_publish' => [
    'fi' => 'Julkaistu',
    'sv' => 'Publicerad',
    'en' => 'Published',
    'it' => 'Pubblicato',
    'el' => 'Δημοσιευμένο',
],
'admin_updates_draft' => [
    'fi' => 'Luonnos',
    'sv' => 'Utkast',
    'en' => 'Draft',
    'it' => 'Bozza',
    'el' => 'Πρόχειρο',
],
'updates_lang_tab_label' => [
    'fi' => 'Kieli',
    'sv' => 'Språk',
    'en' => 'Language',
    'it' => 'Lingua',
    'el' => 'Γλώσσα',
],
'updates_field_title' => [
    'fi' => 'Otsikko',
    'sv' => 'Rubrik',
    'en' => 'Title',
    'it' => 'Titolo',
    'el' => 'Τίτλος',
],
'updates_field_content' => [
    'fi' => 'Sisältö',
    'sv' => 'Innehåll',
    'en' => 'Content',
    'it' => 'Contenuto',
    'el' => 'Περιεχόμενο',
],
'updates_field_is_published' => [
    'fi' => 'Julkaise käyttäjille',
    'sv' => 'Publicera för användare',
    'en' => 'Publish to users',
    'it' => 'Pubblica agli utenti',
    'el' => 'Δημοσίευση στους χρήστες',
],
'updates_linked_feedback' => [
    'fi' => 'Linkitetty palaute',
    'sv' => 'Länkad feedback',
    'en' => 'Linked feedback',
    'it' => 'Feedback collegato',
    'el' => 'Συνδεδεμένη ανατροφοδότηση',
],
'feedback_create_update' => [
    'fi' => 'Luo päivitys tästä palautteesta',
    'sv' => 'Skapa uppdatering från denna feedback',
    'en' => 'Create update from this feedback',
    'it' => 'Crea aggiornamento da questo feedback',
    'el' => 'Δημιουργία ενημέρωσης από αυτήν την ανατροφοδότηση',
],
'updates_error_save' => [
    'fi' => 'Päivityksen tallennus epäonnistui.',
    'sv' => 'Det gick inte att spara uppdateringen.',
    'en' => 'Failed to save update.',
    'it' => 'Impossibile salvare l\'aggiornamento.',
    'el' => 'Αποτυχία αποθήκευσης ενημέρωσης.',
],
'updates_error_delete' => [
    'fi' => 'Päivityksen poisto epäonnistui.',
    'sv' => 'Det gick inte att ta bort uppdateringen.',
    'en' => 'Failed to delete update.',
    'it' => 'Impossibile eliminare l\'aggiornamento.',
    'el' => 'Αποτυχία διαγραφής ενημέρωσης.',
],
'updates_read_more' => [
    'fi' => 'Lue lisää',
    'sv' => 'Läs mer',
    'en' => 'Read more',
    'it' => 'Per saperne di più',
    'el' => 'Διαβάστε περισσότερα',
],
'updates_close' => [
    'fi' => 'Sulje',
    'sv' => 'Stäng',
    'en' => 'Close',
    'it' => 'Chiudi',
    'el' => 'Κλείσιμο',
],
'updates_field_publish_date' => [
    'fi' => 'Julkaisupäivä',
    'sv' => 'Publiceringsdatum',
    'en' => 'Publish date',
    'it' => 'Data di pubblicazione',
    'el' => 'Ημερομηνία δημοσίευσης',
],
'updates_filter_all' => [
    'fi' => 'Kaikki',
    'sv' => 'Alla',
    'en' => 'All',
    'it' => 'Tutti',
    'el' => 'Όλα',
],
'updates_filter_label' => [
    'fi' => 'Suodata kuukauden mukaan:',
    'sv' => 'Filtrera efter månad:',
    'en' => 'Filter by month:',
    'it' => 'Filtra per mese:',
    'el' => 'Φιλτράρισμα ανά μήνα:',
],
'updates_new_badge' => [
    'fi' => 'Uusia päivityksiä',
    'sv' => 'Nya uppdateringar',
    'en' => 'New updates',
    'it' => 'Nuovi aggiornamenti',
    'el' => 'Νέες ενημερώσεις',
],
'updates_field_images' => [
    'fi' => 'Kuvat',
    'sv' => 'Bilder',
    'en' => 'Images',
    'it' => 'Immagini',
    'el' => 'Εικόνες',
],
'updates_images_help' => [
    'fi' => 'Lisää enintään 3 ruutukaappausta (max 2 MB/kuva).',
    'sv' => 'Lägg till upp till 3 skärmbilder (max 2 MB/bild).',
    'en' => 'Add up to 3 screenshots (max 2 MB each).',
    'it' => 'Aggiungi fino a 3 screenshot (max 2 MB ciascuno).',
    'el' => 'Προσθέστε έως 3 στιγμιότυπα (μέγ. 2 MB το καθένα).',
],
'updates_image_remove' => [
    'fi' => 'Poista kuva',
    'sv' => 'Ta bort bild',
    'en' => 'Remove image',
    'it' => 'Rimuovi immagine',
    'el' => 'Αφαίρεση εικόνας',
],
'updates_image_too_large' => [
    'fi' => 'Kuva on liian suuri (max 2 MB).',
    'sv' => 'Bilden är för stor (max 2 MB).',
    'en' => 'Image is too large (max 2 MB).',
    'it' => 'L\'immagine è troppo grande (max 2 MB).',
    'el' => 'Η εικόνα είναι πολύ μεγάλη (μέγ. 2 MB).',
],
'updates_screenshot_alt' => [
    'fi' => 'Kuvakaappaus',
    'sv' => 'Skärmbild',
    'en' => 'Screenshot',
    'it' => 'Schermata',
    'el' => 'Στιγμιότυπο οθόνης',
],
];