<?php
/**
 * View Page - Flash detail view, metadata, previews, cards
 */
return [
'card_1_summary' => [
    'fi' => '1. Yhteenveto & kuvat',
    'sv' => '1. Sammanfattning & bilder',
    'en' => '1. Summary & images',
    'it' => '1. Riepilogo & immagini',
    'el' => '1. Σύνοψη & εικόνες',
],
'card_2_investigation' => [
    'fi' => '2. Juurisyyt & toimenpiteet',
    'sv' => '2. Grundorsaker & åtgärder',
    'en' => '2. Root causes & actions',
    'it' => '2. Cause & azioni',
    'el' => '2. Αιτίες & ενέργειες',
],
'card_1' => [
    'fi' => 'Kortti 1',
    'sv' => 'Kort 1',
    'en' => 'Card 1',
    'it' => 'Scheda 1',
    'el' => 'Κάρτα 1',
],
'card_2' => [
    'fi' => 'Kortti 2',
    'sv' => 'Kort 2',
    'en' => 'Card 2',
    'it' => 'Scheda 2',
    'el' => 'Κάρτα 2',
],
'preview_2_not_generated' => [
    'fi' => 'Kortin 2 esikatselukuvaa ei ole vielä generoitu.',
    'sv' => 'Kort 2:s förhandsvisning har inte genererats ännu.',
    'en' => 'Card 2 preview has not been generated yet.',
    'it' => 'L\'anteprima della scheda 2 non è ancora stata generata.',
    'el' => 'Η προεπισκόπηση της κάρτας 2 δεν έχει δημιουργηθεί ακόμα.',
],
'card_modified' => [
    'fi' => 'viimeksi muokattu',
    'sv' => 'senast ändrad',
    'en' => 'last modified',
    'it' => 'ultima modifica',
    'el' => 'τελευταία τροποποίηση',
],
'card_open' => [
    'fi' => 'Avaa',
    'sv' => 'Öppna',
    'en' => 'Open',
    'it' => 'Apri',
    'el' => 'Άνοιγμα',
],
'meta_title_internal' => [
    'fi' => 'Otsikko (vain järjestelmää varten)',
    'sv' => 'Rubrik (endast för systemet)',
    'en' => 'Title (system only)',
    'it' => 'Titolo (solo per il sistema)',
    'el' => 'Τίτλος (μόνο για το σύστημα)',
],
'meta_summary_short' => [
    'fi' => 'Lyhyt yhteenveto',
    'sv' => 'Kort sammanfattning',
    'en' => 'Short summary',
    'it' => 'Breve sommario',
    'el' => 'Σύντομη σύνοψη',
],
'meta_description_long' => [
    'fi' => 'Pitkä kuvaus',
    'sv' => 'Lång beskrivning',
    'en' => 'Long description',
    'it' => 'Descrizione estesa',
    'el' => 'Εκτενής περιγραφή',
],
'meta_type' => [
    'fi' => 'Tyyppi',
    'sv' => 'Typ',
    'en' => 'Type',
    'it' => 'Tipo',
    'el' => 'Τύπος',
],
'meta_site' => [
    'fi' => 'Työmaa',
    'sv' => 'Arbetsplats',
    'en' => 'Worksite',
    'it' => 'Cantiere',
    'el' => 'Εργοτάξιο',
],
'meta_occurred_at' => [
    'fi' => 'Tapahtuma-aika',
    'sv' => 'Tidpunkt',
    'en' => 'Time of incident',
    'it' => 'Data/ora evento',
    'el' => 'Χρόνος συμβάντος',
],
'meta_system_heading' => [
    'fi' => 'Järjestelmätiedot',
    'sv' => 'Systeminformation',
    'en' => 'System information',
    'it' => 'Informazioni di sistema',
    'el' => 'Πληροφορίες συστήματος',
],
'meta_language' => [
    'fi' => 'Kieli',
    'sv' => 'Språk',
    'en' => 'Language',
    'it' => 'Lingua',
    'el' => 'Γλώσσα',
],
'meta_created_at' => [
    'fi' => 'Luotu',
    'sv' => 'Skapad',
    'en' => 'Created',
    'it' => 'Creato',
    'el' => 'Δημιουργήθηκε',
],
'meta_updated_at' => [
    'fi' => 'Viimeksi muokattu',
    'sv' => 'Senast ändrad',
    'en' => 'Last modified',
    'it' => 'Ultima modifica',
    'el' => 'Τροποποιήθηκε τελευταία',
],
'preview_and_save' => [
    'fi' => 'Esikatselu ja tallennus',
    'sv' => 'Förhandsgranska och spara',
    'en' => 'Preview and save',
    'it' => 'Anteprima e salva',
    'el' => 'Προεπισκόπηση και αποθήκευση',
],
'preview_type_red' => [
    'fi' => 'ENSITIEDOTE',
    'sv' => 'FÖRSTA UNDERRÄTTELSE',
    'en' => 'FIRST RELEASE',
    'it' => 'PRIMO RILASCIO',
    'el' => 'ΠΡΩΤΗ ΔΗΜΟΣΙΕΥΣΗ',
],
'preview_type_yellow' => [
    'fi' => 'VAARATILANNE',
    'sv' => 'FARLIG SITUATION',
    'en' => 'DANGEROUS SITUATION',
    'it' => 'SITUAZIONE PERICOLOSA',
    'el' => 'ΕΠΙΚΙΝΔΥΝΗ ΚΑΤΑΣΤΑΣΗ',
],
'preview_type_green' => [
    'fi' => 'TUTKINTATIEDOTE',
    'sv' => 'UTREDNINGSRAPPORT',
    'en' => 'INVESTIGATION REPORT',
    'it' => 'RILASCIO DOPO L\'INDAGINE',
    'el' => 'ΕΚΘΕΣΗ ΕΡΕΥΝΑΣ',
],
'preview_brand' => [
    'fi' => 'TAPOJÄRVI SAFETY',
    'sv' => 'TAPOJÄRVI SAFETY',
    'en' => 'TAPOJÄRVI SAFETY',
    'it' => 'TAPOJÄRVI SAFETY',
    'el' => 'TAPOJÄRVI SAFETY',
],
'preview_text_continues' => [
    'fi' => '...[tekstiä jatkuu]',
    'sv' => '...[texten fortsätter]',
    'en' => '...[text continues]',
    'it' => '...[il testo continua]',
    'el' => '...[το κείμενο συνεχίζεται]',
],
'preview_meta_site' => [
    'fi' => 'TYÖMAA:',
    'sv' => 'ARBETSPLATS:',
    'en' => 'WORKSITE:',
    'it' => 'CANTIERE:',
    'el' => 'ΕΡΓΟΤΆΞΙΟ:',
],
'preview_meta_date' => [
    'fi' => 'MILLOIN?',
    'sv' => 'NÄR?',
    'en' => 'WHEN?',
    'it' => 'QUANDO?',
    'el' => 'ΠΌΤΕ;',
],
'display_targets_priority_group' => [
    'fi' => 'Aina näkyvät näyttökohteet',
    'sv' => 'Alltid synliga skärmval',
    'en' => 'Always visible display targets',
    'it' => 'Destinazioni schermo sempre visibili',
    'el' => 'Πάντα ορατοί στόχοι οθόνης',
],
'display_targets_display_only_chip' => [
    'fi' => 'Vain infonäytöissä',
    'sv' => 'Endast informationsskärmar',
    'en' => 'Display-only',
    'it' => 'Solo schermi informativi',
    'el' => 'Μόνο οθόνες ενημέρωσης',
],
'display_targets_uncategorized_chip' => [
    'fi' => 'Kategorisoimattomat',
    'sv' => 'Okategoriserade',
    'en' => 'Uncategorized',
    'it' => 'Non categorizzati',
    'el' => 'Μη κατηγοριοποιημένα',
],
'display_targets_default_chip' => [
    'fi' => 'Oletuksena valitut',
    'sv' => 'Förvalda',
    'en' => 'Default selected',
    'it' => 'Selezionati per default',
    'el' => 'Προεπιλεγμένα',
],
'activity_tab_versions' => [
    'fi' => 'Versiot',
    'sv' => 'Versioner',
    'en' => 'Versions',
    'it' => 'Versioni',
    'el' => 'Εκδόσεις',
],
'version_ensitiedote' => [
    'fi' => 'Ensitiedote',
    'sv' => 'Första underrättelse',
    'en' => 'First release',
    'it' => 'Prima notifica',
    'el' => 'Πρώτη ειδοποίηση',
],
'version_tutkintatiedote' => [
    'fi' => 'Tutkintatiedote',
    'sv' => 'Utredningsmeddelande',
    'en' => 'Investigation report',
    'it' => 'Rapporto di indagine',
    'el' => 'Έκθεση έρευνας',
],
'version_vaaratilanne' => [
    'fi' => 'Vaaratilanne',
    'sv' => 'Farlig situation',
    'en' => 'Dangerous situation',
    'it' => 'Situazione pericolosa',
    'el' => 'Επικίνδυνη κατάσταση',
],
'version_paivitys' => [
    'fi' => 'Päivitys',
    'sv' => 'Uppdatering',
    'en' => 'Update',
    'it' => 'Aggiornamento',
    'el' => 'Ενημέρωση',
],
'version_published' => [
    'fi' => 'Julkaistu',
    'sv' => 'Publicerad',
    'en' => 'Published',
    'it' => 'Pubblicato',
    'el' => 'Δημοσιεύτηκε',
],
'version_view' => [
    'fi' => 'Näytä',
    'sv' => 'Visa',
    'en' => 'View',
    'it' => 'Visualizza',
    'el' => 'Προβολή',
],
'version_download' => [
    'fi' => 'Lataa JPG',
    'sv' => 'Ladda ner JPG',
    'en' => 'Download JPG',
    'it' => 'Scarica JPG',
    'el' => 'Λήψη JPG',
],
'version_no_versions' => [
    'fi' => 'Ei julkaistuja versioita',
    'sv' => 'Inga publicerade versioner',
    'en' => 'No published versions',
    'it' => 'Nessuna versione pubblicata',
    'el' => 'Δεν υπάρχουν δημοσιευμένες εκδόσεις',
],
'version_current' => [
    'fi' => 'Nykyinen',
    'sv' => 'Aktuell', 
    'en' => 'Current',
    'it' => 'Attuale',
    'el' => 'Τρέχουσα',
],
'version_number' => [
    'fi' => 'Versio',
    'sv' => 'Version',
    'en' => 'Version',
    'it' => 'Versione',
    'el' => 'Έκδοση',
],
'log_delete' => [
    'fi' => 'Poista',
    'sv' => 'Radera',
    'en' => 'Delete',
    'it' => 'Elimina',
    'el' => 'Διαγραφή',
],
'log_delete_alt' => [
    'fi' => 'Poista lokimerkintä',
    'sv' => 'Radera loggpost',
    'en' => 'Delete log entry',
    'it' => 'Elimina voce di registro',
    'el' => 'Διαγραφή καταχώρησης',
],
'log_delete_title' => [
    'fi' => 'Poista lokimerkintä',
    'sv' => 'Radera loggpost',
    'en' => 'Delete log entry',
    'it' => 'Elimina voce di registro',
    'el' => 'Διαγραφή καταχώρησης',
],
'log_delete_confirm' => [
    'fi' => 'Haluatko varmasti poistaa tämän lokimerkinnän? Tätä toimintoa ei voi peruuttaa.',
    'sv' => 'Är du säker på att du vill radera denna loggpost? Denna åtgärd kan inte ångras.',
    'en' => 'Are you sure you want to delete this log entry? This action cannot be undone.',
    'it' => 'Sei sicuro di voler eliminare questa voce di registro? Questa azione non può essere annullata.',
    'el' => 'Είστε βέβαιοι ότι θέλετε να διαγράψετε αυτήν την καταχώρηση; Αυτή η ενέργεια δεν μπορεί να αναιρεθεί.',
],
'log_deleted' => [
    'fi' => 'Lokimerkintä poistettu',
    'sv' => 'Loggpost raderad',
    'en' => 'Log entry deleted',
    'it' => 'Voce di registro eliminata',
    'el' => 'Η καταχώρηση διαγράφηκε',
],
'log_delete_error' => [
    'fi' => 'Virhe lokimerkinnän poistamisessa',
    'sv' => 'Fel vid radering av loggpost',
    'en' => 'Error deleting log entry',
    'it' => 'Errore nell\'eliminazione della voce di registro',
    'el' => 'Σφάλμα κατά τη διαγραφή καταχώρησης',
],
'reviewer_section_title' => [
    'fi' => 'Tarkistaja',
    'sv' => 'Granskare',
    'en' => 'Reviewer',
    'it' => 'Revisore',
    'el' => 'Ελεγκτής',
],
'add_reviewer' => [
    'fi' => 'Lisää tarkistaja',
    'sv' => 'Lägg till granskare',
    'en' => 'Add reviewer',
    'it' => 'Aggiungi revisore',
    'el' => 'Προσθήκη ελεγκτή',
],
'replace_reviewer' => [
    'fi' => 'Vaihda tarkistaja',
    'sv' => 'Byt granskare',
    'en' => 'Replace reviewer',
    'it' => 'Sostituisci revisore',
    'el' => 'Αντικατάσταση ελεγκτή',
],
'remove_reviewer' => [
    'fi' => 'Poista tarkistaja',
    'sv' => 'Ta bort granskare',
    'en' => 'Remove reviewer',
    'it' => 'Rimuovi revisore',
    'el' => 'Κατάργηση ελεγκτή',
],
'reviewer_search_placeholder' => [
    'fi' => '🔍 Hae käyttäjiä...',
    'sv' => '🔍 Sök användare...',
    'en' => '🔍 Search users...',
    'it' => '🔍 Cerca utenti...',
    'el' => '🔍 Αναζήτηση χρηστών...',
],
'reviewer_add_modal_title' => [
    'fi' => 'Lisää tarkistaja',
    'sv' => 'Lägg till granskare',
    'en' => 'Add reviewer',
    'it' => 'Aggiungi revisore',
    'el' => 'Προσθήκη ελεγκτή',
],
'reviewer_replace_modal_title' => [
    'fi' => 'Vaihda tarkistaja',
    'sv' => 'Byt granskare',
    'en' => 'Replace reviewer',
    'it' => 'Sostituisci revisore',
    'el' => 'Αντικατάσταση ελεγκτή',
],
'reviewer_current_reviewers' => [
    'fi' => 'Nykyiset tarkistajat:',
    'sv' => 'Nuvarande granskare:',
    'en' => 'Current reviewers:',
    'it' => 'Revisori attuali:',
    'el' => 'Τρέχοντες ελεγκτές:',
],
'reviewer_no_reviewers' => [
    'fi' => 'Ei tarkistajia',
    'sv' => 'Inga granskare',
    'en' => 'No reviewers',
    'it' => 'Nessun revisore',
    'el' => 'Δεν υπάρχουν ελεγκτές',
],
'reviewer_select_user' => [
    'fi' => 'Valitse käyttäjä',
    'sv' => 'Välj användare',
    'en' => 'Select user',
    'it' => 'Seleziona utente',
    'el' => 'Επιλογή χρήστη',
],
'reviewer_remove_confirm' => [
    'fi' => 'Haluatko varmasti poistaa tämän tarkistajan?',
    'sv' => 'Är du säker på att du vill ta bort denna granskare?',
    'en' => 'Are you sure you want to remove this reviewer?',
    'it' => 'Sei sicuro di voler rimuovere questo revisore?',
    'el' => 'Είστε βέβαιοι ότι θέλετε να καταργήσετε αυτόν τον ελεγκτή;',
],
'reviewer_added' => [
    'fi' => 'Tarkistaja lisätty',
    'sv' => 'Granskare tillagd',
    'en' => 'Reviewer added',
    'it' => 'Revisore aggiunto',
    'el' => 'Προστέθηκε ελεγκτής',
],
'reviewer_replaced' => [
    'fi' => 'Tarkistaja vaihdettu',
    'sv' => 'Granskare bytt',
    'en' => 'Reviewer replaced',
    'it' => 'Revisore sostituito',
    'el' => 'Αντικαταστάθηκε ελεγκτής',
],
'reviewer_removed' => [
    'fi' => 'Tarkistaja poistettu',
    'sv' => 'Granskare borttagen',
    'en' => 'Reviewer removed',
    'it' => 'Revisore rimosso',
    'el' => 'Καταργήθηκε ελεγκτής',
],
'reviewer_error' => [
    'fi' => 'Virhe tarkistajan käsittelyssä',
    'sv' => 'Fel vid hantering av granskare',
    'en' => 'Error processing reviewer',
    'it' => 'Errore nel processare il revisore',
    'el' => 'Σφάλμα επεξεργασίας ελεγκτή',
],
'reviewer_assigned_at' => [
    'fi' => 'Lisätty',
    'sv' => 'Tillagd',
    'en' => 'Added',
    'it' => 'Aggiunto',
    'el' => 'Προστέθηκε',
],
'reviewer_no_users_found' => [
    'fi' => 'Ei käyttäjiä löydetty',
    'sv' => 'Inga användare hittades',
    'en' => 'No users found',
    'it' => 'Nessun utente trovato',
    'el' => 'Δεν βρέθηκαν χρήστες',
],
'btn_report' => [
    'fi' => 'Raportti',
    'en' => 'Report',
    'sv' => 'Rapport',
    'it' => 'Rapporto',
    'el' => 'Αναφορά',
],
'report_generating' => [
    'fi' => 'Luodaan raporttia...',
    'sv' => 'Skapar rapport...',
    'en' => 'Generating report...',
    'it' => 'Generazione report...',
    'el' => 'Δημιουργία αναφοράς...',
],
'report_success' => [
    'fi' => 'Raportti ladattu onnistuneesti',
    'sv' => 'Rapporten har laddats ner',
    'en' => 'Report downloaded successfully',
    'it' => 'Report scaricato con successo',
    'el' => 'Η αναφορά λήφθηκε επιτυχώς',
],
'report_error' => [
    'fi' => 'Raportin generointi epäonnistui',
    'sv' => 'Rapporten kunde inte genereras',
    'en' => 'Report generation failed',
    'it' => 'Generazione report fallita',
    'el' => 'Η δημιουργία αναφοράς απέτυχε',
],
'report_button_loading' => [
    'fi' => 'Luodaan...',
    'sv' => 'Skapar...',
    'en' => 'Generating...',
    'it' => 'Creazione...',
    'el' => 'Δημιουργία...',
],
'report_button_done' => [
    'fi' => 'Valmis!',
    'sv' => 'Klar!',
    'en' => 'Done!',
    'it' => 'Fatto!',
    'el' => 'Έτοιμο!',
],
'report_button_error' => [
    'fi' => 'Virhe!',
    'sv' => 'Fel!',
    'en' => 'Error!',
    'it' => 'Errore!',
    'el' => 'Σφάλμα!',
],
'lang_add_button_text' => [
    'fi' => '+Lisää',
    'sv' => '+Lägg till',
    'en' => '+Add',
    'it' => '+Aggiungi',
    'el' => '+Προσθήκη',
],
'lang_tooltip_active_fi' => [
    'fi' => 'Suomi (aktiivinen)',
    'sv' => 'Finska (aktiv)',
    'en' => 'Finnish (active)',
    'it' => 'Finlandese (attivo)',
    'el' => 'Φινλανδικά (ενεργό)',
],
'lang_tooltip_active_sv' => [
    'fi' => 'Ruotsi (aktiivinen)',
    'sv' => 'Svenska (aktiv)',
    'en' => 'Swedish (active)',
    'it' => 'Svedese (attivo)',
    'el' => 'Σουηδικά (ενεργό)',
],
'lang_tooltip_active_en' => [
    'fi' => 'Englanti (aktiivinen)',
    'sv' => 'Engelska (aktiv)',
    'en' => 'English (active)',
    'it' => 'Inglese (attivo)',
    'el' => 'Αγγλικά (ενεργό)',
],
'lang_tooltip_active_it' => [
    'fi' => 'Italia (aktiivinen)',
    'sv' => 'Italienska (aktiv)',
    'en' => 'Italian (active)',
    'it' => 'Italiano (attivo)',
    'el' => 'Ιταλικά (ενεργό)',
],
'lang_tooltip_active_el' => [
    'fi' => 'Kreikka (aktiivinen)',
    'sv' => 'Grekiska (aktiv)',
    'en' => 'Greek (active)',
    'it' => 'Greco (attivo)',
    'el' => 'Ελληνικά (ενεργό)',
],
'lang_tooltip_goto_fi' => [
    'fi' => 'Suomi – Siirry versioon',
    'sv' => 'Finska – Gå till version',
    'en' => 'Finnish – Go to version',
    'it' => 'Finlandese – Vai alla versione',
    'el' => 'Φινλανδικά – Μετάβαση στην έκδοση',
],
'lang_tooltip_goto_sv' => [
    'fi' => 'Ruotsi – Siirry versioon',
    'sv' => 'Svenska – Gå till version',
    'en' => 'Swedish – Go to version',
    'it' => 'Svedese – Vai alla versione',
    'el' => 'Σουηδικά – Μετάβαση στην έκδοση',
],
'lang_tooltip_goto_en' => [
    'fi' => 'Englanti – Siirry versioon',
    'sv' => 'Engelska – Gå till version',
    'en' => 'English – Go to version',
    'it' => 'Inglese – Vai alla versione',
    'el' => 'Αγγλικά – Μετάβαση στην έκδοση',
],
'lang_tooltip_goto_it' => [
    'fi' => 'Italia – Siirry versioon',
    'sv' => 'Italienska – Gå till version',
    'en' => 'Italian – Go to version',
    'it' => 'Italiano – Vai alla versione',
    'el' => 'Ιταλικά – Μετάβαση στην έκδοση',
],
'lang_tooltip_goto_el' => [
    'fi' => 'Kreikka – Siirry versioon',
    'sv' => 'Grekiska – Gå till version',
    'en' => 'Greek – Go to version',
    'it' => 'Greco – Vai alla versione',
    'el' => 'Ελληνικά – Μετάβαση στην έκδοση',
],
'lang_tooltip_add_fi' => [
    'fi' => 'Lisää suomenkielinen versio',
    'sv' => 'Lägg till finsk version',
    'en' => 'Add Finnish version',
    'it' => 'Aggiungi versione finlandese',
    'el' => 'Προσθήκη φινλανδικής έκδοσης',
],
'lang_tooltip_add_sv' => [
    'fi' => 'Lisää ruotsinkielinen versio',
    'sv' => 'Lägg till svensk version',
    'en' => 'Add Swedish version',
    'it' => 'Aggiungi versione svedese',
    'el' => 'Προσθήκη σουηδικής έκδοσης',
],
'lang_tooltip_add_en' => [
    'fi' => 'Lisää englanninkielinen versio',
    'sv' => 'Lägg till engelsk version',
    'en' => 'Add English version',
    'it' => 'Aggiungi versione inglese',
    'el' => 'Προσθήκη αγγλικής έκδοσης',
],
'lang_tooltip_add_it' => [
    'fi' => 'Lisää italiankielinen versio',
    'sv' => 'Lägg till italiensk version',
    'en' => 'Add Italian version',
    'it' => 'Aggiungi versione italiana',
    'el' => 'Προσθήκη ιταλικής έκδοσης',
],
'lang_tooltip_add_el' => [
    'fi' => 'Lisää kreikankielinen versio',
    'sv' => 'Lägg till grekisk version',
    'en' => 'Add Greek version',
    'it' => 'Aggiungi versione greca',
    'el' => 'Προσθήκη ελληνικής έκδοσης',
],
'comment_email_subscribe' => [
    'fi' => 'Haluan sähköposti-ilmoitukset tämän SafetyFlashin uusista kommenteista',
    'sv' => 'Jag vill få e-postmeddelanden om nya kommentarer på denna SafetyFlash',
    'en' => 'I want email notifications about new comments on this SafetyFlash',
    'it' => 'Voglio ricevere notifiche via e-mail per i nuovi commenti su questo SafetyFlash',
    'el' => 'Θέλω να λαμβάνω ειδοποιήσεις μέσω email για νέα σχόλια σε αυτό το SafetyFlash'
],
'settings_modal_title' => [
    'fi' => 'Raportin asetukset',
    'sv' => 'Rapportinställningar',
    'en' => 'Report settings',
    'it' => 'Impostazioni del rapporto',
    'el' => 'Ρυθμίσεις αναφοράς',
],
'settings_original_type_label' => [
    'fi' => 'Alkuperäinen tyyppi',
    'sv' => 'Ursprunglig typ',
    'en' => 'Original type',
    'it' => 'Tipo originale',
    'el' => 'Αρχικός τύπος',
],
'settings_original_type_none' => [
    'fi' => '— Ei määritetty —',
    'sv' => '— Inte angiven —',
    'en' => '— Not set —',
    'it' => '— Non impostato —',
    'el' => '— Δεν έχει οριστεί —',
],
'settings_original_type_saved' => [
    'fi' => 'Tallennettu',
    'sv' => 'Sparad',
    'en' => 'Saved',
    'it' => 'Salvato',
    'el' => 'Αποθηκεύτηκε',
],
'settings_original_type_error' => [
    'fi' => 'Tallennus epäonnistui',
    'sv' => 'Fel vid sparning',
    'en' => 'Save failed',
    'it' => 'Salvataggio non riuscito',
    'el' => 'Αποτυχία αποθήκευσης',
],
'body_parts_section_title' => [
    'fi' => 'Kehonosat',
    'sv' => 'Kroppsdelar',
    'en' => 'Body parts',
    'it' => 'Parti del corpo',
    'el' => 'Μέλη του σώματος',
],
'additional_info_tab_label' => [
    'fi' => 'Lisätiedot',
    'sv' => 'Info',
    'en' => 'Info',
    'it' => 'Info',
    'el' => 'Πληρ.',
],
'additional_info_description' => [
    'fi' => 'Tähän voit lisätä tarkentavia tekstejä, jotka eivät mahdu varsinaiseen Safetyflash-kuvaan. Nämä tiedot tulostuvat automaattisesti PDF-raportin liitteeksi.',
    'sv' => 'Här kan du lägga till preciserande texter som inte får plats i den egentliga Safetyflash-bilden. Dessa uppgifter skrivs automatiskt ut som bilaga till PDF-rapporten.',
    'en' => 'Here you can add clarifying texts that do not fit in the actual Safetyflash image. This information will automatically be printed as an appendix to the PDF report.',
    'it' => 'Qui puoi aggiungere testi esplicativi che non rientrano nell\'immagine Safetyflash. Queste informazioni verranno automaticamente stampate come allegato al report PDF.',
    'el' => 'Εδώ μπορείτε να προσθέσετε διευκρινιστικά κείμενα που δεν χωρούν στην εικόνα Safetyflash. Αυτές οι πληροφορίες θα εκτυπωθούν αυτόματα ως παράρτημα στην αναφορά PDF.',
],
'additional_info_placeholder' => [
    'fi' => 'Kirjoita lisätietoja tapahtumasta...',
    'sv' => 'Skriv ytterligare information om händelsen...',
    'en' => 'Write additional information about the event...',
    'it' => 'Scrivi informazioni aggiuntive sull\'evento...',
    'el' => 'Γράψτε πρόσθετες πληροφορίες για το συμβάν...',
],
'additional_info_add_btn' => [
    'fi' => 'Lisää teksti',
    'sv' => 'Lägg till text',
    'en' => 'Add text',
    'it' => 'Aggiungi testo',
    'el' => 'Προσθήκη κειμένου',
],
'additional_info_saved' => [
    'fi' => 'Tallennettu',
    'sv' => 'Sparat',
    'en' => 'Saved',
    'it' => 'Salvato',
    'el' => 'Αποθηκεύτηκε',
],
'additional_info_save_error' => [
    'fi' => 'Tallennus epäonnistui',
    'sv' => 'Fel vid sparning',
    'en' => 'Save failed',
    'it' => 'Salvataggio non riuscito',
    'el' => 'Αποτυχία αποθήκευσης',
],
'additional_info_unknown_author' => [
    'fi' => 'Tuntematon',
    'sv' => 'Okänd',
    'en' => 'Unknown',
    'it' => 'Sconosciuto',
    'el' => 'Άγνωστος',
],
'additional_info_pdf_section' => [
    'fi' => 'Lisätiedot tapahtumasta',
    'sv' => 'Ytterligare information om händelsen',
    'en' => 'Additional information about the event',
    'it' => 'Informazioni aggiuntive sull\'evento',
    'el' => 'Πρόσθετες πληροφορίες για το συμβάν',
],
'additional_info_modal_add_title' => [
    'fi' => 'Lisää teksti',
    'sv' => 'Lägg till text',
    'en' => 'Add text',
    'it' => 'Aggiungi testo',
    'el' => 'Προσθήκη κειμένου',
],
'additional_info_modal_edit_title' => [
    'fi' => 'Muokkaa tekstiä',
    'sv' => 'Redigera text',
    'en' => 'Edit text',
    'it' => 'Modifica testo',
    'el' => 'Επεξεργασία κειμένου',
],
'badge_athena_exported' => [
    'fi' => 'Athena · Viety',
    'sv' => 'Athena · Exporterad',
    'en' => 'Athena · Exported',
    'it' => 'Athena · Esportato',
    'el' => 'Athena · Εξαγμένο',
],
'badge_athena_not_exported' => [
    'fi' => 'Ei vielä viety Athenaan',
    'sv' => 'Ännu inte exporterad till Athena',
    'en' => 'Not yet exported to Athena',
    'it' => 'Non ancora esportato su Athena',
    'el' => 'Δεν έχει εξαχθεί ακόμα στο Athena',
],
'badge_athena_exported_by' => [
    'fi' => 'Viety',
    'sv' => 'Exporterad',
    'en' => 'Exported',
    'it' => 'Esportato',
    'el' => 'Εξαγμένο',
],
];
