ALTER TABLE sf_worksites
    ADD COLUMN IF NOT EXISTS show_in_worksite_lists TINYINT(1) NOT NULL DEFAULT 1,
    ADD COLUMN IF NOT EXISTS show_in_display_targets TINYINT(1) NOT NULL DEFAULT 1,
    ADD COLUMN IF NOT EXISTS is_default_display TINYINT(1) NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS site_type VARCHAR(32) NULL,
    ADD COLUMN IF NOT EXISTS created_at DATETIME NULL,
    ADD COLUMN IF NOT EXISTS updated_at DATETIME NULL;
